#!/usr/bin/env bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # t:cache-time=1d
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o t:h \
                      --long cache-time:,help \
                      -n $(basename -- $0) -- "$@")
declare cache_time=1d
eval set -- "$TEMP"
while true; do
    case "$1" in

        -t|--cache-time)
            cache_time=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-t, '
            printf %-24s '--cache-time=CACHE_TIME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code
