#!/usr/bin/env bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # t:save-to-dir

## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o t:h \
                      --long save-to-dir:,help \
                      -n "$(basename -- "$0")" -- "$@")
declare save_to_dir=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -t|--save-to-dir)
            save_to_dir=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %6s '-t, '
            printf %-24s '--save-to-dir=SAVE_TO_DIR'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

misc dump-jira-db -t "${save_to_dir}" -n "$1" > "$1".sql
misc dump-jira-db -t "${save_to_dir}" -n "$2" > "$2".sql

diff "$1".sql "$2".sql
