#!/usr/bin/env bash
set -e

cat "$1" | misc json-sorted |
    jq 'del(..|.id?) | del(..|.self?) | del(..|.position?)' |
    perl -pe 's,\\r\\n,\\n,g' |
    tee "$1".txt

cat "$2" | misc json-sorted |
    jq 'del(..|.id?) | del(..|.self?) | del(..|.position?)' |
    perl -pe 's,\\r\\n,\\n,g' |
    tee "$2".txt

. atexit rm "$1".txt "$2".txt

misc diff-texts -f "$1".txt "$2".txt
