#!/usr/bin/env bash
set -e

misc diff-texts \
     "$(
cat "$1" | misc json-sorted | jq 'del(..|.id?) | del(..|.self?) | del(..|.position?)' | perl -pe 's,\\r\\n,\\n,g'
)" \
     "$(
cat "$2" | misc json-sorted | jq 'del(..|.id?) | del(..|.self?) | del(..|.position?)' | perl -pe 's,\\r\\n,\\n,g'
)"
