#!/usr/bin/env bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # t:save-to-dir n:file-name

## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o n:t:h \
                      --long file-name:,save-to-dir:,help \
                      -n "$(basename -- "$0")" -- "$@")
declare file_name=
declare save_to_dir=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -n|--file-name)
            file_name=$2
            shift 2

            ;;
        -t|--save-to-dir)
            save_to_dir=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %6s '-n, '
            printf %-24s '--file-name=FILE_NAME'
            echo
            printf %6s '-t, '
            printf %-24s '--save-to-dir=SAVE_TO_DIR'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

sudo java -cp /usr/share/maven-repo/com/h2database/h2/1.4.191/h2-1.4.191.jar  org.h2.tools.Script -user sa -url jdbc:h2:file:${save_to_dir}/${file_name} -script /tmp/$$.sql
cat /tmp/$$.sql
sudo rm -f /tmp/$$.sql
