#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(system systemx capture capturex);

use HTML::Query 'Query';

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# f:html-file q:query-text a:attribute
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $attribute = "";
my $html_file = "";
my $query_text = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-a, ';
    printf "%-24s", '--attribute=ATTRIBUTE';
    if (length('--attribute=ATTRIBUTE') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-f, ';
    printf "%-24s", '--html-file=HTML-FILE';
    if (length('--html-file=HTML-FILE') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-q, ';
    printf "%-24s", '--query-text=QUERY-TEXT';
    if (length('--query-text=QUERY-TEXT') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'attribute|a=s' => \$attribute,
    'html-file|f=s' => \$html_file,
    'query-text|q=s' => \$query_text,
    'help|h!' => \&$handler_help,
);


## end generated code

my $q = Query( file  => $html_file  );
my @r = $q->query($query_text)->get_elements();

if ($attribute) {
    map {say $_->attr($attribute)} @r;
} else {
    use Data::Dumper;
    print Dumper(\@r);
}
