#!/bin/bash
declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}
* TODO create issuetype
* TODO edit issue type field scheme (better enter from project page)
* TODO edit issuetype scheme (remember to save! there is a save button at the bottom!)
* TODO edit workflow scheme (add, assign)
* TODO edit issue type screen schemes
# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # ddebug s:serial
## end code-generator
## start generated code

## end generated code
