#!/bin/bash
set -e

cat <<'EOFcc6741846980'
# {%org-mode%}
1. 先 deploy 到 jira-sync 上
2. 再 deploy 到 jira-prod 上

* DONE "把所有 field 字段列出来，在目标上改名（通过 field 名字）、创建，应该有一个脚本，migrate-fields"
  CLOSED: [2019-12-23 月 10:27]
  :LOGBOOK:
  - State "DONE"       from "DONE"       [2019-12-23 月 10:27]
  - State "DONE"       from              [2019-12-23 月 10:27]
  :END:

* DONE yes-or-no-p "把所有 screen 列出来，在目标上改名（通过 screen id 对比）、创建"
  CLOSED: [2019-12-23 月 10:27]
  :LOGBOOK:
  - State "DONE"       from              [2019-12-23 月 10:27]
  :END:

* DONE yes-or-no-p "修改 issuetype 的 screen 关联"
  CLOSED: [2019-12-23 月 15:41]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2019-12-23 月 15:41]
  :END:

* DONE yes-or-no-p "把 workflow export 出来，在目标上 import"
  CLOSED: [2019-12-23 月 14:39]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2019-12-23 月 14:39]
  :END:

* DONE yes-or-no-p "把 issuetype 关联到新的 workflow"
  CLOSED: [2019-12-23 月 15:36]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2019-12-23 月 15:36]
  :END:
* DONE yes-or-no-p "把所有 dynamic export 出来，在目标上 import"
  CLOSED: [2019-12-23 月 15:36]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2019-12-23 月 15:36]
  :END:
# {%/org-mode%}
EOFcc6741846980

./migrate-fields
yes-or-no-p "修改 issuetype 的 screen 关联"
yes-or-no-p "把 workflow export 出来，在目标上 import"
yes-or-no-p "把 issuetype 关联到新的 workflow"
yes-or-no-p "把所有 dynamic export 出来，在目标上 import"
