#+title: 我在Github上的个人博客
# bhj-tags: blog

* 关于我

我是一个软件工程师。我写了一些自由软件代码，一开始只是想解决自己的一些
问题，但慢慢也希望这些软件对别人也有点用处。

我使用的键盘布局是DVP -- Programmer Dvorak，英文、中文均使用此键盘格局。
在Emacs/Linux/Windows下使用的中文输入法都是我自己开发的SDIM输入法。这样
你应该了解我有多特立独行了吧？

我在水木的账号是flonk，平时常逛 [[http://www.newsmth.net/bbsbfind.php?q%3D1&board%3DEmacs&title%3D&title2%3D&title3%3D&userid%3Dflonk&dt%3D2222][Emacs]] 版。另一个用新闻组发表贴子的话用
的账号是 [[http://www.newsmth.net/bbsbfind.php?q=1&board=Emacs&title=&title2=&title3=&userid=baohaojun.&dt=2222][baohaojun.]] 。

* 我的自由软件项目

- [[../../../2012/01/31/beagrep-cn.org][beagrep]]
  
  Beagrep在两G代码中grep readlink只需0.23秒。它源自[[http://en.wikipedia.org/wiki/Beagle_(software)][beagle]]，一个桌面搜索
  引擎，我对其进行了修改，以便能精确地进行搜索，从而可以用它来大大加快
  grep的速度，这对阅读源代码非常有用，特别是如Android那样巨大的开源项目
  的源代码。

  Beagrep同时支持Linux、Windows和MacOS。

- [[../../../2011/12/28/org-jira.org][org-jira]]

  用Emacs的org-mode来管理Jira（一个很受欢迎的bug tracking/task
  management系统）。

  

- [[http://github.com/baohaojun/system-config/tree/master/gcode/scim-cs/ime-py][SDIM]]

  SDIM，中文名字影舞笔，是我开发的五笔输入法，目前全世界只有我自己一个
  用户（就像我写的大部分其他软件一样）。它可以在4个平台下运行，
  Linux/Windows/Emacs/MacOS，这样我在每个平台下的键盘输入习惯可以最大程
  度的保持一致： =C-g= 表示取消中文输入； =C-\= 表示输入法切换；可以进
  行中英文混输，等等。

- scim-fcitx

  最早对输入法感兴趣是2004年左右听了苏哲（SCIM输入法平台作者）的一个介
  绍（当时研究生快毕业，住的地方离亚嵌举办这个活动的地址很近），他说他
  对当前（当时）Linux中文输入法有两大阵营Fcitx和Scim表示担忧，一年之后
  我趁一个五一长假把Fcitx移植到了Scim平台，并发布在LinuxSir论坛上。回到
  公司没多久，公司里的一位长老过来对我说，你是我认识的第一位有自己的开
  源项目的人，呵呵:-)

- [[http://github.com/baohaojun/system-config/tree/master/bin][rename-refactory]]

  一个代码重构工具，用bash脚本实现，我用它来实现我认为最重要的一种重构：
  重命名。

  * 与git相结合

  * 处理文件内容中的重命名、文件名字的重命名、（递归）目录名字的重命名，
    symlink目标路径的重命名。

- [[../../../2012/12/27/coding-android-java-in-emacs.org][Ajoke]]

  在Emacs下进行Android Java编程。

- 其他
  
  还有很多其他的小软件、小脚本。我把它们都放到一个github项目里进行管理。
  详情见 [[../../../2012/10/22/my-config-cn.org][我的配置环境]] 。


