#!/usr/bin/env bash

(
    cd ~/.cache/sessions/
    rm xfce4-session-* -f
)

if test "${DESKTOP_SESSION}" = sawfish; then
    # maybe using lxde
    while true; do
        xfce4-session
        sleep 2
    done
fi
