#!/bin/bash
echo sawfish starting sub programs
sudo modprobe -r pcspkr 
python3 ~/gcode/scim-cs/ime-py/ime-server.py&
if test -f ~/.offlineimaprc; then
    (
	while true; 
	do 
	    python2.6 ~/bin/windows/Imap4Monitor/Imap4Monitor.py;
	    sleep 2; 
	done
    )&
fi

while true; do
    (
	cd ~/gcode/gmail-notify-1.6.1.1;
	GA_LABEL=/BigOne  ./notifier.py;
	sleep 5;
    )
done >~/.gmail-notifier.log 2>&1 &
qq

while true; do (cd ~/gcode/offline.wikipedia/mywiki; python manage.py runserver --noreload >>~/.offline-wiki.log 2>&1); sleep 2; done& 
download-today

command renew-xauth
killall syndaemon
syndaemon -i 1 -d

for x in ~/external/sawfish/start/*; do
    (
	echo executing "$x"
	test -e "$x" && "$x"&
    )
done

while true; do
    if ps aux|grep ssh|grep bhj@216 -q; 
    then
        true;
    else
        ssh -C2qN -D 8080 bhj@216.194.70.6; 
    fi
    sleep 2; 
done

# for x in /etc/xdg/autostart/*; do
#     (
# 	$(cat "$x"|perl -ne '
# if (m/^\s*Exec\s*=\s*(.*)/) {
#     print $1;
# }'
# 	)&
#     )
# done
