#!/usr/bin/env bash

. .funlock ~/system-config/.sawfish/start/.run-dir-once.lock

m wait-for-desktop-env

if xrandr | grep -P 'HDMI. connected|^DP1 connected'; then
    switch-to-hdmi
    switch-to-hdmi-and-laptop
fi

emacs.bhj&

(
    export check_program=tmux

    if ! which $check_program; then
        xterm -e bash -c '
hint "你没有装过 $check_program，现在为你安装 $check_program。"
sudo apt-get install $check_program
hint "$check_program 安装完成，请按回车键关闭此窗口"
'
    fi
)

if false && test -e ~/.local-config/etc/baohaojun; then
    if ps.pl bbs.robot.tmux; then
        konsole.bhj
    else
        konsole.bhj bbs-robot --use-current-screen-window
    fi
else
    konsole.bhj
fi&

while ! emacsclient -e '(message "hello")' | grep -q '"hello"'; do
    sleep 1
done

if xrandr | grep -P 'HDMI. connected|^DP1 connected'; then
    switch-to-hdmi
    switch-to-hdmi-and-laptop
fi

after-emacs-start
