#!/bin/bash

while test "$(sawfish-client -e '(window-exists-p "xfce4-panel")')" != t; do
    sleep 1
done
emacs.bhj&
konsole.bhj&

while ! emacsclient -e '(message "hello")' | grep -q '"hello"'; do
    sleep 1
done

if xrandr | grep -P 'HDMI. connected|^DP1 connected'; then
    switch-to-hdmi
    switch-to-hdmi-and-laptop
fi

do-natural-scrolling
