#!/bin/bash

input=$(readlink -f /dev/input/by-id/*4000-if01* | perl -npe 's!^/dev/!!')
input00=$(readlink -f /dev/input/by-id/*4000-event* | perl -npe 's!^/dev/!!')
if test "$input"; then
    sudo cp ~/etc/lib/udev/keymaps/microsoft-ergonomic-keyboard /lib/udev/keymaps/microsoft-ergonomic-keyboard
    sudo cp ~/etc/lib/udev/keymaps/microsoft-ergonomic-keyboard-if00 /lib/udev/keymaps/microsoft-ergonomic-keyboard-if00
    sudo /lib/udev/keymap "$input" /lib/udev/keymaps/microsoft-ergonomic-keyboard
    sudo /lib/udev/keymap "$input00" /lib/udev/keymaps/microsoft-ergonomic-keyboard-if00
fi
