#!/usr/bin/env bash

set -x

m wait-for-desktop-env

xrdb -merge ~/system-config/.Xresources
if test -e ~/.config/system-config/.Xresources; then
    xrdb -merge ~/.config/system-config/.Xresources
fi
