#!/bin/bash

set -e
exec > ~/.cache/system-config/logs/$(basename $0).log 2>&1
pid=$(ps.pl xorg/Xorg|pn 1)
if test -z "$pid"; then
    pid=$(ps.pl /bin/xorg|pn 1)
fi

ln -sf "$(sudo ls -l "/proc/$pid/fd" | grep -e '/dev/tty[0-9]' | perl -npe 's/.*-> //')" ~/.xtty

