#!/bin/bash

cd /tmp

while true; do
    if test -e ~/.config/no-ww; then
        exit
    fi
    AliWangWang
    sleep 5
done&

while true; do
    if test -e ~/.config/no-ww; then
        exit
    fi
    HOME=~/tmp AliWangWang
    sleep 5
done&
