#!/bin/bash

cd /tmp

flag=~/.config/no-ww

function start-ww() {
    mkdir -p ~/.logs

    (
        while true; do
            if test -e $flag; then
                exit
            fi
            (
                flock 9
                AliWangWang
            )
            sleep 5
        done&
    ) 9> ~/.logs/ww.lock
}

start-ww
HOME=~/tmp start-ww
