local emojis = {
   {'©', '© COPYRIGHT SIGN unicode', 'emojis/iphone-emoji/COPYRIGHT_SIGN.png'},
   {'®', '® REGISTERED SIGN unicode', 'emojis/iphone-emoji/REGISTERED_SIGN.png'},
   {'🀄', '🀄 MAHJONG TILE RED DRAGON unicode', 'emojis/iphone-emoji/MAHJONG_TILE_RED_DRAGON.png'},
   {'🃏', '🃏 PLAYING CARD BLACK JOKER unicode', 'emojis/iphone-emoji/PLAYING_CARD_BLACK_JOKER.png'},
   {'🅰', '🅰 NEGATIVE SQUARED LATIN CAPITAL LETTER A unicode', 'emojis/iphone-emoji/NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_A.png'},
   {'🅱', '🅱 NEGATIVE SQUARED LATIN CAPITAL LETTER B unicode', 'emojis/iphone-emoji/NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_B.png'},
   {'🅾', '🅾 NEGATIVE SQUARED LATIN CAPITAL LETTER O unicode', 'emojis/iphone-emoji/NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_O.png'},
   {'🅿', '🅿 NEGATIVE SQUARED LATIN CAPITAL LETTER P unicode', 'emojis/iphone-emoji/NEGATIVE_SQUARED_LATIN_CAPITAL_LETTER_P.png'},
   {'🆎', '🆎 NEGATIVE SQUARED AB unicode', 'emojis/iphone-emoji/NEGATIVE_SQUARED_AB.png'},
   {'🆑', '🆑 SQUARED CL unicode', 'emojis/iphone-emoji/SQUARED_CL.png'},
   {'🆒', '🆒 SQUARED COOL unicode', 'emojis/iphone-emoji/SQUARED_COOL.png'},
   {'🆓', '🆓 SQUARED FREE unicode', 'emojis/iphone-emoji/SQUARED_FREE.png'},
   {'🆔', '🆔 SQUARED ID unicode', 'emojis/iphone-emoji/SQUARED_ID.png'},
   {'🆕', '🆕 SQUARED NEW unicode', 'emojis/iphone-emoji/SQUARED_NEW.png'},
   {'🆖', '🆖 SQUARED NG unicode', 'emojis/iphone-emoji/SQUARED_NG.png'},
   {'🆗', '🆗 SQUARED OK unicode', 'emojis/iphone-emoji/SQUARED_OK.png'},
   {'🆘', '🆘 SQUARED SOS unicode', 'emojis/iphone-emoji/SQUARED_SOS.png'},
   {'🆙', '🆙 SQUARED UP WITH EXCLAMATION MARK unicode', 'emojis/iphone-emoji/SQUARED_UP_WITH_EXCLAMATION_MARK.png'},
   {'🆚', '🆚 SQUARED VS unicode', 'emojis/iphone-emoji/SQUARED_VS.png'},
   {'🈁', '🈁 SQUARED KATAKANA KOKO unicode', 'emojis/iphone-emoji/SQUARED_KATAKANA_KOKO.png'},
   {'🈂', '🈂 SQUARED KATAKANA SA unicode', 'emojis/iphone-emoji/SQUARED_KATAKANA_SA.png'},
   {'🈚', '🈚 SQUARED CJK UNIFIED IDEOGRAPH-7121 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-7121.png'},
   {'🈯', '🈯 SQUARED CJK UNIFIED IDEOGRAPH-6307 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-6307.png'},
   {'🈲', '🈲 SQUARED CJK UNIFIED IDEOGRAPH-7981 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-7981.png'},
   {'🈳', '🈳 SQUARED CJK UNIFIED IDEOGRAPH-7A7A unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-7A7A.png'},
   {'🈴', '🈴 SQUARED CJK UNIFIED IDEOGRAPH-5408 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-5408.png'},
   {'🈵', '🈵 SQUARED CJK UNIFIED IDEOGRAPH-6E80 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-6E80.png'},
   {'🈶', '🈶 SQUARED CJK UNIFIED IDEOGRAPH-6709 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-6709.png'},
   {'🈷', '🈷 SQUARED CJK UNIFIED IDEOGRAPH-6708 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-6708.png'},
   {'🈸', '🈸 SQUARED CJK UNIFIED IDEOGRAPH-7533 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-7533.png'},
   {'🈹', '🈹 SQUARED CJK UNIFIED IDEOGRAPH-5272 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-5272.png'},
   {'🈺', '🈺 SQUARED CJK UNIFIED IDEOGRAPH-55B6 unicode', 'emojis/iphone-emoji/SQUARED_CJK_UNIFIED_IDEOGRAPH-55B6.png'},
   {'🉐', '🉐 CIRCLED IDEOGRAPH ADVANTAGE unicode', 'emojis/iphone-emoji/CIRCLED_IDEOGRAPH_ADVANTAGE.png'},
   {'🉑', '🉑 CIRCLED IDEOGRAPH ACCEPT unicode', 'emojis/iphone-emoji/CIRCLED_IDEOGRAPH_ACCEPT.png'},
   {'🌀', '🌀 CYCLONE unicode', 'emojis/iphone-emoji/CYCLONE.png'},
   {'🌁', '🌁 FOGGY unicode', 'emojis/iphone-emoji/FOGGY.png'},
   {'🌂', '🌂 CLOSED UMBRELLA unicode', 'emojis/iphone-emoji/CLOSED_UMBRELLA.png'},
   {'🌃', '🌃 NIGHT WITH STARS unicode', 'emojis/iphone-emoji/NIGHT_WITH_STARS.png'},
   {'🌄', '🌄 SUNRISE OVER MOUNTAINS unicode', 'emojis/iphone-emoji/SUNRISE_OVER_MOUNTAINS.png'},
   {'🌅', '🌅 SUNRISE unicode', 'emojis/iphone-emoji/SUNRISE.png'},
   {'🌆', '🌆 CITYSCAPE AT DUSK unicode', 'emojis/iphone-emoji/CITYSCAPE_AT_DUSK.png'},
   {'🌇', '🌇 SUNSET OVER BUILDINGS unicode', 'emojis/iphone-emoji/SUNSET_OVER_BUILDINGS.png'},
   {'🌈', '🌈 RAINBOW unicode', 'emojis/iphone-emoji/RAINBOW.png'},
   {'🌉', '🌉 BRIDGE AT NIGHT unicode', 'emojis/iphone-emoji/BRIDGE_AT_NIGHT.png'},
   {'🌊', '🌊 WATER WAVE unicode', 'emojis/iphone-emoji/WATER_WAVE.png'},
   {'🌋', '🌋 VOLCANO unicode', 'emojis/iphone-emoji/VOLCANO.png'},
   {'🌌', '🌌 MILKY WAY unicode', 'emojis/iphone-emoji/MILKY_WAY.png'},
   {'🌍', '🌍 EARTH GLOBE EUROPE-AFRICA unicode', 'emojis/iphone-emoji/EARTH_GLOBE_EUROPE-AFRICA.png'},
   {'🌎', '🌎 EARTH GLOBE AMERICAS unicode', 'emojis/iphone-emoji/EARTH_GLOBE_AMERICAS.png'},
   {'🌏', '🌏 EARTH GLOBE ASIA-AUSTRALIA unicode', 'emojis/iphone-emoji/EARTH_GLOBE_ASIA-AUSTRALIA.png'},
   {'🌐', '🌐 GLOBE WITH MERIDIANS unicode', 'emojis/iphone-emoji/GLOBE_WITH_MERIDIANS.png'},
   {'🌑', '🌑 NEW MOON SYMBOL unicode', 'emojis/iphone-emoji/NEW_MOON_SYMBOL.png'},
   {'🌒', '🌒 WAXING CRESCENT MOON SYMBOL unicode', 'emojis/iphone-emoji/WAXING_CRESCENT_MOON_SYMBOL.png'},
   {'🌓', '🌓 FIRST QUARTER MOON SYMBOL unicode', 'emojis/iphone-emoji/FIRST_QUARTER_MOON_SYMBOL.png'},
   {'🌔', '🌔 WAXING GIBBOUS MOON SYMBOL unicode', 'emojis/iphone-emoji/WAXING_GIBBOUS_MOON_SYMBOL.png'},
   {'🌕', '🌕 FULL MOON SYMBOL unicode', 'emojis/iphone-emoji/FULL_MOON_SYMBOL.png'},
   {'🌖', '🌖 WANING GIBBOUS MOON SYMBOL unicode', 'emojis/iphone-emoji/WANING_GIBBOUS_MOON_SYMBOL.png'},
   {'🌗', '🌗 LAST QUARTER MOON SYMBOL unicode', 'emojis/iphone-emoji/LAST_QUARTER_MOON_SYMBOL.png'},
   {'🌘', '🌘 WANING CRESCENT MOON SYMBOL unicode', 'emojis/iphone-emoji/WANING_CRESCENT_MOON_SYMBOL.png'},
   {'🌙', '🌙 CRESCENT MOON unicode', 'emojis/iphone-emoji/CRESCENT_MOON.png'},
   {'🌚', '🌚 NEW MOON WITH FACE unicode', 'emojis/iphone-emoji/NEW_MOON_WITH_FACE.png'},
   {'🌛', '🌛 FIRST QUARTER MOON WITH FACE unicode', 'emojis/iphone-emoji/FIRST_QUARTER_MOON_WITH_FACE.png'},
   {'🌜', '🌜 LAST QUARTER MOON WITH FACE unicode', 'emojis/iphone-emoji/LAST_QUARTER_MOON_WITH_FACE.png'},
   {'🌝', '🌝 FULL MOON WITH FACE unicode', 'emojis/iphone-emoji/FULL_MOON_WITH_FACE.png'},
   {'🌞', '🌞 SUN WITH FACE unicode', 'emojis/iphone-emoji/SUN_WITH_FACE.png'},
   {'🌟', '🌟 GLOWING STAR unicode', 'emojis/iphone-emoji/GLOWING_STAR.png'},
   {'🌠', '🌠 SHOOTING STAR unicode', 'emojis/iphone-emoji/SHOOTING_STAR.png'},
   {'🌰', '🌰 CHESTNUT unicode', 'emojis/iphone-emoji/CHESTNUT.png'},
   {'🌱', '🌱 SEEDLING unicode', 'emojis/iphone-emoji/SEEDLING.png'},
   {'🌲', '🌲 EVERGREEN TREE unicode', 'emojis/iphone-emoji/EVERGREEN_TREE.png'},
   {'🌳', '🌳 DECIDUOUS TREE unicode', 'emojis/iphone-emoji/DECIDUOUS_TREE.png'},
   {'🌴', '🌴 PALM TREE unicode', 'emojis/iphone-emoji/PALM_TREE.png'},
   {'🌵', '🌵 CACTUS unicode', 'emojis/iphone-emoji/CACTUS.png'},
   {'🌷', '🌷 TULIP unicode', 'emojis/iphone-emoji/TULIP.png'},
   {'🌸', '🌸 CHERRY BLOSSOM unicode', 'emojis/iphone-emoji/CHERRY_BLOSSOM.png'},
   {'🌹', '🌹 ROSE unicode', 'emojis/iphone-emoji/ROSE.png'},
   {'🌺', '🌺 HIBISCUS unicode', 'emojis/iphone-emoji/HIBISCUS.png'},
   {'🌻', '🌻 SUNFLOWER unicode', 'emojis/iphone-emoji/SUNFLOWER.png'},
   {'🌼', '🌼 BLOSSOM unicode', 'emojis/iphone-emoji/BLOSSOM.png'},
   {'🌽', '🌽 EAR OF MAIZE unicode', 'emojis/iphone-emoji/EAR_OF_MAIZE.png'},
   {'🌾', '🌾 EAR OF RICE unicode', 'emojis/iphone-emoji/EAR_OF_RICE.png'},
   {'🌿', '🌿 HERB unicode', 'emojis/iphone-emoji/HERB.png'},
   {'🍀', '🍀 FOUR LEAF CLOVER unicode', 'emojis/iphone-emoji/FOUR_LEAF_CLOVER.png'},
   {'🍁', '🍁 MAPLE LEAF unicode', 'emojis/iphone-emoji/MAPLE_LEAF.png'},
   {'🍂', '🍂 FALLEN LEAF unicode', 'emojis/iphone-emoji/FALLEN_LEAF.png'},
   {'🍃', '🍃 LEAF FLUTTERING IN WIND unicode', 'emojis/iphone-emoji/LEAF_FLUTTERING_IN_WIND.png'},
   {'🍄', '🍄 MUSHROOM unicode', 'emojis/iphone-emoji/MUSHROOM.png'},
   {'🍅', '🍅 TOMATO unicode', 'emojis/iphone-emoji/TOMATO.png'},
   {'🍆', '🍆 AUBERGINE unicode', 'emojis/iphone-emoji/AUBERGINE.png'},
   {'🍇', '🍇 GRAPES unicode', 'emojis/iphone-emoji/GRAPES.png'},
   {'🍈', '🍈 MELON unicode', 'emojis/iphone-emoji/MELON.png'},
   {'🍉', '🍉 WATERMELON unicode', 'emojis/iphone-emoji/WATERMELON.png'},
   {'🍊', '🍊 TANGERINE unicode', 'emojis/iphone-emoji/TANGERINE.png'},
   {'🍋', '🍋 LEMON unicode', 'emojis/iphone-emoji/LEMON.png'},
   {'🍌', '🍌 BANANA unicode', 'emojis/iphone-emoji/BANANA.png'},
   {'🍍', '🍍 PINEAPPLE unicode', 'emojis/iphone-emoji/PINEAPPLE.png'},
   {'🍎', '🍎 RED APPLE unicode', 'emojis/iphone-emoji/RED_APPLE.png'},
   {'🍏', '🍏 GREEN APPLE unicode', 'emojis/iphone-emoji/GREEN_APPLE.png'},
   {'🍐', '🍐 PEAR unicode', 'emojis/iphone-emoji/PEAR.png'},
   {'🍑', '🍑 PEACH unicode', 'emojis/iphone-emoji/PEACH.png'},
   {'🍒', '🍒 CHERRIES unicode', 'emojis/iphone-emoji/CHERRIES.png'},
   {'🍓', '🍓 STRAWBERRY unicode', 'emojis/iphone-emoji/STRAWBERRY.png'},
   {'🍔', '🍔 HAMBURGER unicode', 'emojis/iphone-emoji/HAMBURGER.png'},
   {'🍕', '🍕 SLICE OF PIZZA unicode', 'emojis/iphone-emoji/SLICE_OF_PIZZA.png'},
   {'🍖', '🍖 MEAT ON BONE unicode', 'emojis/iphone-emoji/MEAT_ON_BONE.png'},
   {'🍗', '🍗 POULTRY LEG unicode', 'emojis/iphone-emoji/POULTRY_LEG.png'},
   {'🍘', '🍘 RICE CRACKER unicode', 'emojis/iphone-emoji/RICE_CRACKER.png'},
   {'🍙', '🍙 RICE BALL unicode', 'emojis/iphone-emoji/RICE_BALL.png'},
   {'🍚', '🍚 COOKED RICE unicode', 'emojis/iphone-emoji/COOKED_RICE.png'},
   {'🍛', '🍛 CURRY AND RICE unicode', 'emojis/iphone-emoji/CURRY_AND_RICE.png'},
   {'🍜', '🍜 STEAMING BOWL unicode', 'emojis/iphone-emoji/STEAMING_BOWL.png'},
   {'🍝', '🍝 SPAGHETTI unicode', 'emojis/iphone-emoji/SPAGHETTI.png'},
   {'🍞', '🍞 BREAD unicode', 'emojis/iphone-emoji/BREAD.png'},
   {'🍟', '🍟 FRENCH FRIES unicode', 'emojis/iphone-emoji/FRENCH_FRIES.png'},
   {'🍠', '🍠 ROASTED SWEET POTATO unicode', 'emojis/iphone-emoji/ROASTED_SWEET_POTATO.png'},
   {'🍡', '🍡 DANGO unicode', 'emojis/iphone-emoji/DANGO.png'},
   {'🍢', '🍢 ODEN unicode', 'emojis/iphone-emoji/ODEN.png'},
   {'🍣', '🍣 SUSHI unicode', 'emojis/iphone-emoji/SUSHI.png'},
   {'🍤', '🍤 FRIED SHRIMP unicode', 'emojis/iphone-emoji/FRIED_SHRIMP.png'},
   {'🍥', '🍥 FISH CAKE WITH SWIRL DESIGN unicode', 'emojis/iphone-emoji/FISH_CAKE_WITH_SWIRL_DESIGN.png'},
   {'🍦', '🍦 SOFT ICE CREAM unicode', 'emojis/iphone-emoji/SOFT_ICE_CREAM.png'},
   {'🍧', '🍧 SHAVED ICE unicode', 'emojis/iphone-emoji/SHAVED_ICE.png'},
   {'🍨', '🍨 ICE CREAM unicode', 'emojis/iphone-emoji/ICE_CREAM.png'},
   {'🍩', '🍩 DOUGHNUT unicode', 'emojis/iphone-emoji/DOUGHNUT.png'},
   {'🍪', '🍪 COOKIE unicode', 'emojis/iphone-emoji/COOKIE.png'},
   {'🍫', '🍫 CHOCOLATE BAR unicode', 'emojis/iphone-emoji/CHOCOLATE_BAR.png'},
   {'🍬', '🍬 CANDY unicode', 'emojis/iphone-emoji/CANDY.png'},
   {'🍭', '🍭 LOLLIPOP unicode', 'emojis/iphone-emoji/LOLLIPOP.png'},
   {'🍮', '🍮 CUSTARD unicode', 'emojis/iphone-emoji/CUSTARD.png'},
   {'🍯', '🍯 HONEY POT unicode', 'emojis/iphone-emoji/HONEY_POT.png'},
   {'🍰', '🍰 SHORTCAKE unicode', 'emojis/iphone-emoji/SHORTCAKE.png'},
   {'🍱', '🍱 BENTO BOX unicode', 'emojis/iphone-emoji/BENTO_BOX.png'},
   {'🍲', '🍲 POT OF FOOD unicode', 'emojis/iphone-emoji/POT_OF_FOOD.png'},
   {'🍳', '🍳 COOKING unicode', 'emojis/iphone-emoji/COOKING.png'},
   {'🍴', '🍴 FORK AND KNIFE unicode', 'emojis/iphone-emoji/FORK_AND_KNIFE.png'},
   {'🍵', '🍵 TEACUP WITHOUT HANDLE unicode', 'emojis/iphone-emoji/TEACUP_WITHOUT_HANDLE.png'},
   {'🍶', '🍶 SAKE BOTTLE AND CUP unicode', 'emojis/iphone-emoji/SAKE_BOTTLE_AND_CUP.png'},
   {'🍷', '🍷 WINE GLASS unicode', 'emojis/iphone-emoji/WINE_GLASS.png'},
   {'🍸', '🍸 COCKTAIL GLASS unicode', 'emojis/iphone-emoji/COCKTAIL_GLASS.png'},
   {'🍹', '🍹 TROPICAL DRINK unicode', 'emojis/iphone-emoji/TROPICAL_DRINK.png'},
   {'🍺', '🍺 BEER MUG unicode', 'emojis/iphone-emoji/BEER_MUG.png'},
   {'🍻', '🍻 CLINKING BEER MUGS unicode', 'emojis/iphone-emoji/CLINKING_BEER_MUGS.png'},
   {'🍼', '🍼 BABY BOTTLE unicode', 'emojis/iphone-emoji/BABY_BOTTLE.png'},
   {'🎀', '🎀 RIBBON unicode', 'emojis/iphone-emoji/RIBBON.png'},
   {'🎁', '🎁 WRAPPED PRESENT unicode', 'emojis/iphone-emoji/WRAPPED_PRESENT.png'},
   {'🎂', '🎂 BIRTHDAY CAKE unicode', 'emojis/iphone-emoji/BIRTHDAY_CAKE.png'},
   {'🎃', '🎃 JACK-O-LANTERN unicode', 'emojis/iphone-emoji/JACK-O-LANTERN.png'},
   {'🎄', '🎄 CHRISTMAS TREE unicode', 'emojis/iphone-emoji/CHRISTMAS_TREE.png'},
   {'🎅', '🎅 FATHER CHRISTMAS unicode', 'emojis/iphone-emoji/FATHER_CHRISTMAS.png'},
   {'🎆', '🎆 FIREWORKS unicode', 'emojis/iphone-emoji/FIREWORKS.png'},
   {'🎇', '🎇 FIREWORK SPARKLER unicode', 'emojis/iphone-emoji/FIREWORK_SPARKLER.png'},
   {'🎈', '🎈 BALLOON unicode', 'emojis/iphone-emoji/BALLOON.png'},
   {'🎉', '🎉 PARTY POPPER unicode', 'emojis/iphone-emoji/PARTY_POPPER.png'},
   {'🎊', '🎊 CONFETTI BALL unicode', 'emojis/iphone-emoji/CONFETTI_BALL.png'},
   {'🎋', '🎋 TANABATA TREE unicode', 'emojis/iphone-emoji/TANABATA_TREE.png'},
   {'🎌', '🎌 CROSSED FLAGS unicode', 'emojis/iphone-emoji/CROSSED_FLAGS.png'},
   {'🎍', '🎍 PINE DECORATION unicode', 'emojis/iphone-emoji/PINE_DECORATION.png'},
   {'🎎', '🎎 JAPANESE DOLLS unicode', 'emojis/iphone-emoji/JAPANESE_DOLLS.png'},
   {'🎏', '🎏 CARP STREAMER unicode', 'emojis/iphone-emoji/CARP_STREAMER.png'},
   {'🎐', '🎐 WIND CHIME unicode', 'emojis/iphone-emoji/WIND_CHIME.png'},
   {'🎑', '🎑 MOON VIEWING CEREMONY unicode', 'emojis/iphone-emoji/MOON_VIEWING_CEREMONY.png'},
   {'🎒', '🎒 SCHOOL SATCHEL unicode', 'emojis/iphone-emoji/SCHOOL_SATCHEL.png'},
   {'🎓', '🎓 GRADUATION CAP unicode', 'emojis/iphone-emoji/GRADUATION_CAP.png'},
   {'🎠', '🎠 CAROUSEL HORSE unicode', 'emojis/iphone-emoji/CAROUSEL_HORSE.png'},
   {'🎡', '🎡 FERRIS WHEEL unicode', 'emojis/iphone-emoji/FERRIS_WHEEL.png'},
   {'🎢', '🎢 ROLLER COASTER unicode', 'emojis/iphone-emoji/ROLLER_COASTER.png'},
   {'🎣', '🎣 FISHING POLE AND FISH unicode', 'emojis/iphone-emoji/FISHING_POLE_AND_FISH.png'},
   {'🎤', '🎤 MICROPHONE unicode', 'emojis/iphone-emoji/MICROPHONE.png'},
   {'🎥', '🎥 MOVIE CAMERA unicode', 'emojis/iphone-emoji/MOVIE_CAMERA.png'},
   {'🎦', '🎦 CINEMA unicode', 'emojis/iphone-emoji/CINEMA.png'},
   {'🎧', '🎧 HEADPHONE unicode', 'emojis/iphone-emoji/HEADPHONE.png'},
   {'🎨', '🎨 ARTIST PALETTE unicode', 'emojis/iphone-emoji/ARTIST_PALETTE.png'},
   {'🎩', '🎩 TOP HAT unicode', 'emojis/iphone-emoji/TOP_HAT.png'},
   {'🎪', '🎪 CIRCUS TENT unicode', 'emojis/iphone-emoji/CIRCUS_TENT.png'},
   {'🎫', '🎫 TICKET unicode', 'emojis/iphone-emoji/TICKET.png'},
   {'🎬', '🎬 CLAPPER BOARD unicode', 'emojis/iphone-emoji/CLAPPER_BOARD.png'},
   {'🎭', '🎭 PERFORMING ARTS unicode', 'emojis/iphone-emoji/PERFORMING_ARTS.png'},
   {'🎮', '🎮 VIDEO GAME unicode', 'emojis/iphone-emoji/VIDEO_GAME.png'},
   {'🎯', '🎯 DIRECT HIT unicode', 'emojis/iphone-emoji/DIRECT_HIT.png'},
   {'🎰', '🎰 SLOT MACHINE unicode', 'emojis/iphone-emoji/SLOT_MACHINE.png'},
   {'🎱', '🎱 BILLIARDS unicode', 'emojis/iphone-emoji/BILLIARDS.png'},
   {'🎲', '🎲 GAME DIE unicode', 'emojis/iphone-emoji/GAME_DIE.png'},
   {'🎳', '🎳 BOWLING unicode', 'emojis/iphone-emoji/BOWLING.png'},
   {'🎴', '🎴 FLOWER PLAYING CARDS unicode', 'emojis/iphone-emoji/FLOWER_PLAYING_CARDS.png'},
   {'🎵', '🎵 MUSICAL NOTE unicode', 'emojis/iphone-emoji/MUSICAL_NOTE.png'},
   {'🎶', '🎶 MULTIPLE MUSICAL NOTES unicode', 'emojis/iphone-emoji/MULTIPLE_MUSICAL_NOTES.png'},
   {'🎷', '🎷 SAXOPHONE unicode', 'emojis/iphone-emoji/SAXOPHONE.png'},
   {'🎸', '🎸 GUITAR unicode', 'emojis/iphone-emoji/GUITAR.png'},
   {'🎹', '🎹 MUSICAL KEYBOARD unicode', 'emojis/iphone-emoji/MUSICAL_KEYBOARD.png'},
   {'🎺', '🎺 TRUMPET unicode', 'emojis/iphone-emoji/TRUMPET.png'},
   {'🎻', '🎻 VIOLIN unicode', 'emojis/iphone-emoji/VIOLIN.png'},
   {'🎼', '🎼 MUSICAL SCORE unicode', 'emojis/iphone-emoji/MUSICAL_SCORE.png'},
   {'🎽', '🎽 RUNNING SHIRT WITH SASH unicode', 'emojis/iphone-emoji/RUNNING_SHIRT_WITH_SASH.png'},
   {'🎾', '🎾 TENNIS RACQUET AND BALL unicode', 'emojis/iphone-emoji/TENNIS_RACQUET_AND_BALL.png'},
   {'🎿', '🎿 SKI AND SKI BOOT unicode', 'emojis/iphone-emoji/SKI_AND_SKI_BOOT.png'},
   {'🏀', '🏀 BASKETBALL AND HOOP unicode', 'emojis/iphone-emoji/BASKETBALL_AND_HOOP.png'},
   {'🏁', '🏁 CHEQUERED FLAG unicode', 'emojis/iphone-emoji/CHEQUERED_FLAG.png'},
   {'🏂', '🏂 SNOWBOARDER unicode', 'emojis/iphone-emoji/SNOWBOARDER.png'},
   {'🏃', '🏃 RUNNER unicode', 'emojis/iphone-emoji/RUNNER.png'},
   {'🏄', '🏄 SURFER unicode', 'emojis/iphone-emoji/SURFER.png'},
   {'🏆', '🏆 TROPHY unicode', 'emojis/iphone-emoji/TROPHY.png'},
   {'🏇', '🏇 HORSE RACING unicode', 'emojis/iphone-emoji/HORSE_RACING.png'},
   {'🏈', '🏈 AMERICAN FOOTBALL unicode', 'emojis/iphone-emoji/AMERICAN_FOOTBALL.png'},
   {'🏉', '🏉 RUGBY FOOTBALL unicode', 'emojis/iphone-emoji/RUGBY_FOOTBALL.png'},
   {'🏊', '🏊 SWIMMER unicode', 'emojis/iphone-emoji/SWIMMER.png'},
   {'🏠', '🏠 HOUSE BUILDING unicode', 'emojis/iphone-emoji/HOUSE_BUILDING.png'},
   {'🏡', '🏡 HOUSE WITH GARDEN unicode', 'emojis/iphone-emoji/HOUSE_WITH_GARDEN.png'},
   {'🏢', '🏢 OFFICE BUILDING unicode', 'emojis/iphone-emoji/OFFICE_BUILDING.png'},
   {'🏣', '🏣 JAPANESE POST OFFICE unicode', 'emojis/iphone-emoji/JAPANESE_POST_OFFICE.png'},
   {'🏤', '🏤 EUROPEAN POST OFFICE unicode', 'emojis/iphone-emoji/EUROPEAN_POST_OFFICE.png'},
   {'🏥', '🏥 HOSPITAL unicode', 'emojis/iphone-emoji/HOSPITAL.png'},
   {'🏦', '🏦 BANK unicode', 'emojis/iphone-emoji/BANK.png'},
   {'🏧', '🏧 AUTOMATED TELLER MACHINE unicode', 'emojis/iphone-emoji/AUTOMATED_TELLER_MACHINE.png'},
   {'🏨', '🏨 HOTEL unicode', 'emojis/iphone-emoji/HOTEL.png'},
   {'🏩', '🏩 LOVE HOTEL unicode', 'emojis/iphone-emoji/LOVE_HOTEL.png'},
   {'🏪', '🏪 CONVENIENCE STORE unicode', 'emojis/iphone-emoji/CONVENIENCE_STORE.png'},
   {'🏫', '🏫 SCHOOL unicode', 'emojis/iphone-emoji/SCHOOL.png'},
   {'🏬', '🏬 DEPARTMENT STORE unicode', 'emojis/iphone-emoji/DEPARTMENT_STORE.png'},
   {'🏭', '🏭 FACTORY unicode', 'emojis/iphone-emoji/FACTORY.png'},
   {'🏮', '🏮 IZAKAYA LANTERN unicode', 'emojis/iphone-emoji/IZAKAYA_LANTERN.png'},
   {'🏯', '🏯 JAPANESE CASTLE unicode', 'emojis/iphone-emoji/JAPANESE_CASTLE.png'},
   {'🏰', '🏰 EUROPEAN CASTLE unicode', 'emojis/iphone-emoji/EUROPEAN_CASTLE.png'},
   {'🐀', '🐀 RAT unicode', 'emojis/iphone-emoji/RAT.png'},
   {'🐁', '🐁 MOUSE unicode', 'emojis/iphone-emoji/MOUSE.png'},
   {'🐂', '🐂 OX unicode', 'emojis/iphone-emoji/OX.png'},
   {'🐃', '🐃 WATER BUFFALO unicode', 'emojis/iphone-emoji/WATER_BUFFALO.png'},
   {'🐄', '🐄 COW unicode', 'emojis/iphone-emoji/COW.png'},
   {'🐅', '🐅 TIGER unicode', 'emojis/iphone-emoji/TIGER.png'},
   {'🐆', '🐆 LEOPARD unicode', 'emojis/iphone-emoji/LEOPARD.png'},
   {'🐇', '🐇 RABBIT unicode', 'emojis/iphone-emoji/RABBIT.png'},
   {'🐈', '🐈 CAT unicode', 'emojis/iphone-emoji/CAT.png'},
   {'🐉', '🐉 DRAGON unicode', 'emojis/iphone-emoji/DRAGON.png'},
   {'🐊', '🐊 CROCODILE unicode', 'emojis/iphone-emoji/CROCODILE.png'},
   {'🐋', '🐋 WHALE unicode', 'emojis/iphone-emoji/WHALE.png'},
   {'🐌', '🐌 SNAIL unicode', 'emojis/iphone-emoji/SNAIL.png'},
   {'🐍', '🐍 SNAKE unicode', 'emojis/iphone-emoji/SNAKE.png'},
   {'🐎', '🐎 HORSE unicode', 'emojis/iphone-emoji/HORSE.png'},
   {'🐏', '🐏 RAM unicode', 'emojis/iphone-emoji/RAM.png'},
   {'🐐', '🐐 GOAT unicode', 'emojis/iphone-emoji/GOAT.png'},
   {'🐑', '🐑 SHEEP unicode', 'emojis/iphone-emoji/SHEEP.png'},
   {'🐒', '🐒 MONKEY unicode', 'emojis/iphone-emoji/MONKEY.png'},
   {'🐓', '🐓 ROOSTER unicode', 'emojis/iphone-emoji/ROOSTER.png'},
   {'🐔', '🐔 CHICKEN unicode', 'emojis/iphone-emoji/CHICKEN.png'},
   {'🐕', '🐕 DOG unicode', 'emojis/iphone-emoji/DOG.png'},
   {'🐖', '🐖 PIG unicode', 'emojis/iphone-emoji/PIG.png'},
   {'🐗', '🐗 BOAR unicode', 'emojis/iphone-emoji/BOAR.png'},
   {'🐘', '🐘 ELEPHANT unicode', 'emojis/iphone-emoji/ELEPHANT.png'},
   {'🐙', '🐙 OCTOPUS unicode', 'emojis/iphone-emoji/OCTOPUS.png'},
   {'🐚', '🐚 SPIRAL SHELL unicode', 'emojis/iphone-emoji/SPIRAL_SHELL.png'},
   {'🐛', '🐛 BUG unicode', 'emojis/iphone-emoji/BUG.png'},
   {'🐜', '🐜 ANT unicode', 'emojis/iphone-emoji/ANT.png'},
   {'🐝', '🐝 HONEYBEE unicode', 'emojis/iphone-emoji/HONEYBEE.png'},
   {'🐞', '🐞 LADY BEETLE unicode', 'emojis/iphone-emoji/LADY_BEETLE.png'},
   {'🐟', '🐟 FISH unicode', 'emojis/iphone-emoji/FISH.png'},
   {'🐠', '🐠 TROPICAL FISH unicode', 'emojis/iphone-emoji/TROPICAL_FISH.png'},
   {'🐡', '🐡 BLOWFISH unicode', 'emojis/iphone-emoji/BLOWFISH.png'},
   {'🐢', '🐢 TURTLE unicode', 'emojis/iphone-emoji/TURTLE.png'},
   {'🐣', '🐣 HATCHING CHICK unicode', 'emojis/iphone-emoji/HATCHING_CHICK.png'},
   {'🐤', '🐤 BABY CHICK unicode', 'emojis/iphone-emoji/BABY_CHICK.png'},
   {'🐥', '🐥 FRONT-FACING BABY CHICK unicode', 'emojis/iphone-emoji/FRONT-FACING_BABY_CHICK.png'},
   {'🐦', '🐦 BIRD unicode', 'emojis/iphone-emoji/BIRD.png'},
   {'🐧', '🐧 PENGUIN unicode', 'emojis/iphone-emoji/PENGUIN.png'},
   {'🐨', '🐨 KOALA unicode', 'emojis/iphone-emoji/KOALA.png'},
   {'🐩', '🐩 POODLE unicode', 'emojis/iphone-emoji/POODLE.png'},
   {'🐪', '🐪 DROMEDARY CAMEL unicode', 'emojis/iphone-emoji/DROMEDARY_CAMEL.png'},
   {'🐫', '🐫 BACTRIAN CAMEL unicode', 'emojis/iphone-emoji/BACTRIAN_CAMEL.png'},
   {'🐬', '🐬 DOLPHIN unicode', 'emojis/iphone-emoji/DOLPHIN.png'},
   {'🐭', '🐭 MOUSE FACE unicode', 'emojis/iphone-emoji/MOUSE_FACE.png'},
   {'🐮', '🐮 COW FACE unicode', 'emojis/iphone-emoji/COW_FACE.png'},
   {'🐯', '🐯 TIGER FACE unicode', 'emojis/iphone-emoji/TIGER_FACE.png'},
   {'🐰', '🐰 RABBIT FACE unicode', 'emojis/iphone-emoji/RABBIT_FACE.png'},
   {'🐱', '🐱 CAT FACE unicode', 'emojis/iphone-emoji/CAT_FACE.png'},
   {'🐲', '🐲 DRAGON FACE unicode', 'emojis/iphone-emoji/DRAGON_FACE.png'},
   {'🐳', '🐳 SPOUTING WHALE unicode', 'emojis/iphone-emoji/SPOUTING_WHALE.png'},
   {'🐴', '🐴 HORSE FACE unicode', 'emojis/iphone-emoji/HORSE_FACE.png'},
   {'🐵', '🐵 MONKEY FACE unicode', 'emojis/iphone-emoji/MONKEY_FACE.png'},
   {'🐶', '🐶 DOG FACE unicode', 'emojis/iphone-emoji/DOG_FACE.png'},
   {'🐷', '🐷 PIG FACE unicode', 'emojis/iphone-emoji/PIG_FACE.png'},
   {'🐸', '🐸 FROG FACE unicode', 'emojis/iphone-emoji/FROG_FACE.png'},
   {'🐹', '🐹 HAMSTER FACE unicode', 'emojis/iphone-emoji/HAMSTER_FACE.png'},
   {'🐺', '🐺 WOLF FACE unicode', 'emojis/iphone-emoji/WOLF_FACE.png'},
   {'🐻', '🐻 BEAR FACE unicode', 'emojis/iphone-emoji/BEAR_FACE.png'},
   {'🐼', '🐼 PANDA FACE unicode', 'emojis/iphone-emoji/PANDA_FACE.png'},
   {'🐽', '🐽 PIG NOSE unicode', 'emojis/iphone-emoji/PIG_NOSE.png'},
   {'🐾', '🐾 PAW PRINTS unicode', 'emojis/iphone-emoji/PAW_PRINTS.png'},
   {'👀', '👀 EYES unicode', 'emojis/iphone-emoji/EYES.png'},
   {'👂', '👂 EAR unicode', 'emojis/iphone-emoji/EAR.png'},
   {'👃', '👃 NOSE unicode', 'emojis/iphone-emoji/NOSE.png'},
   {'👄', '👄 MOUTH unicode', 'emojis/iphone-emoji/MOUTH.png'},
   {'👅', '👅 TONGUE unicode', 'emojis/iphone-emoji/TONGUE.png'},
   {'👆', '👆 WHITE UP POINTING BACKHAND INDEX unicode', 'emojis/iphone-emoji/WHITE_UP_POINTING_BACKHAND_INDEX.png'},
   {'👇', '👇 WHITE DOWN POINTING BACKHAND INDEX unicode', 'emojis/iphone-emoji/WHITE_DOWN_POINTING_BACKHAND_INDEX.png'},
   {'👈', '👈 WHITE LEFT POINTING BACKHAND INDEX unicode', 'emojis/iphone-emoji/WHITE_LEFT_POINTING_BACKHAND_INDEX.png'},
   {'👉', '👉 WHITE RIGHT POINTING BACKHAND INDEX unicode', 'emojis/iphone-emoji/WHITE_RIGHT_POINTING_BACKHAND_INDEX.png'},
   {'👊', '👊 FISTED HAND SIGN unicode', 'emojis/iphone-emoji/FISTED_HAND_SIGN.png'},
   {'👋', '👋 WAVING HAND SIGN unicode', 'emojis/iphone-emoji/WAVING_HAND_SIGN.png'},
   {'👌', '👌 OK HAND SIGN unicode', 'emojis/iphone-emoji/OK_HAND_SIGN.png'},
   {'👍', '👍 THUMBS UP SIGN unicode', 'emojis/iphone-emoji/THUMBS_UP_SIGN.png'},
   {'👎', '👎 THUMBS DOWN SIGN unicode', 'emojis/iphone-emoji/THUMBS_DOWN_SIGN.png'},
   {'👏', '👏 CLAPPING HANDS SIGN unicode', 'emojis/iphone-emoji/CLAPPING_HANDS_SIGN.png'},
   {'👐', '👐 OPEN HANDS SIGN unicode', 'emojis/iphone-emoji/OPEN_HANDS_SIGN.png'},
   {'👑', '👑 CROWN unicode', 'emojis/iphone-emoji/CROWN.png'},
   {'👒', '👒 WOMANS HAT unicode', 'emojis/iphone-emoji/WOMANS_HAT.png'},
   {'👓', '👓 EYEGLASSES unicode', 'emojis/iphone-emoji/EYEGLASSES.png'},
   {'👔', '👔 NECKTIE unicode', 'emojis/iphone-emoji/NECKTIE.png'},
   {'👕', '👕 T-SHIRT unicode', 'emojis/iphone-emoji/T-SHIRT.png'},
   {'👖', '👖 JEANS unicode', 'emojis/iphone-emoji/JEANS.png'},
   {'👗', '👗 DRESS unicode', 'emojis/iphone-emoji/DRESS.png'},
   {'👘', '👘 KIMONO unicode', 'emojis/iphone-emoji/KIMONO.png'},
   {'👙', '👙 BIKINI unicode', 'emojis/iphone-emoji/BIKINI.png'},
   {'👚', '👚 WOMANS CLOTHES unicode', 'emojis/iphone-emoji/WOMANS_CLOTHES.png'},
   {'👛', '👛 PURSE unicode', 'emojis/iphone-emoji/PURSE.png'},
   {'👜', '👜 HANDBAG unicode', 'emojis/iphone-emoji/HANDBAG.png'},
   {'👝', '👝 POUCH unicode', 'emojis/iphone-emoji/POUCH.png'},
   {'👞', '👞 MANS SHOE unicode', 'emojis/iphone-emoji/MANS_SHOE.png'},
   {'👟', '👟 ATHLETIC SHOE unicode', 'emojis/iphone-emoji/ATHLETIC_SHOE.png'},
   {'👠', '👠 HIGH-HEELED SHOE unicode', 'emojis/iphone-emoji/HIGH-HEELED_SHOE.png'},
   {'👡', '👡 WOMANS SANDAL unicode', 'emojis/iphone-emoji/WOMANS_SANDAL.png'},
   {'👢', '👢 WOMANS BOOTS unicode', 'emojis/iphone-emoji/WOMANS_BOOTS.png'},
   {'👣', '👣 FOOTPRINTS unicode', 'emojis/iphone-emoji/FOOTPRINTS.png'},
   {'👤', '👤 BUST IN SILHOUETTE unicode', 'emojis/iphone-emoji/BUST_IN_SILHOUETTE.png'},
   {'👥', '👥 BUSTS IN SILHOUETTE unicode', 'emojis/iphone-emoji/BUSTS_IN_SILHOUETTE.png'},
   {'👦', '👦 BOY unicode', 'emojis/iphone-emoji/BOY.png'},
   {'👧', '👧 GIRL unicode', 'emojis/iphone-emoji/GIRL.png'},
   {'👨', '👨 MAN unicode', 'emojis/iphone-emoji/MAN.png'},
   {'👩', '👩 WOMAN unicode', 'emojis/iphone-emoji/WOMAN.png'},
   {'👪', '👪 FAMILY unicode', 'emojis/iphone-emoji/FAMILY.png'},
   {'👫', '👫 MAN AND WOMAN HOLDING HANDS unicode', 'emojis/iphone-emoji/MAN_AND_WOMAN_HOLDING_HANDS.png'},
   {'👬', '👬 TWO MEN HOLDING HANDS unicode', 'emojis/iphone-emoji/TWO_MEN_HOLDING_HANDS.png'},
   {'👭', '👭 TWO WOMEN HOLDING HANDS unicode', 'emojis/iphone-emoji/TWO_WOMEN_HOLDING_HANDS.png'},
   {'👮', '👮 POLICE OFFICER unicode', 'emojis/iphone-emoji/POLICE_OFFICER.png'},
   {'👯', '👯 WOMAN WITH BUNNY EARS unicode', 'emojis/iphone-emoji/WOMAN_WITH_BUNNY_EARS.png'},
   {'👰', '👰 BRIDE WITH VEIL unicode', 'emojis/iphone-emoji/BRIDE_WITH_VEIL.png'},
   {'👱', '👱 PERSON WITH BLOND HAIR unicode', 'emojis/iphone-emoji/PERSON_WITH_BLOND_HAIR.png'},
   {'👲', '👲 MAN WITH GUA PI MAO unicode', 'emojis/iphone-emoji/MAN_WITH_GUA_PI_MAO.png'},
   {'👳', '👳 MAN WITH TURBAN unicode', 'emojis/iphone-emoji/MAN_WITH_TURBAN.png'},
   {'👴', '👴 OLDER MAN unicode', 'emojis/iphone-emoji/OLDER_MAN.png'},
   {'👵', '👵 OLDER WOMAN unicode', 'emojis/iphone-emoji/OLDER_WOMAN.png'},
   {'👶', '👶 BABY unicode', 'emojis/iphone-emoji/BABY.png'},
   {'👷', '👷 CONSTRUCTION WORKER unicode', 'emojis/iphone-emoji/CONSTRUCTION_WORKER.png'},
   {'👸', '👸 PRINCESS unicode', 'emojis/iphone-emoji/PRINCESS.png'},
   {'👹', '👹 JAPANESE OGRE unicode', 'emojis/iphone-emoji/JAPANESE_OGRE.png'},
   {'👺', '👺 JAPANESE GOBLIN unicode', 'emojis/iphone-emoji/JAPANESE_GOBLIN.png'},
   {'👻', '👻 GHOST unicode', 'emojis/iphone-emoji/GHOST.png'},
   {'👼', '👼 BABY ANGEL unicode', 'emojis/iphone-emoji/BABY_ANGEL.png'},
   {'👽', '👽 EXTRATERRESTRIAL ALIEN unicode', 'emojis/iphone-emoji/EXTRATERRESTRIAL_ALIEN.png'},
   {'👾', '👾 ALIEN MONSTER unicode', 'emojis/iphone-emoji/ALIEN_MONSTER.png'},
   {'👿', '👿 IMP unicode', 'emojis/iphone-emoji/IMP.png'},
   {'💀', '💀 SKULL unicode', 'emojis/iphone-emoji/SKULL.png'},
   {'💁', '💁 INFORMATION DESK PERSON unicode', 'emojis/iphone-emoji/INFORMATION_DESK_PERSON.png'},
   {'💂', '💂 GUARDSMAN unicode', 'emojis/iphone-emoji/GUARDSMAN.png'},
   {'💃', '💃 DANCER unicode', 'emojis/iphone-emoji/DANCER.png'},
   {'💄', '💄 LIPSTICK unicode', 'emojis/iphone-emoji/LIPSTICK.png'},
   {'💅', '💅 NAIL POLISH unicode', 'emojis/iphone-emoji/NAIL_POLISH.png'},
   {'💆', '💆 FACE MASSAGE unicode', 'emojis/iphone-emoji/FACE_MASSAGE.png'},
   {'💇', '💇 HAIRCUT unicode', 'emojis/iphone-emoji/HAIRCUT.png'},
   {'💈', '💈 BARBER POLE unicode', 'emojis/iphone-emoji/BARBER_POLE.png'},
   {'💉', '💉 SYRINGE unicode', 'emojis/iphone-emoji/SYRINGE.png'},
   {'💊', '💊 PILL unicode', 'emojis/iphone-emoji/PILL.png'},
   {'💋', '💋 KISS MARK unicode', 'emojis/iphone-emoji/KISS_MARK.png'},
   {'💌', '💌 LOVE LETTER unicode', 'emojis/iphone-emoji/LOVE_LETTER.png'},
   {'💍', '💍 RING unicode', 'emojis/iphone-emoji/RING.png'},
   {'💎', '💎 GEM STONE unicode', 'emojis/iphone-emoji/GEM_STONE.png'},
   {'💏', '💏 KISS unicode', 'emojis/iphone-emoji/KISS.png'},
   {'💐', '💐 BOUQUET unicode', 'emojis/iphone-emoji/BOUQUET.png'},
   {'💑', '💑 COUPLE WITH HEART unicode', 'emojis/iphone-emoji/COUPLE_WITH_HEART.png'},
   {'💒', '💒 WEDDING unicode', 'emojis/iphone-emoji/WEDDING.png'},
   {'💓', '💓 BEATING HEART unicode', 'emojis/iphone-emoji/BEATING_HEART.png'},
   {'💔', '💔 BROKEN HEART unicode', 'emojis/iphone-emoji/BROKEN_HEART.png'},
   {'💕', '💕 TWO HEARTS unicode', 'emojis/iphone-emoji/TWO_HEARTS.png'},
   {'💖', '💖 SPARKLING HEART unicode', 'emojis/iphone-emoji/SPARKLING_HEART.png'},
   {'💗', '💗 GROWING HEART unicode', 'emojis/iphone-emoji/GROWING_HEART.png'},
   {'💘', '💘 HEART WITH ARROW unicode', 'emojis/iphone-emoji/HEART_WITH_ARROW.png'},
   {'💙', '💙 BLUE HEART unicode', 'emojis/iphone-emoji/BLUE_HEART.png'},
   {'💚', '💚 GREEN HEART unicode', 'emojis/iphone-emoji/GREEN_HEART.png'},
   {'💛', '💛 YELLOW HEART unicode', 'emojis/iphone-emoji/YELLOW_HEART.png'},
   {'💜', '💜 PURPLE HEART unicode', 'emojis/iphone-emoji/PURPLE_HEART.png'},
   {'💝', '💝 HEART WITH RIBBON unicode', 'emojis/iphone-emoji/HEART_WITH_RIBBON.png'},
   {'💞', '💞 REVOLVING HEARTS unicode', 'emojis/iphone-emoji/REVOLVING_HEARTS.png'},
   {'💟', '💟 HEART DECORATION unicode', 'emojis/iphone-emoji/HEART_DECORATION.png'},
   {'💠', '💠 DIAMOND SHAPE WITH A DOT INSIDE unicode', 'emojis/iphone-emoji/DIAMOND_SHAPE_WITH_A_DOT_INSIDE.png'},
   {'💡', '💡 ELECTRIC LIGHT BULB unicode', 'emojis/iphone-emoji/ELECTRIC_LIGHT_BULB.png'},
   {'💢', '💢 ANGER SYMBOL unicode', 'emojis/iphone-emoji/ANGER_SYMBOL.png'},
   {'💣', '💣 BOMB unicode', 'emojis/iphone-emoji/BOMB.png'},
   {'💤', '💤 SLEEPING SYMBOL unicode', 'emojis/iphone-emoji/SLEEPING_SYMBOL.png'},
   {'💥', '💥 COLLISION SYMBOL unicode', 'emojis/iphone-emoji/COLLISION_SYMBOL.png'},
   {'💦', '💦 SPLASHING SWEAT SYMBOL unicode', 'emojis/iphone-emoji/SPLASHING_SWEAT_SYMBOL.png'},
   {'💧', '💧 DROPLET unicode', 'emojis/iphone-emoji/DROPLET.png'},
   {'💨', '💨 DASH SYMBOL unicode', 'emojis/iphone-emoji/DASH_SYMBOL.png'},
   {'💩', '💩 PILE OF POO unicode', 'emojis/iphone-emoji/PILE_OF_POO.png'},
   {'💪', '💪 FLEXED BICEPS unicode', 'emojis/iphone-emoji/FLEXED_BICEPS.png'},
   {'💫', '💫 DIZZY SYMBOL unicode', 'emojis/iphone-emoji/DIZZY_SYMBOL.png'},
   {'💬', '💬 SPEECH BALLOON unicode', 'emojis/iphone-emoji/SPEECH_BALLOON.png'},
   {'💭', '💭 THOUGHT BALLOON unicode', 'emojis/iphone-emoji/THOUGHT_BALLOON.png'},
   {'💮', '💮 WHITE FLOWER unicode', 'emojis/iphone-emoji/WHITE_FLOWER.png'},
   {'💯', '💯 HUNDRED POINTS SYMBOL unicode', 'emojis/iphone-emoji/HUNDRED_POINTS_SYMBOL.png'},
   {'💰', '💰 MONEY BAG unicode', 'emojis/iphone-emoji/MONEY_BAG.png'},
   {'💱', '💱 CURRENCY EXCHANGE unicode', 'emojis/iphone-emoji/CURRENCY_EXCHANGE.png'},
   {'💲', '💲 HEAVY DOLLAR SIGN unicode', 'emojis/iphone-emoji/HEAVY_DOLLAR_SIGN.png'},
   {'💳', '💳 CREDIT CARD unicode', 'emojis/iphone-emoji/CREDIT_CARD.png'},
   {'💴', '💴 BANKNOTE WITH YEN SIGN unicode', 'emojis/iphone-emoji/BANKNOTE_WITH_YEN_SIGN.png'},
   {'💵', '💵 BANKNOTE WITH DOLLAR SIGN unicode', 'emojis/iphone-emoji/BANKNOTE_WITH_DOLLAR_SIGN.png'},
   {'💶', '💶 BANKNOTE WITH EURO SIGN unicode', 'emojis/iphone-emoji/BANKNOTE_WITH_EURO_SIGN.png'},
   {'💷', '💷 BANKNOTE WITH POUND SIGN unicode', 'emojis/iphone-emoji/BANKNOTE_WITH_POUND_SIGN.png'},
   {'💸', '💸 MONEY WITH WINGS unicode', 'emojis/iphone-emoji/MONEY_WITH_WINGS.png'},
   {'💹', '💹 CHART WITH UPWARDS TREND AND YEN SIGN unicode', 'emojis/iphone-emoji/CHART_WITH_UPWARDS_TREND_AND_YEN_SIGN.png'},
   {'💺', '💺 SEAT unicode', 'emojis/iphone-emoji/SEAT.png'},
   {'💻', '💻 PERSONAL COMPUTER unicode', 'emojis/iphone-emoji/PERSONAL_COMPUTER.png'},
   {'💼', '💼 BRIEFCASE unicode', 'emojis/iphone-emoji/BRIEFCASE.png'},
   {'💽', '💽 MINIDISC unicode', 'emojis/iphone-emoji/MINIDISC.png'},
   {'💾', '💾 FLOPPY DISK unicode', 'emojis/iphone-emoji/FLOPPY_DISK.png'},
   {'💿', '💿 OPTICAL DISC unicode', 'emojis/iphone-emoji/OPTICAL_DISC.png'},
   {'📀', '📀 DVD unicode', 'emojis/iphone-emoji/DVD.png'},
   {'📁', '📁 FILE FOLDER unicode', 'emojis/iphone-emoji/FILE_FOLDER.png'},
   {'📂', '📂 OPEN FILE FOLDER unicode', 'emojis/iphone-emoji/OPEN_FILE_FOLDER.png'},
   {'📃', '📃 PAGE WITH CURL unicode', 'emojis/iphone-emoji/PAGE_WITH_CURL.png'},
   {'📄', '📄 PAGE FACING UP unicode', 'emojis/iphone-emoji/PAGE_FACING_UP.png'},
   {'📅', '📅 CALENDAR unicode', 'emojis/iphone-emoji/CALENDAR.png'},
   {'📆', '📆 TEAR-OFF CALENDAR unicode', 'emojis/iphone-emoji/TEAR-OFF_CALENDAR.png'},
   {'📇', '📇 CARD INDEX unicode', 'emojis/iphone-emoji/CARD_INDEX.png'},
   {'📈', '📈 CHART WITH UPWARDS TREND unicode', 'emojis/iphone-emoji/CHART_WITH_UPWARDS_TREND.png'},
   {'📉', '📉 CHART WITH DOWNWARDS TREND unicode', 'emojis/iphone-emoji/CHART_WITH_DOWNWARDS_TREND.png'},
   {'📊', '📊 BAR CHART unicode', 'emojis/iphone-emoji/BAR_CHART.png'},
   {'📋', '📋 CLIPBOARD unicode', 'emojis/iphone-emoji/CLIPBOARD.png'},
   {'📌', '📌 PUSHPIN unicode', 'emojis/iphone-emoji/PUSHPIN.png'},
   {'📍', '📍 ROUND PUSHPIN unicode', 'emojis/iphone-emoji/ROUND_PUSHPIN.png'},
   {'📎', '📎 PAPERCLIP unicode', 'emojis/iphone-emoji/PAPERCLIP.png'},
   {'📏', '📏 STRAIGHT RULER unicode', 'emojis/iphone-emoji/STRAIGHT_RULER.png'},
   {'📐', '📐 TRIANGULAR RULER unicode', 'emojis/iphone-emoji/TRIANGULAR_RULER.png'},
   {'📑', '📑 BOOKMARK TABS unicode', 'emojis/iphone-emoji/BOOKMARK_TABS.png'},
   {'📒', '📒 LEDGER unicode', 'emojis/iphone-emoji/LEDGER.png'},
   {'📓', '📓 NOTEBOOK unicode', 'emojis/iphone-emoji/NOTEBOOK.png'},
   {'📔', '📔 NOTEBOOK WITH DECORATIVE COVER unicode', 'emojis/iphone-emoji/NOTEBOOK_WITH_DECORATIVE_COVER.png'},
   {'📕', '📕 CLOSED BOOK unicode', 'emojis/iphone-emoji/CLOSED_BOOK.png'},
   {'📖', '📖 OPEN BOOK unicode', 'emojis/iphone-emoji/OPEN_BOOK.png'},
   {'📗', '📗 GREEN BOOK unicode', 'emojis/iphone-emoji/GREEN_BOOK.png'},
   {'📘', '📘 BLUE BOOK unicode', 'emojis/iphone-emoji/BLUE_BOOK.png'},
   {'📙', '📙 ORANGE BOOK unicode', 'emojis/iphone-emoji/ORANGE_BOOK.png'},
   {'📚', '📚 BOOKS unicode', 'emojis/iphone-emoji/BOOKS.png'},
   {'📛', '📛 NAME BADGE unicode', 'emojis/iphone-emoji/NAME_BADGE.png'},
   {'📜', '📜 SCROLL unicode', 'emojis/iphone-emoji/SCROLL.png'},
   {'📝', '📝 MEMO unicode', 'emojis/iphone-emoji/MEMO.png'},
   {'📞', '📞 TELEPHONE RECEIVER unicode', 'emojis/iphone-emoji/TELEPHONE_RECEIVER.png'},
   {'📟', '📟 PAGER unicode', 'emojis/iphone-emoji/PAGER.png'},
   {'📠', '📠 FAX MACHINE unicode', 'emojis/iphone-emoji/FAX_MACHINE.png'},
   {'📡', '📡 SATELLITE ANTENNA unicode', 'emojis/iphone-emoji/SATELLITE_ANTENNA.png'},
   {'📢', '📢 PUBLIC ADDRESS LOUDSPEAKER unicode', 'emojis/iphone-emoji/PUBLIC_ADDRESS_LOUDSPEAKER.png'},
   {'📣', '📣 CHEERING MEGAPHONE unicode', 'emojis/iphone-emoji/CHEERING_MEGAPHONE.png'},
   {'📤', '📤 OUTBOX TRAY unicode', 'emojis/iphone-emoji/OUTBOX_TRAY.png'},
   {'📥', '📥 INBOX TRAY unicode', 'emojis/iphone-emoji/INBOX_TRAY.png'},
   {'📦', '📦 PACKAGE unicode', 'emojis/iphone-emoji/PACKAGE.png'},
   {'📧', '📧 E-MAIL SYMBOL unicode', 'emojis/iphone-emoji/E-MAIL_SYMBOL.png'},
   {'📨', '📨 INCOMING ENVELOPE unicode', 'emojis/iphone-emoji/INCOMING_ENVELOPE.png'},
   {'📩', '📩 ENVELOPE WITH DOWNWARDS ARROW ABOVE unicode', 'emojis/iphone-emoji/ENVELOPE_WITH_DOWNWARDS_ARROW_ABOVE.png'},
   {'📪', '📪 CLOSED MAILBOX WITH LOWERED FLAG unicode', 'emojis/iphone-emoji/CLOSED_MAILBOX_WITH_LOWERED_FLAG.png'},
   {'📫', '📫 CLOSED MAILBOX WITH RAISED FLAG unicode', 'emojis/iphone-emoji/CLOSED_MAILBOX_WITH_RAISED_FLAG.png'},
   {'📬', '📬 OPEN MAILBOX WITH RAISED FLAG unicode', 'emojis/iphone-emoji/OPEN_MAILBOX_WITH_RAISED_FLAG.png'},
   {'📭', '📭 OPEN MAILBOX WITH LOWERED FLAG unicode', 'emojis/iphone-emoji/OPEN_MAILBOX_WITH_LOWERED_FLAG.png'},
   {'📮', '📮 POSTBOX unicode', 'emojis/iphone-emoji/POSTBOX.png'},
   {'📯', '📯 POSTAL HORN unicode', 'emojis/iphone-emoji/POSTAL_HORN.png'},
   {'📰', '📰 NEWSPAPER unicode', 'emojis/iphone-emoji/NEWSPAPER.png'},
   {'📱', '📱 MOBILE PHONE unicode', 'emojis/iphone-emoji/MOBILE_PHONE.png'},
   {'📲', '📲 MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT unicode', 'emojis/iphone-emoji/MOBILE_PHONE_WITH_RIGHTWARDS_ARROW_AT_LEFT.png'},
   {'📳', '📳 VIBRATION MODE unicode', 'emojis/iphone-emoji/VIBRATION_MODE.png'},
   {'📴', '📴 MOBILE PHONE OFF unicode', 'emojis/iphone-emoji/MOBILE_PHONE_OFF.png'},
   {'📵', '📵 NO MOBILE PHONES unicode', 'emojis/iphone-emoji/NO_MOBILE_PHONES.png'},
   {'📶', '📶 ANTENNA WITH BARS unicode', 'emojis/iphone-emoji/ANTENNA_WITH_BARS.png'},
   {'📷', '📷 CAMERA unicode', 'emojis/iphone-emoji/CAMERA.png'},
   {'📹', '📹 VIDEO CAMERA unicode', 'emojis/iphone-emoji/VIDEO_CAMERA.png'},
   {'📺', '📺 TELEVISION unicode', 'emojis/iphone-emoji/TELEVISION.png'},
   {'📻', '📻 RADIO unicode', 'emojis/iphone-emoji/RADIO.png'},
   {'📼', '📼 VIDEOCASSETTE unicode', 'emojis/iphone-emoji/VIDEOCASSETTE.png'},
   {'🔀', '🔀 TWISTED RIGHTWARDS ARROWS unicode', 'emojis/iphone-emoji/TWISTED_RIGHTWARDS_ARROWS.png'},
   {'🔁', '🔁 CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS unicode', 'emojis/iphone-emoji/CLOCKWISE_RIGHTWARDS_AND_LEFTWARDS_OPEN_CIRCLE_ARROWS.png'},
   {'🔂', '🔂 CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY unicode', 'emojis/iphone-emoji/CLOCKWISE_RIGHTWARDS_AND_LEFTWARDS_OPEN_CIRCLE_ARROWS_WITH_CIRCLED_ONE_OVERLAY.png'},
   {'🔃', '🔃 CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS unicode', 'emojis/iphone-emoji/CLOCKWISE_DOWNWARDS_AND_UPWARDS_OPEN_CIRCLE_ARROWS.png'},
   {'🔄', '🔄 ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS unicode', 'emojis/iphone-emoji/ANTICLOCKWISE_DOWNWARDS_AND_UPWARDS_OPEN_CIRCLE_ARROWS.png'},
   {'🔅', '🔅 LOW BRIGHTNESS SYMBOL unicode', 'emojis/iphone-emoji/LOW_BRIGHTNESS_SYMBOL.png'},
   {'🔆', '🔆 HIGH BRIGHTNESS SYMBOL unicode', 'emojis/iphone-emoji/HIGH_BRIGHTNESS_SYMBOL.png'},
   {'🔇', '🔇 SPEAKER WITH CANCELLATION STROKE unicode', 'emojis/iphone-emoji/SPEAKER_WITH_CANCELLATION_STROKE.png'},
   {'🔈', '🔈 SPEAKER unicode', 'emojis/iphone-emoji/SPEAKER.png'},
   {'🔉', '🔉 SPEAKER WITH ONE SOUND WAVE unicode', 'emojis/iphone-emoji/SPEAKER_WITH_ONE_SOUND_WAVE.png'},
   {'🔊', '🔊 SPEAKER WITH THREE SOUND WAVES unicode', 'emojis/iphone-emoji/SPEAKER_WITH_THREE_SOUND_WAVES.png'},
   {'🔋', '🔋 BATTERY unicode', 'emojis/iphone-emoji/BATTERY.png'},
   {'🔌', '🔌 ELECTRIC PLUG unicode', 'emojis/iphone-emoji/ELECTRIC_PLUG.png'},
   {'🔍', '🔍 LEFT-POINTING MAGNIFYING GLASS unicode', 'emojis/iphone-emoji/LEFT-POINTING_MAGNIFYING_GLASS.png'},
   {'🔎', '🔎 RIGHT-POINTING MAGNIFYING GLASS unicode', 'emojis/iphone-emoji/RIGHT-POINTING_MAGNIFYING_GLASS.png'},
   {'🔏', '🔏 LOCK WITH INK PEN unicode', 'emojis/iphone-emoji/LOCK_WITH_INK_PEN.png'},
   {'🔐', '🔐 CLOSED LOCK WITH KEY unicode', 'emojis/iphone-emoji/CLOSED_LOCK_WITH_KEY.png'},
   {'🔑', '🔑 KEY unicode', 'emojis/iphone-emoji/KEY.png'},
   {'🔒', '🔒 LOCK unicode', 'emojis/iphone-emoji/LOCK.png'},
   {'🔓', '🔓 OPEN LOCK unicode', 'emojis/iphone-emoji/OPEN_LOCK.png'},
   {'🔔', '🔔 BELL unicode', 'emojis/iphone-emoji/BELL.png'},
   {'🔕', '🔕 BELL WITH CANCELLATION STROKE unicode', 'emojis/iphone-emoji/BELL_WITH_CANCELLATION_STROKE.png'},
   {'🔖', '🔖 BOOKMARK unicode', 'emojis/iphone-emoji/BOOKMARK.png'},
   {'🔗', '🔗 LINK SYMBOL unicode', 'emojis/iphone-emoji/LINK_SYMBOL.png'},
   {'🔘', '🔘 RADIO BUTTON unicode', 'emojis/iphone-emoji/RADIO_BUTTON.png'},
   {'🔙', '🔙 BACK WITH LEFTWARDS ARROW ABOVE unicode', 'emojis/iphone-emoji/BACK_WITH_LEFTWARDS_ARROW_ABOVE.png'},
   {'🔚', '🔚 END WITH LEFTWARDS ARROW ABOVE unicode', 'emojis/iphone-emoji/END_WITH_LEFTWARDS_ARROW_ABOVE.png'},
   {'🔛', '🔛 ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE unicode', 'emojis/iphone-emoji/ON_WITH_EXCLAMATION_MARK_WITH_LEFT_RIGHT_ARROW_ABOVE.png'},
   {'🔜', '🔜 SOON WITH RIGHTWARDS ARROW ABOVE unicode', 'emojis/iphone-emoji/SOON_WITH_RIGHTWARDS_ARROW_ABOVE.png'},
   {'🔝', '🔝 TOP WITH UPWARDS ARROW ABOVE unicode', 'emojis/iphone-emoji/TOP_WITH_UPWARDS_ARROW_ABOVE.png'},
   {'🔞', '🔞 NO ONE UNDER EIGHTEEN SYMBOL unicode', 'emojis/iphone-emoji/NO_ONE_UNDER_EIGHTEEN_SYMBOL.png'},
   {'🔟', '🔟 KEYCAP TEN unicode', 'emojis/iphone-emoji/KEYCAP_TEN.png'},
   {'🔠', '🔠 INPUT SYMBOL FOR LATIN CAPITAL LETTERS unicode', 'emojis/iphone-emoji/INPUT_SYMBOL_FOR_LATIN_CAPITAL_LETTERS.png'},
   {'🔡', '🔡 INPUT SYMBOL FOR LATIN SMALL LETTERS unicode', 'emojis/iphone-emoji/INPUT_SYMBOL_FOR_LATIN_SMALL_LETTERS.png'},
   {'🔢', '🔢 INPUT SYMBOL FOR NUMBERS unicode', 'emojis/iphone-emoji/INPUT_SYMBOL_FOR_NUMBERS.png'},
   {'🔣', '🔣 INPUT SYMBOL FOR SYMBOLS unicode', 'emojis/iphone-emoji/INPUT_SYMBOL_FOR_SYMBOLS.png'},
   {'🔤', '🔤 INPUT SYMBOL FOR LATIN LETTERS unicode', 'emojis/iphone-emoji/INPUT_SYMBOL_FOR_LATIN_LETTERS.png'},
   {'🔥', '🔥 FIRE unicode', 'emojis/iphone-emoji/FIRE.png'},
   {'🔦', '🔦 ELECTRIC TORCH unicode', 'emojis/iphone-emoji/ELECTRIC_TORCH.png'},
   {'🔧', '🔧 WRENCH unicode', 'emojis/iphone-emoji/WRENCH.png'},
   {'🔨', '🔨 HAMMER unicode', 'emojis/iphone-emoji/HAMMER.png'},
   {'🔩', '🔩 NUT AND BOLT unicode', 'emojis/iphone-emoji/NUT_AND_BOLT.png'},
   {'🔪', '🔪 HOCHO unicode', 'emojis/iphone-emoji/HOCHO.png'},
   {'🔫', '🔫 PISTOL unicode', 'emojis/iphone-emoji/PISTOL.png'},
   {'🔬', '🔬 MICROSCOPE unicode', 'emojis/iphone-emoji/MICROSCOPE.png'},
   {'🔭', '🔭 TELESCOPE unicode', 'emojis/iphone-emoji/TELESCOPE.png'},
   {'🔮', '🔮 CRYSTAL BALL unicode', 'emojis/iphone-emoji/CRYSTAL_BALL.png'},
   {'🔯', '🔯 SIX POINTED STAR WITH MIDDLE DOT unicode', 'emojis/iphone-emoji/SIX_POINTED_STAR_WITH_MIDDLE_DOT.png'},
   {'🔰', '🔰 JAPANESE SYMBOL FOR BEGINNER unicode', 'emojis/iphone-emoji/JAPANESE_SYMBOL_FOR_BEGINNER.png'},
   {'🔱', '🔱 TRIDENT EMBLEM unicode', 'emojis/iphone-emoji/TRIDENT_EMBLEM.png'},
   {'🔲', '🔲 BLACK SQUARE BUTTON unicode', 'emojis/iphone-emoji/BLACK_SQUARE_BUTTON.png'},
   {'🔳', '🔳 WHITE SQUARE BUTTON unicode', 'emojis/iphone-emoji/WHITE_SQUARE_BUTTON.png'},
   {'🔴', '🔴 LARGE RED CIRCLE unicode', 'emojis/iphone-emoji/LARGE_RED_CIRCLE.png'},
   {'🔵', '🔵 LARGE BLUE CIRCLE unicode', 'emojis/iphone-emoji/LARGE_BLUE_CIRCLE.png'},
   {'🔶', '🔶 LARGE ORANGE DIAMOND unicode', 'emojis/iphone-emoji/LARGE_ORANGE_DIAMOND.png'},
   {'🔷', '🔷 LARGE BLUE DIAMOND unicode', 'emojis/iphone-emoji/LARGE_BLUE_DIAMOND.png'},
   {'🔸', '🔸 SMALL ORANGE DIAMOND unicode', 'emojis/iphone-emoji/SMALL_ORANGE_DIAMOND.png'},
   {'🔹', '🔹 SMALL BLUE DIAMOND unicode', 'emojis/iphone-emoji/SMALL_BLUE_DIAMOND.png'},
   {'🔺', '🔺 UP-POINTING RED TRIANGLE unicode', 'emojis/iphone-emoji/UP-POINTING_RED_TRIANGLE.png'},
   {'🔻', '🔻 DOWN-POINTING RED TRIANGLE unicode', 'emojis/iphone-emoji/DOWN-POINTING_RED_TRIANGLE.png'},
   {'🔼', '🔼 UP-POINTING SMALL RED TRIANGLE unicode', 'emojis/iphone-emoji/UP-POINTING_SMALL_RED_TRIANGLE.png'},
   {'🔽', '🔽 DOWN-POINTING SMALL RED TRIANGLE unicode', 'emojis/iphone-emoji/DOWN-POINTING_SMALL_RED_TRIANGLE.png'},
   {'🕐', '🕐 CLOCK FACE ONE OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_ONE_OCLOCK.png'},
   {'🕑', '🕑 CLOCK FACE TWO OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_TWO_OCLOCK.png'},
   {'🕒', '🕒 CLOCK FACE THREE OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_THREE_OCLOCK.png'},
   {'🕓', '🕓 CLOCK FACE FOUR OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_FOUR_OCLOCK.png'},
   {'🕔', '🕔 CLOCK FACE FIVE OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_FIVE_OCLOCK.png'},
   {'🕕', '🕕 CLOCK FACE SIX OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_SIX_OCLOCK.png'},
   {'🕖', '🕖 CLOCK FACE SEVEN OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_SEVEN_OCLOCK.png'},
   {'🕗', '🕗 CLOCK FACE EIGHT OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_EIGHT_OCLOCK.png'},
   {'🕘', '🕘 CLOCK FACE NINE OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_NINE_OCLOCK.png'},
   {'🕙', '🕙 CLOCK FACE TEN OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_TEN_OCLOCK.png'},
   {'🕚', '🕚 CLOCK FACE ELEVEN OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_ELEVEN_OCLOCK.png'},
   {'🕛', '🕛 CLOCK FACE TWELVE OCLOCK unicode', 'emojis/iphone-emoji/CLOCK_FACE_TWELVE_OCLOCK.png'},
   {'🕜', '🕜 CLOCK FACE ONE-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_ONE-THIRTY.png'},
   {'🕝', '🕝 CLOCK FACE TWO-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_TWO-THIRTY.png'},
   {'🕞', '🕞 CLOCK FACE THREE-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_THREE-THIRTY.png'},
   {'🕟', '🕟 CLOCK FACE FOUR-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_FOUR-THIRTY.png'},
   {'🕠', '🕠 CLOCK FACE FIVE-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_FIVE-THIRTY.png'},
   {'🕡', '🕡 CLOCK FACE SIX-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_SIX-THIRTY.png'},
   {'🕢', '🕢 CLOCK FACE SEVEN-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_SEVEN-THIRTY.png'},
   {'🕣', '🕣 CLOCK FACE EIGHT-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_EIGHT-THIRTY.png'},
   {'🕤', '🕤 CLOCK FACE NINE-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_NINE-THIRTY.png'},
   {'🕥', '🕥 CLOCK FACE TEN-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_TEN-THIRTY.png'},
   {'🕦', '🕦 CLOCK FACE ELEVEN-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_ELEVEN-THIRTY.png'},
   {'🕧', '🕧 CLOCK FACE TWELVE-THIRTY unicode', 'emojis/iphone-emoji/CLOCK_FACE_TWELVE-THIRTY.png'},
   {'🗻', '🗻 MOUNT FUJI unicode', 'emojis/iphone-emoji/MOUNT_FUJI.png'},
   {'🗼', '🗼 TOKYO TOWER unicode', 'emojis/iphone-emoji/TOKYO_TOWER.png'},
   {'🗽', '🗽 STATUE OF LIBERTY unicode', 'emojis/iphone-emoji/STATUE_OF_LIBERTY.png'},
   {'🗾', '🗾 SILHOUETTE OF JAPAN unicode', 'emojis/iphone-emoji/SILHOUETTE_OF_JAPAN.png'},
   {'🗿', '🗿 MOYAI unicode', 'emojis/iphone-emoji/MOYAI.png'},
   {'😀', '😀 GRINNING FACE unicode', 'emojis/iphone-emoji/GRINNING_FACE.png'},
   {'😁', '😁 GRINNING FACE WITH SMILING EYES unicode', 'emojis/iphone-emoji/GRINNING_FACE_WITH_SMILING_EYES.png'},
   {'😂', '😂 FACE WITH TEARS OF JOY unicode', 'emojis/iphone-emoji/FACE_WITH_TEARS_OF_JOY.png'},
   {'😃', '😃 SMILING FACE WITH OPEN MOUTH unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_OPEN_MOUTH.png'},
   {'😄', '😄 SMILING FACE WITH OPEN MOUTH AND SMILING EYES unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_OPEN_MOUTH_AND_SMILING_EYES.png'},
   {'😅', '😅 SMILING FACE WITH OPEN MOUTH AND COLD SWEAT unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT.png'},
   {'😆', '😆 SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_OPEN_MOUTH_AND_TIGHTLY-CLOSED_EYES.png'},
   {'😇', '😇 SMILING FACE WITH HALO unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_HALO.png'},
   {'😈', '😈 SMILING FACE WITH HORNS unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_HORNS.png'},
   {'😉', '😉 WINKING FACE unicode', 'emojis/iphone-emoji/WINKING_FACE.png'},
   {'😊', '😊 SMILING FACE WITH SMILING EYES unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_SMILING_EYES.png'},
   {'😋', '😋 FACE SAVOURING DELICIOUS FOOD unicode', 'emojis/iphone-emoji/FACE_SAVOURING_DELICIOUS_FOOD.png'},
   {'😌', '😌 RELIEVED FACE unicode', 'emojis/iphone-emoji/RELIEVED_FACE.png'},
   {'😍', '😍 SMILING FACE WITH HEART-SHAPED EYES unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_HEART-SHAPED_EYES.png'},
   {'😎', '😎 SMILING FACE WITH SUNGLASSES unicode', 'emojis/iphone-emoji/SMILING_FACE_WITH_SUNGLASSES.png'},
   {'😏', '😏 SMIRKING FACE unicode', 'emojis/iphone-emoji/SMIRKING_FACE.png'},
   {'😐', '😐 NEUTRAL FACE unicode', 'emojis/iphone-emoji/NEUTRAL_FACE.png'},
   {'😑', '😑 EXPRESSIONLESS FACE unicode', 'emojis/iphone-emoji/EXPRESSIONLESS_FACE.png'},
   {'😒', '😒 UNAMUSED FACE unicode', 'emojis/iphone-emoji/UNAMUSED_FACE.png'},
   {'😓', '😓 FACE WITH COLD SWEAT unicode', 'emojis/iphone-emoji/FACE_WITH_COLD_SWEAT.png'},
   {'😔', '😔 PENSIVE FACE unicode', 'emojis/iphone-emoji/PENSIVE_FACE.png'},
   {'😕', '😕 CONFUSED FACE unicode', 'emojis/iphone-emoji/CONFUSED_FACE.png'},
   {'😖', '😖 CONFOUNDED FACE unicode', 'emojis/iphone-emoji/CONFOUNDED_FACE.png'},
   {'😗', '😗 KISSING FACE unicode', 'emojis/iphone-emoji/KISSING_FACE.png'},
   {'😘', '😘 FACE THROWING A KISS unicode', 'emojis/iphone-emoji/FACE_THROWING_A_KISS.png'},
   {'😙', '😙 KISSING FACE WITH SMILING EYES unicode', 'emojis/iphone-emoji/KISSING_FACE_WITH_SMILING_EYES.png'},
   {'😚', '😚 KISSING FACE WITH CLOSED EYES unicode', 'emojis/iphone-emoji/KISSING_FACE_WITH_CLOSED_EYES.png'},
   {'😛', '😛 FACE WITH STUCK-OUT TONGUE unicode', 'emojis/iphone-emoji/FACE_WITH_STUCK-OUT_TONGUE.png'},
   {'😜', '😜 FACE WITH STUCK-OUT TONGUE AND WINKING EYE unicode', 'emojis/iphone-emoji/FACE_WITH_STUCK-OUT_TONGUE_AND_WINKING_EYE.png'},
   {'😝', '😝 FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES unicode', 'emojis/iphone-emoji/FACE_WITH_STUCK-OUT_TONGUE_AND_TIGHTLY-CLOSED_EYES.png'},
   {'😞', '😞 DISAPPOINTED FACE unicode', 'emojis/iphone-emoji/DISAPPOINTED_FACE.png'},
   {'😟', '😟 WORRIED FACE unicode', 'emojis/iphone-emoji/WORRIED_FACE.png'},
   {'😠', '😠 ANGRY FACE unicode', 'emojis/iphone-emoji/ANGRY_FACE.png'},
   {'😡', '😡 POUTING FACE unicode', 'emojis/iphone-emoji/POUTING_FACE.png'},
   {'😢', '😢 CRYING FACE unicode', 'emojis/iphone-emoji/CRYING_FACE.png'},
   {'😣', '😣 PERSEVERING FACE unicode', 'emojis/iphone-emoji/PERSEVERING_FACE.png'},
   {'😤', '😤 FACE WITH LOOK OF TRIUMPH unicode', 'emojis/iphone-emoji/FACE_WITH_LOOK_OF_TRIUMPH.png'},
   {'😥', '😥 DISAPPOINTED BUT RELIEVED FACE unicode', 'emojis/iphone-emoji/DISAPPOINTED_BUT_RELIEVED_FACE.png'},
   {'😦', '😦 FROWNING FACE WITH OPEN MOUTH unicode', 'emojis/iphone-emoji/FROWNING_FACE_WITH_OPEN_MOUTH.png'},
   {'😧', '😧 ANGUISHED FACE unicode', 'emojis/iphone-emoji/ANGUISHED_FACE.png'},
   {'😨', '😨 FEARFUL FACE unicode', 'emojis/iphone-emoji/FEARFUL_FACE.png'},
   {'😩', '😩 WEARY FACE unicode', 'emojis/iphone-emoji/WEARY_FACE.png'},
   {'😪', '😪 SLEEPY FACE unicode', 'emojis/iphone-emoji/SLEEPY_FACE.png'},
   {'😫', '😫 TIRED FACE unicode', 'emojis/iphone-emoji/TIRED_FACE.png'},
   {'😬', '😬 GRIMACING FACE unicode', 'emojis/iphone-emoji/GRIMACING_FACE.png'},
   {'😭', '😭 LOUDLY CRYING FACE unicode', 'emojis/iphone-emoji/LOUDLY_CRYING_FACE.png'},
   {'😮', '😮 FACE WITH OPEN MOUTH unicode', 'emojis/iphone-emoji/FACE_WITH_OPEN_MOUTH.png'},
   {'😯', '😯 HUSHED FACE unicode', 'emojis/iphone-emoji/HUSHED_FACE.png'},
   {'😰', '😰 FACE WITH OPEN MOUTH AND COLD SWEAT unicode', 'emojis/iphone-emoji/FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT.png'},
   {'😱', '😱 FACE SCREAMING IN FEAR unicode', 'emojis/iphone-emoji/FACE_SCREAMING_IN_FEAR.png'},
   {'😲', '😲 ASTONISHED FACE unicode', 'emojis/iphone-emoji/ASTONISHED_FACE.png'},
   {'😳', '😳 FLUSHED FACE unicode', 'emojis/iphone-emoji/FLUSHED_FACE.png'},
   {'😴', '😴 SLEEPING FACE unicode', 'emojis/iphone-emoji/SLEEPING_FACE.png'},
   {'😵', '😵 DIZZY FACE unicode', 'emojis/iphone-emoji/DIZZY_FACE.png'},
   {'😶', '😶 FACE WITHOUT MOUTH unicode', 'emojis/iphone-emoji/FACE_WITHOUT_MOUTH.png'},
   {'😷', '😷 FACE WITH MEDICAL MASK unicode', 'emojis/iphone-emoji/FACE_WITH_MEDICAL_MASK.png'},
   {'😸', '😸 GRINNING CAT FACE WITH SMILING EYES unicode', 'emojis/iphone-emoji/GRINNING_CAT_FACE_WITH_SMILING_EYES.png'},
   {'😹', '😹 CAT FACE WITH TEARS OF JOY unicode', 'emojis/iphone-emoji/CAT_FACE_WITH_TEARS_OF_JOY.png'},
   {'😺', '😺 SMILING CAT FACE WITH OPEN MOUTH unicode', 'emojis/iphone-emoji/SMILING_CAT_FACE_WITH_OPEN_MOUTH.png'},
   {'😻', '😻 SMILING CAT FACE WITH HEART-SHAPED EYES unicode', 'emojis/iphone-emoji/SMILING_CAT_FACE_WITH_HEART-SHAPED_EYES.png'},
   {'😼', '😼 CAT FACE WITH WRY SMILE unicode', 'emojis/iphone-emoji/CAT_FACE_WITH_WRY_SMILE.png'},
   {'😽', '😽 KISSING CAT FACE WITH CLOSED EYES unicode', 'emojis/iphone-emoji/KISSING_CAT_FACE_WITH_CLOSED_EYES.png'},
   {'😾', '😾 POUTING CAT FACE unicode', 'emojis/iphone-emoji/POUTING_CAT_FACE.png'},
   {'😿', '😿 CRYING CAT FACE unicode', 'emojis/iphone-emoji/CRYING_CAT_FACE.png'},
   {'🙀', '🙀 WEARY CAT FACE unicode', 'emojis/iphone-emoji/WEARY_CAT_FACE.png'},
   {'🙅', '🙅 FACE WITH NO GOOD GESTURE unicode', 'emojis/iphone-emoji/FACE_WITH_NO_GOOD_GESTURE.png'},
   {'🙆', '🙆 FACE WITH OK GESTURE unicode', 'emojis/iphone-emoji/FACE_WITH_OK_GESTURE.png'},
   {'🙇', '🙇 PERSON BOWING DEEPLY unicode', 'emojis/iphone-emoji/PERSON_BOWING_DEEPLY.png'},
   {'🙈', '🙈 SEE-NO-EVIL MONKEY unicode', 'emojis/iphone-emoji/SEE-NO-EVIL_MONKEY.png'},
   {'🙉', '🙉 HEAR-NO-EVIL MONKEY unicode', 'emojis/iphone-emoji/HEAR-NO-EVIL_MONKEY.png'},
   {'🙊', '🙊 SPEAK-NO-EVIL MONKEY unicode', 'emojis/iphone-emoji/SPEAK-NO-EVIL_MONKEY.png'},
   {'🙋', '🙋 HAPPY PERSON RAISING ONE HAND unicode', 'emojis/iphone-emoji/HAPPY_PERSON_RAISING_ONE_HAND.png'},
   {'🙌', '🙌 PERSON RAISING BOTH HANDS IN CELEBRATION unicode', 'emojis/iphone-emoji/PERSON_RAISING_BOTH_HANDS_IN_CELEBRATION.png'},
   {'🙍', '🙍 PERSON FROWNING unicode', 'emojis/iphone-emoji/PERSON_FROWNING.png'},
   {'🙎', '🙎 PERSON WITH POUTING FACE unicode', 'emojis/iphone-emoji/PERSON_WITH_POUTING_FACE.png'},
   {'🙏', '🙏 PERSON WITH FOLDED HANDS unicode', 'emojis/iphone-emoji/PERSON_WITH_FOLDED_HANDS.png'},
   {'🚀', '🚀 ROCKET unicode', 'emojis/iphone-emoji/ROCKET.png'},
   {'🚁', '🚁 HELICOPTER unicode', 'emojis/iphone-emoji/HELICOPTER.png'},
   {'🚂', '🚂 STEAM LOCOMOTIVE unicode', 'emojis/iphone-emoji/STEAM_LOCOMOTIVE.png'},
   {'🚃', '🚃 RAILWAY CAR unicode', 'emojis/iphone-emoji/RAILWAY_CAR.png'},
   {'🚄', '🚄 HIGH-SPEED TRAIN unicode', 'emojis/iphone-emoji/HIGH-SPEED_TRAIN.png'},
   {'🚅', '🚅 HIGH-SPEED TRAIN WITH BULLET NOSE unicode', 'emojis/iphone-emoji/HIGH-SPEED_TRAIN_WITH_BULLET_NOSE.png'},
   {'🚆', '🚆 TRAIN unicode', 'emojis/iphone-emoji/TRAIN.png'},
   {'🚇', '🚇 METRO unicode', 'emojis/iphone-emoji/METRO.png'},
   {'🚈', '🚈 LIGHT RAIL unicode', 'emojis/iphone-emoji/LIGHT_RAIL.png'},
   {'🚉', '🚉 STATION unicode', 'emojis/iphone-emoji/STATION.png'},
   {'🚊', '🚊 TRAM unicode', 'emojis/iphone-emoji/TRAM.png'},
   {'🚋', '🚋 TRAM CAR unicode', 'emojis/iphone-emoji/TRAM_CAR.png'},
   {'🚌', '🚌 BUS unicode', 'emojis/iphone-emoji/BUS.png'},
   {'🚍', '🚍 ONCOMING BUS unicode', 'emojis/iphone-emoji/ONCOMING_BUS.png'},
   {'🚎', '🚎 TROLLEYBUS unicode', 'emojis/iphone-emoji/TROLLEYBUS.png'},
   {'🚏', '🚏 BUS STOP unicode', 'emojis/iphone-emoji/BUS_STOP.png'},
   {'🚐', '🚐 MINIBUS unicode', 'emojis/iphone-emoji/MINIBUS.png'},
   {'🚑', '🚑 AMBULANCE unicode', 'emojis/iphone-emoji/AMBULANCE.png'},
   {'🚒', '🚒 FIRE ENGINE unicode', 'emojis/iphone-emoji/FIRE_ENGINE.png'},
   {'🚓', '🚓 POLICE CAR unicode', 'emojis/iphone-emoji/POLICE_CAR.png'},
   {'🚔', '🚔 ONCOMING POLICE CAR unicode', 'emojis/iphone-emoji/ONCOMING_POLICE_CAR.png'},
   {'🚕', '🚕 TAXI unicode', 'emojis/iphone-emoji/TAXI.png'},
   {'🚖', '🚖 ONCOMING TAXI unicode', 'emojis/iphone-emoji/ONCOMING_TAXI.png'},
   {'🚗', '🚗 AUTOMOBILE unicode', 'emojis/iphone-emoji/AUTOMOBILE.png'},
   {'🚘', '🚘 ONCOMING AUTOMOBILE unicode', 'emojis/iphone-emoji/ONCOMING_AUTOMOBILE.png'},
   {'🚙', '🚙 RECREATIONAL VEHICLE unicode', 'emojis/iphone-emoji/RECREATIONAL_VEHICLE.png'},
   {'🚚', '🚚 DELIVERY TRUCK unicode', 'emojis/iphone-emoji/DELIVERY_TRUCK.png'},
   {'🚛', '🚛 ARTICULATED LORRY unicode', 'emojis/iphone-emoji/ARTICULATED_LORRY.png'},
   {'🚜', '🚜 TRACTOR unicode', 'emojis/iphone-emoji/TRACTOR.png'},
   {'🚝', '🚝 MONORAIL unicode', 'emojis/iphone-emoji/MONORAIL.png'},
   {'🚞', '🚞 MOUNTAIN RAILWAY unicode', 'emojis/iphone-emoji/MOUNTAIN_RAILWAY.png'},
   {'🚟', '🚟 SUSPENSION RAILWAY unicode', 'emojis/iphone-emoji/SUSPENSION_RAILWAY.png'},
   {'🚠', '🚠 MOUNTAIN CABLEWAY unicode', 'emojis/iphone-emoji/MOUNTAIN_CABLEWAY.png'},
   {'🚡', '🚡 AERIAL TRAMWAY unicode', 'emojis/iphone-emoji/AERIAL_TRAMWAY.png'},
   {'🚢', '🚢 SHIP unicode', 'emojis/iphone-emoji/SHIP.png'},
   {'🚣', '🚣 ROWBOAT unicode', 'emojis/iphone-emoji/ROWBOAT.png'},
   {'🚤', '🚤 SPEEDBOAT unicode', 'emojis/iphone-emoji/SPEEDBOAT.png'},
   {'🚥', '🚥 HORIZONTAL TRAFFIC LIGHT unicode', 'emojis/iphone-emoji/HORIZONTAL_TRAFFIC_LIGHT.png'},
   {'🚦', '🚦 VERTICAL TRAFFIC LIGHT unicode', 'emojis/iphone-emoji/VERTICAL_TRAFFIC_LIGHT.png'},
   {'🚧', '🚧 CONSTRUCTION SIGN unicode', 'emojis/iphone-emoji/CONSTRUCTION_SIGN.png'},
   {'🚨', '🚨 POLICE CARS REVOLVING LIGHT unicode', 'emojis/iphone-emoji/POLICE_CARS_REVOLVING_LIGHT.png'},
   {'🚩', '🚩 TRIANGULAR FLAG ON POST unicode', 'emojis/iphone-emoji/TRIANGULAR_FLAG_ON_POST.png'},
   {'🚪', '🚪 DOOR unicode', 'emojis/iphone-emoji/DOOR.png'},
   {'🚫', '🚫 NO ENTRY SIGN unicode', 'emojis/iphone-emoji/NO_ENTRY_SIGN.png'},
   {'🚬', '🚬 SMOKING SYMBOL unicode', 'emojis/iphone-emoji/SMOKING_SYMBOL.png'},
   {'🚭', '🚭 NO SMOKING SYMBOL unicode', 'emojis/iphone-emoji/NO_SMOKING_SYMBOL.png'},
   {'🚮', '🚮 PUT LITTER IN ITS PLACE SYMBOL unicode', 'emojis/iphone-emoji/PUT_LITTER_IN_ITS_PLACE_SYMBOL.png'},
   {'🚯', '🚯 DO NOT LITTER SYMBOL unicode', 'emojis/iphone-emoji/DO_NOT_LITTER_SYMBOL.png'},
   {'🚰', '🚰 POTABLE WATER SYMBOL unicode', 'emojis/iphone-emoji/POTABLE_WATER_SYMBOL.png'},
   {'🚱', '🚱 NON-POTABLE WATER SYMBOL unicode', 'emojis/iphone-emoji/NON-POTABLE_WATER_SYMBOL.png'},
   {'🚲', '🚲 BICYCLE unicode', 'emojis/iphone-emoji/BICYCLE.png'},
   {'🚳', '🚳 NO BICYCLES unicode', 'emojis/iphone-emoji/NO_BICYCLES.png'},
   {'🚴', '🚴 BICYCLIST unicode', 'emojis/iphone-emoji/BICYCLIST.png'},
   {'🚵', '🚵 MOUNTAIN BICYCLIST unicode', 'emojis/iphone-emoji/MOUNTAIN_BICYCLIST.png'},
   {'🚶', '🚶 PEDESTRIAN unicode', 'emojis/iphone-emoji/PEDESTRIAN.png'},
   {'🚷', '🚷 NO PEDESTRIANS unicode', 'emojis/iphone-emoji/NO_PEDESTRIANS.png'},
   {'🚸', '🚸 CHILDREN CROSSING unicode', 'emojis/iphone-emoji/CHILDREN_CROSSING.png'},
   {'🚹', '🚹 MENS SYMBOL unicode', 'emojis/iphone-emoji/MENS_SYMBOL.png'},
   {'🚺', '🚺 WOMENS SYMBOL unicode', 'emojis/iphone-emoji/WOMENS_SYMBOL.png'},
   {'🚻', '🚻 RESTROOM unicode', 'emojis/iphone-emoji/RESTROOM.png'},
   {'🚼', '🚼 BABY SYMBOL unicode', 'emojis/iphone-emoji/BABY_SYMBOL.png'},
   {'🚽', '🚽 TOILET unicode', 'emojis/iphone-emoji/TOILET.png'},
   {'🚾', '🚾 WATER CLOSET unicode', 'emojis/iphone-emoji/WATER_CLOSET.png'},
   {'🚿', '🚿 SHOWER unicode', 'emojis/iphone-emoji/SHOWER.png'},
   {'🛀', '🛀 BATH unicode', 'emojis/iphone-emoji/BATH.png'},
   {'🛁', '🛁 BATHTUB unicode', 'emojis/iphone-emoji/BATHTUB.png'},
   {'🛂', '🛂 PASSPORT CONTROL unicode', 'emojis/iphone-emoji/PASSPORT_CONTROL.png'},
   {'🛃', '🛃 CUSTOMS unicode', 'emojis/iphone-emoji/CUSTOMS.png'},
   {'🛄', '🛄 BAGGAGE CLAIM unicode', 'emojis/iphone-emoji/BAGGAGE_CLAIM.png'},
   {'🛅', '🛅 LEFT LUGGAGE unicode', 'emojis/iphone-emoji/LEFT_LUGGAGE.png'},
   {'‼', '‼ DOUBLE EXCLAMATION MARK unicode', 'emojis/iphone-emoji/DOUBLE_EXCLAMATION_MARK.png'},
   {'⁉', '⁉ EXCLAMATION QUESTION MARK unicode', 'emojis/iphone-emoji/EXCLAMATION_QUESTION_MARK.png'},
   {'™', '™ TRADE MARK SIGN unicode', 'emojis/iphone-emoji/TRADE_MARK_SIGN.png'},
   {'ℹ', 'ℹ INFORMATION SOURCE unicode', 'emojis/iphone-emoji/INFORMATION_SOURCE.png'},
   {'↔', '↔ LEFT RIGHT ARROW unicode', 'emojis/iphone-emoji/LEFT_RIGHT_ARROW.png'},
   {'↕', '↕ UP DOWN ARROW unicode', 'emojis/iphone-emoji/UP_DOWN_ARROW.png'},
   {'↖', '↖ NORTH WEST ARROW unicode', 'emojis/iphone-emoji/NORTH_WEST_ARROW.png'},
   {'↗', '↗ NORTH EAST ARROW unicode', 'emojis/iphone-emoji/NORTH_EAST_ARROW.png'},
   {'↘', '↘ SOUTH EAST ARROW unicode', 'emojis/iphone-emoji/SOUTH_EAST_ARROW.png'},
   {'↙', '↙ SOUTH WEST ARROW unicode', 'emojis/iphone-emoji/SOUTH_WEST_ARROW.png'},
   {'↩', '↩ LEFTWARDS ARROW WITH HOOK unicode', 'emojis/iphone-emoji/LEFTWARDS_ARROW_WITH_HOOK.png'},
   {'↪', '↪ RIGHTWARDS ARROW WITH HOOK unicode', 'emojis/iphone-emoji/RIGHTWARDS_ARROW_WITH_HOOK.png'},
   {'⌚', '⌚ WATCH unicode', 'emojis/iphone-emoji/WATCH.png'},
   {'⌛', '⌛ HOURGLASS unicode', 'emojis/iphone-emoji/HOURGLASS.png'},
   {'⏩', '⏩ BLACK RIGHT-POINTING DOUBLE TRIANGLE unicode', 'emojis/iphone-emoji/BLACK_RIGHT-POINTING_DOUBLE_TRIANGLE.png'},
   {'⏪', '⏪ BLACK LEFT-POINTING DOUBLE TRIANGLE unicode', 'emojis/iphone-emoji/BLACK_LEFT-POINTING_DOUBLE_TRIANGLE.png'},
   {'⏫', '⏫ BLACK UP-POINTING DOUBLE TRIANGLE unicode', 'emojis/iphone-emoji/BLACK_UP-POINTING_DOUBLE_TRIANGLE.png'},
   {'⏬', '⏬ BLACK DOWN-POINTING DOUBLE TRIANGLE unicode', 'emojis/iphone-emoji/BLACK_DOWN-POINTING_DOUBLE_TRIANGLE.png'},
   {'⏰', '⏰ ALARM CLOCK unicode', 'emojis/iphone-emoji/ALARM_CLOCK.png'},
   {'⏳', '⏳ HOURGLASS WITH FLOWING SAND unicode', 'emojis/iphone-emoji/HOURGLASS_WITH_FLOWING_SAND.png'},
   {'Ⓜ', 'Ⓜ CIRCLED LATIN CAPITAL LETTER M unicode', 'emojis/iphone-emoji/CIRCLED_LATIN_CAPITAL_LETTER_M.png'},
   {'▪', '▪ BLACK SMALL SQUARE unicode', 'emojis/iphone-emoji/BLACK_SMALL_SQUARE.png'},
   {'▫', '▫ WHITE SMALL SQUARE unicode', 'emojis/iphone-emoji/WHITE_SMALL_SQUARE.png'},
   {'▶', '▶ BLACK RIGHT-POINTING TRIANGLE unicode', 'emojis/iphone-emoji/BLACK_RIGHT-POINTING_TRIANGLE.png'},
   {'◀', '◀ BLACK LEFT-POINTING TRIANGLE unicode', 'emojis/iphone-emoji/BLACK_LEFT-POINTING_TRIANGLE.png'},
   {'◻', '◻ WHITE MEDIUM SQUARE unicode', 'emojis/iphone-emoji/WHITE_MEDIUM_SQUARE.png'},
   {'◼', '◼ BLACK MEDIUM SQUARE unicode', 'emojis/iphone-emoji/BLACK_MEDIUM_SQUARE.png'},
   {'◽', '◽ WHITE MEDIUM SMALL SQUARE unicode', 'emojis/iphone-emoji/WHITE_MEDIUM_SMALL_SQUARE.png'},
   {'◾', '◾ BLACK MEDIUM SMALL SQUARE unicode', 'emojis/iphone-emoji/BLACK_MEDIUM_SMALL_SQUARE.png'},
   {'☀', '☀ BLACK SUN WITH RAYS unicode', 'emojis/iphone-emoji/BLACK_SUN_WITH_RAYS.png'},
   {'☁', '☁ CLOUD unicode', 'emojis/iphone-emoji/CLOUD.png'},
   {'☎', '☎ BLACK TELEPHONE unicode', 'emojis/iphone-emoji/BLACK_TELEPHONE.png'},
   {'☑', '☑ BALLOT BOX WITH CHECK unicode', 'emojis/iphone-emoji/BALLOT_BOX_WITH_CHECK.png'},
   {'☔', '☔ UMBRELLA WITH RAIN DROPS unicode', 'emojis/iphone-emoji/UMBRELLA_WITH_RAIN_DROPS.png'},
   {'☕', '☕ HOT BEVERAGE unicode', 'emojis/iphone-emoji/HOT_BEVERAGE.png'},
   {'☝', '☝ WHITE UP POINTING INDEX unicode', 'emojis/iphone-emoji/WHITE_UP_POINTING_INDEX.png'},
   {'☺', '☺ WHITE SMILING FACE unicode', 'emojis/iphone-emoji/WHITE_SMILING_FACE.png'},
   {'♈', '♈ ARIES unicode', 'emojis/iphone-emoji/ARIES.png'},
   {'♉', '♉ TAURUS unicode', 'emojis/iphone-emoji/TAURUS.png'},
   {'♊', '♊ GEMINI unicode', 'emojis/iphone-emoji/GEMINI.png'},
   {'♋', '♋ CANCER unicode', 'emojis/iphone-emoji/CANCER.png'},
   {'♌', '♌ LEO unicode', 'emojis/iphone-emoji/LEO.png'},
   {'♍', '♍ VIRGO unicode', 'emojis/iphone-emoji/VIRGO.png'},
   {'♎', '♎ LIBRA unicode', 'emojis/iphone-emoji/LIBRA.png'},
   {'♏', '♏ SCORPIUS unicode', 'emojis/iphone-emoji/SCORPIUS.png'},
   {'♐', '♐ SAGITTARIUS unicode', 'emojis/iphone-emoji/SAGITTARIUS.png'},
   {'♑', '♑ CAPRICORN unicode', 'emojis/iphone-emoji/CAPRICORN.png'},
   {'♒', '♒ AQUARIUS unicode', 'emojis/iphone-emoji/AQUARIUS.png'},
   {'♓', '♓ PISCES unicode', 'emojis/iphone-emoji/PISCES.png'},
   {'♠', '♠ BLACK SPADE SUIT unicode', 'emojis/iphone-emoji/BLACK_SPADE_SUIT.png'},
   {'♣', '♣ BLACK CLUB SUIT unicode', 'emojis/iphone-emoji/BLACK_CLUB_SUIT.png'},
   {'♥', '♥ BLACK HEART SUIT unicode', 'emojis/iphone-emoji/BLACK_HEART_SUIT.png'},
   {'♦', '♦ BLACK DIAMOND SUIT unicode', 'emojis/iphone-emoji/BLACK_DIAMOND_SUIT.png'},
   {'♨', '♨ HOT SPRINGS unicode', 'emojis/iphone-emoji/HOT_SPRINGS.png'},
   {'♻', '♻ BLACK UNIVERSAL RECYCLING SYMBOL unicode', 'emojis/iphone-emoji/BLACK_UNIVERSAL_RECYCLING_SYMBOL.png'},
   {'♿', '♿ WHEELCHAIR SYMBOL unicode', 'emojis/iphone-emoji/WHEELCHAIR_SYMBOL.png'},
   {'⚓', '⚓ ANCHOR unicode', 'emojis/iphone-emoji/ANCHOR.png'},
   {'⚠', '⚠ WARNING SIGN unicode', 'emojis/iphone-emoji/WARNING_SIGN.png'},
   {'⚡', '⚡ HIGH VOLTAGE SIGN unicode', 'emojis/iphone-emoji/HIGH_VOLTAGE_SIGN.png'},
   {'⚪', '⚪ MEDIUM WHITE CIRCLE unicode', 'emojis/iphone-emoji/MEDIUM_WHITE_CIRCLE.png'},
   {'⚫', '⚫ MEDIUM BLACK CIRCLE unicode', 'emojis/iphone-emoji/MEDIUM_BLACK_CIRCLE.png'},
   {'⚽', '⚽ SOCCER BALL unicode', 'emojis/iphone-emoji/SOCCER_BALL.png'},
   {'⚾', '⚾ BASEBALL unicode', 'emojis/iphone-emoji/BASEBALL.png'},
   {'⛄', '⛄ SNOWMAN WITHOUT SNOW unicode', 'emojis/iphone-emoji/SNOWMAN_WITHOUT_SNOW.png'},
   {'⛅', '⛅ SUN BEHIND CLOUD unicode', 'emojis/iphone-emoji/SUN_BEHIND_CLOUD.png'},
   {'⛎', '⛎ OPHIUCHUS unicode', 'emojis/iphone-emoji/OPHIUCHUS.png'},
   {'⛔', '⛔ NO ENTRY unicode', 'emojis/iphone-emoji/NO_ENTRY.png'},
   {'⛪', '⛪ CHURCH unicode', 'emojis/iphone-emoji/CHURCH.png'},
   {'⛲', '⛲ FOUNTAIN unicode', 'emojis/iphone-emoji/FOUNTAIN.png'},
   {'⛳', '⛳ FLAG IN HOLE unicode', 'emojis/iphone-emoji/FLAG_IN_HOLE.png'},
   {'⛵', '⛵ SAILBOAT unicode', 'emojis/iphone-emoji/SAILBOAT.png'},
   {'⛺', '⛺ TENT unicode', 'emojis/iphone-emoji/TENT.png'},
   {'⛽', '⛽ FUEL PUMP unicode', 'emojis/iphone-emoji/FUEL_PUMP.png'},
   {'✂', '✂ BLACK SCISSORS unicode', 'emojis/iphone-emoji/BLACK_SCISSORS.png'},
   {'✅', '✅ WHITE HEAVY CHECK MARK unicode', 'emojis/iphone-emoji/WHITE_HEAVY_CHECK_MARK.png'},
   {'✈', '✈ AIRPLANE unicode', 'emojis/iphone-emoji/AIRPLANE.png'},
   {'✉', '✉ ENVELOPE unicode', 'emojis/iphone-emoji/ENVELOPE.png'},
   {'✊', '✊ RAISED FIST unicode', 'emojis/iphone-emoji/RAISED_FIST.png'},
   {'✋', '✋ RAISED HAND unicode', 'emojis/iphone-emoji/RAISED_HAND.png'},
   {'✌', '✌ VICTORY HAND unicode', 'emojis/iphone-emoji/VICTORY_HAND.png'},
   {'✏', '✏ PENCIL unicode', 'emojis/iphone-emoji/PENCIL.png'},
   {'✒', '✒ BLACK NIB unicode', 'emojis/iphone-emoji/BLACK_NIB.png'},
   {'✔', '✔ HEAVY CHECK MARK unicode', 'emojis/iphone-emoji/HEAVY_CHECK_MARK.png'},
   {'✖', '✖ HEAVY MULTIPLICATION X unicode', 'emojis/iphone-emoji/HEAVY_MULTIPLICATION_X.png'},
   {'✨', '✨ SPARKLES unicode', 'emojis/iphone-emoji/SPARKLES.png'},
   {'✳', '✳ EIGHT SPOKED ASTERISK unicode', 'emojis/iphone-emoji/EIGHT_SPOKED_ASTERISK.png'},
   {'✴', '✴ EIGHT POINTED BLACK STAR unicode', 'emojis/iphone-emoji/EIGHT_POINTED_BLACK_STAR.png'},
   {'❄', '❄ SNOWFLAKE unicode', 'emojis/iphone-emoji/SNOWFLAKE.png'},
   {'❇', '❇ SPARKLE unicode', 'emojis/iphone-emoji/SPARKLE.png'},
   {'❌', '❌ CROSS MARK unicode', 'emojis/iphone-emoji/CROSS_MARK.png'},
   {'❎', '❎ NEGATIVE SQUARED CROSS MARK unicode', 'emojis/iphone-emoji/NEGATIVE_SQUARED_CROSS_MARK.png'},
   {'❓', '❓ BLACK QUESTION MARK ORNAMENT unicode', 'emojis/iphone-emoji/BLACK_QUESTION_MARK_ORNAMENT.png'},
   {'❔', '❔ WHITE QUESTION MARK ORNAMENT unicode', 'emojis/iphone-emoji/WHITE_QUESTION_MARK_ORNAMENT.png'},
   {'❕', '❕ WHITE EXCLAMATION MARK ORNAMENT unicode', 'emojis/iphone-emoji/WHITE_EXCLAMATION_MARK_ORNAMENT.png'},
   {'❗', '❗ HEAVY EXCLAMATION MARK SYMBOL unicode', 'emojis/iphone-emoji/HEAVY_EXCLAMATION_MARK_SYMBOL.png'},
   {'❤', '❤ HEAVY BLACK HEART unicode', 'emojis/iphone-emoji/HEAVY_BLACK_HEART.png'},
   {'➕', '➕ HEAVY PLUS SIGN unicode', 'emojis/iphone-emoji/HEAVY_PLUS_SIGN.png'},
   {'➖', '➖ HEAVY MINUS SIGN unicode', 'emojis/iphone-emoji/HEAVY_MINUS_SIGN.png'},
   {'➗', '➗ HEAVY DIVISION SIGN unicode', 'emojis/iphone-emoji/HEAVY_DIVISION_SIGN.png'},
   {'➡', '➡ BLACK RIGHTWARDS ARROW unicode', 'emojis/iphone-emoji/BLACK_RIGHTWARDS_ARROW.png'},
   {'➰', '➰ CURLY LOOP unicode', 'emojis/iphone-emoji/CURLY_LOOP.png'},
   {'➿', '➿ DOUBLE CURLY LOOP unicode', 'emojis/iphone-emoji/DOUBLE_CURLY_LOOP.png'},
   {'⤴', '⤴ ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS unicode', 'emojis/iphone-emoji/ARROW_POINTING_RIGHTWARDS_THEN_CURVING_UPWARDS.png'},
   {'⤵', '⤵ ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS unicode', 'emojis/iphone-emoji/ARROW_POINTING_RIGHTWARDS_THEN_CURVING_DOWNWARDS.png'},
   {'⬅', '⬅ LEFTWARDS BLACK ARROW unicode', 'emojis/iphone-emoji/LEFTWARDS_BLACK_ARROW.png'},
   {'⬆', '⬆ UPWARDS BLACK ARROW unicode', 'emojis/iphone-emoji/UPWARDS_BLACK_ARROW.png'},
   {'⬇', '⬇ DOWNWARDS BLACK ARROW unicode', 'emojis/iphone-emoji/DOWNWARDS_BLACK_ARROW.png'},
   {'⬛', '⬛ BLACK LARGE SQUARE unicode', 'emojis/iphone-emoji/BLACK_LARGE_SQUARE.png'},
   {'⬜', '⬜ WHITE LARGE SQUARE unicode', 'emojis/iphone-emoji/WHITE_LARGE_SQUARE.png'},
   {'⭐', '⭐ WHITE MEDIUM STAR unicode', 'emojis/iphone-emoji/WHITE_MEDIUM_STAR.png'},
   {'⭕', '⭕ HEAVY LARGE CIRCLE unicode', 'emojis/iphone-emoji/HEAVY_LARGE_CIRCLE.png'},
   {'〰', '〰 WAVY DASH unicode', 'emojis/iphone-emoji/WAVY_DASH.png'},
   {'〽', '〽 PART ALTERNATION MARK unicode', 'emojis/iphone-emoji/PART_ALTERNATION_MARK.png'},
   {'㊗', '㊗ CIRCLED IDEOGRAPH CONGRATULATION unicode', 'emojis/iphone-emoji/CIRCLED_IDEOGRAPH_CONGRATULATION.png'},
   {'㊙', '㊙ CIRCLED IDEOGRAPH SECRET unicode', 'emojis/iphone-emoji/CIRCLED_IDEOGRAPH_SECRET.png'},
   {'[呵呵]', '[呵呵] HeHe sina-weibo', 'emojis/weibo-emojis/d_hehe.png'},
   {'[嘻嘻]', '[嘻嘻] XiXi sina-weibo', 'emojis/weibo-emojis/d_xixi.png'},
   {'[哈哈]', '[哈哈] HaHa sina-weibo', 'emojis/weibo-emojis/d_haha.png'},
   {'[爱你]', '[爱你] AiNi sina-weibo', 'emojis/weibo-emojis/d_aini.png'},
   {'[挖鼻屎]', '[挖鼻屎] WaBiShi sina-weibo', 'emojis/weibo-emojis/d_wabishi.png'},
   {'[吃惊]', '[吃惊] ChiJing sina-weibo', 'emojis/weibo-emojis/d_chijing.png'},
   {'[晕]', '[晕] Yun sina-weibo', 'emojis/weibo-emojis/d_yun.png'},
   {'[泪]', '[泪] Lei sina-weibo', 'emojis/weibo-emojis/d_lei.png'},
   {'[馋嘴]', '[馋嘴] ChanZui sina-weibo', 'emojis/weibo-emojis/d_chanzui.png'},
   {'[抓狂]', '[抓狂] ZhuaKuang sina-weibo', 'emojis/weibo-emojis/d_zhuakuang.png'},
   {'[哼]', '[哼] Heng sina-weibo', 'emojis/weibo-emojis/d_heng.png'},
   {'[可爱]', '[可爱] KeAi sina-weibo', 'emojis/weibo-emojis/d_keai.png'},
   {'[怒]', '[怒] Nu sina-weibo', 'emojis/weibo-emojis/d_nu.png'},
   {'[汗]', '[汗] Han sina-weibo', 'emojis/weibo-emojis/d_han.png'},
   {'[害羞]', '[害羞] HaiXiu sina-weibo', 'emojis/weibo-emojis/d_haixiu.png'},
   {'[睡觉]', '[睡觉] ShuiJue sina-weibo', 'emojis/weibo-emojis/d_shuijiao.png'},
   {'[钱]', '[钱] Qian sina-weibo', 'emojis/weibo-emojis/d_qian.png'},
   {'[偷笑]', '[偷笑] TouXiao sina-weibo', 'emojis/weibo-emojis/d_touxiao.png'},
   {'[笑cry]', '[笑cry] XiaoCRY sina-weibo', 'emojis/weibo-emojis/d_xiaoku.png'},
   {'[doge]', '[doge] DOGE sina-weibo', 'emojis/weibo-emojis/d_doge.png'},
   {'[喵喵]', '[喵喵] MiaoMiao sina-weibo', '/home/bhj/tmp/weibo/res/drawable-hdpi/d_miao.png'},
   {'[酷]', '[酷] Ku sina-weibo', 'emojis/weibo-emojis/d_ku.png'},
   {'[衰]', '[衰] Shuai sina-weibo', 'emojis/weibo-emojis/d_shuai.png'},
   {'[闭嘴]', '[闭嘴] BiZui sina-weibo', 'emojis/weibo-emojis/d_bizui.png'},
   {'[鄙视]', '[鄙视] BiShi sina-weibo', 'emojis/weibo-emojis/d_bishi.png'},
   {'[花心]', '[花心] HuaXin sina-weibo', 'emojis/weibo-emojis/d_huaxin.png'},
   {'[鼓掌]', '[鼓掌] GuZhang sina-weibo', 'emojis/weibo-emojis/d_guzhang.png'},
   {'[悲伤]', '[悲伤] BeiShang sina-weibo', 'emojis/weibo-emojis/d_beishang.png'},
   {'[思考]', '[思考] SiKao sina-weibo', 'emojis/weibo-emojis/d_sikao.png'},
   {'[生病]', '[生病] ShengBing sina-weibo', 'emojis/weibo-emojis/d_shengbing.png'},
   {'[亲亲]', '[亲亲] QinQin sina-weibo', 'emojis/weibo-emojis/d_qinqin.png'},
   {'[怒骂]', '[怒骂] NuMa sina-weibo', 'emojis/weibo-emojis/d_numa.png'},
   {'[太开心]', '[太开心] TaiKaiXin sina-weibo', 'emojis/weibo-emojis/d_taikaixin.png'},
   {'[懒得理你]', '[懒得理你] LanDeLiNi sina-weibo', 'emojis/weibo-emojis/d_landelini.png'},
   {'[右哼哼]', '[右哼哼] YouHengHeng sina-weibo', 'emojis/weibo-emojis/d_youhengheng.png'},
   {'[左哼哼]', '[左哼哼] ZuoHengHeng sina-weibo', 'emojis/weibo-emojis/d_zuohengheng.png'},
   {'[嘘]', '[嘘] Xu sina-weibo', 'emojis/weibo-emojis/d_xu.png'},
   {'[委屈]', '[委屈] WeiQu sina-weibo', 'emojis/weibo-emojis/d_weiqu.png'},
   {'[吐]', '[吐] Tu sina-weibo', 'emojis/weibo-emojis/d_tu.png'},
   {'[可怜]', '[可怜] KeLian sina-weibo', 'emojis/weibo-emojis/d_kelian.png'},
   {'[打哈气]', '[打哈气] DaHaQi sina-weibo', 'emojis/weibo-emojis/d_dahaqi.png'},
   {'[挤眼]', '[挤眼] JiYan sina-weibo', 'emojis/weibo-emojis/d_jiyan.png'},
   {'[失望]', '[失望] ShiWang sina-weibo', 'emojis/weibo-emojis/d_shiwang.png'},
   {'[顶]', '[顶] Ding sina-weibo', 'emojis/weibo-emojis/d_ding.png'},
   {'[疑问]', '[疑问] YiWen sina-weibo', 'emojis/weibo-emojis/d_yiwen.png'},
   {'[困]', '[困] Kun sina-weibo', 'emojis/weibo-emojis/d_kun.png'},
   {'[感冒]', '[感冒] GanMao sina-weibo', 'emojis/weibo-emojis/d_ganmao.png'},
   {'[拜拜]', '[拜拜] BaiBai sina-weibo', 'emojis/weibo-emojis/d_baibai.png'},
   {'[黑线]', '[黑线] HeiXian sina-weibo', 'emojis/weibo-emojis/d_heixian.png'},
   {'[阴险]', '[阴险] YinXian sina-weibo', 'emojis/weibo-emojis/d_yinxian.png'},
   {'[打脸]', '[打脸] DaLian sina-weibo', 'emojis/weibo-emojis/d_dalian.png'},
   {'[傻眼]', '[傻眼] ShaYan sina-weibo', 'emojis/weibo-emojis/d_shayan.png'},
   {'[互粉]', '[互粉] HuFen sina-weibo', 'emojis/weibo-emojis/f_hufen.png'},
   {'[心]', '[心] Xin sina-weibo', 'emojis/weibo-emojis/l_xin.png'},
   {'[伤心]', '[伤心] ShangXin sina-weibo', 'emojis/weibo-emojis/l_shangxin.png'},
   {'[猪头]', '[猪头] ZhuTou sina-weibo', 'emojis/weibo-emojis/d_zhutou.png'},
   {'[熊猫]', '[熊猫] XiongMao sina-weibo', 'emojis/weibo-emojis/d_xiongmao.png'},
   {'[兔子]', '[兔子] TuZi sina-weibo', 'emojis/weibo-emojis/d_tuzi.png'},
   {'[握手]', '[握手] WoShou sina-weibo', 'emojis/weibo-emojis/h_woshou.png'},
   {'[作揖]', '[作揖] ZuoYi sina-weibo', 'emojis/weibo-emojis/h_zuoyi.png'},
   {'[赞]', '[赞] Zan sina-weibo', 'emojis/weibo-emojis/h_zan.png'},
   {'[耶]', '[耶] Ye sina-weibo', 'emojis/weibo-emojis/h_ye.png'},
   {'[good]', '[good] GOOD sina-weibo', 'emojis/weibo-emojis/h_good.png'},
   {'[弱]', '[弱] Ruo sina-weibo', 'emojis/weibo-emojis/h_ruo.png'},
   {'[不要]', '[不要] BuYao sina-weibo', 'emojis/weibo-emojis/h_buyao.png'},
   {'[ok]', '[ok] OK sina-weibo', 'emojis/weibo-emojis/h_ok.png'},
   {'[haha]', '[haha] HAHA sina-weibo', 'emojis/weibo-emojis/h_haha.png'},
   {'[来]', '[来] Lai sina-weibo', 'emojis/weibo-emojis/h_lai.png'},
   {'[威武]', '[威武] WeiWu sina-weibo', 'emojis/weibo-emojis/f_v5.png'},
   {'[鲜花]', '[鲜花] XianHua sina-weibo', 'emojis/weibo-emojis/w_xianhua.png'},
   {'[钟]', '[钟] Zhong sina-weibo', 'emojis/weibo-emojis/o_zhong.png'},
   {'[浮云]', '[浮云] FuYun sina-weibo', 'emojis/weibo-emojis/w_fuyun.png'},
   {'[飞机]', '[飞机] FeiJi sina-weibo', 'emojis/weibo-emojis/o_feiji.png'},
   {'[月亮]', '[月亮] YueLiang sina-weibo', 'emojis/weibo-emojis/w_yueliang.png'},
   {'[太阳]', '[太阳] TaiYang sina-weibo', 'emojis/weibo-emojis/w_taiyang.png'},
   {'[微风]', '[微风] WeiFeng sina-weibo', 'emojis/weibo-emojis/w_weifeng.png'},
   {'[下雨]', '[下雨] XiaYu sina-weibo', 'emojis/weibo-emojis/w_xiayu.png'},
   {'[给力]', '[给力] GeiLi sina-weibo', 'emojis/weibo-emojis/f_geili.png'},
   {'[神马]', '[神马] ShenMa sina-weibo', 'emojis/weibo-emojis/f_shenma.png'},
   {'[围观]', '[围观] WeiGuan sina-weibo', 'emojis/weibo-emojis/o_weiguan.png'},
   {'[话筒]', '[话筒] HuaTong sina-weibo', 'emojis/weibo-emojis/o_huatong.png'},
   {'[奥特曼]', '[奥特曼] AoTeMan sina-weibo', 'emojis/weibo-emojis/d_aoteman.png'},
   {'[萌]', '[萌] Meng sina-weibo', 'emojis/weibo-emojis/f_meng.png'},
   {'[囧]', '[囧] Jiong sina-weibo', 'emojis/weibo-emojis/f_jiong.png'},
   {'[织]', '[织] Zhi sina-weibo', 'emojis/weibo-emojis/f_zhi.png'},
   {'[礼物]', '[礼物] LiWu sina-weibo', 'emojis/weibo-emojis/o_liwu.png'},
   {'[喜]', '[喜] Xi sina-weibo', 'emojis/weibo-emojis/f_xi.png'},
   {'[围脖]', '[围脖] WeiBo sina-weibo', 'emojis/weibo-emojis/more_weibo.png'},
   {'[音乐]', '[音乐] YinYue sina-weibo', 'emojis/weibo-emojis/o_yinyue.png'},
   {'[绿丝带]', '[绿丝带] LvSiDai sina-weibo', 'emojis/weibo-emojis/o_lvsidai.png'},
   {'[蛋糕]', '[蛋糕] DanGao sina-weibo', 'emojis/weibo-emojis/o_dangao.png'},
   {'[蜡烛]', '[蜡烛] LaZhu sina-weibo', 'emojis/weibo-emojis/o_lazhu.png'},
   {'[干杯]', '[干杯] GanBei sina-weibo', 'emojis/weibo-emojis/o_ganbei.png'},
   {'[男孩儿]', '[男孩儿] NanHaiEr sina-weibo', 'emojis/weibo-emojis/d_nanhaier.png'},
   {'[女孩儿]', '[女孩儿] NvHaiEr sina-weibo', 'emojis/weibo-emojis/d_nvhaier.png'},
   {'[肥皂]', '[肥皂] FeiZao sina-weibo', 'emojis/weibo-emojis/d_feizao.png'},
   {'[照相机]', '[照相机] ZhaoXiangJi sina-weibo', 'emojis/weibo-emojis/o_zhaoxiangji.png'},
   {'[浪]', '[浪] Lang sina-weibo', 'emojis/weibo-emojis/d_lang.png'},
   {'[沙尘暴]', '[沙尘暴] ShaChenBao sina-weibo', 'emojis/weibo-emojis/w_shachenbao.png'},
   {'[笑哈哈]', '[笑哈哈] XiaoHaHa sina-weibo', 'emojis/weibo-emojis/lxh_xiaohaha.png'},
   {'[好爱哦]', '[好爱哦] HaoAiO sina-weibo', 'emojis/weibo-emojis/lxh_haoaio.png'},
   {'[噢耶]', '[噢耶] OYe sina-weibo', 'emojis/weibo-emojis/lxh_oye.png'},
   {'[偷乐]', '[偷乐] TouLe sina-weibo', 'emojis/weibo-emojis/lxh_toule.png'},
   {'[泪流满面]', '[泪流满面] LeiLiuManMian sina-weibo', 'emojis/weibo-emojis/lxh_leiliumanmian.png'},
   {'[巨汗]', '[巨汗] JuHan sina-weibo', 'emojis/weibo-emojis/lxh_juhan.png'},
   {'[抠鼻屎]', '[抠鼻屎] KouBiShi sina-weibo', 'emojis/weibo-emojis/lxh_koubishi.png'},
   {'[求关注]', '[求关注] QiuGuanZhu sina-weibo', 'emojis/weibo-emojis/lxh_qiuguanzhu.png'},
   {'[好喜欢]', '[好喜欢] HaoXiHuan sina-weibo', 'emojis/weibo-emojis/lxh_haoxihuan.png'},
   {'[崩溃]', '[崩溃] BengKui sina-weibo', 'emojis/weibo-emojis/lxh_bengkui.png'},
   {'[好囧]', '[好囧] HaoJiong sina-weibo', 'emojis/weibo-emojis/lxh_haojiong.png'},
   {'[震惊]', '[震惊] ZhenJing sina-weibo', 'emojis/weibo-emojis/lxh_zhenjing.png'},
   {'[别烦我]', '[别烦我] BieFanWo sina-weibo', 'emojis/weibo-emojis/lxh_biefanwo.png'},
   {'[不好意思]', '[不好意思] BuHaoYiSi sina-weibo', 'emojis/weibo-emojis/lxh_buhaoyisi.png'},
   {'[羞嗒嗒]', '[羞嗒嗒] XiuDaDa sina-weibo', 'emojis/weibo-emojis/lxh_xiudada.png'},
   {'[得意地笑]', '[得意地笑] DeYiDeXiao sina-weibo', 'emojis/weibo-emojis/lxh_deyidexiao.png'},
   {'[纠结]', '[纠结] JiuJie sina-weibo', 'emojis/weibo-emojis/lxh_jiujie.png'},
   {'[悲催]', '[悲催] BeiCui sina-weibo', 'emojis/weibo-emojis/lxh_beicui.png'},
   {'[甩甩手]', '[甩甩手] ShuaiShuaiShou sina-weibo', 'emojis/weibo-emojis/lxh_shuaishuaishou.png'},
   {'[好棒]', '[好棒] HaoBang sina-weibo', 'emojis/weibo-emojis/lxh_haobang.png'},
   {'[瞧瞧]', '[瞧瞧] QiaoQiao sina-weibo', 'emojis/weibo-emojis/lxh_qiaoqiao.png'},
   {'[不想上班]', '[不想上班] BuXiangShangBan sina-weibo', 'emojis/weibo-emojis/lxh_buxiangshangban.png'},
   {'[困死了]', '[困死了] KunSiLe sina-weibo', 'emojis/weibo-emojis/lxh_kunsile.png'},
   {'[许愿]', '[许愿] XuYuan sina-weibo', 'emojis/weibo-emojis/lxh_xuyuan.png'},
   {'[丘比特]', '[丘比特] QiuBiTe sina-weibo', 'emojis/weibo-emojis/lxh_qiubite.png'},
   {'[有鸭梨]', '[有鸭梨] YouYaLi sina-weibo', 'emojis/weibo-emojis/lxh_youyali.png'},
   {'[想一想]', '[想一想] XiangYiXiang sina-weibo', 'emojis/weibo-emojis/lxh_xiangyixiang.png'},
   {'[躁狂症]', '[躁狂症] ZaoKuangZheng sina-weibo', 'emojis/weibo-emojis/kuangzaozheng.png'},
   {'[转发]', '[转发] ZhuanFa sina-weibo', 'emojis/weibo-emojis/lxh_zhuanfa.png'},
   {'[互相膜拜]', '[互相膜拜] HuXiangMoBai sina-weibo', 'emojis/weibo-emojis/lxh_xianghumobai.png'},
   {'[雷锋]', '[雷锋] LeiFeng sina-weibo', 'emojis/weibo-emojis/lxh_leifeng.png'},
   {'[杰克逊]', '[杰克逊] JieKeXun sina-weibo', 'emojis/weibo-emojis/lxh_jiekexun.png'},
   {'[玫瑰]', '[玫瑰] MeiGui sina-weibo', 'emojis/weibo-emojis/lxh_meigui.png'},
   {'[hold住]', '[hold住] HOLDZhu sina-weibo', 'emojis/weibo-emojis/lxh_holdzhu.png'},
   {'[群体围观]', '[群体围观] QunTiWeiGuan sina-weibo', 'emojis/weibo-emojis/lxh_quntiweiguan.png'},
   {'[推荐]', '[推荐] TuiJian sina-weibo', 'emojis/weibo-emojis/lxh_tuijian.png'},
   {'[赞啊]', '[赞啊] ZanA sina-weibo', 'emojis/weibo-emojis/lxh_zana.png'},
   {'[被电]', '[被电] BeiDian sina-weibo', 'emojis/weibo-emojis/lxh_beidian.png'},
   {'[霹雳]', '[霹雳] PiLi sina-weibo', 'emojis/weibo-emojis/lxh_pili.png'},
   {'[微笑]', '[微笑] WeiXiao [Smile] weixin-qq', 'emojis/qq-emojis/smiley_0.png'},
   {'[撇嘴]', '[撇嘴] PieZui [Grimace] weixin-qq', 'emojis/qq-emojis/smiley_1.png'},
   {'[色]', '[色] Se [Drool] weixin-qq', 'emojis/qq-emojis/smiley_2.png'},
   {'[发呆]', '[发呆] FaDai [Scowl] weixin-qq', 'emojis/qq-emojis/smiley_3.png'},
   {'[得意]', '[得意] DeYi [CoolGuy] weixin-qq', 'emojis/qq-emojis/smiley_4.png'},
   {'[流泪]', '[流泪] LiuLei [Sob] weixin-qq', 'emojis/qq-emojis/smiley_5.png'},
   {'[害羞]', '[害羞] HaiXiu [Shy] weixin-qq', 'emojis/qq-emojis/smiley_6.png'},
   {'[闭嘴]', '[闭嘴] BiZui [Silent] weixin-qq', 'emojis/qq-emojis/smiley_7.png'},
   {'[睡]', '[睡] Shui [Sleep] weixin-qq', 'emojis/qq-emojis/smiley_8.png'},
   {'[大哭]', '[大哭] DaKu [Cry] weixin-qq', 'emojis/qq-emojis/smiley_9.png'},
   {'[尴尬]', '[尴尬] GanGa [Awkward] weixin-qq', 'emojis/qq-emojis/smiley_10.png'},
   {'[发怒]', '[发怒] FaNu [Angry] weixin-qq', 'emojis/qq-emojis/smiley_11.png'},
   {'[调皮]', '[调皮] DiaoPi [Tongue] weixin-qq', 'emojis/qq-emojis/smiley_12.png'},
   {'[呲牙]', '[呲牙] CiYa [Grin] weixin-qq', 'emojis/qq-emojis/smiley_13.png'},
   {'[惊讶]', '[惊讶] JingYa [Surprise] weixin-qq', 'emojis/qq-emojis/smiley_14.png'},
   {'[难过]', '[难过] NanGuo [Frown] weixin-qq', 'emojis/qq-emojis/smiley_15.png'},
   {'[酷]', '[酷] Ku [Ruthless] weixin-qq', 'emojis/qq-emojis/smiley_16.png'},
   {'[冷汗]', '[冷汗] LengHan [Blush] weixin-qq', 'emojis/qq-emojis/smiley_17.png'},
   {'[抓狂]', '[抓狂] ZhuaKuang [Scream] weixin-qq', 'emojis/qq-emojis/smiley_18.png'},
   {'[吐]', '[吐] Tu [Puke] weixin-qq', 'emojis/qq-emojis/smiley_19.png'},
   {'[偷笑]', '[偷笑] TouXiao [Chuckle] weixin-qq', 'emojis/qq-emojis/smiley_20.png'},
   {'[可爱]', '[可爱] KeAi [Joyful] weixin-qq', 'emojis/qq-emojis/smiley_21.png'},
   {'[白眼]', '[白眼] BaiYan [Slight] weixin-qq', 'emojis/qq-emojis/smiley_22.png'},
   {'[傲慢]', '[傲慢] AoMan [Smug] weixin-qq', 'emojis/qq-emojis/smiley_23.png'},
   {'[饥饿]', '[饥饿] JiE [Hungry] weixin-qq', 'emojis/qq-emojis/smiley_24.png'},
   {'[困]', '[困] Kun [Drowsy] weixin-qq', 'emojis/qq-emojis/smiley_25.png'},
   {'[惊恐]', '[惊恐] JingKong [Panic] weixin-qq', 'emojis/qq-emojis/smiley_26.png'},
   {'[流汗]', '[流汗] LiuHan [Sweat] weixin-qq', 'emojis/qq-emojis/smiley_27.png'},
   {'[憨笑]', '[憨笑] HanXiao [Laugh] weixin-qq', 'emojis/qq-emojis/smiley_28.png'},
   {'[大兵]', '[大兵] DaBing [Commando] weixin-qq', 'emojis/qq-emojis/smiley_29.png'},
   {'[奋斗]', '[奋斗] FenDou [Determined] weixin-qq', 'emojis/qq-emojis/smiley_30.png'},
   {'[咒骂]', '[咒骂] ZhouMa [Scold] weixin-qq', 'emojis/qq-emojis/smiley_31.png'},
   {'[疑问]', '[疑问] YiWen [Shocked] weixin-qq', 'emojis/qq-emojis/smiley_32.png'},
   {'[嘘]', '[嘘] Xu [Shhh] weixin-qq', 'emojis/qq-emojis/smiley_33.png'},
   {'[晕]', '[晕] Yun [Dizzy] weixin-qq', 'emojis/qq-emojis/smiley_34.png'},
   {'[折磨]', '[折磨] Zhe:mo [Tormented] weixin-qq', 'emojis/qq-emojis/smiley_35.png'},
   {'[衰]', '[衰] Shuai [Toasted] weixin-qq', 'emojis/qq-emojis/smiley_36.png'},
   {'[骷髅]', '[骷髅] KuLou [Skull] weixin-qq', 'emojis/qq-emojis/smiley_37.png'},
   {'[敲打]', '[敲打] QiaoDa [Hammer] weixin-qq', 'emojis/qq-emojis/smiley_38.png'},
   {'[再见]', '[再见] ZaiJian [Wave] weixin-qq', 'emojis/qq-emojis/smiley_39.png'},
   {'[擦汗]', '[擦汗] CaHan [Speechless] weixin-qq', 'emojis/qq-emojis/smiley_40.png'},
   {'[抠鼻]', '[抠鼻] KouBi [NosePick] weixin-qq', 'emojis/qq-emojis/smiley_41.png'},
   {'[鼓掌]', '[鼓掌] GuZhang [Clap] weixin-qq', 'emojis/qq-emojis/smiley_42.png'},
   {'[糗大了]', '[糗大了] QiuDaLe [Shame] weixin-qq', 'emojis/qq-emojis/smiley_43.png'},
   {'[坏笑]', '[坏笑] HuaiXiao [Trick] weixin-qq', 'emojis/qq-emojis/smiley_44.png'},
   {'[左哼哼]', '[左哼哼] ZuoHengHeng [Bah ! L] weixin-qq', 'emojis/qq-emojis/smiley_45.png'},
   {'[右哼哼]', '[右哼哼] YouHengHeng [Bah ! R] weixin-qq', 'emojis/qq-emojis/smiley_46.png'},
   {'[哈欠]', '[哈欠] HaQian [Yawn] weixin-qq', 'emojis/qq-emojis/smiley_47.png'},
   {'[鄙视]', '[鄙视] BiShi [Pooh-pooh] weixin-qq', 'emojis/qq-emojis/smiley_48.png'},
   {'[委屈]', '[委屈] WeiQu [Shrunken] weixin-qq', 'emojis/qq-emojis/smiley_49.png'},
   {'[快哭了]', '[快哭了] KuaiKuLe [TearingUp] weixin-qq', 'emojis/qq-emojis/smiley_50.png'},
   {'[阴险]', '[阴险] YinXian [Sly] weixin-qq', 'emojis/qq-emojis/smiley_51.png'},
   {'[亲亲]', '[亲亲] QinQin [Kiss] weixin-qq', 'emojis/qq-emojis/smiley_52.png'},
   {'[吓]', '[吓] He [Wrath] weixin-qq', 'emojis/qq-emojis/smiley_53.png'},
   {'[可怜]', '[可怜] KeLian [Whimper] weixin-qq', 'emojis/qq-emojis/smiley_54.png'},
   {'[菜刀]', '[菜刀] CaiDao [Cleaver] weixin-qq', 'emojis/qq-emojis/smiley_55.png'},
   {'[西瓜]', '[西瓜] XiGua [Watermelon] weixin-qq', 'emojis/qq-emojis/smiley_56.png'},
   {'[啤酒]', '[啤酒] PiJiu [Beer] weixin-qq', 'emojis/qq-emojis/smiley_57.png'},
   {'[篮球]', '[篮球] LanQiu [Basketball] weixin-qq', 'emojis/qq-emojis/smiley_58.png'},
   {'[乒乓]', '[乒乓] PingPang [PingPong] weixin-qq', 'emojis/qq-emojis/smiley_59.png'},
   {'[咖啡]', '[咖啡] KaFei [Coffee] weixin-qq', 'emojis/qq-emojis/smiley_60.png'},
   {'[饭]', '[饭] Fan [Rice] weixin-qq', 'emojis/qq-emojis/smiley_61.png'},
   {'[猪头]', '[猪头] ZhuTou [Pig] weixin-qq', 'emojis/qq-emojis/smiley_62.png'},
   {'[玫瑰]', '[玫瑰] MeiGui [Rose] weixin-qq', 'emojis/qq-emojis/smiley_63.png'},
   {'[凋谢]', '[凋谢] DiaoXie [Wilt] weixin-qq', 'emojis/qq-emojis/smiley_64.png'},
   {'[示爱]', '[示爱] ShiAi [Lips] weixin-qq', 'emojis/qq-emojis/smiley_65.png'},
   {'[爱心]', '[爱心] AiXin [Heart] weixin-qq', 'emojis/qq-emojis/smiley_66.png'},
   {'[心碎]', '[心碎] XinSui [BrokenHeart] weixin-qq', 'emojis/qq-emojis/smiley_67.png'},
   {'[蛋糕]', '[蛋糕] DanGao [Cake] weixin-qq', 'emojis/qq-emojis/smiley_68.png'},
   {'[闪电]', '[闪电] ShanDian [Lightning] weixin-qq', 'emojis/qq-emojis/smiley_69.png'},
   {'[炸弹]', '[炸弹] ZhaDan [Bomb] weixin-qq', 'emojis/qq-emojis/smiley_70.png'},
   {'[刀]', '[刀] Dao [Dagger] weixin-qq', 'emojis/qq-emojis/smiley_71.png'},
   {'[足球]', '[足球] ZuQiu [Soccer] weixin-qq', 'emojis/qq-emojis/smiley_72.png'},
   {'[瓢虫]', '[瓢虫] PiaoChong [Ladybug] weixin-qq', 'emojis/qq-emojis/smiley_73.png'},
   {'[便便]', '[便便] BianBian [Poop] weixin-qq', 'emojis/qq-emojis/smiley_74.png'},
   {'[月亮]', '[月亮] YueLiang [Moon] weixin-qq', 'emojis/qq-emojis/smiley_75.png'},
   {'[太阳]', '[太阳] TaiYang [Sun] weixin-qq', 'emojis/qq-emojis/smiley_76.png'},
   {'[礼物]', '[礼物] LiWu [Gift] weixin-qq', 'emojis/qq-emojis/smiley_77.png'},
   {'[拥抱]', '[拥抱] YongBao [Hug] weixin-qq', 'emojis/qq-emojis/smiley_78.png'},
   {'[强]', '[强] Qiang [Strong] weixin-qq', 'emojis/qq-emojis/smiley_79.png'},
   {'[弱]', '[弱] Ruo [Weak] weixin-qq', 'emojis/qq-emojis/smiley_80.png'},
   {'[握手]', '[握手] WoShou [Shake] weixin-qq', 'emojis/qq-emojis/smiley_81.png'},
   {'[胜利]', '[胜利] ShengLi [Peace] weixin-qq', 'emojis/qq-emojis/smiley_82.png'},
   {'[抱拳]', '[抱拳] BaoQuan [Fight] weixin-qq', 'emojis/qq-emojis/smiley_83.png'},
   {'[勾引]', '[勾引] GouYin [Beckon] weixin-qq', 'emojis/qq-emojis/smiley_84.png'},
   {'[拳头]', '[拳头] QuanTou [Fist] weixin-qq', 'emojis/qq-emojis/smiley_85.png'},
   {'[差劲]', '[差劲] ChaJing [Pinky] weixin-qq', 'emojis/qq-emojis/smiley_86.png'},
   {'[爱你]', '[爱你] AiNi [RockOn] weixin-qq', 'emojis/qq-emojis/smiley_87.png'},
   {'[NO]', '[NO] NO [NO] weixin-qq', 'emojis/qq-emojis/smiley_88.png'},
   {'[OK]', '[OK] OK [OK] weixin-qq', 'emojis/qq-emojis/smiley_89.png'},
   {'[爱情]', '[爱情] AiQing [InLove] weixin-qq', 'emojis/qq-emojis/smiley_90.png'},
   {'[飞吻]', '[飞吻] FeiWen [Blowkiss] weixin-qq', 'emojis/qq-emojis/smiley_91.png'},
   {'[跳跳]', '[跳跳] TiaoTiao [Waddle] weixin-qq', 'emojis/qq-emojis/smiley_92.png'},
   {'[发抖]', '[发抖] FaDou [Tremble] weixin-qq', 'emojis/qq-emojis/smiley_93.png'},
   {'[怄火]', '[怄火] OuHuo [Aaagh] weixin-qq', 'emojis/qq-emojis/smiley_94.png'},
   {'[转圈]', '[转圈] ZhuanQuan [Twirl] weixin-qq', 'emojis/qq-emojis/smiley_95.png'},
   {'[磕头]', '[磕头] KeTou [Kotow] weixin-qq', 'emojis/qq-emojis/smiley_96.png'},
   {'[回头]', '[回头] HuiTou [Dramatic] weixin-qq', 'emojis/qq-emojis/smiley_97.png'},
   {'[跳绳]', '[跳绳] TiaoSheng [JumpRope] weixin-qq', 'emojis/qq-emojis/smiley_98.png'},
   {'[挥手]', '[挥手] HuiShou [Surrender] weixin-qq', 'emojis/qq-emojis/smiley_99.png'},
   {'[激动]', '[激动] JiDong [Exciting] weixin-qq', 'emojis/qq-emojis/smiley_100.png'},
   {'[街舞]', '[街舞] JieWu [HipHot] weixin-qq', 'emojis/qq-emojis/smiley_101.png'},
   {'[献吻]', '[献吻] XianWen [ShowLove] weixin-qq', 'emojis/qq-emojis/smiley_102.png'},
   {'[左太极]', '[左太极] ZuoTaiJi [TaiChi L] weixin-qq', 'emojis/qq-emojis/smiley_103.png'},
   {'[右太极]', '[右太极] YouTaiJi [TaiChi R] weixin-qq', 'emojis/qq-emojis/smiley_104.png'},
}

return emojis;
