#!/bin/sh
#
# Copyright (c) Josef "Jeff" Sipek, 2006-2011
#

USAGE=""
if [ -z "$GUILT_VERSION" ]; then
	echo "Invoking `basename $0` directly is no longer supported." >&2
	exit 1
fi

_main() {

if [ $# -ne 0 ]; then
	usage
fi

n=`wc -l < $applied`
n=`expr $n + 1`

get_series | sed -n -e "$n,\$p"

}
