#!/bin/bash
# [[file:~/src/github/org-kungfu/org-kungfu.org::jql][jql]]
set -e
get-config() {
    git config -f ~/.config/org-kungfu/config.ini "$@"
}


## start code-generator "^\\s *#\\s *"
# generate-getopt -P u:user='$(get-config ok.username)' \
    # p:pass='$(get-config ok.password)' \
    # U:jiraurl='$(get-config ok.jiraurl)'
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o U:p:u:h \
                      --long jiraurl:,pass:,user:,help \
                      -n $(basename -- $0) -- "$@")
declare jiraurl=$(get-config ok.jiraurl)
declare pass=$(get-config ok.password)
declare user=$(get-config ok.username)
eval set -- "$TEMP"
while true; do
    case "$1" in

        -U|--jiraurl)
            jiraurl=$2
            shift 2

            ;;
        -p|--pass)
            pass=$2
            shift 2

            ;;
        -u|--user)
            user=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-U, '
            printf %-24s '--jiraurl=JIRAURL...'
            echo
            printf %06s '-p, '
            printf %-24s '--pass=PASS...'
            echo
            printf %06s '-u, '
            printf %-24s '--user=USER...'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

jql_str=$(
    urlify "$@"
       )

curl -s -u "${user}:${pass}" "${jiraurl}rest/api/2/search?jql=$jql_str"
# jql ends here
