System-config is my customizations of Posix systems (Linux/Cygwin/Mac
OS X). It aims to reproduce my complete working environment with a
single command.

It will download and install the debian programs that I need, compile
the projects that I wrote myself, and properly configure the dot files
(=.bashrc=, =.emacs=, and so on).

Among my open source projects that system-config will download and
compile, there's a very useful project named [[https://github.com/baohaojun/beagrep][beagrep]]. It combines a
search engine with grep. It is very useful for reading source code. In
fact I use it to read system-config's own source code (code reading is
like solving puzzles, solving puzzles is about looking for answers, and
what's best for looking for answers? Search Engines. Beagrep is a local
search engine best tuned for software projects).

* How to use it

Under debian linux or other debian derived systems such as ubuntu, it's simple to set up system-config:

#+BEGIN_SRC sh
  git clone https://github.com/baohaojun/system-config/ ~/system-config &&
      ~/system-config/bin/Linux/after-check-out.sh
#+END_SRC

You probably need to fix some bugs when running =after-check-out.sh=. And then, make system-config your own by forking it and customizing it.

On non debian systems, it's not automated yet -- patches are welcome.

* Disclaimer

System-config started out as a very personal project. If you decided to use it, please do so at your own risk, there is absolutely no warranty of any kind😅.

If you have your own customization, it would be a good idea that you back them up before you try system-config. It's a good idea that you too put your own customization into a git repo, if you have not done so already.

* Sub projects

System-config comes with some sub projects. They will be git cloned into =~/src/github/=, such as [[http://github.com/baohaojun/emacs.d][~/src/github/emacs.d]].
