local map = {}
map['com.alibaba.android.rimet/com.alibaba.android.dingtalkim.activities.AddRobotActivity'] = 'No-Post'
map['com.alibaba.android.rimet/com.alibaba.android.dingtalkim.activities.ChatMsgActivity'] = 'Find-Button'
map['com.alibaba.android.rimet/com.alibaba.android.dingtalkim.activities.ConfirmCreatingConversationActivity'] = 'No-Post'
map['com.alibaba.android.rimet/com.alibaba.lightapp.runtime.activity.CommonWebViewActivity'] = 'No-Post'
map['com.amazon.kindle/com.amazon.kcp.oob.MainActivity'] = 'No-Post'
map['com.amazon.kindle/com.amazon.kcp.reader.StandAloneBookReaderActivity'] = 'No-Post'
map['com.android.contacts/com.android.contacts.activities.DialtactsActivity'] = 'No-Post'
map['com.netease.onmyoji/com.netease.onmyoji.Client'] = 'Enter-Key'
map['com.sina.weibo/com.sina.weibo.weiyou.DMSingleChatActivity'] = 'Find-Button'
map['com.tencent.mm/com.tencent.mm.plugin.fts.ui.FTSMainUI'] = 'Enter-Key'
map['com.tencent.mm/com.tencent.mm.plugin.profile.ui.SayHiWithSnsPermissionUI'] = 'No-Post'
map['com.tencent.mm/com.tencent.mm.plugin.sns.ui.SnsCommentDetailUI'] = 'Find-Button'
map['com.tencent.mm/com.tencent.mm.ui.chatting.ChattingUI'] = 'Find-Button'
map['com.tencent.mm/com.tencent.mm.ui.LauncherUI'] = 'Find-Button'
return map
