#!/bin/bash

case $1 in
    hibernate)
        ;;
    suspend)
        ;;
    thaw)
        ;;
    resume|post)
        (
            su bhj -c "sleep 1 && bash -x ~bhj/bin/switch-touchpad &"
            echo done "$@"
            echo
        ) > ~bhj/.logs/$(basename $0).log 2>&1
        ;;
    pre)
        ;;
    *)  echo "ERROR: called incorrectly."
        ;;
esac
