* 注意

目前（2011-11-21）我们只支持在Windows下用MarsBurner烧Sultan的手机，以后会加入对DKB、Jasmin等设备的烧机支持。

（因为有些共享文件夹的链接需要在IE下才能打开，所以请考虑在windows IE下浏览此页面，Sorry！）

* 准备工作

需要装vc2008动态运行库、装烧机模式的驱动

** vc2008 redist包安装

第一次运行MarsBurner之前，如果以前没有安装过vc2008的动态库，则需要安装一下，否则双击MarsBurner快捷方式图标后Windows会出如下错误提示：

#+begin_example
The application has failed to start because its side-by-side configuration is incorrect.
#+end_example

你可以直接从 [[//bible/Public/user/tools-team/vc2008-sp1-redist-x86.exe][这个共享文件]] 安装。

如果不能访问我们的内部共享目录，请访问 [[http://www.microsoft.com/download/en/details.aspx?displaylang=en&id=5582][这个微软网页]] 。

** 进入烧机模式

在Sultan手机上进入烧机模式，需要先按着Vol Down键，再开机。*注意*如果用插拔电池的方式开机的话，需要先按着Vol Down，再插入电池。

进入烧机模式后，手机会显示绿色背景，上有flashing mode提示，见下图（TBD，补图）：

** 安装烧机驱动

手机进入烧机模式后，用usb线与PC相连，如果以前没有装过烧机驱动，则需要到设备管理器里安装一下这个驱动。

驱动程序的位置在你的MarsBurner安装目录的drivers子目录下，如果你的MarsBurner安装选的是默认位置，你可以点击 [[C:/Program%20Files/marvell/MarsBurner/drivers][此处]] 直接打开驱动程序所在的目录。

* 烧机

** 安装MarsBurner

最新的安装程序在 [[//bible/Public/user/tools-team/MarsBurner][这里]] 能找到。如果以前装过较老的版本，则点击安装程序后会自动提示卸载之前版本，不需要专门先卸载再安装。

** 获取CM-release包

 * 到 [[//bible/cm/][这个共享文件夹]] 下找最新的（或相应版本的）CM release包，拷贝到自己的PC上。

   *注意*：本地拷贝的全路径中不能含有中文字符，因为这样会导致MarsBurner不能正确烧写。
   
   

** 运行MarsBurner

这里需要注意的是在Win7下需要用administrator权限来运行MarsBurner。

启动后点“...”的按钮，选择CM release拷贝文件夹下的pxa910_sultan.blf文件。

手机进入烧机模式，并用usb线连到PC，注意这时MarsBurner上的usb图标由灰色
变为绿色，并且“Flash”按钮也由disable变成enable，表示已经检测到烧机模式
的手机与PC连接。这时就可以点Flash按钮进行烧机了。

烧机成功后会有提示。TBD：补图。




* 烧或不烧OBM的风险

Marvell的平台上会出现把手机烧成“砖头”的情况：无法起机、无法再进烧机模式。
下面给大家介绍一下这里面涉及到的各种故事，希望通过普及这些知识，能尽量
避免出现烧成砖头的情况。

** 什么是OBM

简单地说，OBM是Marvell平台特有的一个底层模块。比Kernel、Kernel的
bootloader都要更底层。比它更底层的就是rom code了。

所以在正常启动的过程中，它的主要任务是在起机的早期阶段，从rom code那里
接过接过控制权，做完它该做的工作后，把控制权转交给bootloader。

** 什么是rom code

几乎所有厂家的CPU都会有自己的rom code，也就是固化在CPU内部的一段代码，
所有的rom code的功能也是大同小异的，那就是完成cpu的最基本的初始化，把控
制权交给下一个模块。

所以在我们的平台上，正常启动过程中rom code的任务就是，在完成基本初始化
后，把OBM模块从系统内部存储的OBM分区上读到DDR中，并跳转到OBM代码的起始
位置。

** 进入烧机模式的条件

上面所说的两个component，除了在正常启动的过程中有它们各自的角色之外，还
都需要承担与烧机相关的任务。

咱们现在做的Marvell平台，想进入烧机模式，需要满足下面的两个条件之一：

- rom code能进入烧机模式。

  要求：手机是空phone。

  空phone的意思就是手机的nand处于出厂状态，全部字节读出来都是一个固定的
  值（所有bit全为1，也就是所有byte全为0xff）。这种情况下，rom code把
  obm分区读到DDR里以后会发现obm模块是不正确的（你想啊，正确的obm模块怎
  么可能所有字节全是一个值呢），于是它就打断了正常启动模式，也就是说，
  不把控制权转交给OBM了（你想啊，OBM这时候全为0xff，交给它那不肯定“跑
  飞”了吗），而是做出这种情况下唯一的选择：进入烧机模式。希望通过烧个机，
  烧出个正确的obm来，这样下次就可以走正常启动流程了。大家可以想一下，如
  果没烧出个正确的obm，会怎么样呢？

  （所以，事实上并不需要要求手机的整个nand都处于出厂状态，只要把OBM所在
  的那块分区擦除为出厂状态就可以让rom code进入烧机模式了）。

- OBM能进入烧机模式。

  如果不满足上面的空phone条件，那么，rom code就会走正常启动流程，把控制
  权交给obm，而obm需要通过某些外部条件，比如，Volume Down键是不是被按下，
  来决定是继续正常启动，还是进入烧机模式。

  先决条件：OBM分区里的OBM代码能正确工作。

  风险就全都出在这儿了：如果我们某一次烧机之后，动过OBM分区，并且烧完之
  后OBM分区里新的代码不能正常工作了，手机也就成砖头了。

** 烧成“砖头”后如何修复

首先，要找Hardware的同事，请他（她）把你的手机拆开，焊上jtag线。

然后，要找会使用jtag的同事，把手机擦除成空phone状态，烧回一个正确的版本。

最后，还是找Hardware的同事，请他（她）把jtag线拆下，把手机重新装回去。


所以，这个代价还是挺大的，尤其是如果出现某一个版本的obm有问题，导致一批
同事的手机都烧成砖头的情况的话，Hardware同事就会很不高兴了，老板也会很
不高兴...

为了避免这种情况出现，请大家一定要小心，不要烧错obm。
