* 乌龙

由于目前我们特殊的办公环境，我们需要同时访问三个网络：

- 外网，也就是Internet。
- 办公室内网，sync源代码、访问CM每天的release包都是这个网络。
- 公司VPN。如果能用上这个网络的话，下载邮件会快一些，同时一些公司内的事务如报销等也必须用它。

关于公司VPN，必须是有laptop的同事，在Windows下、才能访问，在Linux下好像是不行的。所以我们以下的描述，都会基于这个标准配置：即Laptop + Windows 7。

- 外网，走无线。
- 内网，走以太。

  这样做的理由，是因为内网访问需要比较大的带宽，比如CM release的包，一
  个有几百兆，我们的以太网是千兆网，秒秒钟就拷完了，走无线的话，至少二
  十倍以上的时间才能拷完，并且辐射大...

  这样会引发一个问题，无法访问外网。当有线、无线两者并存的时候，操作系
  统会认为有线网络优于无线网络，从而访问Internet的路由默认置为从有线网
  络走，可是我们的有线网络配成了内网，是无法访问Internet的。

  所以这时候需要改一下路由表，设成无线路由优先：

  #+begin_example
  route delete 0.0.0.0
  route add -p 0.0.0.0 mask 0.0.0.0 192.168.1.1 metric 1 IF 11
  route add -p 0.0.0.0 mask 0.0.0.0 10.21.128.2 metric 30 IF 10
  #+end_example
  
  解释一下：

  1) 把所有0.0.0.0也就是所谓的默认路由都删掉，因为我们下面要重设它，
     不删的话，可能重设的路由不能马上生效。

  2) 增加一条网关为无线网关（192.168.1.1）、优先级最高（也即metric最
     小，为1）、网卡为无线网卡（Interface，IF为我的无线网卡IF号
     11[fn:: 这里不同的机器可能是不同的，在 ~route print~ 命令的顶部会列
     出你机器上所有的网卡IF]）、重启保留（-p参数）的路由。

  3) 与2)是类似的，增加一条从有线网络走的默认路由，但是把优先级调成较低（metric 30）。

  另外要注意的是，在改route表的时候，一定要用administrator！在Win7开始
  菜单里搜到cmd.exe后，点右键选“Run as Administrator”。

  

- 关于vpn，问题比较多，也是我出了几次乌龙的原因：

** 谁动了我的路由?!!

我们的vpn软件，Juniper Network Connect，内建了路由表监测和绑架的功能。
也就是说，

- 它会实时地监测所有10.*的路由，一旦系统中出现这样的路由，它会马上将其
  删除，只允许自己的10.0.0.0路由；

- 一旦发现有人改了10.*的路由的优先级也就是metric参数，它会马上将其改回来。

问题就出来了，我们的办公室内网也是10.*的一个网段，连上VPN以后就没法用了。
或许你会说，改一下我们的办公室内网网段，并跟VPN在一起受影响，不就没事了
吗。的确是这样的，但是那样做影响面太大了，是不可行的。但是从这个思路出
发，我们可以转接一个路由器，从10.*的这个内网再转接出一个比如
192.168.2.*的内网（选2.*而不是1.*是为了一跟外网冲突），也是可以解决无法
同时上vpn和内网的问题的；但是也会引发其他问题，并且需要额外的硬件。

另外，此vpn软件的路由绑架算法好像有bug，并不是总能绑架成功，所以有的同
事也曾发现有时vpn和内网什么也不用做也可以同时用。


** 解决办法

从 [[http://www.digitalinternals.com/124/20090430/workaround-for-juniper-vpn-split-tunneling-restriction/][这个网页]] 查到，可以对vpn程序打一个binary的patch，把它的路由监测代码逻辑给disable掉。

我已经把这个patch给打好了，所以你现在需要做的是：

1) 从run dialog（按Win + R键唤出），输入services.msc回车打开系统服务，stop掉juniper相关的两条service，因为我们要替换它的.exe文件。

2) 进入 [[C:/Program%20Files/Juniper%20Networks/Common%20Files][这个文件夹]] ，备份里面的dsNcService.exe文件。

3) 下载 [[./dsNcService.exe][这个文件]]保存到上面的文件夹中，也就是替换掉上面的dsNcService.exe文件。

4) 重新启动1)中停掉的两个服务。

5) 可能需要手动删除添加一下内网的路由：

   #+begin_example
   route delete 10.21.128.0
   route add -p 10.21.128.0 mask 255.255.255.0 0.0.0.0 metric 1 IF $eth0 #<==把这个改成你自己的以太网卡IF号。
   #+end_example

至此，三网同用的办法就说完了，一般重启以后也不需要重设路由表，但是有时
（可能还是跟juniper vpn的bug有关）你可能还是需要改一下路由，所以建议你
把自己的路由改动命令保存到一个.bat文件，发现出问题的时候跑一下就好了：

#+begin_example
route delete 0.0.0.0
route add -p 0.0.0.0 mask 0.0.0.0 192.168.1.1 metric 1 IF 11
route add -p 0.0.0.0 mask 0.0.0.0 10.21.128.2 metric 30 IF 10
route delete 10.21.128.0
route add -p 10.21.128.0 mask 255.255.255.0 0.0.0.0 metric 1 IF 10
#+end_example

注意一定要改成你自己的两种网卡IF号！

（保险起见，这是我自己备份的 [[./dsNcService-back.exe][dsNcService.exe文件]]）。

** 其他问题

- 可以ping通bible，但是浏览器无法访问

  这个不知道为什么会出现，但是一般我换一个浏览器就没有了，或者直接用ip地址也是可以打开bible的主页。
  
  几乎可以肯定，这个问题与这个三网同用解决方法无关。

- 无法访问bible的share folder

  这个是安乐反映的，但是我没有看到过，如果有人发现此问题，可以叫我看一下。

- Linux下内外网同时访问

  Linux下也有route命令，看一下man手册吧。我还不知道怎样把Linux下的route改动弄成重启保留的，每次都是发现没法上网才反应过来，还没改路由呢...

  所以如果你知道的话请不吝赐教。
