#!/usr/bin/env bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # s:summary \
    # t:type '?"one of Story,任务,Improvement,Bug,Epic,New Feature,Technical task,WBS,子任务,文档,测试,过程问题,问题跟踪,"' \
    # d:description \
    # cdo-commit \
    # b:move-to-board
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o d:cb:s:t:h \
                      --long description:,do-commit,move-to-board:,summary:,type:,help,no-do-commit \
                      -n $(basename -- $0) -- "$@")
declare description=
declare do_commit=false
declare move_to_board=
declare summary=
declare type=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -d|--description)
            description=$2
            shift 2

            ;;
        -c|--do-commit|--no-do-commit)
            if test "$1" = --no-do-commit; then
                do_commit=false
            else
                do_commit=true
            fi
            shift

            ;;
        -b|--move-to-board)
            move_to_board=$2
            shift 2

            ;;
        -s|--summary)
            summary=$2
            shift 2

            ;;
        -t|--type)
            type=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %6s '-d, '
            printf %-24s '--description=DESCRIPTION'
            echo
            printf %6s '-c, '
            printf %-24s '--[no-]do-commit'
            echo
            printf %6s '-b, '
            printf %-24s '--move-to-board=MOVE_TO_BOARD'
            echo
            printf %6s '-s, '
            printf %-24s '--summary=SUMMARY'
            echo
            printf %6s '-t, '
            printf %-24s '--type=TYPE'
            echo "one of Story,任务,Improvement,Bug,Epic,New Feature,Technical task,WBS,子任务,文档,测试,过程问题,问题跟踪,"
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${description}"; then
    description=${summary}
fi

jkd c -p EP -t "${type}" --field-value Summary="${summary}" --field-value Description="${description}" 2>&1 | tee ~/tmp/c-ep.log
issue=$(cat ~/tmp/c-ep.log | perl -ne 'print "$1\n" if m,(EP-\d+),' | sort -u)
firefox --new-tab ${scm_jira_url}browse/$issue

putclip ${scm_jira_url}browse/$issue

if test "${do_commit}" = true; then
    jkd commit -t "${type,,}" -i ${issue}
fi

if test "${move_to_board}"; then
    jkd mits -b "${move_to_board}" -i ${issue}
fi
