#!/bin/bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # n:screen-name d:screen-description
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o d:n:h \
                      --long screen-description:,screen-name:,help \
                      -n $(basename -- $0) -- "$@")
declare screen_description=
declare screen_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -d|--screen-description)
            screen_description=$2
            shift 2

            ;;
        -n|--screen-name)
            screen_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-d, '
            printf %-24s '--screen-description=SCREEN_DESCRIPTION'
            echo
            printf %06s '-n, '
            printf %-24s '--screen-name=SCREEN_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

putclip "${screen_description}"
putclip "${screen_name}"

jkd go screens add &>/dev/null&

hint "please create the screen $name in browser, description: '$description'"
