#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use JSON;

my $json = JSON->new->utf8->canonical->pretty;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# s:screenscheme-name d:screenscheme-description @:screen-name @:screen-id
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $screen_id = "";
my $screen_name = "";
my $screenscheme_description = "";
my $screenscheme_name = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '';
    printf "%-24s", '--screen-id=SCREEN-ID';
    if (length('--screen-id=SCREEN-ID') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '';
    printf "%-24s", '--screen-name=SCREEN-NAME';
    if (length('--screen-name=SCREEN-NAME') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-d, ';
    printf "%-24s", '--screenscheme-description=SCREENSCHEME-DESCRIPTION';
    if (length('--screenscheme-description=SCREENSCHEME-DESCRIPTION') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-s, ';
    printf "%-24s", '--screenscheme-name=SCREENSCHEME-NAME';
    if (length('--screenscheme-name=SCREENSCHEME-NAME') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'screen-id=s' => \$screen_id,
    'screen-name=s' => \$screen_name,
    'screenscheme-description|d=s' => \$screenscheme_description,
    'screenscheme-name|s=s' => \$screenscheme_name,
    'help|h!' => \&$handler_help,
);


## end generated code

if (not $screen_id) {
    $screen_id = decode_utf8(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd", "name2id", "-i", "$screen_name", "-a", "screens"));
}

my @params_values = (
    'inline=true',
    'decorator=dialog',
    'fieldScreenSchemeName=' . $screenscheme_name,
    'fieldScreenSchemeDescription=' . $screenscheme_description,
    'fieldScreenId=' . $screen_id,
);

runx(
    "jkd", "webcurl", "$ENV{scm_jira_url}secure/admin/AddFieldScreenScheme.jspa", "-X", "POST",
    map { ('--data-urlencode', $_) } @params_values
);
