#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# n:screen-name d:screen-description
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $screen_description = "";
my $screen_name = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-d, ';
    printf "%-24s", '--screen-description=SCREEN-DESCRIPTION';
    if (length('--screen-description=SCREEN-DESCRIPTION') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-n, ';
    printf "%-24s", '--screen-name=SCREEN-NAME';
    if (length('--screen-name=SCREEN-NAME') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'screen-description|d=s' => \$screen_description,
    'screen-name|n=s' => \$screen_name,
    'help|h!' => \&$handler_help,
);


## end generated code

my @params_values = (
    "inline=true",
    "decorator=dialog",
    "fieldScreenName=${screen_name}",
    "fieldScreenDescription=${screen_description}",
);

runx(
    "jkd", "webcurl", "$ENV{scm_jira_url}secure/admin/AddFieldScreen.jspa", "-X", "POST",
    map { ('--data-urlencode', $_) } @params_values
);

capturex(
    "cached-run", "-e", "scm_jira_url", "-r", "jkd", "rest", "screens"
);
