#!/bin/bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}
指定一个 Screen 的名字，列出此 screen 下所有 fields 的名字
# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # s:screen-name
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o s:h \
                      --long screen-name:,help \
                      -n $(basename -- $0) -- "$@")
declare screen_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -s|--screen-name)
            screen_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-s, '
            printf %-24s '--screen-name=SCREEN_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${screen_name}"; then
    die "You must specify screen name"
fi

screen_id=$(
    jkd rest screens | jq '.[]|if .name == "'"${screen_name}"'" then .id else null end | values' -r
         )

tab_ids=$(
    jkd rest screens/${screen_id}/tabs | jq '.[]|.id' -r
       )

for tid in ${tab_ids}; do
    jkd rest screens/${screen_id}/tabs/${tid}/fields | jq .
done
