#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use JSON;

my $json = JSON->new->utf8->canonical->pretty;

use Mojo::DOM;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# i:screenscheme-id
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $screenscheme_id = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-i, ';
    printf "%-24s", '--screenscheme-id=SCREENSCHEME-ID';
    if (length('--screenscheme-id=SCREENSCHEME-ID') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'screenscheme-id|i=s' => \$screenscheme_id,
    'help|h!' => \&$handler_help,
);


## end generated code
use File::Slurp;

my $html_text;

if (not $screenscheme_id) {
    die "Must specify the screenscheme id";
}
$html_text = decode_utf8 capturex("jkd", "webget", "$ENV{scm_jira_url}secure/admin/ConfigureFieldScreenScheme.jspa?id=${screenscheme_id}");

my $dom = Mojo::DOM->new->parse($html_text);

if ($ENV{jkd_verbose}) {
    say STDERR encode_utf8 $html_text;
}
my %screenscheme;

$dom->find('*[class="screen-issue-operation"]')->each
    (
        sub {
            my $scene_name = $_->text;

            my $screen_elem = $_->parent->parent->at('a[href^="ConfigureFieldScreen.jspa"]');
            (my $screen_id = $screen_elem->attr('href')) =~ s,.*id=(\d+),$1,;
            (my $screen_name) = $screen_elem->text;

            $screenscheme{$scene_name} = {
                name => $screen_name,
                id => $screen_id,
            };
        }
    );


$html_text = decode_utf8 capturex("jkd", "webget", "$ENV{scm_jira_url}secure/admin/EditFieldScreenScheme!default.jspa?id=${screenscheme_id}");
$dom = Mojo::DOM->new->parse($html_text);

my $name = $dom->at('input[name="fieldScreenSchemeName"]')->attr('value');
my $description = $dom->at('input[name="fieldScreenSchemeDescription"]')->attr('value');

$screenscheme{name} = $name;
$screenscheme{description} = $description;
print decode_utf8($json->encode(\%screenscheme));
