#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;
use JSON;

my $json = JSON->new->utf8->canonical->pretty;


use Mojo::DOM;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# f:html-file i:fieldconfigscheme-id
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $html_file = "";
my $fieldconfigscheme_id = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-f, ';
    printf "%-24s", '--html-file=HTML-FILE';
    if (length('--html-file=HTML-FILE') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-i, ';
    printf "%-24s", '--fieldconfigscheme-id=FIELDCONFIGSCHEME-ID';
    if (length('--fieldconfigscheme-id=FIELDCONFIGSCHEME-ID') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'html-file|f=s' => \$html_file,
    'fieldconfigscheme-id|i=s' => \$fieldconfigscheme_id,
    'help|h!' => \&$handler_help,
);


## end generated code
use File::Slurp;

my $html_text;

if ($html_file) {
    $html_text = decode_utf8 read_file($html_file);
} else {
    if (not $fieldconfigscheme_id) {
        die "Must specify the fieldconfigscheme id";
    }
    $html_text = decode_utf8 capturex("jkd", "webget", "$ENV{scm_jira_url}secure/admin/ConfigureFieldLayoutScheme!default.jspa?id=${fieldconfigscheme_id}");
}


my $dom = Mojo::DOM->new->parse($html_text);

if ($ENV{jkd_verbose}) {
    say STDERR $html_text;
}
my %fieldconfigscheme;

$dom->find('strong[data-scheme-field="issue-type"]')->each
    (
        sub {
            my $scene_name = $_->text;

            my $fieldconfig_elem = $_->parent->parent->at('a[data-scheme-field="field-configuration"]');
            (my $fieldconfig_id = $fieldconfig_elem->attr('href')) =~ s,.*id=(\d+),$1,;
            (my $fieldconfig_name) = $fieldconfig_elem->text;

            $fieldconfigscheme{$scene_name} = {
                name => $fieldconfig_name,
                id => $fieldconfig_id,
            };
        }
    );

print decode_utf8($json->encode(\%fieldconfigscheme));
