#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use JSON;

my $json = JSON->new->utf8->canonical->pretty;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}
* action = update
- update the field
* action = import
- import (create) the field
* action = sync-to
将指定的字段的配置（json）同步到其他环境
* action = screens
print the screens that this field is attached

* 参数说明

- issuetype :: 这个参数主要用于获取对应的 fieldconfig
# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# a:action f:field-name j:json-data i:issuetype @:j2
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $action = "";
my $field_name = "";
my $issuetype = "";
my $j2 = "";
my $json_data = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-a, ';
    printf "%-24s", '--action=ACTION';
    if (length('--action=ACTION') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-f, ';
    printf "%-24s", '--field-name=FIELD-NAME';
    if (length('--field-name=FIELD-NAME') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-i, ';
    printf "%-24s", '--issuetype=ISSUETYPE';
    if (length('--issuetype=ISSUETYPE') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '';
    printf "%-24s", '--j2=J2';
    if (length('--j2=J2') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-j, ';
    printf "%-24s", '--json-data=JSON-DATA';
    if (length('--json-data=JSON-DATA') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'action|a=s' => \$action,
    'field-name|f=s' => \$field_name,
    'issuetype|i=s' => \$issuetype,
    'j2=s' => \$j2,
    'json-data|j=s' => \$json_data,
    'help|h!' => \&$handler_help,
);


## end generated code


my $fields_json = $json->decode(scalar capture("cached-run -e scm_jira_url jkd rest field"));

my $field_id;
map {
    if ($_->{name} eq "$field_name") {
        ($field_id = $_->{id}) =~ s,.*_,,;
    }
} @$fields_json;

if ($action eq "update") {
    $json_data = $json->decode(encode_utf8 $json_data);
    if (not $field_name) {
        $field_name = $json_data->{name};
        die "Can't find field name" unless $field_name;
    }

    my $searcher = $json_data->{search_template} || "-1";
    my @params_values = (
        'name=' . $json_data->{name},
        "description=" . $json_data->{description},
        "searcher=${searcher}",
        "id=${field_id}",
        "fieldType=",
        "redirectURI=",
        "Update=Update",
    );

    runx(
        "debug-run", "jkd", "webcurl", "$ENV{scm_jira_url}secure/admin/EditCustomField.jspa", "-X", "POST",
        map { ('--data-urlencode', $_) } @params_values
    );
} elsif ($action eq "sync-to") {
    my %jira_envs = (
        $ENV{scm_jira_test2_url} => 1,
        $ENV{scm_jira_test1_url} => 1,
        $ENV{scm_jira_prod_url} => 1,
    );

    my $field_json =
        $json->decode(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd", "dump-field", "-f", $field_name));

    for (keys %jira_envs) {
        if ($_ ne $ENV{scm_jira_url}) {
            if ($issuetype) {

                runx("debug-run", "jkd", "-j", "$_", "issuetype",
                     "-n", $issuetype,
                     "-a", "update-field",
                     "--field-name", $field_name,
                     "--field-json", decode_utf8($json->encode($field_json)));

            } else {
                runx("debug-run", "jkd", "-j", "$_", "field", "-a", "update", "-j", decode_utf8($json->encode($field_json)));
            }

        }
    }
} elsif ($action eq "screens") {
    my $screens_html =
        decode_utf8(scalar capturex("debug-run", "cached-run", "-e", "scm_jira_url",
                                    "jkd", "webcurl", "$ENV{scm_jira_url}secure/admin/AssociatedScreensForCustomField.jspa?customFieldId=customfield_${field_id}"));


    use Mojo::DOM;
    my $dom = Mojo::DOM->new->parse($screens_html);

    my @screens;
    # say STDERR "$screens_html";
    $dom->find('a[href^="ConfigureFieldScreen.jspa"]')->each(
        sub {
            say STDERR "$_";
            push @screens, $_->text;
        }
    );

    print decode_utf8($json->encode(\@screens));

} elsif ($action eq "change-type") {
    my $type = $ARGV[0];
    if (not $type) {
        die "Must specify the type or j2 to get the type" if not $j2;

        my $field_dump_j2 =
            $json->decode(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd", "-j", "$j2", "dump-field", "-f", "$field_name"));
        $type = $field_dump_j2->{schema}{custom};
        die "Can't get type from $j2" unless $type;
    }

    my $screens = $json->decode(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd", "field", "-a", "screens", "-f", "$field_name"));
    my @screens = @$screens;
    my %screen_jsons;

    for (@screens) {
        $screen_jsons{$_} =
            $json->decode(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd",
                                          "dump-screen", "-s", $_));
    }

    my $field_json =
        $json->decode(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd", "dump-field", "-f", "${field_name}"));

    $field_json->{name} = "$field_name.type.changed.to.${type}";
    runx(
        "jkd", "field", "-a", "update", "-f", "$field_name", "-j", decode_utf8($json->encode($field_json))
    );

    my $field_types_json =
        $json->decode(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd",
                                      "webcurl", "$ENV{scm_jira_url}rest/globalconfig/1/customfieldtypes"));

    my $field_search_key;
    map {
        $field_search_key = $_->{searchers}[0] if $type eq $_->{key};
    } @{$field_types_json->{types}};

    $field_json->{name} = $field_name;
    $field_json->{schema}{custom} = $type;
    $field_json->{search_template} = $field_search_key;

    my $new_field_json =
        $json->decode(scalar capturex("cached-run", "-e", "scm_jira_url", "jkd", "import-field", "-j", decode_utf8($json->encode($field_json))));

    for (@screens) {
        runx(
            "jkd", "screen", "-a", "add-fields", "-j", decode_utf8($json->encode($screen_jsons{$_})), "--after-field", $field_json->{id}, $new_field_json->{id}
        );

        runx(
            "jkd", "screen", "-a", "delete-fields", "-j", decode_utf8($json->encode($screen_jsons{$_})), $field_json->{id}
        );
    }

    say STDERR "new search key is $field_search_key";
}
