#!/bin/bash
set -e

declare -A admin_pages=(
    [screens]=secure/admin/ViewFieldScreens.jspa
    [dynamic-forms]=secure/admin/DFConfiguration.jspa
    [webhooks]=plugins/servlet/webhooks
)

which_page=$(
    select-args -p "which admin page do you want?" "${!admin_pages[@]}"
          )

firefox ${scm_jira_url}${admin_pages[$which_page]}
