#!/bin/bash
set -e

declare -A admin_pages=(
    [screens]=secure/admin/ViewFieldScreens.jspa
    [dynamic-forms]=secure/admin/DFConfiguration.jspa
    [webhooks]=plugins/servlet/webhooks
    [project]=plugins/servlet/project-config/'$(get-project-key)'/summary
    ["custom-fields (edit description 1)"]=secure/admin/ViewCustomFields.jspa
    [create-issue]=projects/'$(get-project-key)'
    ["field-config(optional/required/edit description 2)"]=secure/admin/ViewFieldLayouts.jspa
    ["admin-issues"]=secure/admin/ViewIssueTypes.jspa
    ["admin-workflows"]=secure/admin/workflows/ListWorkflows.jspa
    ["admin-add-issuetypes"]="hint: project -> issuetypes -> actions (top-right corner) -> edit issuetypes -> add issuetypes"
    ["admin-assign-workflow-to-issuetype"]="hint: project -> workflows -> ..."
    ["admin-field-scheme-config(optional/required switch 2)"]="hint: associate a field configuration scheme with your issue type!"
)

if ! is-tty-io; then
    original_url=$(get-firefox-tab-url)
    scm_jira_url=$(echo ${original_url} | perl -pe 's,(.*?//.*?/).*,$1,; s,/*$,/,')

    FIREFOX_PROFILE_ARG=$(sawfish-window get-top-window-env '^FIREFOX_PROFILE_ARG=' || true)
    export THE_FIREFOX=$(sawfish-window get-top-window-env '^THE_FIREFOX=' || true)
fi


which_page=$(
    select-args -i "$1" -p "which admin page do you want?" "${!admin_pages[@]}"
          )
shift || true

path=${admin_pages[$which_page]}

get-project-key() {
    jkd get rest/api/2/project|jq '.[]|.key + " : " + .name' -r |
        select-output-line -p "Which project?" cat | pn 1
}

if [[ $path =~ \$\( ]]; then
    eval path=$path
elif [[ $path =~ hint: ]]; then
    EMACS=t yes-or-no-p -y "$path"
    exit
fi

firefox ${FIREFOX_PROFILE_ARG} ${scm_jira_url}${path}
