#!/bin/bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # m:match
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o m:h \
                      --long match:,help \
                      -n $(basename -- $0) -- "$@")
declare match=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -m|--match)
            match=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-m, '
            printf %-24s '--match=MATCH'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

jkd rest groups/picker?query=${match}\&maxResults=30000|jq '.groups|.[]|.name' -r
