#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use feature 'signatures';
no warnings "experimental::signatures";

use URI;
use URI::QueryParam;

my $u = URI->new("$ENV{scm_jira_url}issues/");
$u->query_param(jql => join(" ", @ARGV));
say STDERR "$u";
runx("firefox", $u);
