#!/usr/bin/env bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # u:jira-url
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o u:h \
                      --long jira-url:,help \
                      -n $(basename -- $0) -- "$@")
declare jira_url=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -u|--jira-url)
            jira_url=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %6s '-u, '
            printf %-24s '--jira-url=JIRA_URL'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if [[ $jira_url =~ selectedIssue= ]]; then
    issue=$(echo "${jira_url}" | perl -ne 'print $1 if m,selectedIssue=(\w+-\d+),')
elif [[ $jira_url =~ /browse/|/issues/ ]]; then
    issue=$(echo "${jira_url}" | perl -ne 'print $1 if m,/(?:browse|issues)/(\w+-\d+),')
else
    die "Can't extract the issue from ${jira_url}"
fi

echo $issue
