#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);


(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# w:workflow-name
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $workflow_name = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-w, ';
    printf "%-24s", '--workflow-name=WORKFLOW-NAME';
    if (length('--workflow-name=WORKFLOW-NAME') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'workflow-name|w=s' => \$workflow_name,
    'help|h!' => \&$handler_help,
);


## end generated code

runx('debug-args', "jkd", "webcurl", "$ENV{scm_jira_url}secure/admin/workflows/DeleteWorkflow.jspa", "-X", "POST", "-L",

     "--data-urlencode", "workflowName=${workflow_name}",
     "--data-urlencode", "workflowMode=live",
     "--data-urlencode", "project=",
     "--data-urlencode", "issueType=",
     "--data-urlencode", "confirmedDelete=true",
     "--data-urlencode", "Delete=Delete");
