#!/bin/bash


## start code-generator "^\\s *#\\s *"
# generate-getopt \
    # 1make-sure-only-1-device '?确保只有一个设备（如果设置了 ANDROID_SERIAL 环境变量，确保这个设备在线）' \
    # sset-device '?需要时，通过 reset-env 脚本设置 ANDROID_SERIAL 变量' \
    # p:prompt-set-device='"你想要使用哪个 adb 设备？"' '?设置 ANDROID_SERIAL 环境变量时的提示信息' \
    # t:device-type='both' "?想要查看哪种类型的设备？可以指定 adb、fastboot 或 both。" \
    # xdebug '?use shell set -x for debug'
## end code-generator
## start generated code
TEMP=$( getopt -o xt:1p:sh \
               --long debug,device-type:,make-sure-only-1-device,prompt-set-device:,set-device,help,no-debug,no-make-sure-only-1-device,no-set-device \
               -n $(basename -- $0) -- "$@")
declare debug=false
declare device_type=both
declare make_sure_only_1_device=false
declare prompt_set_device="你想要使用哪个 adb 设备？"
declare set_device=false
eval set -- "$TEMP"
while true; do
    case "$1" in

        -x|--debug|--no-debug)
            if test "$1" = --no-debug; then
                debug=false
            else
                debug=true
            fi
            shift
            ;;
        -t|--device-type)
            device_type=$2
            shift 2
            ;;
        -1|--make-sure-only-1-device|--no-make-sure-only-1-device)
            if test "$1" = --no-make-sure-only-1-device; then
                make_sure_only_1_device=false
            else
                make_sure_only_1_device=true
            fi
            shift
            ;;
        -p|--prompt-set-device)
            prompt_set_device=$2
            shift 2
            ;;
        -s|--set-device|--no-set-device)
            if test "$1" = --no-set-device; then
                set_device=false
            else
                set_device=true
            fi
            shift
            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-x, '
            printf %-24s '--[no-]debug'
            echo 'use shell set -x for debug'
            printf %06s '-t, '
            printf %-24s '--device-type=DEVICE_TYPE'
            echo
            printf "%30s" ""
            echo '想要查看哪种类型的设备？可以指定 adb、fastboot 或 both。'
            printf %06s '-1, '
            printf %-24s '--[no-]make-sure-only-1-device'
            echo
            printf "%30s" ""
            echo '确保只有一个设备（如果设置了 ANDROID_SERIAL 环境变量，确保这个设备在线）'
            printf %06s '-p, '
            printf %-24s '--prompt-set-device=PROMPT_SET_DEVICE'
            echo
            printf "%30s" ""
            echo '设置 ANDROID_SERIAL 环境变量时的提示信息'
            printf %06s '-s, '
            printf %-24s '--[no-]set-device'
            echo '需要时，通过 reset-env 脚本设置 ANDROID_SERIAL 变量'
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test "$debug" = true; then
    set -x
fi

if test "$set_device" = true; then
    function set-device() {
        local ret=$?
        if test "$ret" != 0; then
            exit $ret
        fi

        reset-env ANDROID_SERIAL $(select-args -p "$prompt_set_device" "$adb_devices" | pn 1)
    }
    . atexit set-device
fi

if adb_devices=$(
        (
            if test "$device_type" = "adb" -o "$device_type" = both; then
                the-true-adb devices
            fi

            if test "$device_type" = "fastboot" -o "$device_type" = both; then
                fastboot devices
            fi
           ) | grep -v 'List of devices attached' | grep .); then
    if test "$make_sure_only_1_device" = false; then
        if test "$set_device" = false; then
            echo "$adb_devices"
        fi
        exit 0
    elif test "$ANDROID_SERIAL"; then
        for x in $(echo "$adb_devices" | pn 1); do
            if test "$x" = "$ANDROID_SERIAL"; then
                echo "$adb_devices" | grep "\Q$x\E" -P
                . atexit
                exit 0
            fi
        done
        # else the specified device not found
        die "你指定的设备 $ANDROID_SERIAL 没有找到"
        exit 1
    else # ANDROID_SERIAL not specified
        if test "$(echo "$adb_devices"|wc -l)" = 1; then
            exit 0
        elif test "$set_device" = true; then
            exit 0
        fi
    fi
else
    exit 1
fi
