#!/bin/bash
set -e

saved_args=("$@")

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}
根据 ACTION 参数，显示指定文件的 gitweb 下载地址或浏览器查看地址。

- download-url :: print the gitweb download url
- browse-url :: print the gitweb browse url
- of :: Open 「File」 in firefox
# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # a:action '?"one of download-url, browse-url, of"' \
    # p:project=@empty@ \
    # b:branch=@empty@ \
    # f:file
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o a:b:f:p:h \
                      --long action:,branch:,file:,project:,help \
                      -n $(basename -- $0) -- "$@")
declare action=
declare branch=@empty@
declare file=
declare project=@empty@
eval set -- "$TEMP"
while true; do
    case "$1" in

        -a|--action)
            action=$2
            shift 2

            ;;
        -b|--branch)
            branch=$2
            shift 2

            ;;
        -f|--file)
            file=$2
            shift 2

            ;;
        -p|--project)
            project=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-a, '
            printf %-24s '--action=ACTION'
            echo "one of download-url, browse-url, of"
            printf %06s '-b, '
            printf %-24s '--branch=BRANCH'
            echo
            printf %06s '-f, '
            printf %-24s '--file=FILE'
            echo
            printf %06s '-p, '
            printf %-24s '--project=PROJECT'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test "${project}" != @empty@; then
    p=${project}
else

    p=$( # project
        repo-abs-path | perl -pe 's,^/*,,'
     )
fi

if test -z "${action}"; then
    action=of
fi

if test -z "${file}" -a -e "$1"; then
    f=$( # file
        gitp "$1"
     )
fi

if test "${branch}" != @empty@; then
    b=${branch}
else
    b=$( # branch
        repo-branch
     )
fi

case "$action" in
    d*)
        echo "${scm_gerrit_url}gitweb?p=$p.git;a=blob_plain;f=$f;hb=refs/heads/$b"
        ;;
    b*)
        if test -z "$b"; then
            echo "${scm_gerrit_url}gitweb?p=$p.git"
        elif test -z "$f"; then
            echo "${scm_gerrit_url}gitweb?p=$p.git;a=log;h=refs/heads/$b"
        else
            echo "${scm_gerrit_url}gitweb?p=$p.git;a=blob;f=$f;hb=refs/heads/$b"
        fi
        ;;
    of)
        of "$(gr gitweb "${saved_args[@]}" -a browse-url)"
        ;;
esac
