#+title: OKR 减肥记
# bhj-tags: reading
今天读完了一本介绍 OKR 的书，“Measure What Matters”。

读这本书主要原因是公司里在推行 OKR 文化，推荐每一位员工都要读这本书，所以我也从 Kindle 上买了一本。

有一位朋友跟我说，他感觉 OKR 其实就是 GTD（Get Things Done），读完以后，我也有这种感觉，不过还不能简单地说 OKR 就是 GTD，应该说是多人组织协作加强版的 GTD。

其实整本书里讲的东西很简单，我可以试着用一句话来总结一下：“OKR 是一种管理的科学，通过 OKR，我们可以破除一些拍脑袋、想当然的迷之管理手段，以达到提升团队的生产力的目的”。

* 迷之管理手段一

一年做一次 Performance Review。

这个可以说是一种迷信了，“我们一直都是这么做的”，然后就很少有人站出来质疑这种方法的有效性了。

但是据书中介绍，大部分接受问卷调查的 HR、管理人员都认为这种方法非常浪费他们的时间，并且基本没有效果。据说 Adobe 公司以前是采用这种方法，每年每个经理都要跟他/她的每个下属做一次 review，整个公司加起来，相当要花掉 40 人年。

* 迷之管理手段二

过分强调 objectives。

这种方法会导致一些意想不到的后果，即人们为达目的不择手段。

这种负面后果有很多种名字，比如“眼镜蛇效应”，说是英国在印度殖民期间，因为官员害怕毒蛇成灾，出了条规定，收购死蛇尸体。一开始大家都去灭蛇了，确实让毒蛇数目大大减少。但很快，一些有“创业”精神的人，开始自己蓄养眼镜蛇谋利，被官员发现后，收购死蛇的规定被取消了。这下养蛇的人无利可图，把养的蛇全都放了出去，结果蛇灾变得比之前更严重了。

* 迷之管理手段三

目标不明确。

目标不明确、优先级不明确，会引发很多恶果［吐］，比如资源浪费，几组人做同一件事情；比如捡了芝麻丢了西瓜；比如活活累死。

* 最大的收获

哈哈哈，不聊那些跟职场相关的话题，OKR 即使在生活中，也可以有很多应用场景。

我个人最大的收获，其实跟 OKR 本身没有太大的关系，而是通过书中介绍，了解到一个叫 MyFitnessPal 的公司，出了一个同名 App 产品（中文名叫减肥宝）。

这个 App 可以把你吃的东西有多少热量帮你记录下来，并结合你的身体状况、减重目标、运动情况，帮你估算出每天应该摄入多少热量。

简直是中年油腻男的福音！我用得完全停不下来！

再加上今年过年时刚刚受到的刺激，最近开始每周游 3 次泳的锻炼计划，体重下降得很快。

过年时跟我哥两家人一起，他比我大 4 岁，但体力比我强很多，每天游泳、时不时还到水库里潜水，现在安静状态下憋气能憋 4 分 45 秒［惊恐］。有一天早上一起游泳，我拿出舍命赔君子的架势陪他游了几圈之后，就蔫巴熄火了。他也停下来，皮笑肉不笑地对我说，“我感觉你有所保留嘛”［捂脸］。之后他向我传授了游泳锻炼的决窍：

1. 先慢游 300~500 米热身
2. 再快游 1000 米
   - 大概用全力冲刺 70~80% 的速度游
   - 每次游到岸边，呼吸 5 口气，就接着继续游
   - 保持心跳速度，不能下降太多，否则没有锻炼效果
3. 每周游 3 次

这短短几句话，像咒语一样，非常有效，真不愧是我的偶像呢，轻而易举地点燃了我心中的火。

“我感觉你有所保留嘛”，嘿嘿嘿。💪
