#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use feature 'signatures';
no warnings "experimental::signatures";

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# g:gerrit-group
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $gerrit_group = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-g, ';
    printf "%-24s", '--gerrit-group=GERRIT-GROUP';
    if (length('--gerrit-group=GERRIT-GROUP') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'gerrit-group|g=s' => \$gerrit_group,
    'help|h!' => \&$handler_help,
);


## end generated code

if ($gerrit_group) {
    push @ARGV, split(' ', decode_utf8(scalar capture("gr ls-members --recursive $gerrit_group|pn 2|grep -v username")));
    say STDERR "argv is @ARGV ";
}


@ARGV = ('dd-jianqun', @ARGV);

map {
    $_ = capturex("str", "quote", "-f", "lua", "$_")
} @ARGV;

my $wrench_command = sprintf("call_ext(%s)", join(",", @ARGV));

runx("debug-run", "Wrench.sh", $wrench_command);
