#!/bin/bash

set -x
if test -e ~/.no-hourly-build; then
    exit 0;
fi

hour=$(date +%_H|tr -d ' ')
export start_hour=$hour

if test $hour -lt 8 -o $hour -gt 20; then
    exit
fi

if test $hour = 20; then
    locate .android-hourly-build > ~/.ahb-dirs
fi

for rebuild_dirs in $(cat ~/.ahb-dirs); do
    rebuild_dirs=$(dirname $rebuild_dirs)
    (
        cd $rebuild_dirs >/dev/null 2>&1 || exit 0
        test -e .repo || exit 0
        if test $hour != 20 && ! android-need-rebuild; then
            exit 0
        fi
        exec 9>~/.android-full-build.lock
        ln -sf ~/.android-full-build.lock .
        flock -n 9 || exit 0
        if test $hour = 20; then
            rm .repo/out-*/ -rf
        fi
        flock -u 9
        rm .build-status
        android-hourly-build $(cat .android-hourly-build)
    )
done
