#!/bin/bash

set -x
if test -e ~/.no-hourly-build; then
    exit 0;
fi

hour=$(date +%_H|tr -d ' ')
export start_hour=$hour

if test $hour -lt 8 -o $hour -gt 20; then
    exit
fi

cd ~/src/ics-autobuild/ >/dev/null 2>&1 || exit 0

(
    if test $hour = 20 -o -e .do_rebuild || android-need-rebuild; then
        if test $hour = 20; then 
            rm ../$(basename $(pwd))-out/out-* -rf
        fi
        exec 9>.android-full-build.lock
        flock -n 9 || exit 0
        flock -u 9
        rm .build-status
        android-hourly-build pxa978ariel_def-eng 
    fi
)

cd ~/src/bpe-autobuild/ >/dev/null 2>&1 || exit 0
touch .do_not_gq_rebase

exec 9>.android-full-build.lock
flock -n 9 || exit 0
flock -u 9
if test $hour = 20 -o -e .do_rebuild || android-need-rebuild; then
    if test $hour = 20; then #maybe need do a full clean build next time.
        rm ../$(basename $(pwd))-out/out-* -rf
    fi
    rm .build-status
    android-hourly-build pxa978ariel_cmcc-eng
fi
