#!/bin/bash
cd ~/system-config/

if system-config-should-fetch; then
    if nice git-pull-mac --fetch-only; then
        system-config-fetch-done || true
    fi
fi

for x in ~/system-config/ ~/src/github/*/; do
    (
        if test -d "$x"/.git; then
            cd "$x"
            system-config-git-merged || true
        fi
    )
done
