#!/usr/bin/env bash
cd ~/system-config/

set -e

for x in ~/system-config/ ~/src/github/*/; do
    (
        if test -d "$x"/.git; then
            cd "$x"
            system-config-git-merged || true
        fi
    )
done
