#!/bin/bash

cd ~/system-config/

if git-need-push; then
    echo git need push
    bhj-notify "personal project" "Your git repository is not clean, please push it"
else
    echo git no need to push
    bhj-notify "personal project"
fi
true
