#!/usr/bin/env bash
set -x
cd ~/.local-config/japanese/
if git-any-changes; then
    git add . && git commit -m 'auto japanese commit'
    if ! git push; then
        git push $(repo-remote) HEAD:$(from-mac) -f
    fi
fi
