#+title: My Page on Github
# bhj-tags: blog

(For Chinese version of this page, click [[../../../2013/02/25/index-cn.org][这里]]).

* About Me

I am a software engineer. I write some open source code, mainly to
scratch my own back at first, but I also want it to be more useful to
other people.

I use dvp -- [[http://www.kaufmann.no/roland/dvorak/index.html][Programmer Dvorak]] as my keyboard layout, use the same
Input Method(s) under Windows/Linux/Emacs, all developed by
myself. Just to show you what a geek I am:-)

* Projects

- [[./beagrep.org][beagrep]]
  
  Beagrep is a fork of [[http://en.wikipedia.org/wiki/Beagle_(software)][beagle]], which is a desktop search engine; I
  hacked beagrep to make it more suitable for precise searching, such as code reading.

  It has both Linux and Windows version.

- [[../28/org-jira.org][org-jira]]

  Brings org mode and Jira together.

- SDIM

  SDIM, or Shadow Dance Input Method, is an input method I develop and
  use myself only. It is available under 3 platforms, Linux, Windows, and Emacs.

- Semi Offline Wikipedia

  It is a fork of [[http://users.softlab.ece.ntua.gr/~ttsiod/buildWikipediaOffline.html][this project]]. I fixed some bugs, updated the
  mediawiki base version, and added one major feature: allow fetching
  pictures when connected to the net (thus the word Semi in the name).

  It uses the beagrep project for fast searching.

- refactory-rename

  A script for one important refactory activity: renaming.

  Supports refactoring any kind of programming language source code.

- Misc
  
  A lot other stuff I wrote. I always try to write something when I
  face a repetitive problem, even when it's very simple.

  You can find them under [[https://github.com/baohaojun/system-config/][system-config.git]]. This project used to be
  named [[https://github.com/baohaojun/windows-config][windows-config]], but I have bitten the bullet and renamed it,
  because it's only by chance that I was using Win32 when I started
  the project for Cygwin configuration; most of the stuff can be used
  on all major POSIX platforms.


