#!/bin/bash
(
    mkdir .repo/tmp -p
    cat <<'EOF' > .repo/tmp/Android.mk
LOCAL_PATH:= $(call my-dir)
selinux_bhj: $(foreach se,seapp_contexts selinux_version sepolicy service_contexts,${PRODUCT_OUT}/root/${se}) sepolicy.recovery
ifeq (${ONE_SHOT_MAKEFILE},${LOCAL_PATH}/Android.mk)
$(info including the main sepolicy file)
ONE_SHOT_MAKEFILE := external/sepolicy/Android.mk
-include device/qcom/sepolicy/Android.mk
include external/sepolicy/Android.mk
# include cts/tests/tests/security/Android.mk
# CUSTOM_MODULES := $(sort $(call get-tagged-modules,$(ALL_MODULE_TAGS)))
$(info CUSTOM_MODULES are ${CUSTOM_MODULES})
endif
EOF
    . ~/src/github/smartcm/scm-helpers/.sepolicy_dir
    if test "$sepolicy_dir" = system/sepolicy; then
        perl -npe 's,external/sepolicy,system/sepolicy,g' -i .repo/tmp/Android.mk
    fi
    cd .repo/tmp
    $do_nice mm -j$jobs $verbose selinux_bhj
)
