#!/bin/bash

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
export BHJ_IN_VNC=true
fspanel&
grep -v lock -i ~/.Xmodmap | grep -v '^pointer' > ~/external/.Xmodmap.vnc
xmodmap ~/external/.Xmodmap.vnc
command renew-xauth ~/.renew-xauth.${DISPLAY##*:}

sawfish&
deluge&
lxpanel&

sleep 3
export MYSCR_SOCKET=onmyoji${DISPLAY##*:}
export MYSCR_SESSION=onmyoji${DISPLAY##*:}
xterm -e myscr&

sleep 3
xterm -e myscr bash -c '
# {%sh-mode%}
exec 9< ~/system-config/etc/subdir-symlinks/.vnc/xstartup
flock -n 9 || exit
(
    exec 9> /dev/null
    oplay -a xbs onmyoji simple-play
    oplay -a kitty onmyoji simple-play
)

screen-lock-on&
while true; do
    if ! screen-is-on; then
        adb-lcd -a off;
    fi
    date;
    sleep 60;
done
# {%/sh-mode%}
'
