#!/usr/bin/env bash

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc
rm -rf ~/tmp/no-play
bash -x adb-charge-switch &> ~/tmp/adb-charge-switch.log || true

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
export BHJ_IN_VNC=true
fspanel&
grep -v lock -i ~/.Xmodmap | grep -v '^pointer' > ~/external/.Xmodmap.vnc
xmodmap ~/external/.Xmodmap.vnc
declare -x -p > ~/.renew-xauth.${DISPLAY##*:}

(
    cd ~/src/reading/sawfish-1.11.90/ &&
        en_US nobrew ./src/sawfish &> ~/tmp/xinitrc.log ||
            sawfish
)&
deluge&
lxpanel&

for x in $(seq 1 15); do
    if ifconfig | grep 192.168.2.80 -q; then
        break
    else
        sleep 2
    fi
done

sudo ntpdate-debian || true
sudo hwclock --set --date "$(today) $(date +%H:%M:%S)" || true

sleep 3
export MYSCR_SOCKET=o${DISPLAY##*:}
export MYSCR_SESSION=o${DISPLAY##*:}
xterm -e myscr&

sleep 3

if test "${DISPLAY##*:}" != 1; then
    exit 0
fi

xterm -e myscr bash -c '
# {%sh-mode%}
for adb_serial in 9dbe919 162c850; do
    if ! adb -s $adb_serial true; then
        if sleep 120 && ! adb -s $adb_serial true; then
            mail-bhj -s "$adb_serial not found" --no-input || true
        fi
    else
        adb-quote "
echo 1 > /sys/class/power_supply/battery/input_suspend
sleep 1
echo 0 > /sys/class/power_supply/battery/input_suspend
"
    fi
done &

exec 9< ~/system-config/etc/subdir-symlinks/.vnc/xstartup

flock -n 9 || exit
(
    exec 9> /dev/null
    oplay -a xbs onmyoji simple-play
    . ~/src/github/private-config/knuth-mode/onmyoji-scripts/leader
    oplay -a ${THE_OTHER_LEADER} onmyoji simple-play
)

screen-lock-on&
while true; do
    if ! screen-is-on; then
        adb-lcd -a off;
    fi
    date;
    sleep 60;
done
# {%/sh-mode%}
'
