#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
export BHJ_IN_VNC=true
fspanel&
grep -v lock -i ~/.Xmodmap | grep -v '^pointer' > ~/external/.Xmodmap.vnc
xmodmap ~/external/.Xmodmap.vnc
command renew-xauth ~/.renew-xauth.${DISPLAY##*:}

sawfish&
deluge&
lxpanel&


sleep 3
export MYSCR_SOCKET=onmyoji
export MYSCR_SESSION=onmyoji
xterm -e myscr bash -c '
# {%sh-mode%}
oplay -a xbs onmyoji simple-play
oplay -a kk onmyoji simple-play
# {%/sh-mode%}
'
