#!/bin/bash

(
    flock -n 5 || { echo "lock failed for manage.py, exit"; exit; }
    while true; do
        cd ~/system-config/gcode/offline.wikipedia/mywiki
        test -e ../en.py -o -e ~/src/ahd || exit
        python ~/system-config/gcode/offline.wikipedia/mywiki/manage.py runserver 0.0.0.0:34567 --noreload >>~/.cache/system-config/logs/offline-wiki.log 2>&1
        sleep 2;
    done
) 5< ~/system-config/gcode/offline.wikipedia/mywiki/manage.py &
