#! /bin/ksh

if [ "$1" = "" ]
then
   echo USAGE: find_branch branch_type
   echo EXAMPLE : find_branch dilip_reset
else
   for x in `/usr/atria/bin/cleartool lsvob |grep -e '^\*'|awk '{print $2}' | /bin/sort`; 
   do 
      y=`/usr/atria/bin/cleartool desc brtype:$1@$x 2>/dev/null`;
      [ "$y" ] && /usr/atria/bin/cleartool find $x -all -elem 'brtype('$1')' -version 'version(.../'$1'/LATEST)' -print;
   done
fi   
# OUTPUT SHOULD LIKE AS FOLLOWS
# /vob/su_vris/lib/vr_error.c@@/main/r10.00.xx/dilip_reset/3
