#!/bin/bash

for x in $(find ~/windows-config/etc/at ~/external/etc/at -maxdepth 1 -type f -o -type l 2>/dev/null); do
    echo bash -c "'bash $x > ~/.logs/at-task.$(echo $x|perl -npe 's,/,.,g')'"|at $(basename $x)
done
