#!/bin/bash

{ cd ~/external/cygwin || cd "$(cat ~/external/.cygwin-dir)"; } && mirrorcyg.pl | mf-download.pl -n ${1:-3}
wget -N http://cygwin.com/setup.exe
cd mirrors.163.com/cygwin && wget http://mirrors.163.com/cygwin/setup.ini -N
