#!/bin/bash

set -ex
if test -d ~/external/cygwin; then
    cd ~/external/cygwin 
elif test -e ~/external/.cygwin-dir; then
    cd "$(cat ~/external/.cygwin-dir)"
else
    true
    exit
fi

mirrorcyg.pl | mf-download.pl -n ${1:-3}
wget -N http://cygwin.com/setup.exe
cd mirrors.163.com/cygwin && wget http://mirrors.163.com/cygwin/setup.ini -N
