#!/bin/bash
set -e
reverse=false
if test "$1" = -r; then
    reverse=true
fi
for x in ~/etc/rsync-into-git/*.src; do
    if test ! -e $x; then
        exit 0
    fi
    src=$(readlink -f $x)
    dst=$(readlink -f ${x/%.src/.dst})
    if test $(basename $dst) = $(basename $src); then
        if test "$reverse" = true; then
            src=$(dirname $src)
        else
            dst=$(dirname $dst)
        fi
    fi
    if test "$reverse" = true; then
        rsync -av $dst $src
    else
        rsync -av $src $dst
    fi
done
