#!/bin/bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}
quote a string as a string literal in specified language.

format can be:

- lua :: for lua
- emacs :: for emacs lisp
# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # f:format '?"one of lua, emacs"'
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o f:h \
                      --long format:,help \
                      -n $(basename -- $0) -- "$@")
declare format=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -f|--format)
            format=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-f, '
            printf %-24s '--format=FORMAT'
            echo "one of lua, emacs"
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test "$#" = 0; then
    bhj-notify "str quote" "quote STDIN"
    set -- "$(cat)"
fi

case "${format}" in
    emacs)
        emacs-quote-string "$1"
        ;;
    lua)
        str.quote.lua "$1"
        ;;
    shell)
        perl -e 'use String::ShellQuote; print shell_quote(@ARGV)' "$1"
        ;;
    *)
        die "Can't work with '${format}'"
        ;;
esac
