#+title: Installing Dictionary Data Separately
# bhj-tags: android app dict

* English version

The CrossDict since version 2.0 will be released separately with the
dictionary data.

You can install the GCIDE dictionary data from [[https://play.google.com/store/apps/details?id=com.baohaojun.crossdictgcide][Google Play]] directly,
or you can download it from [[http://vdisk.weibo.com/s/thlHF][Sina Vdisk]] and install it manually if you
can't access Google Play.

The first time you run the CrossDictGcide dictionary data APK, it will
take some time to copy the data files to sdcard. Please wait
patiently. After it is finished, you can safely uninstall it to save
storage space.

It has 2 advantages arranged this way:

1. Ease of upgrading the dictionary software.

2. Saving storage space by uninstalling the dictionary data APK.

* 中文版本

CrossDict从2.0版开始将与其字典数据分开发布。

你可以从[[https://play.google.com/store/apps/details?id=com.baohaojun.crossdictgcide][Google Play]]直接安装GCIDE字典数据，或者如果你不能使用Google
Play的话也可以从 [[http://vdisk.weibo.com/s/thlHF][新浪微盘]] 上下载安装。

第一次运行这个字典数据APK的时候，它需要花一段时间（几十秒钟的样子）把数
据文件拷贝到sd卡上。请耐心等待。拷贝结束后，你可以安全的将此字典数据
APK从设备中卸载而不影响使用。

这样的安排有两个好处：

1. 字典软件本身的升级变得更加方便。

2. 卸载字典数据APK可以节省存储空间。
