#!/bin/bash

set -e

if test "$(readlink -f "$BASH_SOURCE")" = "$(readlink -f "$(echo "$0" | grep / || which "$0" 2>/dev/null)" )"; then
    die "We can't be executed"
else
    if test "$1"; then
        lock=~/.cache/system-config/force-1/$1
    else
        lock=~/.cache/system-config/force-1/$(readlink -f $0)
    fi
    mkdir -p $(dirname "$lock")
    exec 9> "$lock"
    flock -n 9 || die "Can't lock $lock"
fi

