#!/bin/bash

github_projects=(
    elpa
    opencc
    twittering-mode
    org-jira
    weibo.emacs
    emacs.d
    DoubanMusic
    guilt
    emacs-clang-complete-async
    mo-git-blame
    bbyac
    yasnippet-snippets
    Firemacs
    ajoke
    beagrep
    crossdict
    gxr
    ibus-sdim
    adb-sync
    Wrench
)

smartcm_projects=(
    gapps-lp
    gapps-6.0
    gapps-t1
    smartcm
)

declare -A project_repo_url

project_repo_url[Wrench]=https://github.com/SmartisanTech/Wrench
