#!/bin/bash
unset FORCE_SYSTEM_CONFIG
unset SYSTEM_CONFIG_INITED
export FORCE_NO_SYSTEM_CONFIG=true
for x in $(set |grep '^\w.*\(\)' -P|pn 1); do
    unset -f "$x"
done

for x in $(alias|pn 2 | pn 1 =); do
    unalias "$x"
done

for x in PS1 PROMPT_COMMAND $(declare -x -p |grep "^declare -x" | pn 3|pn 1 =); do
    unset "$x"
done

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
if [ "`id -u`" -eq 0 ]; then
    true
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH

. /etc/profile
for f in ~/.bash_profile ~/.bash_login ~/.profile; do
    if test -e "$f"; then
        . "$f"
        break
    fi
done
