.\" beagle-status(1) manpage
.\"
.\" Copyright (C) 2005 Novell, Inc.
.\"
.TH BEAGLE-STATUS "1" "Feb 2005" "beagle" "Linux User's Manual"
.SH NAME
beagle-status \- repeatedly display Beagle status
.SH SYNOPSIS
.B beagle-status
.SH DESCRIPTION
.PP
.BR beagle-status
repeatedly displays status about
.BR beagled (1),
the Beagle daemon, in a top-like fashion.
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2005 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagled (1),
.BR beagle-query (1),
.BR beagle-shutdown (1),
