#!/usr/bin/env bash

# This line will be automatically uncommented when you "make install"
#installed=1

if [ -z $installed ]; then
    CMD="./beagle-info"
else
    CMD="beagle-info"
fi

while true; do
    clear
    echo -n "beagle-status at "
    date
    $CMD --status
    sleep 5
done

