#!/bin/bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P j:job-name n:build-number \
    # d:description='"@NULL@"'
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o n:d:j:h \
                      --long build-number:,description:,job-name:,help \
                      -n $(basename -- $0) -- "$@")
declare build_number=
declare description="@NULL@"
declare job_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -n|--build-number)
            build_number=$2
            shift 2

            ;;
        -d|--description)
            description=$2
            shift 2

            ;;
        -j|--job-name)
            job_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-n, '
            printf %-24s '--build-number=BUILD_NUMBER'
            echo
            printf %06s '-d, '
            printf %-24s '--description=DESCRIPTION'
            echo
            printf %06s '-j, '
            printf %-24s '--job-name=JOB_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${BUILD_URL}" && test -z "${job_name}" -o -z "${build_number}"; then
    die "Must specify job_name and build_number"
fi

if test -z "${BUILD_URL}" || test "${job_name}" -a "${build_number}"; then
    BUILD_URL=${scm_jenkins_url}job/${job_name}/${build_number}/
fi


if test "${description}" = @NULL@; then
    jc curl ${BUILD_URL}api/json | jq -r .description
else
    jc curl ${BUILD_URL}submitDescription -X POST --data-urlencode "description=$description"
fi
