#!/bin/bash

set -e

## start code-generator "^\\s *#\\s *"
# generate-getopt n:node-name f:from-node
## end code-generator
## start generated code
TEMP=$( getopt -o f:n:h \
               --long from-node:,node-name:,help \
               -n $(basename -- $0) -- "$@")
declare from_node=
declare node_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -f|--from-node)
            from_node=$2
            shift 2

            ;;
        -n|--node-name)
            node_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-f, '
            printf %-24s '--from-node=FROM_NODE'
            echo
            printf %06s '-n, '
            printf %-24s '--node-name=NODE_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

jc curl computer/createItem -X POST --data "name=${node_name}&mode=copy&from=${from_node}"

jc update computer/"${node_name}"/config.xml
