#!/usr/bin/env bash
set -e

jobname_escaped="$(uri-escape "$1")"

if jc get-job "$1" &>/dev/null; then
    jc update "job/$jobname_escaped/config.xml"
else
    jc update "createItem?name=$jobname_escaped"
fi
jc ojob "$1" &>/dev/null || true
