#!/usr/bin/env bash

## start code-generator "^\\s *#\\s *"
# generate-getopt -P j:job-name @prod2test
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o j:h \
                      --long job-name:,prod2test,help,no-prod2test \
                      -n $(basename -- $0) -- "$@")
declare job_name=
declare prod2test=false
eval set -- "$TEMP"
while true; do
    case "$1" in

        -j|--job-name)
            job_name=$2
            shift 2

            ;;
        --prod2test|--no-prod2test)
            if test "$1" = --no-prod2test; then
                prod2test=false
            else
                prod2test=true
            fi
            shift

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %6s '-j, '
            printf %-24s '--job-name=JOB_NAME'
            echo
            printf "%06s" " "
            printf %-24s '--[no-]prod2test'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test "${prod2test}" = true; then
    tmp=$scm_jenkins_prod_server
    scm_jenkins_prod_server=$scm_jenkins_test_server
    scm_jenkins_test_server=$tmp
fi

(
    task=$(basename "$job_name")
    log working with $task
    save-it() {
        save.-to-git -m "auto commit at $(now), before jc get-job"
        rm $task.xml -f
        jc get-job-for-edit -t "$task" --extra-save "$task.before-edit.xml"
        save.-to-git -m "auto commit at $(now), before edit"
    }

    for server in $scm_jenkins_test_server $scm_jenkins_prod_server; do
        cd ~/src/jenkins-tasks/.sites/${server}
        save-it
    done

    if test ! -e $task.xml; then
        EMACS=t hint "copying $task from test to prod, as prod don't have it"
        cp ../$scm_jenkins_test_server/$task.xml .
        jc create-job $task < $task.xml || true
        jc ojob $task
    else
        if diff $task.xml ../$scm_jenkins_test_server/$task.xml; then
            EMACS=t hint "No need to update $PWD/$task, prod same with test ../$scm_jenkins_test_server/$task.xml"
            exit
        fi
        cp ../$scm_jenkins_test_server/$task.xml .
        ew $task.xml
    fi
)
