#!/usr/bin/env python

import jenkins
import os, sys

import json

server = jenkins.Jenkins(
    os.environ['scm_jenkins_url'],
    username = os.environ['scm_jenkins_user'],
    password = os.environ['scm_jenkins_password']
)

print json.dumps(server.get_queue_info())
