#!/usr/bin/env perl
use strict;

use JSON;
## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl b:build-url
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $build_url = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-b, ';
  printf "%-24s", '--build-url=BUILD-URL';
  if (length('--build-url=BUILD-URL') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'build-url|b=s' => \$build_url,
            'help|h!' => \&$handler_help,
           );


## end generated code

my $build_json = decode_json(qx(jc curl ${build_url}api/json));

my %envmap;
for (@{$build_json->{actions}}) {
  if ($_->{_class} eq "hudson.model.ParametersAction") {
    for (@{$_->{parameters}}) {
      $envmap{$_->{name}} = $_->{value};
    }
  }
}

print encode_json \%envmap;
