#!/bin/bash
set -e

## start code-generator "^\\s *#\\s *"
# generate-getopt -P n:node-name
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o n:h \
                      --long node-name:,help \
                      -n $(basename -- $0) -- "$@")
declare node_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -n|--node-name)
            node_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-n, '
            printf %-24s '--node-name=NODE_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${node_name}"; then
    if test "$#" = 1; then
        node_name=$1
    else
        die "Must specify the node nade!"
    fi
fi

jc curl computer/${node_name}/config.xml
