#!/usr/bin/env perl
use strict;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl n:node d:depth=0
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $depth = 0;
my $node = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-d, ';
  printf "%-24s", '--depth=DEPTH';
  if (length('--depth=DEPTH') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";
  printf "%6s", '-n, ';
  printf "%-24s", '--node=NODE';
  if (length('--node=NODE') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'depth|d=s' => \$depth,
            'node|n=s' => \$node,
            'help|h!' => \&$handler_help,
           );


## end generated code
system("jc", "curl", "computer/$node/api/json?depth=$depth");
