#!/usr/bin/env perl
use strict;

use JSON;
## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl q:queue-url
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $queue_url = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-q, ';
  printf "%-24s", '--queue-url=QUEUE-URL';
  if (length('--queue-url=QUEUE-URL') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'queue-url|q=s' => \$queue_url,
            'help|h!' => \&$handler_help,
           );


## end generated code

my $queue_json = decode_json(qx(jc curl ${queue_url}api/json));

my %envmap;
for (@{$queue_json->{actions}}) {
  if ($_->{_class} eq "hudson.model.ParametersAction") {
    for (@{$_->{parameters}}) {
      $envmap{$_->{name}} = $_->{value};
    }
  }
}

print encode_json \%envmap;
