#!/bin/bash
set -e

## start code-generator "^\\s *#\\s *"
# generate-getopt -P b:build-url
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o b:h \
                      --long build-url:,help \
                      -n $(basename -- $0) -- "$@")
declare build_url=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -b|--build-url)
            build_url=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-b, '
            printf %-24s '--build-url=BUILD_URL'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${build_url}"; then
    die "Must specify the build_url"
fi

jc curl ${build_url}injectedEnvVars/export -H"Accept:application/json"
