#!/usr/bin/env perl
use strict;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl t:role-type='"projectRoles"' '?"one of globalRoles, projectRoles(default), slaveRoles"' n:role-name
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $role_name = "";
my $role_type = "projectRoles";

my $handler_help = sub {
    print ;
    print "\n\n选项和参数：\n";
    printf "%6s", '-n, ';
    printf "%-24s", '--role-name=ROLE-NAME';
    if (length('--role-name=ROLE-NAME') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-t, ';
    printf "%-24s", '--role-type=ROLE-TYPE';
    if (length('--role-type=ROLE-TYPE') > 24 and length("one of globalRoles, projectRoles(default), slaveRoles") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "one of globalRoles, projectRoles(default), slaveRoles";
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'role-name|n=s' => \$role_name,
    'role-type|t=s' => \$role_type,
    'help|h!' => \&$handler_help,
);


## end generated code

use Encode;

use URI::Encode qw(uri_encode uri_decode);

$role_name = decode_utf8 $role_name;
$role_name = uri_encode($role_name);

system "jc", "curl", "role-strategy/strategy/getRole?type=${role_type}&roleName=${role_name}"
