#!/usr/bin/env bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P b:build-url='${BUILD_URL}' uun-keep
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o b:uh \
                      --long build-url:,un-keep,help,no-un-keep \
                      -n "$(basename -- "$0")" -- "$@")
declare build_url=${BUILD_URL}
declare un_keep=false
eval set -- "$TEMP"
while true; do
    case "$1" in

        -b|--build-url)
            build_url=$2
            shift 2

            ;;
        -u|--un-keep|--no-un-keep)
            if test "$1" = --no-un-keep; then
                un_keep=false
            else
                un_keep=true
            fi
            shift

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %6s '-b, '
            printf %-24s '--build-url=BUILD_URL'
            echo
            printf %6s '-u, '
            printf %-24s '--[no-]un-keep'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test "${un_keep}" = false; then
    if test "$(jc curl "${build_url%/}/api/json"|jq .keepLog -r)" = true; then
        exit
    fi
fi

jc curl "${build_url%/}/toggleLogKeep" -X POST
