#!/bin/bash

## start code-generator "^\\s *#\\s *"
# generate-getopt -P l:label
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o l:h \
                      --long label:,help \
                      -n $(basename -- $0) -- "$@")
declare label=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -l|--label)
            label=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-l, '
            printf %-24s '--label=LABEL'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${label}"; then
    jc curl computer/ |grep -o 'href="/computer/[^\s]*/"' -P |sort -u|grep -v '(master)'|pn 3 /|sort -u
else
    jc curl label/${label}/api/json | perl -e "$(
cat <<'EOFc1e5a328463f'
# {%perl-mode%}
use JSON;
my $label_json = decode_json(join("", <>));

use v5.10;
for (@{$label_json->{nodes}}) {
    say $_->{nodeName};
}
# {%/perl-mode%}
EOFc1e5a328463f

)"
fi
