#!/usr/bin/env perl
use strict;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl s:server-url
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $server_url = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-s, ';
  printf "%-24s", '--server-url=SERVER-URL';
  if (length('--server-url=SERVER-URL') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'server-url|s=s' => \$server_url,
            'help|h!' => \&$handler_help,
           );


## end generated code

$server_url =~ s,/*$,/,;

my $json_info = qx(jc curl ${server_url}api/json);

use JSON;
$json_info = decode_json $json_info;

use v5.10;
for (@{$json_info->{views}}) {
  say $_->{name};
}
