#!/usr/bin/env bash
set -e

## start code-generator "^\\s *#\\s *"
# generate-getopt -P n:node-name
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o n:h \
                      --long node-name:,help \
                      -n $(basename -- $0) -- "$@")
declare node_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -n|--node-name)
            node_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %6s '-n, '
            printf %-24s '--node-name=NODE_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test "$(jc curl computer/${node_name}/api/json | jq .offline)" = false; then
    jc curl computer/${node_name}/toggleOffline -X POST --data-urlencode "offlineMessage=offline by jc" --data-urlencode "Submit=Mark this node temporarily offline"
else
    log "${node_name} already offline"
fi
