#!/usr/bin/env perl
use strict;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P j:job-name '?"也可以指定 job url"' \
# p:test-path '?"比如 \$..causes.*.userId，查找是谁启动的；\$..parameters.*.value，参数"' \
# s:short-cut '?"简写，可以用 who 查责任人，params 查参数"' \
# v:test-value '?"比如 baohaojun"' \
# e:eval '?"使用指定的表达示进行判断，而不是默认的正则表达式匹配"' \

## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $eval = "";
my $job_name = "";
my $short_cut = "";
my $test_path = "";
my $test_value = "";

my $handler_help = sub {
    print ;
    print "\n\n选项和参数：\n";
    printf "%6s", '-e, ';
    printf "%-24s", '--eval=EVAL';
    if (length('--eval=EVAL') > 24 and length("使用指定的表达示进行判断，而不是默认的正则表达式匹配") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "使用指定的表达示进行判断，而不是默认的正则表达式匹配";
    print "\n";
    printf "%6s", '-j, ';
    printf "%-24s", '--job-name=JOB-NAME';
    if (length('--job-name=JOB-NAME') > 24 and length("也可以指定 job url") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "也可以指定 job url";
    print "\n";
    printf "%6s", '-s, ';
    printf "%-24s", '--short-cut=SHORT-CUT';
    if (length('--short-cut=SHORT-CUT') > 24 and length("简写，可以用 who 查责任人，params 查参数") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "简写，可以用 who 查责任人，params 查参数";
    print "\n";
    printf "%6s", '-p, ';
    printf "%-24s", '--test-path=TEST-PATH';
    if (length('--test-path=TEST-PATH') > 24 and length("比如 \$..causes.*.userId，查找是谁启动的；\$..parameters.*.value，参数") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "比如 \$..causes.*.userId，查找是谁启动的；\$..parameters.*.value，参数";
    print "\n";
    printf "%6s", '-v, ';
    printf "%-24s", '--test-value=TEST-VALUE';
    if (length('--test-value=TEST-VALUE') > 24 and length("比如 baohaojun") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "比如 baohaojun";
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'eval|e=s' => \$eval,
    'job-name|j=s' => \$job_name,
    'short-cut|s=s' => \$short_cut,
    'test-path|p=s' => \$test_path,
    'test-value|v=s' => \$test_value,
    'help|h!' => \&$handler_help,
);


## end generated code
my $job_url = $job_name;

if ( $job_url !~ m,://, ) {
    $job_url = "$ENV{scm_jenkins_url}job/${job_name}/";
}

if ($short_cut and $test_path) {
    die "不能同时指定 short-cut 和 test-path！"
}

if ($short_cut eq "who") {
    $test_path = '$..causes.*.userId';
} elsif ($short_cut =~ m/^(params?|parameters?)/) {
    $test_path = '$..parameters.*.value';
}

use JSON;
use JSON::Path;
my $job_json = decode_json(qx(jc curl ${job_url}api/json?depth=1));

use v5.10;
my $jpath = JSON::Path->new('$..builds.*');

for ($jpath->values($job_json)) {
    my $jpath2 = JSON::Path->new($test_path);
    if (grep {
        if ($eval) {
            eval $eval
        } else {
            if (ref $_ eq "JSON::PP::Boolean") {
                $_ = $_ ? "true" : "false";
            }

            $_ =~ m/\Q$test_value\E/i
        }
    } $jpath2->values($_)) {
        print "$job_url" . $_->{number} . "\n";
    }
}
