#!/usr/bin/env bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P f:old-job-name-or-url t:to-new-job-name
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o f:t:h \
                      --long old-job-name-or-url:,to-new-job-name:,help \
                      -n $(basename -- $0) -- "$@")
declare old_job_name_or_url=
declare to_new_job_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -f|--old-job-name-or-url)
            old_job_name_or_url=$2
            shift 2

            ;;
        -t|--to-new-job-name)
            to_new_job_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %6s '-f, '
            printf %-24s '--old-job-name-or-url=OLD_JOB_NAME_OR_URL'
            echo
            printf %6s '-t, '
            printf %-24s '--to-new-job-name=TO_NEW_JOB_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

old_job_url=${old_job_name_or_url}

if ! [[ $old_job_name_or_url =~ /job/ ]]; then
    old_job_url=${scm_jenkins_url}job/${old_job_name_or_url}/
fi

jc curl "${old_job_url}doRename?newName=$to_new_job_name" -X POST
