#!/usr/bin/env perl
use strict;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl j:job-url
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $job_url = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-j, ';
  printf "%-24s", '--job-url=JOB-URL';
  if (length('--job-url=JOB-URL') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'job-url|j=s' => \$job_url,
            'help|h!' => \&$handler_help,
           );


## end generated code

use JSON;
my $job_json = decode_json(qx(jc curl ${job_url}api/json));

my @builds;
for (@{$job_json->{builds}}) {
  my $build_url = $_->{url};
  push @builds, decode_json(qx(jc curl ${build_url}api/json));
}

print encode_json(\@builds);
