#!/bin/bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P j:job-name n:build-number u:build-url rrebuild
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o n:u:j:rh \
                      --long build-number:,build-url:,job-name:,rebuild,help,no-rebuild \
                      -n $(basename -- $0) -- "$@")
declare build_number=
declare build_url=
declare job_name=
declare rebuild=false
eval set -- "$TEMP"
while true; do
    case "$1" in

        -n|--build-number)
            build_number=$2
            shift 2

            ;;
        -u|--build-url)
            build_url=$2
            shift 2

            ;;
        -j|--job-name)
            job_name=$2
            shift 2

            ;;
        -r|--rebuild|--no-rebuild)
            if test "$1" = --no-rebuild; then
                rebuild=false
            else
                rebuild=true
            fi
            shift

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-n, '
            printf %-24s '--build-number=BUILD_NUMBER'
            echo
            printf %06s '-u, '
            printf %-24s '--build-url=BUILD_URL'
            echo
            printf %06s '-j, '
            printf %-24s '--job-name=JOB_NAME'
            echo
            printf %06s '-r, '
            printf %-24s '--[no-]rebuild'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${build_url}"; then
    if test "${job_name}" -a "${build_number}"; then
        build_url=${scm_jenkins_url}job/${job_name}/${build_number}
    fi
fi

build_url=$(echo "${build_url}" | perl -pe 's,/*$,,')
if test -z "${build_url}"; then
    die "Can't stop it without job/build info, check usage with jc stop-build --help"
fi

jc curl "${build_url}/stop" -X POST

if test "${rebuild}" = true; then
    if ! jc rebuild -u "${build_url}"; then
        log should use trigger?
        jc curl ${build_url}/gerrit-trigger-retrigger-this -v
        jc curl ${build_url}/gerrit-trigger-retrigger-this/ -v
    fi
fi
