#!/bin/bash
for x in "$@"; do
    if test -e "$x"; then
        grep -Hn '^TRACE_EVENT\(\s*\S+\s*,' -P "$x" | perl -ne 'if (s/(.*?):(\d+):(TRACE_EVENT\s*\(\s*(\S+)\s*,.*)/trace_$4 function $2 $1 $3/g) {print}' | tee ~/.cache/system-config/logs/$(basename $0).log
    fi
done

#($tag, $type, $line_num, $file) = m/^\s*(\S+)\s+(.*?)\s+(\d+)\s+(\S+)/;
# echo $0 "$@" >> ~/.cache/system-config/logs/$(basename $0).log 2>&1
