#!/bin/bash

set -e
set -x
url=$1
md5=$2
mkdir -p "`dirname $md5`"
seq=`echo $md5|md5sum|pn 1`
seq=`printf %d 0x"${seq:0:2}"`
((seq = seq % 7))
(
    flock 200
    test -e "$md5".url && test -e "$md5" && exit
    if test -e ~/.wikiproxyrc; then
        . ~/.wikiproxyrc
        # export http_proxy=localhost:18080
    fi
    curl "$url" > "$md5".$$.tmp 2>~/.logs/wiki-cache-image-thumb$seq.lock
    mv "$md5".$$.tmp "$md5"
    echo "$url" > "$md5".url
) 200>~/.logs/wiki-cache-image-thumb$seq.lock
