#!/usr/bin/env perl

# we will require that each ARG must appear in the wiki title, the
# first one is special, we will use it for beagrep

use strict;
use utf8;
use Encode;
use Digest::MD5;

# for (@ARGV) {
#     print STDERR "arg '$_' " . Digest::MD5::md5_hex($_) . "\n";
# }

chomp(my $mypath = `readlink -f $0`);
chomp(my $mydir = `dirname $mypath`);
our $lang = shift @ARGV or die "Error: must supply lang!";

open(my $where, "<", "$mydir/$lang.py") or die "Error openning where-file at $mydir/$lang.py";
chomp(my $file_info = <$where>);
close $where;
$file_info =~ s/.*?"//;
$file_info =~ s/.xml.bz2/.idx/;
my $beagrep_dir = $file_info . ".beagrep";

chdir $beagrep_dir or die "Error: cant chdir $beagrep_dir";

my $arg = shift @ARGV or die "Error: at least one argument is needed";

open(my $file, "-|", "beagrep", "-e", $arg, "-i") or die "Error: failed beagrep";

my @args;
for (@ARGV) {
    @args = (@args, lc $_);
}

while(<$file>) {
    my $found = 1;
    next unless m/:.*?:(.*)$/;
    my $line = $1;
    my $lc_line = lc $1;
    for my $arg (@args) {
        if (index($lc_line, lc $arg) == -1) {
            $found = 0;
            last;
        }
    }

    if ($found) {
        system('wiki-sorted-idx-title-query', $lang, $line);
    }
}



