.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.\" (c) 2001 Filip Van Raemdonck <mechanix@debian.org>
.\"
.\" This manpage is in the public domain.
.\"

.TH update-mime-database 1 "26 Jul 2002" "Filip Van Raemdonck" "X Desktop Group"

.SH NAME
update-mime-database \- a program to build the Shared MIME-Info database cache

.SH SYNOPSIS
.B update-mime-database \-h
|
.B \-v
| [
.B \-V
]
.I MIME-DIR

.SH DESCRIPTION
.B update-mime-database
is a program which is responsible for updating the shared mime-info cache
according to the system described in the
.UR http://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec
Shared MIME-Info Database specification
.UE
from the X Desktop Group.

.SH OPTIONS
.TP
\fB\-h\fR
Print out a command summary.
.TP
\fB\-v\fR
Print out the version information.
.TP
\fB\-V\fR
Be verbose.

.SH ARGUMENTS
.TP
\fBMIME-DIR\fR
This is the directory for which
.B update-mime-database
should rebuild the cache. Mandatory if none of the options is provided.

.SH AUTHOR
Filip Van Raemdonck (mechanix@debian.org) wrote this manpage for the
Debian GNU/Linux project, but it may be used by others.

.SH LICENCE
Copyright (C) 2002 Thomas Leonard.
.br
You may redistribute copies of
.B update-mime-database
under the terms of the GNU General Public License.

