#!/bin/bash
## Bash completion for the Android SDK tools.
##
## Copyright (c) 2009 Matt Brubeck
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
## THE SOFTWARE.

function _android()
{
  local cur prev opts cmds type types c subcommand
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="--help --silent --verbose"
  cmds="list create move delete update"
  types="avd target project"
  subcommand=""
  type=""

  # Look for the subcommand.
  c=1
  while [ $c -lt $COMP_CWORD ]; do
    word="${COMP_WORDS[c]}"
    for cmd in $cmds; do
      if [ "$cmd" = "$word" ]; then
        subcommand="$word"
      fi
    done
    for w in $types; do
      if [ "$w" = "$word" ]; then
        type="$word"
      fi
    done
    c=$((++c))
  done

  case "$subcommand $type" in
    " ")
      case "$cur" in
        -*)
          COMPREPLY=( $(compgen -W "$opts" -- ${cur}) )
          ;;
      esac
      COMPREPLY=( $(compgen -W "$cmds" -- ${cur}) )
      ;;
    "list ")
      COMPREPLY=( $(compgen -W "avd target" -- ${cur}) )
      ;;
    "create "|"update ")
      COMPREPLY=( $(compgen -W "avd project" -- ${cur}) )
      ;;
    "move "|"delete ")
      COMPREPLY=( $(compgen -W "avd" -- ${cur}) )
      ;;
  esac

  case "$cur" in
    -*)
      case "$subcommand $type" in
        "delete ")
          COMPREPLY=( $(compgen -W "avd" -- ${cur}) )
          ;;
        "create avd")
          COMPREPLY=( $(compgen -W "--target --sdcard --path --name --force --skin" -- ${cur}) )
          ;;
        "move avd")
          COMPREPLY=( $(compgen -W "--path --name --rename" -- ${cur}) )
          ;;
        "delete avd"|"update avd")
          COMPREPLY=( $(compgen -W "--name" -- ${cur}) )
          ;;
        "create project")
          COMPREPLY=( $(compgen -W "--package --name --activity --target --path" -- ${cur}) )
          ;;
        "update project")
          COMPREPLY=( $(compgen -W "--target --path --name" -- ${cur}) )
          ;;
      esac
      ;;
  esac
  return 0
}
complete -o default -F _android android

function _adb_push()
{
    cur="${COMP_WORDS[COMP_CWORD]}"
    _adb_util_list_files none "$cur"
    return 0
}

complete -o default -o filenames -o nospace -F _adb_push adb_push adb_pull

function _fastboot()
{
  local cur prev opts cmds c subcommand device_selected
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="-w -s -p -c -i -b -n"
  cmds="update flashall flash erase getvar boot devices \
        reboot reboot-bootloader oem"
  subcommand=""
  partition_list="boot recovery system userdata"
  device_selected=""

  # Look for the subcommand.
  c=1
  while [ $c -lt $COMP_CWORD ]; do
    word="${COMP_WORDS[c]}"
    if [ "$word" = "-s" ]; then
      device_selected=true
    fi
    for cmd in $cmds; do
      if [ "$cmd" = "$word" ]; then
        subcommand="$word"
      fi
    done
    c=$((++c))
  done

  case "${subcommand}" in
    '')
      case "${prev}" in
        -s)
          # Use 'fastboot devices' to list serial numbers.
          COMPREPLY=( $(compgen -W "$(fastboot devices|cut -f1)" -- ${cur} ) )
          return 0
          ;;
      esac
      case "${cur}" in
        -*)
          COMPREPLY=( $(compgen -W "$opts" -- ${cur}) )
          return 0
          ;;
      esac
      if [ -z "$device_selected" ]; then
        local num_devices=$(( $(fastboot devices 2>/dev/null|wc -l) ))
        if [ "$num_devices" -gt "1" ]; then
          # With multiple devices, you must choose a device first.
          COMPREPLY=( $(compgen -W "-s" -- ${cur}) )
          return 0
        fi
      fi
      COMPREPLY=( $(compgen -W "${cmds}" -- ${cur}) )
      return 0
      ;;
    flash)
      # partition name
      COMPREPLY=( $(compgen -W "${partition_list}" -- ${cur}) )
      return 0
      ;;
    erase)
      # partition name
      COMPREPLY=( $(compgen -W "${partition_list}" -- ${cur}) )
      return 0
      ;;
  esac
}
complete -o default -F _fastboot fastboot

function _emulator()
{
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="-system -datadir -kernel -ramdisk -init-data -data -partition-size -cache \
    -no-cache -sdcard -wipe-data -avd -skindir -skin -no-skin -memory -netspeed -netdelay \
    -netfast -trace -show-kernel -shell -no-jni -logcat -no-audio -audio \
    -audio-in -audio-out -raw-keys -radio -port -ports -onion -onion-alpha \
    -onion-rotation -scale -dpi-device -http-proxy -timezone -dns-server \
    -cpu-delay -no-boot-anim -no-window -version -report-console -gps -keyset \
    -shell-serial -old-system -tcpdump -bootchart -nand-limits -qemu -verbose -debug -help \
    -help-disk-images -help-keys -help-debug-tags -help-char-devices \
    -help-environment -help-keyset-file -help-virtual-device -help-sdk-images \
    -help-build-images -help-all"

  case "$cur" in
    -*)
      COMPREPLY=( $(compgen -W "$opts" -- ${cur}) )
      return 0
      ;;
  esac
}
complete -o default -F _emulator emulator

function _android_env()
{
    local cur prev
    local IFS=$'\n'

    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    case "$prev" in
        *android-env)
            COMPREPLY=( $(skeleton_compgen_word.pl \
                -m 1000 \
                -d '\n' -- \
                "$(extract-def sh $(lookup-file build/envsetup.sh))" \
                "$cur")
            )
            return 0
            ;;

        get*_build_var)
            COMPREPLY=( $(skeleton_compgen_word.pl \
                -m 1000 \
                -d '\n' -- \
                "$(extract-def make $(lookup-file build/core/envsetup.mk))" \
                "$cur")
            )
            return 0
            ;;
        esac
}

complete -o default -F _android_env android-env

function _android_full_build() {
    local cur prev
    local IFS=$'\n'

    cur="${COMP_WORDS[COMP_CWORD]}"

    COMPREPLY=( $(skeleton_compgen_word.pl \
        -m 1000 \
        -d '\n' -- \
        "$(
            cd $(lookup-file .repo/..) >/dev/null 2>&1
            . build/envsetup.sh >/dev/null 2>&1
            for x in "${LUNCH_MENU_CHOICES[@]}"; do
                echo "$x"
            done
        )" \
            "$cur")
    )
    return 0
}

complete -o default -F _android_full_build android-full-build android-set-product android-hourly-build android-make
