#!/bin/bash
_ps_list()
{
    local IFS=$'\n'
    COMPREPLY=( $(skeleton_compgen_word.pl -d '\n' -- "$(ps -u $USER -o pid,cmd|perl -ne 's,\\,/,g; s/^\s*//; s/ +/ /g; s,/,.,g; s/ *$//; print unless 1..1')" "$cur"|tee ~/1.txt) )
}

_ps_kill()
{
    local cmd cur prev skinsdir i j k=0
    local IFS=$'\n'

    COMPREPLY=()
    cmd=${COMP_WORDS[0]}
    _get_comp_words_by_ref cur prev

    case $COMP_CWORD in
        *)
	    _ps_list
	    echo -n > ~/2.txt
	    for x in "${COMPREPLY[@]}"; do
		echo $x >> ~/2.txt
	    done
            return 0
            ;;
    esac

    return 0
}

complete -o default -F _ps_kill ps-kill
