#!/bin/bash
_ps_list()
{
    local IFS=$'\n'
    COMPREPLY=( 
	$(
	    skeleton_compgen_word.pl -d '\n' -- \
		"$(
                    ps.pl 2>/dev/null "$cur" |
                    tee ~/.cache/system-config/logs/ps.pl.out | 
                    perl -ne '
                        s,\\,/,g;
                        s/^\s*//;
                        s/ +/ /g;
                        s,/,.,g;
                        s/ *$//;
                        print;
                    '
                )" \
		"$cur"
	)
    )
}

_ps_kill()
{
    local cmd cur prev skinsdir i j k=0
    local IFS=$'\n'

    COMPREPLY=()
    cmd=${COMP_WORDS[0]}
    _get_comp_words_by_ref cur prev

    case $COMP_CWORD in
        *)
	    _ps_list
            return 0
            ;;
    esac

    return 0
}

complete -o filenames -F _ps_kill ps-kill ps-killall
