#!/bin/bash

function _re()
{
    local cur prev
    local IFS=$'\n'

    COMPREPLY=()
    set -- "${COMP_WORDS[@]}"
    shift
    

    COMPREPLY=( $(skeleton_compgen_word.pl \
	-d '\n' -p \; -f ~/.bash_history.bak \
	-- "$@")
    )
    return 0
}

complete -o default -F _re re
	    
