.\" info(5)
.\" $Id: info.5 5191 2013-02-23 00:11:18Z karl $
.\"
.\" Copyright 1998, 2005, 2011 Free Software Foundation, Inc.
.\"
.\" Copying and distribution of this file, with or without modification,
.\" are permitted in any medium without royalty provided the copyright
.\" notice and this notice are preserved.
.\"
.de EX
.nf
.ft CW
.in +5
..
.de EE
.in -5
.ft R
.fi
..
.TH INFO 5 "GNU Info" "FSF"
.SH NAME
info \- readable online documentation
.SH DESCRIPTION
The Info file format is an easily-parsable representation for online
documents.  It can be read by
.I emacs(1)
and
.I info(1)
among other programs.
.PP
Info files are usually created from
.I texinfo(5)
sources by
.IR makeinfo(1) ,
but can be created from scratch if so desired.
.PP
For a full description of the Texinfo language and associated tools,
please see the Texinfo manual (written in Texinfo itself).  Most likely,
running this command from your shell:
.EX
info texinfo
.EE
or this key sequence from inside Emacs:
.EX
M-x info RET m texinfo RET
.EE
will get you there.
.SH AVAILABILITY
http://www.gnu.org/software/texinfo/
.SH "REPORTING BUGS"
Please send bug reports to bug-texinfo@gnu.org,
general questions and discussion to help-texinfo@gnu.org.
.SH "SEE ALSO"
info(1), install-info(1), makeinfo(1), texi2dvi(1),
.br
texindex(1).
.br
emacs(1), tex(1).
.br
texinfo(5).
