#+TITLE: 2019 年个人总结

* 身体

今年开始认真地锻炼身体了，坚持得还不错，每周都游 3~4 次泳，体重从年初的 82Kg 下降到了现在 72Kg，刚好 10Kg，完成了春节时定下的小目标。

这里要特别感谢的一个人，就是我哥包昊滨。去年兄弟两家人一起过了个年，中间跟他一起游了几次泳，第一次游的时候就把我刺激坏了。一上来就说，我们来比赛吧，一起游 10 圈，看谁游得快。结果我到第 3 圈的时候就不行了，感觉快要挂了。他游过来皮笑肉不笑地贱贱地对我说，『我感觉你有所保留嘛』。。。然后对我传授了他自己总结出来的游泳密技，很简单，就是：

1. 先热身 300 米
2. 用全力冲刺 80% 的力量和速度，游 1000 米
3. 每 50 米休息（最多休息喘 5 口气的时间）

他的这个建议就像魔咒一样，我开始锻炼之后，完全停不下来了，感觉是上瘾了。

前几天跟他聊天的时候，我吹了个牛，说自己现在去游泳的时候「下水之前就像以前抽烟的时候烟瘾犯了一样，手足无措，浑身不舒服，赶紧跳下去游起来才能好」。

结果他贱贱地回答，「哦是吗。我现在开始练蝶泳了啦，每次就游个 1000 米蝶泳啊」。[捂脸]

另外非常想要感谢的，是现在一起工作的伙伴们，几乎每天中午吃完饭以后，都会大家一起走一走，站一站，聊一会儿天。这个活动非常治愈，非常防老年痴呆。

如果说我有没有什么减重心得的话，呃，简直是个笑话。其实减重很简单，没有什么秘决，就是保证输入（摄入的热量）小于输出（消耗的热量）就可以了。

比较好笑的是，我在过程中接触到了一个叫「减肥宝」的软件（因为公司组织学习 OKR，而开发这个软件的公司在 OKR 那本书里被当成一个案例）。

那段时间我每顿饭都拿一个厨房料理称称一下，然后输一个热量到减肥宝里进去。每次游完泳之后，我也会输一个消耗掉的热量进去。

效果特别明显！简直可以称得上神奇般地立竿见影的效果，减肥宝根据我输入的热量差值计算出来我的体重的变化可准了！还给我画了一条预测体重下降趋势的曲线！这极大地增强了我坚持下去的决心和信心。

然而，一两个月之后，我慢慢意识到减肥宝并没有那么神奇了。

首先，我一开始输入的游泳的热量消耗完全是错误的，我输入的是网上随便查的一个数值，据说只有专业运动员的游法才能达到那种热量消耗。

其次，每天称体重有个一公斤以内的浮动太正常了，但我一开始完全不知道这一点，全把它当成减肥宝算得准的证据了。

幸好，当我对减肥宝失望了的时候，我的游泳已经有点儿成瘾了，然后就一直坚持了下来。

（由此想到，减肥宝以及 OKR 有没有用？当然有用！有没有那么有用？哈哈哈）

* 头脑

很幸运，之前在老罗的公司工作了 4 年多的时间。老罗是一个很有思想的人，什么问题都敢于思考。我从他身上学到了很多（其实没有太多，只学到了一条，就是独立思考，但就这一条感觉已经是一整个世界）。

然而，我都已经快 40 了，才开始学独立思考，不会太晚了吗？不觉得丢人吗。

还好了，本来浑浑噩噩地也不是不可以过完这一生。

尤其是，我之前就比较喜欢的一种心理状态『Flow』，讲究的就是不能思考太多啊。前怕狼后怕虎的话，肯定不容易 Flow 起来啊。

另外，还有一件感觉很幸运的事情，就是学了日语，然后接触到了一些有趣的思想。

之前有人问过我，为什么要学日语，嗯，这个问题，有点不好回答，为什么呢，因为不好意思回答。

因为我一开始学日语，就是为了装逼，为了跟别人不一样啊。

有一首歌是这么唱的『我们不一样，不一样，不一样』，简直是放屁，不一样的，怎么能是『我们』呢？一旦用上了复数的「我们」，就全都是一个Ｘ样儿了好吗，只有单数的「我」才是不一样的，好吗？！😁每次听到这首歌，都感觉好像看见一群傻子在一起喊口号给自己加油打气一样。😆

呃，扯远了，为什么开始学日语并不重要。学了日语之后，我的收获是什么，才是我想说说的。

目前最大的收获，就是接触了村上春树。一个快 70 岁的老人，写了几十年的小说，为了保持稳定的创作，坚持跑了几十年步，极其自律的一个人。

我在用日语看他的「村上さんのところ」，一个他跟读者通过 Email 进行问答互动的网站，最后所有邮件集结成的一本书，在国内的 Kindle 上能买到的村上春树的作品就只有这一本。

我刚才强行回答的那个「我为什么要学日语」的答案，就是抄袭了他关于「你年轻的时候为什么那么爱学英语」的回答，他说「可能是为了跟别人不一样吧，年轻的时候跟别人不一样，感觉是很重要的一件事情」。

就是没想到我快 40 了，也还是很想让自己跟别人不一样[嘿哈]。

里面有很多人，问村上一些关于人生的哲学问题，比如人活着的意义是什么；或者问他作为一个老年人，怎么看待自己体力下降、身体机能衰退的问题；或者人生中碰到特别悲伤的事情该怎么办。

村上春树一般都非常平淡地回答，这种问题太难了，他不想考虑这样的问题；悲伤的时候可以去学一只猫，发一会儿呆。。。

既学习了日语，又学习了一些做人的道理，这可以说是我当初漫无目的地开始学习日语的时候没有想到过的人生的小确幸了（小确幸这个词也是村上春树发明的）。

目前个人最喜欢的两个问答：

** 关于老化

比如有一位 37 岁的女士问村上，『三十代过半，「正在变老」的感受和失望的瞬间慢慢变多了。不是说不想变老，就是感觉有种失望。村上先生，您对自身的老化有失望的地方吗，那种时候是怎么办的？。。。』

村上答『是吗，三十代后半的人就已经「正在变老」了啊。我在那个年纪的时候生活很忙，那种事情考虑一下的空闲也没有。对自己的老化有失望的地方吗？在变老的感受虽然是有的，特别的失望倒并没有呢。因为变老这件事情，也是有好处的。会失去一些东西，但是也会得到一些东西。跟失去的比起来，得到的不能稍微更多一点的话。。。这是我眼下的课题。』

（这个问答极大地缓解了我对自己即将 40 了这一事实的恐惧心理。[耶]）

** 关于人生太难了

比如一个 29 岁的女士觉得人生艰难，问村上『去年开始，从未感到过的「人生太难了」的感觉突然开始了。读着村上先生的小说、天天不知道该干点儿什么地捱到今天。工作和恋爱全都不顺。「将来到底会变成什么样呢」，每次想到这个问题，我就完全不知道该怎么办才好。跟朋友请教的话，他们建议我去找到自己想要做的事情，可我怎么也想不出来，每天就只好吃吃美食，读读书，这样一天一天地混日子，「只要今天是开心的就好」。如果是村上先生的话，这样的时候会怎么克服呢？』

村上答『我作为一个单纯的人，也只能说一些相对单纯的事情。请让身体动起来。跟自己的身体对话。你的情况，只能那样开始。让身体动起来难吗？保持呼吸难吗？那是一样的。对你来说，让身体动起来，是和保持呼吸一样必要的事情。如果不喜欢运动的话，去收拾一下屋子、熨一下衣服、清理一下浴缸、什么都行。专注地让身体动起来。不这样做的话，不管过多久，你也没法从那种状态下脱离出来的哟。加油』。

（这个问答让我想起我哥对我说的那句，『我感觉你有所保留嘛』，简单到不能再简单的一句话，却彻底改变了我对运动的态度和运动的习惯。这也太神奇了，完全想不通是什么原理。）

* 学习

作为一个 Emacs 的铁杆用户，我一直非常希望尽可能多的活动都可以用 Emacs 来完成，学习也不例外，之前一直在思考怎么在学习的过程中更好的利用 Emacs，今年我想到了一种新的学习方法。

就是需要学什么新的工具、技术的话，我现在会采取如下操作：

1. 找到该工具比较权威的文档
2. 把文档拷贝到 Emacs 里，对其开始编辑，一边阅读，一边编辑
3. 那些比较简单的、我不用看都已经知道了的，或者稍微一推导一思考就能理解的，全部 *删掉*（相当于把书读薄了？）
4. 那些我自己不容易理解的段落、以前不知道的内容等等，留下来，进一步编辑，将其改写、简化（删掉一些多余的、不影响理解的助词等），自己复述一遍，加深理解
5. 最后剩下的内容，我会考虑把它放到「快捷短语」里（参考下节开源项目）

* 开源项目

以下是 2019 年工作之外业余开发的一些开源软件工具，其中前两个有独立的项目，名字分别就叫 org-kungfu 和 cuty。后面的几个都在我的 system-config 项目里。

1. org-kungfu 和 jkd（用 org-mode 方便快捷地编辑 atlassian 的 confluence pages 文档和 jira 文本）
2. cuty（个人成长辅助集中注意力软件，每隔 3 分钟检查一次我是不是在用手机刷微博，会强行返回桌面并要求做 10 个深蹲作为惩罚）
3. 用 Emacs 聊手机钉钉、微信
4. 用 Emacs 实现了一个桌面系统剪贴板管理器
5. Linux 桌面全局快捷短语输入

其中最后这个小工具是受了 Richard Stallman 的故事的启发。以前上网的时候，经常看到 Stallman 在邮件里长篇大论地回复别人，阐述他对于自由软件的理想理念。当时觉得这个大佬精力真旺盛，真闲，有这么多时间精力跟别人说这些。后来才知道，他用来记录「快捷短语」输入的文件有好几个Ｍ！谁说「快捷短语」必须都是短的？大佬的那些长篇大论全都是快捷短语！😅
