.\" beagrep-imlogviewer(8) manpage
.\"
.\" Copyright (C) 2004-2007 Novell, Inc.
.\"
.TH BEAGREP-IMLOGVIEWER "8" "14 Mar 2007"
.SH NAME
beagrep-imlogviewer
.SH SYNOPSIS
.B beagrep-imlogviewer --client <CLIENT> 
[\fIoptions\fR] <log file or directory>
.SH DESCRIPTION
.PP
Beagrep tool to the logs of instant messaging programs.
.PP
.SH OPTIONS
.TP
.B --client
Client that the log belongs to (e.g. gaim).
.TP
.B --highlight-search
Words to highlight in the buffer.
.TP
.B --search
Search query to filter hits on.
.TP
.B --help
Display a summary of command-line options
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagrepd (1),
.BR http://beagrep-project.org
