.\" beagrep-build-index(8) manpage
.\"
.\" Copyright (C) 2005 Novell, Inc.
.\"
.TH BEAGREP "8" "Jul 2005" "beagrep" ""
.SH NAME
beagrep-build-index
.SH SYNOPSIS
.B beagrep-build-index
[\fIoptions\fR] 
<\fIindex_path\fR>
<\fIpath\fR>
[\fIpath path path\fR]
.SH DESCRIPTION
.PP
.BR beagrep-build-index ,
is a tool designed for building static indexes outside of the Beagrep daemon. 
.PP
Running
.BR beagrep-build-index
by hand is of use for those wishing to create and build static indexes used by
the Beagrep daemon. The static indexes can be helpful in many cases but most
notably used as system-wide indexes shared by all users, and as a way for
system-administrators to run indexing on a central server in a network
environment. 
.PP
.BR beagrep-build-index
will index the data specified by the \fIpath\fR arguments and create an index
in the \fIindex_path\fR directory. If a suitable index is found in the index
directory, it will automatically append data to the index if the file at hand
has been modified since it was last indexed. If it can't find a suitable index
(non-existant or version-mismatch) is will purge the directory recursively.
.PP
The 
.BR beagrep-build-index
tool is not intended to be invoked by the standard user.
.SH OPTIONS
.BR beagrep-build-index
takes the following options
.TP
.B --recursive
If specified, do recursive crawling on the paths specified	
.TP
.B --debug
If specified, echo verbose debugging information
.TP
.B --cache-text
If specified, build text-cache of documents used for snippets
.TP
.B --allow-pattern [pattern]
Only allow files that match the pattern to be indexed.
.TP
.B --deny-pattern [pattern]
Keep any files that match the pattern from being indexed.
.TP
.B --remap \fR[\fIpath1\fR:\fIpath2\fR]
If specified, remap the target path by prefix. \fIpath1\fR will be replaced
with \fIpath2\fR. This option is intended to be used when generating pre-built
indexes, where the final path will be differ from the current one.
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2005 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagrepd (1),
.BR beagrep-manage-index (8)
