.\" beagrep-extract-content(8) manpage
.\"
.\" Copyright (C) 2004-2007 Novell, Inc.
.\"
.TH BEAGREP-EXTRACT-CONTENT "8" "14 Mar 2007"
.SH NAME
beagrep-extract-content
.SH SYNOPSIS
.B beagrep-extract-content
[\fIoptions\fR] file [file ...]
.SH DESCRIPTION
.PP
Low-level Beagrep tool to examine data extracted from a file.
.PP
.SH OPTIONS
.TP
.B --debug
Print debug info to the console
.TP
.B --tokenize
Tokenize the text before printing
.TP
.B --show-children
Show filtering information for items created by filters
.TP
.B --mimetype=<mime_type>
Use filter for mime_type
.TP
.B --outfile=<filename>
Output file name
.TP
.B --help
Display a summary of command-line options
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagrepd (1),
.BR http://beagrep-project.org
