#!/bin/bash

# This line will be automatically uncommented when you "make install"
installed=1

if [ -z $installed ] ; then
    echo "*** Running uninstalled ManageIndex.exe ***"
    THIS_PATH="../Util:../BeagrepClient:."
    THIS_EXE="./ManageIndex.exe"

    export BEAGREP_TOOL_PATH="../tools"
    export MONO_PATH="../Util:../BeagrepClient${MONO_PATH+:$MONO_PATH}"
    export LD_LIBRARY_PATH="../glue/.libs${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"
    export BEAGREP_FILTER_PATH="../Filters${BEAGREP_FILTER_PATH+:$BEAGREP_FILTER_PATH}"

    if [ -z $BEAGREP_CONF_DIR ]; then
	    export BEAGREP_CONF_DIR="../conf-data"
    fi

else
    THIS_PATH="/home/bhj/external/local/lib/beagrep"
    THIS_EXE="/home/bhj/external/local/lib/beagrep/ManageIndex.exe"

    export MONO_PATH="/home/bhj/external/local/lib/beagrep${MONO_PATH+:$MONO_PATH}"
    export LD_LIBRARY_PATH="/home/bhj/external/local/lib/beagrep${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"
fi

MONO_PATH="$THIS_PATH${MONO_PATH+:$MONO_PATH}" exec -a beagrep-manage-index mono $MONO_EXTRA_ARGS $THIS_EXE "$@"

