#!/usr/bin/env bash
set -e

init-da
if test -z "$1"; then
    set -- "$(ask-for-input-with-sawfish -p "what is the scene's name")"
fi

find-scene "$1"
bhj-notify "find-scene" "find-scene $1 completed"
