#!/bin/bash

h=$(date +%H)
m=$(date +%M | perl -npe 's/^0+//')
m=$((m - m % 15))
m=$(printf %02d $m)

echo $h:$m
if test $# = 2; then
    h=$1
    m=$2
fi
for x in ~/system-config/etc/at/$h:$m ~/external/etc/at/$h:$m; do
    if test -e "$x"; then
        mkdir -p ~/.logs/at-tasks
        bash $x > ~/.logs/at-tasks/$(echo $x|perl -npe 's,/,.,g') 2>&1
    fi
done
