#!/bin/bash
cd ~/doc/ime
find . -type f|xargs bash -c 'for x in "$@"; do echo read $x; sdim_add_cand $(basename "$x"); done' xx

sdim_sync_cands | 
sort -u | 
sed -e 's/sdim_add_cand //' |
xargs bash -c 'for x in "$@"; do dir=$(echo $x|md5sum|cut -b 1-2); mkdir -p $dir; echo write $dir/$x; touch $dir/"$x"; done' xx
