#!/bin/bash
test -e ~/.sdim-single && exit
export SDIM_SYNC_CANDS=true
cd ~/doc/ime
tmpf=/tmp/$(basename $0).$$
find . -type f|xargs bash -c 'for x in "$@"; do echo sdim-add-cand $(basename "$x"); done' xx | sort -u > $tmpf.git

sdim-add-cands-replay | sort -u > $tmpf.ime

diff $tmpf.git $tmpf.ime | grep "^<"|cut -b 3-|bash

diff $tmpf.git $tmpf.ime | grep "^>"|cut -b 3-|
sed -e 's/sdim-add-cand //' |
xargs bash -c 'for x in "$@"; do dir=$(echo $x|md5sum|cut -b 1-2); mkdir -p $dir; echo write $dir/$x; touch $dir/"$x"; done' xx
if test -z "$DEBUG"; then rm $tmpf.ime $tmpf.git; fi
