#!/bin/bash
set -e

if test $# = 1; then
    if [[ $1 =~ ${scm_jenkins_test_url} ]]; then
        set -- "$1" ${scm_jenkins_prod_url}"${1#${scm_jenkins_test_url}}"
    else
        set -- "$1" ${scm_jenkins_test_url}"${1#${scm_jenkins_prod_url}}"
    fi
fi

tmp_dir=~/tmp/jc.comp-test/$1

mkdir -p "$tmp_dir"
cd $tmp_dir

get-jenkins-url() {
    echo $1 | perl -ne 'print $1 if m,(.*?://.*?/),' | grep . || echo ${scm_jenkins_url}
}

get-edit-dir() {
    echo ~/src/jenkins-tasks/.sites/$(get-jenkins-url "$1" | perl -pe 's,.*://(.*?)/.*,$1,')/
}

get-job-config() {
    task=$(basename $1)
    dir=$(get-edit-dir $1)
    (
        cd $dir
        jenkins_url=$(get-jenkins-url $1)
        jc -j "${jenkins_url}" get-job-for-edit -t "$task"
    )
}

get-job-config $1
get-job-config $2

echo "$1 <=> $2"
meld $(get-edit-dir $1)/${1##*/}.xml \
     $(get-edit-dir $2)/${2##*/}.xml
