#!/bin/bash
set -e

. aterr bhj-notify "falied to run $*"

## start code-generator "^\\s *#\\s *"
# generate-getopt -P e:ext=mock
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o e:h \
                      --long ext:,help \
                      -n $(basename -- $0) -- "$@")
declare ext=mock
eval set -- "$TEMP"
while true; do
    case "$1" in

        -e|--ext)
            ext=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-e, '
            printf %-24s '--ext=EXT'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code


if test "$#" = 0; then
    job=$(jc get-browser-tab-job)

    set -- "$job" "$job.${ext}"
fi

job_xml=$(jc get-job $1)

echo "${job_xml}" | jc create-job $2
