#!/usr/bin/env bash
set -e
declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # b:build-url
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o b:h \
                      --long build-url:,help \
                      -n $(basename -- $0) -- "$@")
declare build_url=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -b|--build-url)
            build_url=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %6s '-b, '
            printf %-24s '--build-url=BUILD_URL'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code
jc curl "${build_url}/api/json"|jq '..|.parameters?|.[]?|.name? + "=" + (.value?|tostring)'|sort | grep -v '"separator-'
