#!/bin/bash
set -e

. aterr bhj-notify "$0" "failed to run $0"

## start code-generator "^\\s *#\\s *"
# generate-getopt -P j:job-name
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o j:h \
                      --long job-name:,help \
                      -n $(basename -- $0) -- "$@")
declare job_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -j|--job-name)
            job_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-j, '
            printf %-24s '--job-name=JOB_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code


original_url=$(get-firefox-tab-url)
jenkins_url=$(echo ${original_url} | perl -pe 's,(.*?//.*?/).*,$1,; s,/*$,/,')

if test "${jenkins_url}" = / || ! declare -x -p | grep 'jenkins.*url' | grep "$jenkins_url" -q; then
    jenkins_url=${scm_jenkins_prod_url}
fi

export FIREFOX_PROFILE_ARG=$(sawfish-window get-top-window-env '^FIREFOX_PROFILE_ARG=' || true)
export THE_FIREFOX=$(sawfish-window get-top-window-env '^THE_FIREFOX=' || true)

if test "${job_name}"; then
    url=${jenkins_url}job/${job_name}
    exec of $url
fi

declare -A function_url_map=(
    ["Configure System"]=configure
    ["Manage Jenkins"]=manage
    ["Manage Plugins"]=pluginManager/advanced
    ["Gerrit Trigger this change"]=yyy
    ["Config Gerrit Trigger"]=gerrit-trigger/
    ["select-a-job"]=xxx
    ["Gerrit Manual Trigger"]=gerrit_manual_trigger/
)


export EMACS=t

which_func=$(
    select-args -i "$1" -o -p "Which function do you want?" "${!function_url_map[@]}"
          )

shift || true

if test "${which_func}" = select-a-job; then
    jobs=$(jc -j ${jenkins_url} list-jobs)
    job=$(select-args -i "$1" -o -p "Which job do you want?" $jobs)

    url=job/${job}
elif test "${which_func}" = "Gerrit Trigger this change"; then
    gerrit_url=$(echo ${original_url} | perl -pe 's,(/c/\d+/?).*,$1,')
    jc gerrit-trigger -s Gerrit -u ${gerrit_url} &> ~/tmp/gerrit-trigger.txt
    build_url=$(
        extract-urls-from-text "$(cat ~/tmp/gerrit-trigger.txt)"
             )
    if test "${build_url}"; then
        firefox "${build_url}"
    else
        e ~/tmp/gerrit-trigger.txt
    fi
    exit
else
    url=${function_url_map["${which_func}"]}
fi

firefox ${jenkins_url}${url}
