#!/bin/bash
set -e

exec >& ~/tmp/go.log

## start code-generator "^\\s *#\\s *"
# generate-getopt -P j:job-name
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o j:h \
                      --long job-name:,help \
                      -n $(basename -- $0) -- "$@")
declare job_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -j|--job-name)
            job_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-j, '
            printf %-24s '--job-name=JOB_NAME'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code


original_url=$(get-firefox-tab-url)
jenkins_url=$(echo ${original_url} | perl -pe 's,(.*?//.*?/).*,$1,; s,/*$,/,')

if test "${job_name}"; then
    url=${jenkins_url}job/${job_name}
    exec of $url
fi

declare -A function_url_map

function_url_map["Configure System"]=configure
function_url_map["Manage Jenkins"]=manage
function_url_map["Manage Plugins"]=pluginManager/
function_url_map["Gerrit Trigger in Jenkins"]=yyy
function_url_map["select-a-job"]=xxx

export EMACS=t

which_func=$(
    select-args -o -p "Which function do you want?" "${!function_url_map[@]}"
     )

if test "${which_func}" = select-a-job; then
    jobs=$(jc -j ${jenkins_url} list-jobs)
    job=$(select-args -o -p "Which job do you want?" $jobs)

    url=job/${job}
elif test "${which_func}" = "Gerrit Trigger in Jenkins"; then
    gerrit_url=$(echo ${original_url} | perl -pe 's,(/c/\d+/?).*,$1,')
    jc gerrit-trigger -s Gerrit -u ${gerrit_url} &> ~/tmp/gerrit-trigger.txt
    build_url=$(
        extract-urls-from-text "$(cat ~/tmp/gerrit-trigger.txt)"
             )
    if test "${build_url}"; then
        firefox "${build_url}"
    else
        e ~/tmp/gerrit-trigger.txt
    fi
    exit
else
    url=${function_url_map["${which_func}"]}
fi

bhj-notify go ${jenkins_url}${url}

of ${jenkins_url}${url}
