#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use Data::Dumper;
use JSON;

my $json = JSON->new->utf8->canonical->pretty;

my @permissions = (
    "com.cloudbees.plugins.credentials.CredentialsProvider.Create",
    "com.cloudbees.plugins.credentials.CredentialsProvider.Delete",
    "com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains",
    "com.cloudbees.plugins.credentials.CredentialsProvider.Update",
    "com.cloudbees.plugins.credentials.CredentialsProvider.View",
    "com.sonyericsson.hudson.plugins.gerrit.trigger.PluginImpl.ManualTrigger",
    "com.sonyericsson.hudson.plugins.gerrit.trigger.PluginImpl.Retrigger",
    "hudson.model.Item.Build",
    "hudson.model.Item.Cancel",
    "hudson.model.Item.Configure",
    "hudson.model.Item.Create",
    "hudson.model.Item.Delete",
    "hudson.model.Item.Discover",
    "hudson.model.Item.Move",
    "hudson.model.Item.Read",
    "hudson.model.Item.Workspace",
    "hudson.model.Run.Delete",
    "hudson.model.Run.Replay",
    "hudson.model.Run.Update",
    "hudson.scm.SCM.Tag",
    "jenkins.metrics.api.Metrics.HealthCheck",
    "jenkins.metrics.api.Metrics.ThreadDump",
    "jenkins.metrics.api.Metrics.View",
    "org.jfrog.hudson.ArtifactoryPlugin.Promote",
    "org.jfrog.hudson.ArtifactoryPlugin.Release",
);

my $permissions_list = decode_utf8($json->encode(\@permissions));

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl \
# t:role-type='"projectRoles"' '?"配置哪种类型的 role：one of globalRoles, projectRoles(default), slaveRoles"' \
# n:role-name '?"比如 SEC_DEV"' \
# p:role-projects-pattern '?"比如 jobA|jobB|jobPatternC。也可以用 +|jobPatternD 来表示增加一个正则表达式"' \
# g:add-group='()' '?"如需添加多个，允许多次指定此参数"' \
# @:add-perm='()' '?"+PERM 代表添加权限、-PERM 代表删除权限，权限列表见\n$permissions_list"' \

## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my @add_group = ();
my @add_perm = ();
my $role_name = "";
my $role_projects_pattern = "";
my $role_type = "projectRoles";

my $handler_help = sub {
    print ;
    print "\n\n选项和参数：\n";
    printf "%6s", '-g, ';
    printf "%-24s", '--add-group=ADD-GROUP';
    if (length('--add-group=ADD-GROUP') > 24 and length("如需添加多个，允许多次指定此参数") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "如需添加多个，允许多次指定此参数";
    print "\n";
    printf "%6s", '';
    printf "%-24s", '--add-perm=ADD-PERM';
    if (length('--add-perm=ADD-PERM') > 24 and length("+PERM 代表添加权限、-PERM 代表删除权限，权限列表见\n$permissions_list") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "+PERM 代表添加权限、-PERM 代表删除权限，权限列表见\n$permissions_list";
    print "\n";
    printf "%6s", '-n, ';
    printf "%-24s", '--role-name=ROLE-NAME';
    if (length('--role-name=ROLE-NAME') > 24 and length("比如 SEC_DEV") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "比如 SEC_DEV";
    print "\n";
    printf "%6s", '-p, ';
    printf "%-24s", '--role-projects-pattern=ROLE-PROJECTS-PATTERN';
    if (length('--role-projects-pattern=ROLE-PROJECTS-PATTERN') > 24 and length("比如 jobA|jobB|jobPatternC。也可以用 +|jobPatternD 来表示增加一个正则表达式") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "比如 jobA|jobB|jobPatternC。也可以用 +|jobPatternD 来表示增加一个正则表达式";
    print "\n";
    printf "%6s", '-t, ';
    printf "%-24s", '--role-type=ROLE-TYPE';
    if (length('--role-type=ROLE-TYPE') > 24 and length("配置哪种类型的 role：one of globalRoles, projectRoles(default), slaveRoles") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "配置哪种类型的 role：one of globalRoles, projectRoles(default), slaveRoles";
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'add-group|g=s' => \@add_group,
    'add-perm=s' => \@add_perm,
    'role-name|n=s' => \$role_name,
    'role-projects-pattern|p=s' => \$role_projects_pattern,
    'role-type|t=s' => \$role_type,
    'help|h!' => \&$handler_help,
);


## end generated code

use autodie qw(:all);
use JSON;
my $role_json = decode_json(qx(jc getRole -t ${role_type} -n ${role_name}));

use v5.10;

say STDERR JSON->new->utf8(1)->pretty(1)->encode($role_json);

my $removeRoleData = sprintf "type=%s&roleNames=%s", ${role_type}, ${role_name};



# system("jc", "curl", "role-strategy/strategy/removeRoles", "--data", "$removeRoleData", "-X", "POST");

my $new_pattern;
if ($role_projects_pattern =~ s,^\+,,) {
  $new_pattern = $role_json->{pattern} . $role_projects_pattern;
} else {
    $new_pattern = $role_projects_pattern;
}
if ($new_pattern) {
    my $updateRoleData = sprintf
        (
            "type=%s&roleName=%s&permissionIds=%s&pattern=%s&overwrite=true",
            $role_type,
            $role_name,
            join(",", keys %{$role_json->{permissionIds}}) . ",",
            $new_pattern
        );

    system("debug-run", "jc", "curl", "role-strategy/strategy/addRole", "--data", "$updateRoleData", "-X", "POST");
}

for my $sid (@{$role_json->{sids}}, @add_group) {
  my $assign_data = sprintf(
                            "type=%s&roleName=%s&sid=%s",
                            $role_type, $role_name, $sid
                           );
  say STDERR "assign $sid to $role_name";
  system "jc", "curl", "role-strategy/strategy/assignRole", "--data", "$assign_data", "-X", "POST";
}
