QT.LibsnoreQt5.VERSION = 0.7.0
QT.LibsnoreQt5.MAJOR_VERSION = 0
QT.LibsnoreQt5.MINOR_VERSION = 7
QT.LibsnoreQt5.PATCH_VERSION = 0
QT.LibsnoreQt5.name = snore-qt5
QT.LibsnoreQt5.defines = 
QT.LibsnoreQt5.includes = /home/bhj/external/local/qt5-ubuntu-1404/include
QT.LibsnoreQt5.private_includes =
QT.LibsnoreQt5.libs = /home/bhj/external/local/qt5-ubuntu-1404/lib/x86_64-linux-gnu
QT.LibsnoreQt5.depends = core gui widgets network
