#!/bin/bash
set -e

## start code-generator "^\\s *#\\s *"
    # generate-getopt -P a:action=edit '?"想执行的操作可以是 edit、delete"' \
        # n:field-name '?"想操作的域名，可以只输入一个片段，参考 sela -h 的 -i 参数说明"'
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o a:n:h \
                      --long action:,field-name:,help \
                      -n $(basename -- $0) -- "$@")
declare action=edit
declare field_name=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -a|--action)
            action=$2
            shift 2

            ;;
        -n|--field-name)
            field_name=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-a, '
            printf %-24s '--action=ACTION'
            echo "想执行的操作可以是 edit、delete"
            printf %06s '-n, '
            printf %-24s '--field-name=FIELD_NAME'
            echo "想操作的域名，可以只输入一个片段，参考 sela -h 的 -i 参数说明"
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code


export SELECT_HISTORY_ORDER='jkd.edit-field'

# http://jira/secure/admin/EditCustomField!default.jspa?id=14204

custom_fields_json=$(
    jkd get rest/api/2/field
                  )

custom_field=$(
    echo "$custom_fields_json" |
        jq '.[]|.id + ": " + .name' -r |
        select-output-line -i "${field_name}" -p "which field to you want?" cat |
        perl -pe 's,:.*,,; s,.*_,,'
            )

case "$action" in
    edit)
        firefox "${scm_jira_url}secure/admin/EditCustomField!default.jspa?id=${custom_field}"
        ;;
    delete)
        firefox "${scm_jira_url}secure/admin/DeleteCustomField!default.jspa?id=${custom_field}"
        ;;
esac
