#!/bin/bash
sudo apt-get clean
sudo apt-get update
sudo apt-get dist-upgrade --download-only --yes

(
    sudo umount -l ~/smb
    smbnetfs ~/smb

    set -ex
    mkdir ~/smb/bible/Public/apse-daily-build/$(today)/bpe-patches -p 
    rsync -av --exclude='*.tgz' --exclude=vmlinux --exclude=System.map ~/smbookmarks/apse-daily-release/pxa978T/$(today)* ~/smb/bible/Public/apse-daily-build/$(today)/

    x=$(echo ~/smb/bible/cm/release-$(today--)/tknevo-ics*/pxa978ariel_cmcc_release/)
    cd $x
    patches=$(echo logo.bin *.blf* *gpt* u-boot.bin *ddr* fact* prdcfg*)
    cp $patches ~/smb/bible/Public/apse-daily-build/$(today)/bpe-patches -av
    
    sudo umount -l ~/bible || true
    sshfs samba@bible:/ ~/bible
    (
        cd ~/bible/home/samba/public/apse-daily-build/$(today)/bpe-patches/
        for x in $(readlink -f ..)/$(today)*; do
            test -d $x || continue
            mkdir -p $(basename $x)
            for y in $x/pxa*/; do
                test -d $y || continue
                mkdir -p $(basename $x)/$(basename $y)
                (
                    cd $(basename $x)/$(basename $y)
                    relative-link $y/* .
                    for p in $patches; do
                        rm -fr $p
                        cp -av  ../../$p . 
                    done
                    ~/src/android/boot/obm/TimBuilder -r $(readlink -f pxa978ariel_cmcc.blf)
                )
            done
        done
    )
)
    
chmod a-w ~/bible/home/samba/public/apse-daily-build/$(today)/ -R
