#!/bin/bash

set -ex
if test -d /home/bpehw; then
    time (
        mkdir -p ~/backup
        sudo rsync -av /home/bpehw/pcb /home/bpehw/doc ~/backup
        sudo getfacl -R /home/bpehw > ~/backup/acl.txt
        cd ~/backup
        sudo su postgres -c 'pg_dump reviewdb' > gerrit.reviewdb.sql
        sudo git add .
        sudo git commit -m $(today)
        sudo git push bhj@r31:backup master:master
        sudo rsync -av /home/gerrit2/ bhj@r31:backup.hwsrv-gerrit/rsync.bak
    )
fi

if test -d ~/backup.hwsrv-gerrit; then
    cd ~/backup.hwsrv-gerrit;
    for x in $(ssh hwsrv/gerrit/ gerrit ls-projects; echo All-Projects); do 
        if test -d $x.git; then
            (
                cd $x.git
                git fetch || true
                git fetch origin refs/changes/*:refs/changes/* || true
            )
        else
            (
                mkdir -p $(dirname $x)
                cd $(dirname $x)
                git clone hwsrv/gerrit/:$x --bare --mirror
            )
        fi
    done
fi
