#!/bin/bash

# This line will be automatically uncommented when you "make install"
installed=1

if [ -z $installed ] ; then
    echo "*** Running uninstalled IndexHelper.exe ***"
    THIS_PATH="../Util:../BeagrepClient:."
    THIS_EXE="./IndexHelper.exe"

    export BEAGREP_TOOL_PATH="../tools"

    export MONO_PATH="../Util:../BeagrepClient${MONO_PATH+:$MONO_PATH}"
    export LD_LIBRARY_PATH="../glue/.libs${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"
    export BEAGREP_FILTER_PATH="../Filters${BEAGREP_FILTER_PATH+:$BEAGREP_FILTER_PATH}"
else
    THIS_PATH="/home/bhj/external/local/lib/beagrep"
    THIS_EXE="/home/bhj/external/local/lib/beagrep/IndexHelper.exe"
fi

if [ -n "$_GET_ON_THE_HEAP_BUDDY_BANDWAGON" ]; then
   n=1
   while [ -e $BEAGREP_HEAP_BUDDY_DIR/outfile.helper.$n ]; do
	 n=$(($n+1))
   done	
   MONO_EXTRA_ARGS="--profile=heap-buddy:$BEAGREP_HEAP_BUDDY_DIR/outfile.helper.$n $MONO_EXTRA_ARGS"
elif [ -n "$_HEY_LETS_DO_A_HEAP_SHOT" ]; then
   n=1
   while [ -e $BEAGREP_HEAP_SHOT_DIR/outfile.helper.$n ]; do
	 n=$(($n+1))
   done	
   MONO_EXTRA_ARGS="--profile=heap-shot:$BEAGREP_HEAP_SHOT_DIR/outfile.helper.$n $MONO_EXTRA_ARGS"

fi

if [ -z "$BEAGREP_MONO_RUNTIME" ]; then
   export BEAGREP_MONO_RUNTIME="mono"
fi

if [ -n "$BEAGREP_MONO_DEBUG_FLAG_IS_SET" ]; then
   MONO_EXTRA_ARGS="--debug $MONO_EXTRA_ARGS"
fi

export MONO_PATH="$THIS_PATH${MONO_PATH+:$MONO_PATH}"

CMDLINE="$BEAGREP_MONO_RUNTIME $MONO_EXTRA_ARGS $THIS_EXE $@"

PROCESS_NAME="beagrepd-helper"
exec -a $PROCESS_NAME $CMDLINE

