#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use Data::Dumper;
use JSON;

my $json = JSON->new->utf8->canonical->pretty;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# j:group-json

## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $group_json = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-j, ';
    printf "%-24s", '--group-json=GROUP-JSON';
    if (length('--group-json=GROUP-JSON') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'group-json|j=s' => \$group_json,
    'help|h!' => \&$handler_help,
);


## end generated code

$group_json = $json->decode(encode_utf8($group_json));

use URI::Escape;
my $group_name = uri_escape_utf8 $group_json->{name};
my $method = 'PUT';
if ($0 =~ m,update-group,) {
    $method = 'POST';
    $group_json = $group_json->{details};
}

runx("debug-run", "artifactory", "my-curl", "api/security/groups/${group_name}", "-X", "$method", "-H", 'Content-Type: application/json', "-d",  decode_utf8($json->encode($group_json)));

run("c -e scm_artifactory_url  artifactory ls-groups >/dev/null");
