#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use Data::Dumper;
use JSON;

my $json = JSON->new->utf8->canonical->pretty;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# n:repo-name c:copy-from-repo '?"从哪个 Repo 拷贝配置"' \
# d:description

## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $copy_from_repo = "";
my $description = "";
my $repo_name = "";

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-c, ';
    printf "%-24s", '--copy-from-repo=COPY-FROM-REPO';
    if (length('--copy-from-repo=COPY-FROM-REPO') > 24 and length("从哪个 Repo 拷贝配置") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "从哪个 Repo 拷贝配置";
    print "\n";
    printf "%6s", '-d, ';
    printf "%-24s", '--description=DESCRIPTION';
    if (length('--description=DESCRIPTION') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";
    printf "%6s", '-n, ';
    printf "%-24s", '--repo-name=REPO-NAME';
    if (length('--repo-name=REPO-NAME') > 24 and length() > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", ;
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'copy-from-repo|c=s' => \$copy_from_repo,
    'description|d=s' => \$description,
    'repo-name|n=s' => \$repo_name,
    'help|h!' => \&$handler_help,
);


## end generated code

my $json_copy =
    $json->decode(scalar capturex("artifactory", "my-curl", "api/repositories/${copy_from_repo}"));

$json_copy->{key} = $repo_name;

die "Must specify description" unless $description;
$json_copy->{description} = $description;

runx("debug-run", "artifactory", "my-curl", "api/repositories/${repo_name}", "-X", "PUT", "-H", 'Content-Type: application/json', "-d",  decode_utf8($json->encode($json_copy)));
