#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use Data::Dumper;
use JSON;

my $json = JSON->new->utf8->canonical->pretty;

(my $comment_doc = <<~'EOFc83131117f09') =~ s,^# .*org-mode.*,,gm;
# {%org-mode%}

# {%/org-mode%}
EOFc83131117f09

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl -P '?"$comment_doc"' \
# mmanual-only=1 '?"只显示手动的权限，不显示jira自动生成的权限"' \

## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("posix_default");



my $manual_only = 1;

my $handler_help = sub {
    print "$comment_doc";
    print "\n\n选项和参数：\n";
    printf "%6s", '-m, ';
    printf "%-24s", '--[no]manual-only';
    if (length('--[no]manual-only') > 24 and length("只显示手动的权限，不显示jira自动生成的权限") > 0) {
        print "\n";
        printf "%30s", "";
    }
    printf "%s", "只显示手动的权限，不显示jira自动生成的权限";
    print "\n";

    my $exit_value = 0;
    if (@_ && $_[0] ne "help" && $_[1] != 1) {
        $exit_value = shift @_;
        print "@_\n";
    }

    exit($exit_value);
};

GetOptions (
    'manual-only|m!' => \$manual_only,
    'help|h!' => \&$handler_help,
);


## end generated code


my $perms =
    $json->decode(scalar capture("cached-run -e scm_artifactory_url artifactory my-curl api/security/permissions"));

if ($manual_only) {
    @{$perms} = grep {$_->{name} !~ m,Deliver To,} @{$perms}
}

use URI::Escape;
for (@$perms) {
    my $url = $_->{uri};
    my $details =
        $json->decode(scalar capturex("cached-run", "-e", "scm_artifactory_url", "artifactory", "my-curl", $url));

    $_->{details} = $details;
}

say decode_utf8($json->encode($perms));
