#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use Data::Dumper;
use JSON;

my $json = JSON->new->utf8->canonical->pretty;

my $perms =
    $json->decode(scalar capture("cached-run artifactory my-curl api/security/permissions"));

use URI::Escape;
for (@$perms) {
    my $url = $_->{uri};
    my $details =
        $json->decode(scalar capturex("cached-run", "artifactory", "my-curl", $url));

    $_->{details} = $details;
}

say decode_utf8($json->encode($perms));
