#!/bin/bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P s:sibling-project
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o s:h \
                      --long sibling-project:,help \
                      -n $(basename -- $0) -- "$@")
declare sibling_project=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -s|--sibling-project)
            sibling_project=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-s, '
            printf %-24s '--sibling-project=SIBLING_PROJECT'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

tmpdir=~/tmp/create-sibling-project.$$
. atexit rm -rf $tmpdir
mkdir -p $tmpdir

cd $tmpdir

git init .
git fetch s:$sibling_project refs/meta/*:refs/meta/*

git reset --hard refs/meta/config

parent_project=$(
    git config -f project.config access.inheritFrom
              )

for p in "$@"; do
    log-run ssh-gerrit create-project "$p" -p "$parent_project" --empty-commit
done

git push s:$p HEAD:refs/meta/config -f
