#!/usr/bin/env bash
set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P c:change
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o c:h \
                      --long change:,help \
                      -n $(basename -- $0) -- "$@")
declare change=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -c|--change)
            change=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-c, '
            printf %-24s '--change=CHANGE'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if [[ $change =~ ^[0-9]+$ ]]; then
    gr rest -a /a/changes/${change} -- -X DELETE
else
    die "CHANGE must be a numebr!"
fi
