#!/bin/bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P q:query
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o q:h \
                      --long query:,help \
                      -n $(basename -- $0) -- "$@")
declare query=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -q|--query)
            query=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-q, '
            printf %-24s '--query=QUERY'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

reviews=$(
    gerrit-query-for-repo-download -q "$query" --fields 'commit-hash author-email subject'
       )

if yes-or-no-p "Continue with $reviews?"; then
    echo "$reviews" | pn 1 |
        while read commit; do
            (
                ssh-gerrit review --abandon $commit && echo $x ok || echo $x failed
            ) < /dev/null
        done
fi
