#!/usr/bin/env perl
use strict;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl c:change
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $change = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-c, ';
  printf "%-24s", '--change=CHANGE';
  if (length('--change=CHANGE') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'change|c=s' => \$change,
            'help|h!' => \&$handler_help,
           );


## end generated code

use JSON;

my $reviewers_json = decode_json(qx(gr rest -a a/changes/$change/reviewers/));

for (@{$reviewers_json}) {
  my $reviewer_id = $_->{_account_id};
  system("gr", "rest", "-a", "a/changes/$change/reviewers/$reviewer_id", "--", "-X", "DELETE");
}
