#!/usr/bin/env perl
use strict;
use v5.10.1; # for say and switch
use autodie qw(:all);
use IPC::System::Simple qw(run runx capture capturex $EXITVAL EXIT_ANY);
binmode(STDOUT, ":utf8");
binmode(STDERR, ":utf8");
use Encode;
use utf8;
@ARGV = map {decode_utf8 $_} @ARGV;

use feature 'signatures';
no warnings "experimental::signatures";

use Data::Dumper;
use JSON;

my $json = JSON->new->utf8->canonical->pretty;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl c:change u:url f:format='"raw"' '?"可以指定 raw 或 base64，后者可直接用于 jc build"'
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $change = "";
my $format = "raw";
my $url = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-c, ';
  printf "%-24s", '--change=CHANGE';
  if (length('--change=CHANGE') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";
  printf "%6s", '-f, ';
  printf "%-24s", '--format=FORMAT';
  if (length('--format=FORMAT') > 24 and length("可以指定 raw 或 base64，后者可直接用于 jc build") > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", "可以指定 raw 或 base64，后者可直接用于 jc build";
  print "\n";
  printf "%6s", '-u, ';
  printf "%-24s", '--url=URL';
  if (length('--url=URL') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'change|c=s' => \$change,
            'format|f=s' => \$format,
            'url|u=s' => \$url,
            'help|h!' => \&$handler_help,
           );


## end generated code

if (not $change and $url) {
  ($change = $url) =~ s,.*//.*?/.*?(\d+).*,$1,;
}

use JSON;
my $change_json = $json->decode(scalar capturex("debug-run", "gr", "q", "-q", "change:$change", "-e", "CURRENT_REVISION"));

my $id = $change_json->[0]{id};
my $revision = $change_json->[0]{current_revision};

my $program;
if ($format eq "base64") {
  $program = "cat";
} else {
  $program = "base64  -d";
}


run("debug-run gr rest -a a/changes/$id/revisions/$revision/files/%2fCOMMIT_MSG/content|$program")
