#!/usr/bin/env perl
use strict;

## start code-generator "^\\s *#\\s *"
# generate-getopt -s perl c:change u:url
## end code-generator
## start generated code
use Getopt::Long;

Getopt::Long::Configure("default");



my $change = "";
my $url = "";

my $handler_help = sub {
  print ;
  print "\n\n选项和参数：\n";
  printf "%6s", '-c, ';
  printf "%-24s", '--change=CHANGE';
  if (length('--change=CHANGE') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";
  printf "%6s", '-u, ';
  printf "%-24s", '--url=URL';
  if (length('--url=URL') > 24 and length() > 0) {
    print "\n";
    printf "%30s", "";
  }
  printf "%s", ;
  print "\n";

  exit(0);
};

GetOptions (
            'change|c=s' => \$change,
            'url|u=s' => \$url,
            'help|h!' => \&$handler_help,
           );


## end generated code

if (not $change and $url) {
  ($change = $url) =~ s,.*//.*?/.*?(\d+).*,$1,;
}

use JSON;
my $change_json = decode_json(qx(gr q -q change:$change -e CURRENT_REVISION));

my $id = $change_json->[0]{id};
my $revision = $change_json->[0]{current_revision};


print qx(gr rest -a a/changes/$id/revisions/$revision/files/%2fCOMMIT_MSG/content|base64  -d);
