#!/bin/bash
set -e

comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}
给定一个新建的仓库，根据既定的规则：

1. 帮其创建相关的 admin、sme、dev 分组
2. 给这些分组分配相关的 gerrit 权限

# {%/org-mode%}
EOFe9576f8668e0
           )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"$comment_doc"' r:repo-project-name \
    # @:create-types='"ADMIN SME DEV"' \
    # @set-permission=true
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o r:h \
                      --long create-types:,repo-project-name:,set-permission,help,no-set-permission \
                      -n $(basename -- $0) -- "$@")
declare create_types="ADMIN SME DEV"
declare repo_project_name=
declare set_permission=true
eval set -- "$TEMP"
while true; do
    case "$1" in

        --create-types)
            create_types=$2
            shift 2

            ;;
        -r|--repo-project-name)
            repo_project_name=$2
            shift 2

            ;;
        --set-permission|--no-set-permission)
            if test "$1" = --no-set-permission; then
                set_permission=false
            else
                set_permission=true
            fi
            shift

            ;;
        -h|--help)
            set +x
            echo -e "$comment_doc"
            echo
            echo Options and arguments:
            printf "%06s" " "
            printf %-24s '--create-types=CREATE_TYPES'
            echo
            printf %06s '-r, '
            printf %-24s '--repo-project-name=REPO_PROJECT_NAME'
            echo
            printf "%06s" " "
            printf %-24s '--[no-]set-permission'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if parent_group_info=$(
    gr repo2group -r "${repo_project_name}" -g ADMIN --print-prefix-too
                    ); then
    parent_group=$(
        set -- $parent_group_info
        echo $1
                )
    prefix=$(
        set -- $parent_group_info
        echo $2
          )

    parent_prefix=${parent_group%ADMIN}

    new_group_name_mid=${repo_project_name//-/--}
    new_group_name_prefix=$prefix${new_group_name_mid//\//-}-
    new_group_name_prefix=${new_group_name_prefix^^}

    declare -A group_contains_relationship=(
        [SME]=ADMIN
        [DEV]=SME
    )

    for t in ${create_types}; do
        (
            if test "${t}" = ADMIN; then
                owner_group=${parent_group}
            else
                owner_group=${new_group_name_prefix}ADMIN
            fi
            for try in $t ADMIN; do
                if debug-run ssh-gerrit --admin create-group ${new_group_name_prefix}${t} \
                              --group ${parent_prefix}${try} \
                              --owner ${owner_group} \
                              $(if test "${group_contains_relationship[$t]}"; then echo --group ${new_group_name_prefix}${group_contains_relationship[$t]}; fi) \
                              -d "'$t for ${repo_project_name}'"; then
                    exit
                fi
            done
            ding --title "Failed to create ${new_group_name_prefix}${t} for ${repo_project_name} " --text "check build log@$BUILD_URL"
            exit 1
        )
    done

    if test "${set_permission}" = true; then
        gr set-project-labels -p "${repo}" --new-project
    fi
else
    die "Can't get parent group info"
fi
