#!/bin/bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P a:access-point '?"Specify which rest api to call"'
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o a:h \
                      --long access-point:,help \
                      -n $(basename -- $0) -- "$@")
declare access_point=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -a|--access-point)
            access_point=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-a, '
            printf %-24s '--access-point=ACCESS_POINT'
            echo
            printf "%30s" ""
            echo "Specify which rest api to call"
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

curl -s -u "${gerrit_user}:${gerrit_web_password}" "${gerrit_server_url}${access_point}" "$@"
