#!/bin/bash

set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}
gr rest [--raw] [-a] ACCESS-POINT [--] [EXTRA_ARGS_TO_CURL...]
# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # a:access-point '?"Specify which rest api to call"' \
    # @raw
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o a:h \
                      --long access-point:,raw,help,no-raw \
                      -n $(basename -- $0) -- "$@")
declare access_point=
declare raw=false
eval set -- "$TEMP"
while true; do
    case "$1" in

        -a|--access-point)
            access_point=$2
            shift 2

            ;;
        --raw|--no-raw)
            if test "$1" = --no-raw; then
                raw=false
            else
                raw=true
            fi
            shift

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-a, '
            printf %-24s '--access-point=ACCESS_POINT'
            echo
            printf "%30s" ""
            echo "Specify which rest api to call"
            printf "%06s" " "
            printf %-24s '--[no-]raw'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${access_point}"; then
    access_point=$1
    shift
fi

if test -z "${access_point}"; then
    die "Must specify the access ponit!"
fi

if [[ $access_point =~ :// ]]; then
    g_url=$access_point
else
    if ! [[ $access_point =~ ^/?a/ ]]; then
        access_point=a/${access_point}
    fi

    if ! [[ $access_point =~ /($|\?) ]]; then
        access_point=${access_point}/
    fi

    g_url="${gerrit_server_url}${access_point}"
fi

set -o pipefail

curl -f -s -u "${gerrit_user}:${gerrit_web_password}" "$g_url" "$@" |
    if test "${raw}" = true; then
        cat
    else
        perl -pe "$(
cat <<'EOF9bb8c2f2757c'
# {%perl-mode%}
s,^\Q)]}'\E\r?\n?,, if 1..1;
# {%/perl-mode%}
EOF9bb8c2f2757c
)"
    fi
