#!/usr/bin/env bash

set -e
## start code-generator "^\\s *#\\s *"
# generate-getopt -P c:change t:topic
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o c:t:h \
                      --long change:,topic:,help \
                      -n $(basename -- $0) -- "$@")
declare change=
declare topic=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -c|--change)
            change=$2
            shift 2

            ;;
        -t|--topic)
            topic=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e
            echo
            echo Options and arguments:
            printf %06s '-c, '
            printf %-24s '--change=CHANGE'
            echo
            printf %06s '-t, '
            printf %-24s '--topic=TOPIC'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code


_curl -X PUT ${scm_gerrit_url}a/changes/${change}/topic -H "Content-Type: application/json" -H "charset=UTF-8" --data "$(
cat <<EOF3dc33dfa770d | grep -v '^#'
# {%json-mode%}
  {
    "topic": "$topic"
  }
# {%/json-mode%}
EOF3dc33dfa770d
)
"
