;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((c++-mode
  (flycheck-mode . nil)
  (ac-clang-flags "-DQT_BOOTSTRAPPED"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtCore"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtDBus"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtGui"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtOpenGLExtensions"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtPlatformSupport"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtSql"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtTest"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets"
                  "-I/usr/include/x86_64-linux-gnu/qt5/QtXml"
                  "-I/usr/include/x86_64-linux-gnu/qt5"
                  "-I/usr/include/c++/4.9"
                  "-I/usr/include/x86_64-linux-gnu/c++/4.9"
                  "-I/usr/include/c++/4.9/backward"
                  "-I/usr/lib/gcc/x86_64-linux-gnu/4.9/include"
                  "-I/usr/local/include"
                  "-I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed"
                  "-I/usr/include/x86_64-linux-gnu"
                  "-I/usr/include"
                  "-I/usr/include/lua5.2"
                  "-I/home/bhj/tmp/build-t1"
                  "-I.")
  (flycheck-clang-include-path "/usr/include/x86_64-linux-gnu/qt5/QtConcurrent"
                               "/usr/include/x86_64-linux-gnu/qt5/QtCore"
                               "/usr/include/x86_64-linux-gnu/qt5/QtDBus"
                               "/usr/include/x86_64-linux-gnu/qt5/QtGui"
                               "/usr/include/x86_64-linux-gnu/qt5/QtNetwork"
                               "/usr/include/x86_64-linux-gnu/qt5/QtOpenGL"
                               "/usr/include/x86_64-linux-gnu/qt5/QtOpenGLExtensions"
                               "/usr/include/x86_64-linux-gnu/qt5/QtPlatformSupport"
                               "/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport"
                               "/usr/include/x86_64-linux-gnu/qt5/QtSql"
                               "/usr/include/x86_64-linux-gnu/qt5/QtTest"
                               "/usr/include/x86_64-linux-gnu/qt5/QtWidgets"
                               "/usr/include/x86_64-linux-gnu/qt5/QtXml"
                               "/usr/include/x86_64-linux-gnu/qt5"
                               "/usr/include/c++/4.9"
                               "/usr/include/x86_64-linux-gnu/c++/4.9"
                               "/usr/include/c++/4.9/backward"
                               "/usr/lib/gcc/x86_64-linux-gnu/4.9/include"
                               "/usr/local/include"
                               "/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed"
                               "/usr/include/x86_64-linux-gnu"
                               "/usr/include"
                               ".")))
