#+title: 高七番外篇：如何戒除一个坏习惯，如何养成一个好习惯

有一个非常好的视频，强烈推荐你看一下，关于怎么改掉一个坏习惯，怎么养成一个好习惯。

（请在油管上搜“5 steps to stop procrastinating, focus and be productive”，看不了的话也没有关系，不影响看这篇文章☺）

视频主要讲的是如何处理『拖延症』。里面给的方法非常简单，就两步：1. 做两个俯卧撑；2. 冲个澡。然后展开详细解释了一下这两个方法的原理。

这篇文章，就结合这个视频讲一下我看完之后的一些心得体会（主要是第一个方法，做俯卧撑）。

* 对待坏习惯的迂回战术

*在对付一个坏习惯的时候，不要硬扛，要从侧面攻击。*

比如一个抽烟成瘾的人，想戒掉抽烟的话，可以考虑这个思路。不要硬撑着，「妈的不抽不抽，老子说不抽就不抽」，结果一旦撑不住了的时候，抽起来比平时更猛。

视频里推荐的方法是，在你想抽烟的时候：

1. 不要硬扛着，就是不抽
2. 也不要放弃抵抗，想抽就抽
3. 而是从侧面分析一下自己为什么想抽烟了，是因为有点儿累了？焦虑了？还是什么别的原因。

   然后！如果可能的话，分析出来别的原因之后，就去想办法解决那些真正的问题，而不是掏出一根烟来抽就完事儿了。

* 对待坏习惯的『狸猫换太子』战术

*给坏习惯打个『标签』，让它和一个好习惯强行发生关系（用一个好习惯干死一个坏习惯[机智]）*。

这个方法，能在改掉一个坏习惯的同时，养成一个好习惯，可以说是非常神奇了。

方法很简单，就是在每次想要拖延的时候，做两个俯卧撑。

（如果只是纯粹为了养成锻炼身体的习惯，也可以和其他不相干的活动捆绑，比如每上一次洗手间就做两个俯卧撑）

坚持一段时间之后，你会神奇般地发现：

1. 你每天做了几十甚至上百个俯卧撑
2. 你的拖延症大大减轻了

这里有一个密决，就是俯卧撑每次至少两个，但不设上限。

很多人可能会问，为什么不是十个，二十个呢，这样不是更好吗？

视频的作者说，你想要养成一个好习惯的话，不要定太高的目标是非常重要的。比如你想养成跑步的习惯的话，建议你定一个每天坚持跑 200 米的目标。从人的心理上来说，达成一个这样的习惯，大家肯定会一致认为比养成一个每天至少跑 5 公里的习惯容易得多，对吧。

关键的决窍来了：你跑完 200 米之后，如果还有兴趣，还可以继续跑啊，反正来都来了。爱跑多少跑多少，不算成绩，没有压力✌。

** 一条朋友圈的更新

之前我在朋友圈里发了一条这样的消息，分享了一下自己跟两个坏习惯作斗争的经验：

#+BEGIN_QUOTE

今天的话题是『瘾』，我是一个曾经抽烟十年，又已戒烟十年的老『瘾君子』。最近发现自己染上了两个新的瘾，网瘾和『晚瘾』（指晚上半夜三更不睡觉，一直在上网刷微Ｂ、微Ｘ，『双瘾齐发』[捂脸]）。

作为一个中年油腻男，任由这两个瘾头发展下去，我觉得我可能还需要在中年油腻前再加一个形容词，挂掉了的中年油腻男。即使命不挂掉👻，人生也会挂掉哇[衰]。

那么，该怎么治疗这两个毛病呢？电击吗？不是的，不要忘了，我是一个程序员。我给自己开发了一个外挂💪。

其实就是一个脚本，每三分钟就检查一下当前的窗口，如果是浏览器的话，就再检查一下当前的网址，如果是微博的话，就自动关闭。

所以现在经常正刷着微博、看着视频呵呵傻乐的时候呢，咔一下就没了😅。

但是完全不会像小孩子被抢走玩具、被强行关掉电视时那样，当场崩溃，相反，会有一种『嗯，怎么回事？哦，又浪费了三分钟了？关得好！老子是成年人！』的自豪感油然而生。

古时候有越王勾践卧薪尝胆，也有头悬梁、锥刺骨，这种治疗方法有点过于暴力了[惊恐]，作为一个现代人，定时关一下微博就够了，嗯！加油💪！

另外还有一个类似的脚本，就是在晚 9:00 以后，每隔 5 分钟自动帮我锁一次屏。

希望对大家有所启发（如果没有的话，也请不要说『你神经病啊，还有所启发』[害羞]）。

#+END_QUOTE

现在！很高兴地告诉大家！我的外挂升级到 2.0 版本了[憨笑]。

在把我的微博关闭之后，它现在还会弹一个窗口：『你小子又在刷微博，被我逮住了吧[斜眼笑]！去，做两个深蹲走起！』。

然后我就去深蹲，最少是两个。但有时候一高兴就做十个。

* 总结

如果大家发现自己有什么坏习惯的话，不要怕，所谓『福兮祸之所倚，祸兮福之所伏』。

在改掉一个坏习惯的同时，也可以收获一个好习惯。

加油💪！

😁
