;;; Code: utf-8

(setq emojis-string-list
      '(("[国庆65周年]" "" ("GuoQing65ZhouNian" "sina-weibo"))
        ("[马上有对象]" "" ("MaShangYouDuiXiang" "sina-weibo"))
        ("[去旅行]" "" ("QuLvXing" "sina-weibo"))
        ("[带着微博去旅行]" "" ("DaiZheWeiBoQuLvXing" "sina-weibo"))
        ("[发红包]" "" ("FaHongBao" "sina-weibo"))
        ("[马到成功]" "" ("MaDaoChengGong" "sina-weibo"))
        ("→_→" "" ("ZuiYou" "sina-weibo"))
        ("[呵呵]" "~/src/github/private-config/etc/weibo-emojis/d_hehe.png" ("HeHe" "sina-weibo"))
        ("[嘻嘻]" "~/src/github/private-config/etc/weibo-emojis/d_xixi.png" ("XiXi" "sina-weibo"))
        ("[哈哈]" "~/src/github/private-config/etc/weibo-emojis/d_haha.png" ("HaHa" "sina-weibo"))
        ("[爱你]" "~/src/github/private-config/etc/weibo-emojis/d_aini.png" ("AiNi" "sina-weibo"))
        ("[挖鼻屎]" "~/src/github/private-config/etc/weibo-emojis/d_wabishi.png" ("WaBiShi" "sina-weibo"))
        ("[吃惊]" "~/src/github/private-config/etc/weibo-emojis/d_chijing.png" ("ChiJing" "sina-weibo"))
        ("[晕]" "~/src/github/private-config/etc/weibo-emojis/d_yun.png" ("Yun" "sina-weibo"))
        ("[泪]" "~/src/github/private-config/etc/weibo-emojis/d_lei.png" ("Lei" "sina-weibo"))
        ("[馋嘴]" "~/src/github/private-config/etc/weibo-emojis/d_chanzui.png" ("ChanZui" "sina-weibo"))
        ("[抓狂]" "~/src/github/private-config/etc/weibo-emojis/d_zhuakuang.png" ("ZhuaKuang" "sina-weibo"))
        ("[哼]" "~/src/github/private-config/etc/weibo-emojis/d_heng.png" ("Heng" "sina-weibo"))
        ("[可爱]" "~/src/github/private-config/etc/weibo-emojis/d_keai.png" ("KeAi" "sina-weibo"))
        ("[怒]" "~/src/github/private-config/etc/weibo-emojis/d_nu.png" ("Nu" "sina-weibo"))
        ("[汗]" "~/src/github/private-config/etc/weibo-emojis/d_han.png" ("Han" "sina-weibo"))
        ("[害羞]" "~/src/github/private-config/etc/weibo-emojis/d_haixiu.png" ("HaiXiu" "sina-weibo"))
        ("[睡觉]" "~/src/github/private-config/etc/weibo-emojis/d_shuijiao.png" ("ShuiJue" "sina-weibo"))
        ("[钱]" "~/src/github/private-config/etc/weibo-emojis/d_qian.png" ("Qian" "sina-weibo"))
        ("[偷笑]" "~/src/github/private-config/etc/weibo-emojis/d_touxiao.png" ("TouXiao" "sina-weibo"))
        ("[笑cry]" "~/src/github/private-config/etc/weibo-emojis/d_xiaoku.png" ("XiaoCRY" "sina-weibo"))
        ("[doge]" "~/src/github/private-config/etc/weibo-emojis/d_doge.png" ("DOGE" "sina-weibo"))
        ("[喵喵]" "~/tmp/weibo/res/drawable-hdpi/d_miao.png" ("MiaoMiao" "sina-weibo"))
        ("[酷]" "~/src/github/private-config/etc/weibo-emojis/d_ku.png" ("Ku" "sina-weibo"))
        ("[衰]" "~/src/github/private-config/etc/weibo-emojis/d_shuai.png" ("Shuai" "sina-weibo"))
        ("[闭嘴]" "~/src/github/private-config/etc/weibo-emojis/d_bizui.png" ("BiZui" "sina-weibo"))
        ("[鄙视]" "~/src/github/private-config/etc/weibo-emojis/d_bishi.png" ("BiShi" "sina-weibo"))
        ("[花心]" "~/src/github/private-config/etc/weibo-emojis/d_huaxin.png" ("HuaXin" "sina-weibo"))
        ("[鼓掌]" "~/src/github/private-config/etc/weibo-emojis/d_guzhang.png" ("GuZhang" "sina-weibo"))
        ("[悲伤]" "~/src/github/private-config/etc/weibo-emojis/d_beishang.png" ("BeiShang" "sina-weibo"))
        ("[思考]" "~/src/github/private-config/etc/weibo-emojis/d_sikao.png" ("SiKao" "sina-weibo"))
        ("[生病]" "~/src/github/private-config/etc/weibo-emojis/d_shengbing.png" ("ShengBing" "sina-weibo"))
        ("[亲亲]" "~/src/github/private-config/etc/weibo-emojis/d_qinqin.png" ("QinQin" "sina-weibo"))
        ("[怒骂]" "~/src/github/private-config/etc/weibo-emojis/d_numa.png" ("NuMa" "sina-weibo"))
        ("[太开心]" "~/src/github/private-config/etc/weibo-emojis/d_taikaixin.png" ("TaiKaiXin" "sina-weibo"))

        ("[懒得理你]" "~/src/github/private-config/etc/weibo-emojis/d_landelini.png" ("LanDeLiNi" "sina-weibo"))
        ("[右哼哼]" "~/src/github/private-config/etc/weibo-emojis/d_youhengheng.png" ("YouHengHeng" "sina-weibo"))
        ("[左哼哼]" "~/src/github/private-config/etc/weibo-emojis/d_zuohengheng.png" ("ZuoHengHeng" "sina-weibo"))
        ("[嘘]" "~/src/github/private-config/etc/weibo-emojis/d_xu.png" ("Xu" "sina-weibo"))
        ("[委屈]" "~/src/github/private-config/etc/weibo-emojis/d_weiqu.png" ("WeiQu" "sina-weibo"))
        ("[吐]" "~/src/github/private-config/etc/weibo-emojis/d_tu.png" ("Tu" "sina-weibo"))
        ("[可怜]" "~/src/github/private-config/etc/weibo-emojis/d_kelian.png" ("KeLian" "sina-weibo"))
        ("[打哈气]" "~/src/github/private-config/etc/weibo-emojis/d_dahaqi.png" ("DaHaQi" "sina-weibo"))
        ("[挤眼]" "~/src/github/private-config/etc/weibo-emojis/d_jiyan.png" ("JiYan" "sina-weibo"))
        ("[失望]" "~/src/github/private-config/etc/weibo-emojis/d_shiwang.png" ("ShiWang" "sina-weibo"))
        ("[顶]" "~/src/github/private-config/etc/weibo-emojis/d_ding.png" ("Ding" "sina-weibo"))
        ("[疑问]" "~/src/github/private-config/etc/weibo-emojis/d_yiwen.png" ("YiWen" "sina-weibo"))
        ("[困]" "~/src/github/private-config/etc/weibo-emojis/d_kun.png" ("Kun" "sina-weibo"))
        ("[感冒]" "~/src/github/private-config/etc/weibo-emojis/d_ganmao.png" ("GanMao" "sina-weibo"))
        ("[拜拜]" "~/src/github/private-config/etc/weibo-emojis/d_baibai.png" ("BaiBai" "sina-weibo"))
        ("[黑线]" "~/src/github/private-config/etc/weibo-emojis/d_heixian.png" ("HeiXian" "sina-weibo"))
        ("[阴险]" "~/src/github/private-config/etc/weibo-emojis/d_yinxian.png" ("YinXian" "sina-weibo"))
        ("[打脸]" "~/src/github/private-config/etc/weibo-emojis/d_dalian.png" ("DaLian" "sina-weibo"))
        ("[傻眼]" "~/src/github/private-config/etc/weibo-emojis/d_shayan.png" ("ShaYan" "sina-weibo"))
        ("[互粉]" "~/src/github/private-config/etc/weibo-emojis/f_hufen.png" ("HuFen" "sina-weibo"))
        ("[心]" "~/src/github/private-config/etc/weibo-emojis/l_xin.png" ("Xin" "sina-weibo"))
        ("[伤心]" "~/src/github/private-config/etc/weibo-emojis/l_shangxin.png" ("ShangXin" "sina-weibo"))
        ("[猪头]" "~/src/github/private-config/etc/weibo-emojis/d_zhutou.png" ("ZhuTou" "sina-weibo"))
        ("[熊猫]" "~/src/github/private-config/etc/weibo-emojis/d_xiongmao.png" ("XiongMao" "sina-weibo"))
        ("[兔子]" "~/src/github/private-config/etc/weibo-emojis/d_tuzi.png" ("TuZi" "sina-weibo"))
        ("[握手]" "~/src/github/private-config/etc/weibo-emojis/h_woshou.png" ("WoShou" "sina-weibo"))
        ("[作揖]" "~/src/github/private-config/etc/weibo-emojis/h_zuoyi.png" ("ZuoYi" "sina-weibo"))
        ("[赞]" "~/src/github/private-config/etc/weibo-emojis/h_zan.png" ("Zan" "sina-weibo"))
        ("[耶]" "~/src/github/private-config/etc/weibo-emojis/h_ye.png" ("Ye" "sina-weibo"))
        ("[good]" "~/src/github/private-config/etc/weibo-emojis/h_good.png" ("GOOD" "sina-weibo"))
        ("[弱]" "~/src/github/private-config/etc/weibo-emojis/h_ruo.png" ("Ruo" "sina-weibo"))
        ("[不要]" "~/src/github/private-config/etc/weibo-emojis/h_buyao.png" ("BuYao" "sina-weibo"))
        ("[ok]" "~/src/github/private-config/etc/weibo-emojis/h_ok.png" ("OK" "sina-weibo"))
        ("[haha]" "~/src/github/private-config/etc/weibo-emojis/h_haha.png" ("HAHA" "sina-weibo"))
        ("[来]" "~/src/github/private-config/etc/weibo-emojis/h_lai.png" ("Lai" "sina-weibo"))
        ("[威武]" "~/src/github/private-config/etc/weibo-emojis/f_v5.png" ("WeiWu" "sina-weibo"))
        ("[鲜花]" "~/src/github/private-config/etc/weibo-emojis/w_xianhua.png" ("XianHua" "sina-weibo"))
        ("[钟]" "~/src/github/private-config/etc/weibo-emojis/o_zhong.png" ("Zhong" "sina-weibo"))
        ("[浮云]" "~/src/github/private-config/etc/weibo-emojis/w_fuyun.png" ("FuYun" "sina-weibo"))
        ("[飞机]" "~/src/github/private-config/etc/weibo-emojis/o_feiji.png" ("FeiJi" "sina-weibo"))

        ("[月亮]" "~/src/github/private-config/etc/weibo-emojis/w_yueliang.png" ("YueLiang" "sina-weibo"))
        ("[太阳]" "~/src/github/private-config/etc/weibo-emojis/w_taiyang.png" ("TaiYang" "sina-weibo"))
        ("[微风]" "~/src/github/private-config/etc/weibo-emojis/w_weifeng.png" ("WeiFeng" "sina-weibo"))
        ("[下雨]" "~/src/github/private-config/etc/weibo-emojis/w_xiayu.png" ("XiaYu" "sina-weibo"))
        ("[给力]" "~/src/github/private-config/etc/weibo-emojis/f_geili.png" ("GeiLi" "sina-weibo"))
        ("[神马]" "~/src/github/private-config/etc/weibo-emojis/f_shenma.png" ("ShenMa" "sina-weibo"))
        ("[围观]" "~/src/github/private-config/etc/weibo-emojis/o_weiguan.png" ("WeiGuan" "sina-weibo"))
        ("[话筒]" "~/src/github/private-config/etc/weibo-emojis/o_huatong.png" ("HuaTong" "sina-weibo"))
        ("[奥特曼]" "~/src/github/private-config/etc/weibo-emojis/d_aoteman.png" ("AoTeMan" "sina-weibo"))
        ("[草泥马]" "" ("CaoNiMa" "sina-weibo"))
        ("[萌]" "~/src/github/private-config/etc/weibo-emojis/f_meng.png" ("Meng" "sina-weibo"))
        ("[囧]" "~/src/github/private-config/etc/weibo-emojis/f_jiong.png" ("Jiong" "sina-weibo"))
        ("[织]" "~/src/github/private-config/etc/weibo-emojis/f_zhi.png" ("Zhi" "sina-weibo"))
        ("[礼物]" "~/src/github/private-config/etc/weibo-emojis/o_liwu.png" ("LiWu" "sina-weibo"))
        ("[喜]" "~/src/github/private-config/etc/weibo-emojis/f_xi.png" ("Xi" "sina-weibo"))
        ("[围脖]" "~/src/github/private-config/etc/weibo-emojis/more_weibo.png" ("WeiBo" "sina-weibo"))
        ("[音乐]" "~/src/github/private-config/etc/weibo-emojis/o_yinyue.png" ("YinYue" "sina-weibo"))
        ("[绿丝带]" "~/src/github/private-config/etc/weibo-emojis/o_lvsidai.png" ("LvSiDai" "sina-weibo"))
        ("[蛋糕]" "~/src/github/private-config/etc/weibo-emojis/o_dangao.png" ("DanGao" "sina-weibo"))
        ("[蜡烛]" "~/src/github/private-config/etc/weibo-emojis/o_lazhu.png" ("LaZhu" "sina-weibo"))

        ("[干杯]" "~/src/github/private-config/etc/weibo-emojis/o_ganbei.png" ("GanBei" "sina-weibo"))
        ("[男孩儿]" "~/src/github/private-config/etc/weibo-emojis/d_nanhaier.png" ("NanHaiEr" "sina-weibo"))
        ("[女孩儿]" "~/src/github/private-config/etc/weibo-emojis/d_nvhaier.png" ("NvHaiEr" "sina-weibo"))
        ("[肥皂]" "~/src/github/private-config/etc/weibo-emojis/d_feizao.png" ("FeiZao" "sina-weibo"))
        ("[照相机]" "~/src/github/private-config/etc/weibo-emojis/o_zhaoxiangji.png" ("ZhaoXiangJi" "sina-weibo"))
        ("[浪]" "~/src/github/private-config/etc/weibo-emojis/d_lang.png" ("Lang" "sina-weibo"))
        ("[沙尘暴]" "~/src/github/private-config/etc/weibo-emojis/w_shachenbao.png" ("ShaChenBao" "sina-weibo"))

        ("[笑哈哈]" "~/src/github/private-config/etc/weibo-emojis/lxh_xiaohaha.png" ("XiaoHaHa" "sina-weibo"))
        ("[好爱哦]" "~/src/github/private-config/etc/weibo-emojis/lxh_haoaio.png" ("HaoAiO" "sina-weibo"))
        ("[噢耶]" "~/src/github/private-config/etc/weibo-emojis/lxh_oye.png" ("OYe" "sina-weibo"))
        ("[偷乐]" "~/src/github/private-config/etc/weibo-emojis/lxh_toule.png" ("TouLe" "sina-weibo"))
        ("[泪流满面]" "~/src/github/private-config/etc/weibo-emojis/lxh_leiliumanmian.png" ("LeiLiuManMian" "sina-weibo"))
        ("[巨汗]" "~/src/github/private-config/etc/weibo-emojis/lxh_juhan.png" ("JuHan" "sina-weibo"))
        ("[抠鼻屎]" "~/src/github/private-config/etc/weibo-emojis/lxh_koubishi.png" ("KouBiShi" "sina-weibo"))
        ("[求关注]" "~/src/github/private-config/etc/weibo-emojis/lxh_qiuguanzhu.png" ("QiuGuanZhu" "sina-weibo"))
        ("[好喜欢]" "~/src/github/private-config/etc/weibo-emojis/lxh_haoxihuan.png" ("HaoXiHuan" "sina-weibo"))
        ("[崩溃]" "~/src/github/private-config/etc/weibo-emojis/lxh_bengkui.png" ("BengKui" "sina-weibo"))
        ("[好囧]" "~/src/github/private-config/etc/weibo-emojis/lxh_haojiong.png" ("HaoJiong" "sina-weibo"))
        ("[震惊]" "~/src/github/private-config/etc/weibo-emojis/lxh_zhenjing.png" ("ZhenJing" "sina-weibo"))
        ("[别烦我]" "~/src/github/private-config/etc/weibo-emojis/lxh_biefanwo.png" ("BieFanWo" "sina-weibo"))
        ("[不好意思]" "~/src/github/private-config/etc/weibo-emojis/lxh_buhaoyisi.png" ("BuHaoYiSi" "sina-weibo"))
        ("[羞嗒嗒]" "~/src/github/private-config/etc/weibo-emojis/lxh_xiudada.png" ("XiuDaDa" "sina-weibo"))
        ("[得意地笑]" "~/src/github/private-config/etc/weibo-emojis/lxh_deyidexiao.png" ("DeYiDeXiao" "sina-weibo"))
        ("[纠结]" "~/src/github/private-config/etc/weibo-emojis/lxh_jiujie.png" ("JiuJie" "sina-weibo"))
        ("[给劲]" "" ("GeiJing" "sina-weibo"))
        ("[悲催]" "~/src/github/private-config/etc/weibo-emojis/lxh_beicui.png" ("BeiCui" "sina-weibo"))
        ("[甩甩手]" "~/src/github/private-config/etc/weibo-emojis/lxh_shuaishuaishou.png" ("ShuaiShuaiShou" "sina-weibo"))

        ("[好棒]" "~/src/github/private-config/etc/weibo-emojis/lxh_haobang.png" ("HaoBang" "sina-weibo"))
        ("[瞧瞧]" "~/src/github/private-config/etc/weibo-emojis/lxh_qiaoqiao.png" ("QiaoQiao" "sina-weibo"))
        ("[不想上班]" "~/src/github/private-config/etc/weibo-emojis/lxh_buxiangshangban.png" ("BuXiangShangBan" "sina-weibo"))
        ("[困死了]" "~/src/github/private-config/etc/weibo-emojis/lxh_kunsile.png" ("KunSiLe" "sina-weibo"))
        ("[许愿]" "~/src/github/private-config/etc/weibo-emojis/lxh_xuyuan.png" ("XuYuan" "sina-weibo"))
        ("[丘比特]" "~/src/github/private-config/etc/weibo-emojis/lxh_qiubite.png" ("QiuBiTe" "sina-weibo"))
        ("[有鸭梨]" "~/src/github/private-config/etc/weibo-emojis/lxh_youyali.png" ("YouYaLi" "sina-weibo"))
        ("[想一想]" "~/src/github/private-config/etc/weibo-emojis/lxh_xiangyixiang.png" ("XiangYiXiang" "sina-weibo"))
        ("[躁狂症]" "~/src/github/private-config/etc/weibo-emojis/kuangzaozheng.png" ("ZaoKuangZheng" "sina-weibo"))
        ("[转发]" "~/src/github/private-config/etc/weibo-emojis/lxh_zhuanfa.png" ("ZhuanFa" "sina-weibo"))
        ("[互相膜拜]" "~/src/github/private-config/etc/weibo-emojis/lxh_xianghumobai.png" ("HuXiangMoBai" "sina-weibo"))
        ("[雷锋]" "~/src/github/private-config/etc/weibo-emojis/lxh_leifeng.png" ("LeiFeng" "sina-weibo"))
        ("[杰克逊]" "~/src/github/private-config/etc/weibo-emojis/lxh_jiekexun.png" ("JieKeXun" "sina-weibo"))
        ("[玫瑰]" "~/src/github/private-config/etc/weibo-emojis/lxh_meigui.png" ("MeiGui" "sina-weibo"))
        ("[hold住]" "~/src/github/private-config/etc/weibo-emojis/lxh_holdzhu.png" ("HOLDZhu" "sina-weibo"))
        ("[群体围观]" "~/src/github/private-config/etc/weibo-emojis/lxh_quntiweiguan.png" ("QunTiWeiGuan" "sina-weibo"))
        ("[推荐]" "~/src/github/private-config/etc/weibo-emojis/lxh_tuijian.png" ("TuiJian" "sina-weibo"))
        ("[赞啊]" "~/src/github/private-config/etc/weibo-emojis/lxh_zana.png" ("ZanA" "sina-weibo"))
        ("[被电]" "~/src/github/private-config/etc/weibo-emojis/lxh_beidian.png" ("BeiDian" "sina-weibo"))
        ("[霹雳]" "~/src/github/private-config/etc/weibo-emojis/lxh_pili.png" ("PiLi" "sina-weibo"))

        ("[微笑]" "~/src/github/private-config/etc/qq-emojis/smiley_0.png" ("WeiXiao" "[Smile]" "weixin-qq"))
        ("[撇嘴]" "~/src/github/private-config/etc/qq-emojis/smiley_1.png" ("PieZui" "[Grimace]" "weixin-qq"))
        ("[色]" "~/src/github/private-config/etc/qq-emojis/smiley_2.png" ("Se" "[Drool]" "weixin-qq"))
        ("[发呆]" "~/src/github/private-config/etc/qq-emojis/smiley_3.png" ("FaDai" "[Scowl]" "weixin-qq"))
        ("[得意]" "~/src/github/private-config/etc/qq-emojis/smiley_4.png" ("DeYi" "[CoolGuy]" "weixin-qq"))
        ("[流泪]" "~/src/github/private-config/etc/qq-emojis/smiley_5.png" ("LiuLei" "[Sob]" "weixin-qq"))
        ("[害羞]" "~/src/github/private-config/etc/qq-emojis/smiley_6.png" ("HaiXiu" "[Shy]" "weixin-qq"))
        ("[闭嘴]" "~/src/github/private-config/etc/qq-emojis/smiley_7.png" ("BiZui" "[Silent]" "weixin-qq"))
        ("[睡]" "~/src/github/private-config/etc/qq-emojis/smiley_8.png" ("Shui" "[Sleep]" "weixin-qq"))
        ("[大哭]" "~/src/github/private-config/etc/qq-emojis/smiley_9.png" ("DaKu" "[Cry]" "weixin-qq"))
        ("[尴尬]" "~/src/github/private-config/etc/qq-emojis/smiley_10.png" ("GanGa" "[Awkward]" "weixin-qq"))
        ("[发怒]" "~/src/github/private-config/etc/qq-emojis/smiley_11.png" ("FaNu" "[Angry]" "weixin-qq"))
        ("[调皮]" "~/src/github/private-config/etc/qq-emojis/smiley_12.png" ("DiaoPi" "[Tongue]" "weixin-qq"))
        ("[呲牙]" "~/src/github/private-config/etc/qq-emojis/smiley_13.png" ("CiYa" "[Grin]" "weixin-qq"))
        ("[惊讶]" "~/src/github/private-config/etc/qq-emojis/smiley_14.png" ("JingYa" "[Surprise]" "weixin-qq"))
        ("[难过]" "~/src/github/private-config/etc/qq-emojis/smiley_15.png" ("NanGuo" "[Frown]" "weixin-qq"))
        ("[酷]" "~/src/github/private-config/etc/qq-emojis/smiley_16.png" ("Ku" "[Ruthless]" "weixin-qq"))
        ("[冷汗]" "~/src/github/private-config/etc/qq-emojis/smiley_17.png" ("LengHan" "[Blush]" "weixin-qq"))
        ("[抓狂]" "~/src/github/private-config/etc/qq-emojis/smiley_18.png" ("ZhuaKuang" "[Scream]" "weixin-qq"))
        ("[吐]" "~/src/github/private-config/etc/qq-emojis/smiley_19.png" ("Tu" "[Puke]" "weixin-qq"))
        ("[偷笑]" "~/src/github/private-config/etc/qq-emojis/smiley_20.png" ("TouXiao" "[Chuckle]" "weixin-qq"))
        ("[可爱]" "~/src/github/private-config/etc/qq-emojis/smiley_21.png" ("KeAi" "[Joyful]" "weixin-qq"))
        ("[白眼]" "~/src/github/private-config/etc/qq-emojis/smiley_22.png" ("BaiYan" "[Slight]" "weixin-qq"))
        ("[傲慢]" "~/src/github/private-config/etc/qq-emojis/smiley_23.png" ("AoMan" "[Smug]" "weixin-qq"))
        ("[饥饿]" "~/src/github/private-config/etc/qq-emojis/smiley_24.png" ("JiE" "[Hungry]" "weixin-qq"))
        ("[困]" "~/src/github/private-config/etc/qq-emojis/smiley_25.png" ("Kun" "[Drowsy]" "weixin-qq"))
        ("[惊恐]" "~/src/github/private-config/etc/qq-emojis/smiley_26.png" ("JingKong" "[Panic]" "weixin-qq"))
        ("[流汗]" "~/src/github/private-config/etc/qq-emojis/smiley_27.png" ("LiuHan" "[Sweat]" "weixin-qq"))
        ("[憨笑]" "~/src/github/private-config/etc/qq-emojis/smiley_28.png" ("HanXiao" "[Laugh]" "weixin-qq"))
        ("[大兵]" "~/src/github/private-config/etc/qq-emojis/smiley_29.png" ("DaBing" "[Commando]" "weixin-qq"))
        ("[奋斗]" "~/src/github/private-config/etc/qq-emojis/smiley_30.png" ("FenDou" "[Determined]" "weixin-qq"))
        ("[咒骂]" "~/src/github/private-config/etc/qq-emojis/smiley_31.png" ("ZhouMa" "[Scold]" "weixin-qq"))
        ("[疑问]" "~/src/github/private-config/etc/qq-emojis/smiley_32.png" ("YiWen" "[Shocked]" "weixin-qq"))
        ("[嘘]" "~/src/github/private-config/etc/qq-emojis/smiley_33.png" ("Xu" "[Shhh]" "weixin-qq"))
        ("[晕]" "~/src/github/private-config/etc/qq-emojis/smiley_34.png" ("Yun" "[Dizzy]" "weixin-qq"))
        ("[折磨]" "~/src/github/private-config/etc/qq-emojis/smiley_35.png" ("Zhe:mo" "[Tormented]" "weixin-qq"))
        ("[衰]" "~/src/github/private-config/etc/qq-emojis/smiley_36.png" ("Shuai" "[Toasted]" "weixin-qq"))
        ("[骷髅]" "~/src/github/private-config/etc/qq-emojis/smiley_37.png" ("KuLou" "[Skull]" "weixin-qq"))
        ("[敲打]" "~/src/github/private-config/etc/qq-emojis/smiley_38.png" ("QiaoDa" "[Hammer]" "weixin-qq"))
        ("[再见]" "~/src/github/private-config/etc/qq-emojis/smiley_39.png" ("ZaiJian" "[Wave]" "weixin-qq"))
        ("[擦汗]" "~/src/github/private-config/etc/qq-emojis/smiley_40.png" ("CaHan" "[Speechless]" "weixin-qq"))
        ("[抠鼻]" "~/src/github/private-config/etc/qq-emojis/smiley_41.png" ("KouBi" "[NosePick]" "weixin-qq"))
        ("[鼓掌]" "~/src/github/private-config/etc/qq-emojis/smiley_42.png" ("GuZhang" "[Clap]" "weixin-qq"))
        ("[糗大了]" "~/src/github/private-config/etc/qq-emojis/smiley_43.png" ("QiuDaLe" "[Shame]" "weixin-qq"))
        ("[坏笑]" "~/src/github/private-config/etc/qq-emojis/smiley_44.png" ("HuaiXiao" "[Trick]" "weixin-qq"))
        ("[左哼哼]" "~/src/github/private-config/etc/qq-emojis/smiley_45.png" ("ZuoHengHeng" "[Bah ! L]" "weixin-qq"))
        ("[右哼哼]" "~/src/github/private-config/etc/qq-emojis/smiley_46.png" ("YouHengHeng" "[Bah ! R]" "weixin-qq"))
        ("[哈欠]" "~/src/github/private-config/etc/qq-emojis/smiley_47.png" ("HaQian" "[Yawn]" "weixin-qq"))
        ("[鄙视]" "~/src/github/private-config/etc/qq-emojis/smiley_48.png" ("BiShi" "[Pooh-pooh]" "weixin-qq"))
        ("[委屈]" "~/src/github/private-config/etc/qq-emojis/smiley_49.png" ("WeiQu" "[Shrunken]" "weixin-qq"))
        ("[快哭了]" "~/src/github/private-config/etc/qq-emojis/smiley_50.png" ("KuaiKuLe" "[TearingUp]" "weixin-qq"))
        ("[阴险]" "~/src/github/private-config/etc/qq-emojis/smiley_51.png" ("YinXian" "[Sly]" "weixin-qq"))
        ("[亲亲]" "~/src/github/private-config/etc/qq-emojis/smiley_52.png" ("QinQin" "[Kiss]" "weixin-qq"))
        ("[吓]" "~/src/github/private-config/etc/qq-emojis/smiley_53.png" ("He" "[Wrath]" "weixin-qq"))
        ("[可怜]" "~/src/github/private-config/etc/qq-emojis/smiley_54.png" ("KeLian" "[Whimper]" "weixin-qq"))
        ("[菜刀]" "~/src/github/private-config/etc/qq-emojis/smiley_55.png" ("CaiDao" "[Cleaver]" "weixin-qq"))
        ("[西瓜]" "~/src/github/private-config/etc/qq-emojis/smiley_56.png" ("XiGua" "[Watermelon]" "weixin-qq"))
        ("[啤酒]" "~/src/github/private-config/etc/qq-emojis/smiley_57.png" ("PiJiu" "[Beer]" "weixin-qq"))
        ("[篮球]" "~/src/github/private-config/etc/qq-emojis/smiley_58.png" ("LanQiu" "[Basketball]" "weixin-qq"))
        ("[乒乓]" "~/src/github/private-config/etc/qq-emojis/smiley_59.png" ("PingPang" "[PingPong]" "weixin-qq"))
        ("[咖啡]" "~/src/github/private-config/etc/qq-emojis/smiley_60.png" ("KaFei" "[Coffee]" "weixin-qq"))
        ("[饭]" "~/src/github/private-config/etc/qq-emojis/smiley_61.png" ("Fan" "[Rice]" "weixin-qq"))
        ("[猪头]" "~/src/github/private-config/etc/qq-emojis/smiley_62.png" ("ZhuTou" "[Pig]" "weixin-qq"))
        ("[玫瑰]" "~/src/github/private-config/etc/qq-emojis/smiley_63.png" ("MeiGui" "[Rose]" "weixin-qq"))
        ("[凋谢]" "~/src/github/private-config/etc/qq-emojis/smiley_64.png" ("DiaoXie" "[Wilt]" "weixin-qq"))
        ("[示爱]" "~/src/github/private-config/etc/qq-emojis/smiley_65.png" ("ShiAi" "[Lips]" "weixin-qq"))
        ("[爱心]" "~/src/github/private-config/etc/qq-emojis/smiley_66.png" ("AiXin" "[Heart]" "weixin-qq"))
        ("[心碎]" "~/src/github/private-config/etc/qq-emojis/smiley_67.png" ("XinSui" "[BrokenHeart]" "weixin-qq"))
        ("[蛋糕]" "~/src/github/private-config/etc/qq-emojis/smiley_68.png" ("DanGao" "[Cake]" "weixin-qq"))
        ("[闪电]" "~/src/github/private-config/etc/qq-emojis/smiley_69.png" ("ShanDian" "[Lightning]" "weixin-qq"))
        ("[炸弹]" "~/src/github/private-config/etc/qq-emojis/smiley_70.png" ("ZhaDan" "[Bomb]" "weixin-qq"))
        ("[刀]" "~/src/github/private-config/etc/qq-emojis/smiley_71.png" ("Dao" "[Dagger]" "weixin-qq"))
        ("[足球]" "~/src/github/private-config/etc/qq-emojis/smiley_72.png" ("ZuQiu" "[Soccer]" "weixin-qq"))
        ("[瓢虫]" "~/src/github/private-config/etc/qq-emojis/smiley_73.png" ("PiaoChong" "[Ladybug]" "weixin-qq"))
        ("[便便]" "~/src/github/private-config/etc/qq-emojis/smiley_74.png" ("BianBian" "[Poop]" "weixin-qq"))
        ("[月亮]" "~/src/github/private-config/etc/qq-emojis/smiley_75.png" ("YueLiang" "[Moon]" "weixin-qq"))
        ("[太阳]" "~/src/github/private-config/etc/qq-emojis/smiley_76.png" ("TaiYang" "[Sun]" "weixin-qq"))
        ("[礼物]" "~/src/github/private-config/etc/qq-emojis/smiley_77.png" ("LiWu" "[Gift]" "weixin-qq"))
        ("[拥抱]" "~/src/github/private-config/etc/qq-emojis/smiley_78.png" ("YongBao" "[Hug]" "weixin-qq"))
        ("[强]" "~/src/github/private-config/etc/qq-emojis/smiley_79.png" ("Qiang" "[Strong]" "weixin-qq"))
        ("[弱]" "~/src/github/private-config/etc/qq-emojis/smiley_80.png" ("Ruo" "[Weak]" "weixin-qq"))
        ("[握手]" "~/src/github/private-config/etc/qq-emojis/smiley_81.png" ("WoShou" "[Shake]" "weixin-qq"))
        ("[胜利]" "~/src/github/private-config/etc/qq-emojis/smiley_82.png" ("ShengLi" "[Peace]" "weixin-qq"))
        ("[抱拳]" "~/src/github/private-config/etc/qq-emojis/smiley_83.png" ("BaoQuan" "[Fight]" "weixin-qq"))
        ("[勾引]" "~/src/github/private-config/etc/qq-emojis/smiley_84.png" ("GouYin" "[Beckon]" "weixin-qq"))
        ("[拳头]" "~/src/github/private-config/etc/qq-emojis/smiley_85.png" ("QuanTou" "[Fist]" "weixin-qq"))
        ("[差劲]" "~/src/github/private-config/etc/qq-emojis/smiley_86.png" ("ChaJing" "[Pinky]" "weixin-qq"))
        ("[爱你]" "~/src/github/private-config/etc/qq-emojis/smiley_87.png" ("AiNi" "[RockOn]" "weixin-qq"))
        ("[NO]" "~/src/github/private-config/etc/qq-emojis/smiley_88.png" ("NO" "[NO]" "weixin-qq"))
        ("[OK]" "~/src/github/private-config/etc/qq-emojis/smiley_89.png" ("OK" "[OK]" "weixin-qq"))
        ("[爱情]" "~/src/github/private-config/etc/qq-emojis/smiley_90.png" ("AiQing" "[InLove]" "weixin-qq"))
        ("[飞吻]" "~/src/github/private-config/etc/qq-emojis/smiley_91.png" ("FeiWen" "[Blowkiss]" "weixin-qq"))
        ("[跳跳]" "~/src/github/private-config/etc/qq-emojis/smiley_92.png" ("TiaoTiao" "[Waddle]" "weixin-qq"))
        ("[发抖]" "~/src/github/private-config/etc/qq-emojis/smiley_93.png" ("FaDou" "[Tremble]" "weixin-qq"))
        ("[怄火]" "~/src/github/private-config/etc/qq-emojis/smiley_94.png" ("OuHuo" "[Aaagh]" "weixin-qq"))
        ("[转圈]" "~/src/github/private-config/etc/qq-emojis/smiley_95.png" ("ZhuanQuan" "[Twirl]" "weixin-qq"))
        ("[磕头]" "~/src/github/private-config/etc/qq-emojis/smiley_96.png" ("KeTou" "[Kotow]" "weixin-qq"))
        ("[回头]" "~/src/github/private-config/etc/qq-emojis/smiley_97.png" ("HuiTou" "[Dramatic]" "weixin-qq"))
        ("[跳绳]" "~/src/github/private-config/etc/qq-emojis/smiley_98.png" ("TiaoSheng" "[JumpRope]" "weixin-qq"))
        ("[挥手]" "~/src/github/private-config/etc/qq-emojis/smiley_99.png" ("HuiShou" "[Surrender]" "weixin-qq"))
        ("[激动]" "~/src/github/private-config/etc/qq-emojis/smiley_100.png" ("JiDong" "[Exciting]" "weixin-qq"))
        ("[街舞]" "~/src/github/private-config/etc/qq-emojis/smiley_101.png" ("JieWu" "[HipHot]" "weixin-qq"))
        ("[献吻]" "~/src/github/private-config/etc/qq-emojis/smiley_102.png" ("XianWen" "[ShowLove]" "weixin-qq"))
        ("[左太极]" "~/src/github/private-config/etc/qq-emojis/smiley_103.png" ("ZuoTaiJi" "[Tai Chi L]" "weixin-qq"))
        ("[右太极]" "~/src/github/private-config/etc/qq-emojis/smiley_104.png" ("YouTaiJi" "[Tai Chi R]" "weixin-qq"))

        ))

(defvar emoji-hash-table (make-hash-table :test 'equal) "The hash table for emojis.")
(defvar emoji-names () "The names of the emojis.")

(while emojis-string-list
  (let ((key (string-join (caddar emojis-string-list) " "))
        (png (cadar emojis-string-list))
        (val (caar emojis-string-list)))
    (unless (string= png "")
      (add-text-properties
       (progn (string-match ".* " key) (match-end 0))
       (length key)
       `(display ,(create-image png))
       key))
    (puthash key val emoji-hash-table)
    (setq emoji-names (cons key emoji-names)))
  (setq emojis-string-list (cdr emojis-string-list)))

(defvar emoji-history nil "History of emojis")
(defun enter-emoji ()
  "Let the user input an emoji interactively"
  (interactive)
  (let ((key (completing-read "Enter your emoji: " emoji-names nil t nil emoji-history)))
    (insert (gethash key emoji-hash-table))))

(provide 'emojis)
;;; emojis.el ends here
