.\" beagle-ping(1) manpage
.\"
.TH BEAGLE "1" "Mar 2007" "beagle-ping" ""
.SH NAME
beagle-ping
.SH SYNOPSIS
.B beagle-ping
.SH DESCRIPTION
.PP
.BR beagle-ping 
prints the version number of the beagle-daemon. It is identical to 
.BR beagle-info 
.BR --daemon-version
.PP
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagled (1),
.BR beagle-info (1),
.BR http://beagle-project.org
