.\" beagrep-ping(1) manpage
.\"
.TH BEAGREP "1" "Mar 2007" "beagrep-ping" ""
.SH NAME
beagrep-ping
.SH SYNOPSIS
.B beagrep-ping
.SH DESCRIPTION
.PP
.BR beagrep-ping 
prints the version number of the beagrep-daemon. It is identical to 
.BR beagrep-info 
.BR --daemon-version
.PP
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagrepd (1),
.BR beagrep-info (1),
.BR http://beagrep-project.org
