#!/bin/bash

# This line will be automatically uncommented when you "make install"
#installed=1

if [ -z $installed ]; then
    CMD="./beagle-info"
else
    CMD="beagle-info"
fi

exec -a beagle-index-info $CMD --index-info
