.\" beagle-index-info(8) manpage
.\"
.\" Copyright (C) 2004-2007 Novell, Inc.
.\"
.TH BEAGLE-INDEX-INFO "8" "14 Mar 2007"
.SH NAME
beagle-index-info
.SH SYNOPSIS
.B beagle-index-info 
.SH DESCRIPTION
.PP
Display statistics of the Beagle indexes. Identical to 
.B beagle-info --index-info
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagled (1),
.BR beagle-index-info(1),
.BR http://beagle-project.org
