.\" beagle-shutdown(1) manpage
.\"
.\" Copyright (C) 2005 Novell, Inc.
.\"
.TH BEAGLE-SHUTDOWN "1" "Feb 2005" "beagle" "Linux User's Manual"
.SH NAME
beagle-shutdown \- cleanly shutdown the Beagle daemon
.SH SYNOPSIS
.B beagle-shutdown
.SH DESCRIPTION
.PP
.BR beagle-shutdown
is used to cleanly shutdown and terminate
.BR beagled (1),
the Beagle daemon. You should use this utility instead of manually killing the
daemon, as this ensures that
.BR beagled
is in a consistent state before terminating.
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2005 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagled (1),
.BR beagle-query (1),
.BR beagle-status (1),
