#!/bin/bash
start_dir=~/.cache/for-code-reading/"$(readlink -f "$PWD")"
# echo Starting at $start_dir 1>&2
while test ! -d "$start_dir"/.beagrep -a "$start_dir" != /
do
    start_dir=${start_dir%/*}
done

if test "$start_dir" = / -o "$start_dir" = $HOME
then
    start_dir=`readlink -f ~/.gtags-dir`
fi

beagrep_dir=$start_dir/.beagrep
echo Beagrep index found at "$beagrep_dir" 1>&2

function wlp() {
    case $(uname) in
	CYGWIN*)
	    cygpath -alm "$1"
	    ;;
	*)
	    readlink -m "$1"
	    ;;
    esac
}

tokens_str=$1
shift
additional_tokens=$(echo "$@")

tokens=`beagrep-get-tokens "$tokens_str"`
if test "$FIND_FILE_ONLY"; then
    tokens=$(echo -n " $tokens" | perl -npe 's/\s+/ filename:/g; s/(^ *| filename:$)//g')
    mkdir -p ~/.logs
    echo $tokens > ~/.logs/$(basename $0).log
fi

tokens="$tokens $additional_tokens"
for x in "$beagrep_dir" `cat $beagrep_dir/../.beagrep-brothers 2>/dev/null`
do 
    beagrep-static-query \
        --add-static-backend "$(wlp "$x")" \
        --backend none --max-hits 100000 "$tokens" | \
        beagrep-unurl.pl|grep -v '#'|sort -u
done
echo /dev/null
