.\" beagrep-settings(1) manpage
.\"
.\" Copyright (C) 2004-2007 Novell, Inc.
.\"
.TH BEAGREP-SETTINGS "1" "14 Mar 2007"
.SH NAME
beagrep-settings
.SH SYNOPSIS
.B beagrep-settings
.SH DESCRIPTION
.PP
A graphical interface to control settings of the Beagrep search system. For more information, see the man page for 
.B beagrep-config
(the command-line tool to control Beagrep settings)
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagrepd (1),
.BR beagrep-config (1),
.BR beagrep-search (1),
.BR http://beagrep-project.org
