.\" beagle-info(1) manpage
.\"
.\" Copyright (C) 2004-2007 Novell, Inc.
.\" Copyright (C) 2008 D Bera <dbera.web@gmail.com>
.\"
.TH BEAGLE "1" "15 Mar 2007" "beagle-info" ""
.SH NAME
beagle-info
.SH SYNOPSIS
.B beagle-info
[\fIoptions\fR] 
.SH DESCRIPTION
.PP
.BR beagle-info 
displays information about Beagle
.SH OPTIONS
.SS Information about the currently running Beagle daemon.
Beagle daemon should be running for these options.
.BR beagle-info
takes the following options:
.TP
.B --daemon-version
Print the version of the running daemon.
.TP
.B --status
Display status of the running daemon.
.TP
.B --index-info
Display statistics of the Beagle indexes.
.TP
.B --is-indexing
Display whether the indexer is currently active.
.TP
.B --all-info
Display all of the above information.
.SS Other information
Beagle daemon need not be running for these options.
.TP
.B --list-backends
List the currently available backends.
.TP
.B  --list-filters
List the currently available filters.
.TP
.B  --list-static-indexes
List the available static indexes.
.TP
.B  --help
Print a summary of command-line options.
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc., \(co 2008 D Bera.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagled (1),
.BR beagle-index-info (8),
.BR beagle-ping (1),
.BR beagle-status (1),
.BR http://beagle-project.org
