#!/bin/bash

# This line will be automatically uncommented when you "make install"
#installed=1

if [ -z $installed ]; then
    CMD="./beagrep-info"
else
    CMD="beagrep-info"
fi

exec -a beagrep-index-info $CMD --index-info
