#!/usr/bin/env perl

for (@ARGV) {
    $_ =~ s/\\./ /g; # get rid of escaped items like \b in "\bhello\b", so that "hello" is used.
    @tokens = (@tokens, $_);
}

$tokens = join(" ", @tokens);

if ($ENV{SOURCECODETAGSMODE} eq "true") {
    $tokens =~ s/\.\*/*/g;
} else {
    use String::ShellQuote;
    $tokens = shell_quote($tokens);

    $tokens = qx/beagrep-break-words $tokens/;
}


$tokens =~ s/\r|\n/ /g;
#$tokens =~ s/\b/*/g;
if (@tokens == 1 and $tokens[0] !~ m/\s|\*/) {
    $tokens = "\"$tokens\"";
}
print "$tokens\n";



# appended_comma = True
