#!/usr/bin/env perl

use Getopt::Long;
use strict;
use String::ShellQuote;

my $pat = '';
my $pathpat = '.';
my $additional_tokens = '';
my $pathdeny = '^$';
chomp(my $pwd =qx/pwd/);
my $pwd_pat='no such componet';
my $list_beagrep;

my $ignore_case;
my $find_file_only = 0;
my $file_default_line = 1;
my $file_tag = "";
my $grep_use_perl_regexp;

open(my $log, ">>", glob("~/.beagrep.log")) or die "Error openning log";
print $log "$0 @ARGV in " . $ENV{PWD} . "\n";

my $grep_add_opts = "";
GetOptions(
    "a=s" => \$additional_tokens,
    "e=s" => \$pat,
    "p=s" => \$pathpat,
    "perl=s" => \$grep_use_perl_regexp,
    "grep=s" => \$grep_add_opts,
    "v=s" => \$pathdeny,
    "d=s" => \$pwd_pat,
    "i!" => \$ignore_case,
    "f!" => \$find_file_only,
    "l!" => \$list_beagrep,
    );

if ($ignore_case) {
  $ignore_case = '-i';
} else {
  $ignore_case = '';
}

if ($grep_use_perl_regexp) {
    $grep_use_perl_regexp = '-P';
} else {
    $grep_use_perl_regexp = '';
}


die 'no regexp specified' unless $pat;
$pwd =~ s!($pwd_pat.*?)/.*!$1!; 
chdir $pwd or die "$pwd: $!";

my $pat_save = $pat;

if ($find_file_only) {
  $ENV{FIND_FILE_ONLY} = 1;
  if ($pat =~ m/:([0-9]+)$/) {
      $file_default_line = $1;
      $pat = substr($pat, 0, rindex($pat, ':'));
      if ($pat =~ m/(.*)\(/) {
          $file_tag = $1;
          $pat = substr($pat, index($pat, '(') + 1);
      }
      $pat_save = $pat;
  }
  $pat =~ s,.*/,,; #beagrep can only find a filename, not a path name.
  $pat_save = $pat;
}

$pat_save =~ s/\\//g; #if it's a path name, it's unlikely to have `\' in it, maybe added by .emacs


$pat = shell_quote($pat);
print "pat is: $pat.\n";

print "beagrep query argument `[01;31m"
  . substr(qx/beagrep-get-tokens $pat/, 0, -1) 
  . "[0m'\n";

my $beagrep_files = qx/beagrep-files $pat $additional_tokens/;
my @beagrep_files = split(/\n/, $beagrep_files);

if ($list_beagrep) {
  for (@beagrep_files) {
    print "$_:$file_default_line: [01;31m****************![0m\n";
  }
  exit 0;
}

if (!$find_file_only) {
  open(my $grep, "|xargs -d '\\n' grep -H -n -I $ignore_case $grep_add_opts $grep_use_perl_regexp -e $pat");

  for (@beagrep_files) {
    next unless m/$pathpat/i;
    next if m/$pathdeny/i;
    print $grep "$_\n";
  }
  close $grep;
}

#see [[http://baohaojun.wordpress.com/2010/05/06/beagrep-grep-sh%E5%8A%9F%E8%83%BD%E5%8F%88%E5%8F%98%E5%BC%BA%E5%A4%A7%E4%BA%86/]] for why
if ($find_file_only || 1) {
    my %set;
    for (@beagrep_files) {
        $set{$_} = 1 if m/$pat_save/i and m/$pathpat/i;
    }
    if ($find_file_only && keys %set > 1 && $file_tag) {
        my $files = qx(grep-gtags -e $file_tag|perl -ne "if (m/:[0-9]+:/) {s/:[0-9]+:.*//; print}"|sort -u);
        my @files = split("\n", $files);
        for (@files) {
            print "$_:$file_default_line: [01;31m****************![0m\n" 
                if $set{$_} and m,/$pat_save$,; # the `and' part is to make file name match totally
        }
    } else {
        for (@beagrep_files) {
            print "$_:$file_default_line: [01;31m****************![0m\n" if $set{$_};
        }
    }
}
