* TODO 失眠

小的时候，正睡着的时候，会突然一个高空坠落一样的惊醒，像一脚踩空一样，据说是你的身体在提醒你，别睡了，再睡下去可能一不小心死掉了。感兴趣的同学可以看一下知乎 https://zhuanlan.zhihu.com/p/37377052，据说这种现象叫「肌抽跃」。

这个现象对我来说，我发现其实除了有点儿吓人之外，也是一种惊喜，吓完了发现「哇，太好了，没事儿没事儿」。然后，很快就能继续睡着，并且睡得还挺香的。

然而最近两年，出现了一种更可怕的现象，不是全身猛抖一下，只是在脑子里突然猛地一下；也不是在熟睡的时候，而是在将睡未睡的时候（一般发生在严重熬夜之后），脑子里好像有个什么东西突然「熔断」了一样。

我怀疑这个现象的功能跟「肌抽跃」是类似的，就是提醒你不能睡了，再睡下去可能要死掉的。我姑且将其称之为「脑抽跃」吧。

所不同的是，发生肌抽跃之后，你会有一些小开心，「没事儿没事儿」，继续睡。发生脑抽跃之后，想要睡着就非常困难了，因为这时候你真的很相信自己有可能会猝死死掉（因为严重熬夜的缘故）。

妈的，简直跟满清十大酷刑里有一种不让人睡觉的酷刑一样，非常痛苦，有没有。本来已经困得要死，觉得再不睡可能要猝死；结果好不容易快睡着的时候，身体给你发一个信号「不许睡！睡着了可能就会死！」。。。人到中年，竟然会有这种事，这个真的是我年轻的时候没有预料到的。

我已经下定了决心，一定要解决这个问题。最好的办法，当然是早睡早起，养成良好的生活习惯。

其次，在偶尔熬夜、失眠的时候，怎么办呢，嗯，这个是我重点想跟大家分享的，就是我最近突然发现一种很养生的失眠处理方案。

故事是这样的，有一天晚上，我又失眠了，然后就开始自助促眠，使用的方法是腹式呼吸法（练瑜珈的朋友应该都听说过）。这个方法很简单，就是吸气的时候，把肚子鼓起来；呼气的时候，通过收缩腹肌把肚子缩进去。

就在这一呼一吸之间，我突然发现，腹肌收缩到极限的时候，我的菊花也会下意识地一紧。然后这个灵感像闪电一样击中了我：腹式呼吸+凯格尔运动！

我的促进睡眠的新办法，是这样的：

1. 深深地吸气，肚子鼓起来
2. 深深地呼气，肚子瘪下去，收缩腹肌
3. 腹肌收缩到极限的时候，主动缩紧一下肛门括约肌（俗称「提肛」运动）

简而言之，一吸，一呼，一紧。

这个方法的好处很多，简直妙不可言，各位有类似困扰的中年男性朋友，你不妨试一试，以后说不定会感谢我的。

首先，单纯的腹式呼吸，根据我的验验，效果不是特别理想，脑子里还是会胡思乱想，天马行空，最后说不定又给你来一个「脑抽跃」。

加上凯格尔运动之后，因为整套动作变得更复杂了，脑子里真的基本上不会再有别的想法。

过了没一会，我就困了，沉沉地睡去了，带着一些对未来美好生活的展望[憨笑]。
