#!/usr/bin/env bash
set -e


declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # s:source-dir r:repo-key t:target-dir p:properties
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o p:r:s:t:h \
                      --long properties:,repo-key:,source-dir:,target-dir:,help \
                      -n $(basename -- $0) -- "$@")
declare properties=
declare repo_key=
declare source_dir=
declare target_dir=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -p|--properties)
            properties=$2
            shift 2

            ;;
        -r|--repo-key)
            repo_key=$2
            shift 2

            ;;
        -s|--source-dir)
            source_dir=$2
            shift 2

            ;;
        -t|--target-dir)
            target_dir=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %6s '-p, '
            printf %-24s '--properties=PROPERTIES'
            echo
            printf %6s '-r, '
            printf %-24s '--repo-key=REPO_KEY'
            echo
            printf %6s '-s, '
            printf %-24s '--source-dir=SOURCE_DIR'
            echo
            printf %6s '-t, '
            printf %-24s '--target-dir=TARGET_DIR'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

source $scm_tools_topdir/.venv/bin/activate
export ARTIFACTORY_WEB_SCHEMA=https://
export ARTIFACTORY_API_USER_PASSWORD=$(
    git config -f $scm_secrets_conf ldap.${ARTIFACTORY_API_USER}.password
       )

python ${scm_tools_topdir}/artifactory_utils/deploy2artifactory.py upload-folder \
               -s "${source_dir}" \
               -r "$repo_key" \
               -t "$target_dir" \
               -p "$properties" \
               -d
