#!/bin/bash
set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}

# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # u:dir-url d:mirror-to-dir
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o u:d:h \
                      --long dir-url:,mirror-to-dir:,help \
                      -n $(basename -- $0) -- "$@")
declare dir_url=
declare mirror_to_dir=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -u|--dir-url)
            dir_url=$2
            shift 2

            ;;
        -d|--mirror-to-dir)
            mirror_to_dir=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-u, '
            printf %-24s '--dir-url=DIR_URL'
            echo
            printf %06s '-d, '
            printf %-24s '--mirror-to-dir=MIRROR_TO_DIR'
            echo
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

# url is like ${scm_artifactory_url}artifactory/REPO-KEY/PATH

api_url=$(
    echo "${dir_url}" | perl -pe 's,(/artifactory/),${1}api/storage/,'
       )

my-curl() {
    curl -f -s -u ${scm_artifactory_user}:$(git config -f $scm_secrets_conf ldap.${scm_artifactory_user}.password) "$@"
}

json=$(
    my-curl "${api_url}"
    )

IFS=$'\n'
children=(
    $(
        echo "${json}" | jq '.children|.[] | "\(.folder):\(.uri)"' -r
    )
)
for c in "${children[@]}"; do
    uri_name=${c#*:}
    is_dir=${c%%:*}
    sub_url=${dir_url%/}${uri_name}
    target_name=${mirror_to_dir}/${uri_name}
    if test "${is_dir}" = true; then
        mkdir -p "${target_name}"
        log "download subdir: '${sub_url}'"
        artifactory mirror-dir -u "$sub_url" -d "${target_name}"
    else
        log download file: ${sub_url}
        my-curl "${sub_url}" -o "${target_name}"
    fi
done
