#!/usr/bin/env bash
set -e

if [[ $1 =~ / ]]; then
    url=$1
    shift
    if ! [[ $url =~ :// ]]; then
        url=${scm_artifactory_url}artifactory/${url#/}
    fi
    url=$(echo "$url" | urlify)
    set -- "$url" "$@"
fi

curl-f -s -u "${scm_artifactory_user}:${scm_artifactory_password:-$(git config -f $scm_secrets_conf ldap.${scm_artifactory_user}.password)}" "$@"
