#!/usr/bin/env bash
set -e

if [[ $1 =~ / ]] && ! [[ $1 =~ ^(${scm_artifactory_url}|${scm_artifactory_url%/}:443/) ]]; then
    url=${scm_artifactory_url}artifactory/${1#/}
    shift
    set -- "$url" "$@"
fi

curl-f -s -u "${scm_artifactory_user}:${scm_artifactory_password:-$(git config -f $scm_secrets_conf ldap.${scm_artifactory_user}.password)}" "$@"
