#!/usr/bin/env bash

set -e

declare comment_doc=$(
    cat <<'EOFe9576f8668e0' | grep -v '#.*org-mode%'
# {%org-mode%}
gr rest [-a] ACCESS-POINT [--] [EXTRA_ARGS_TO_CURL...]
# {%/org-mode%}
EOFe9576f8668e0
        )

## start code-generator "^\\s *#\\s *"
# generate-getopt -P '?"${comment_doc}"' \
    # a:access-point '?"Specify which rest api to call"'
## end code-generator
## start generated code
TEMP=$(POSIXLY_CORRECT=true getopt -o a:h \
                      --long access-point:,help \
                      -n $(basename -- $0) -- "$@")
declare access_point=
eval set -- "$TEMP"
while true; do
    case "$1" in

        -a|--access-point)
            access_point=$2
            shift 2

            ;;
        -h|--help)
            set +x
            echo -e "${comment_doc}"
            echo
            echo Options and arguments:
            printf %06s '-a, '
            printf %-24s '--access-point=ACCESS_POINT'
            echo
            printf "%30s" ""
            echo "Specify which rest api to call"
            exit
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            die "internal error: $(. bt; echo; bt | indent-stdin)"
            ;;
    esac
done


## end generated code

if test -z "${access_point}"; then
    access_point=$1
    shift
fi

if test -z "${access_point}"; then
    die "Must specify the access ponit!"
fi

if [[ $access_point =~ :// ]]; then
    a_url=$access_point
else

    if ! [[ $access_point =~ /($|\?) ]]; then
        access_point=${access_point}/
    fi

    a_url="${scm_artifactory_url}artifactory/${access_point#/}"
fi

artifactory my-curl "$a_url"
