// Obtained from a tab separated file by
// cat propertylist | sed "s_^\([^/]\)\([^ \t]*\)[ \t]*\(.*\)_'\1\2': '\3',_"

PropertyNameTable = {
// Cafeful: if property names are repeated, the last one stays
// General beagle
'beagle:FileType': 'File type',
'beagle:HitType': 'Result type',
'beagle:IsChild': '',
'beagle:Source': 'Backend',
'beagle:MimeType': 'Mimetype',
'beagle:SplitFilename': '',
'beagle:ExactFilename': 'Filename',
'beagle:Filename': '',
'beagle:FilenameExtension': '',
'beagle:NoPunctFilename': '',
'beagle:NoContent': '',
'beagle:InternalUri': '',
'beagle:ParentDirUri': 'Parent dir',
'fixme:filesize': '',
// FilterAbiword.cs
'fixme:appname': 'Creating application',
'dc:description': 'Description',
'fixme:keywords': 'Keywords',
'dc:relation': 'Relation',
'dc:rights': 'Copyright',
'dc:source': 'Source',
'dc:contributor': 'Contributor',
'dc:subject': 'Subject',
'dc:creator': 'Author',
'dc:coverage': 'Coverage',
'dc:type': 'Type',
'dc:language': 'Language',
'dc:title': 'Title',
'dc:publisher': 'Publisher',
// FilterArchive
'fixme:inside_archive': 'Archive content',
'fixme:relativeuri': '',
'fixme:comment': 'Comment',
// FilterBmp
'exif:Planes': 'EXIF planes',
'exif:Compression': 'EXIF compression',
'exif:XResolution': 'X Resolution',
'exif:YResolution': 'Y Resolution',
'exif:NumberOfColors': 'Number of colours',
'exif:ImportantColors': 'Important colours',
// FilterDeb
'fixme:arch': 'Architecture',
'fixme:depends': 'Depends on package',
'fixme:recommend': 'Recommended package',
'fixme:conflict': 'Conflict with package',
'fixme:replaces': 'Replaces package',
'fixme:provides': 'Package provides',
'fixme:size': 'Size',
// FilterDesktop
'fixme:Icon': 'Icon',
'fixme:Exec': 'Executable',
'fixme:Name': 'Name',
'fixme:Comment': 'Comment',
'fixme:Categories': 'Categories',
'fixme:Type': 'Type',
'fixme:Keywords': 'Keywords',
'fixme:X-KDE-Keywords': 'KDE Keywords',
// FilterDocbook
'fixme:id': '',
'fixme:base_title': 'Docbook base title',
'fixme:language': 'Language',
'fixme:parent_id': '',
'fixme:parent_title': 'Docbook parent title',
// FilterDOC
'fixme:word-count': 'Number of words',
'fixme:page-count': 'Number of pages',
// FilterEbuild
'fixme:install_time': 'Installation date',
'fixme:desktop_file': 'Desktop file name',
'fixme:contents_byte_count': 'Number of bytes',
'fixme:contents_file_count': 'Number of files',
'fixme:contents_dir_count': 'Number of directories',
// FilterGif
'gif:version': 'GIF version',
'gif:loopcount': 'Number of repetitions',
'gif:numframes': 'Number of frames',
// FilterImage
'fixme:width': 'Width',
'fixme:height': 'Height',
'fixme:depth': 'Depth',
'fspot:IsIndexed': 'Present in F-Spot',
'fspot:Description': 'F-Spot description',
'fspot:Tag': 'F-Spot tag',
'image:tag': '',
'digikam:IsIndexed': 'Present in Digikam',
'digikam:caption': 'Digikam caption',
'digikam:Tag': 'Digikam tag',
'exif:Model': 'Camera model',
'fixme:license': 'License',
// FilterJpeg
'jfif:Comment': 'JFIF comment',
'exif:UserComment': 'EXIF comment',
'exif:ImageDescription': 'Image description',
'exif:PixelXDimension': 'Width in pixels',
'exif:PixelYDimension': 'Height in pixels',
'exif:ISOSpeedRatings': 'ISO speed rating',
'exif:ShutterSpeedValue': 'Shutter speed',
'exif:ExposureTime': 'Exposure time',
'exif:FNumber': 'F-Number',
'exif:ApertureValue': 'Aperture',
'exif:FocalLength': 'Lens focal length',
'exif:Flash': 'Flash',
'exif:DateTime': 'Image date',
'iptc:location': 'IPTC location',
'iptc:caption': 'IPTC caption',
'iptc:keyword': 'IPTC keyword',
// FilterKAddressBook
'vCard:PREFEMAIL': 'Preferred email',
'vCard:EMAIL': 'Email',
'vCard:FN': 'Fullname',
'vCard:NICKNAME': 'Nickname',
'vCard:BDAY': 'Birthday',
'vCard:TITLE': 'Title',
'vCard:ROLE': 'Role',
'vCard:CATEGORIES': 'Categories',
'vCard:NAME': 'Name',
'vCard:NOTE': 'Notes',
'dc:date': '',
'vCard:CLASS': 'Class',
'vCard:UID': '',
'vCard:TEL': 'Telephone number',
'vCard:TEL:WORK': 'Work telephone number',
'vCard:TEL:HOME': 'Residence telephone number',
'vCard:TEL:CELL': 'Cell phone number',
'vCard:URL': 'Homepage',
// FilterKNotes
'fixme:priority': 'Priority',
'fixme:class': 'Class',
'fixme:uid': '',
// FilterKopeteLog
'fixme:client': 'Application',
'fixme:protocol': 'Protocol',
'fixme:identity': 'IM Identity',
'fixme:speakingto': 'Chatting with',
// FilterKOrganizer
'fixme:created': 'Creation date',
'fixme:duetime': 'Due date',
'fixme:starttime': 'Start date',
'fixme:enddate': 'End date',
// FilterMail - if parent:fixme:hasAttachments, add parent: in front of all of these
'fixme:date': 'Date',
'fixme:to': 'Receipient',
'fixme:to_address': 'Recpt Address',
'fixme:to_name': 'Recpt Name',
'fixme:cc': 'CC list',
'fixme:cc_address': 'CC address',
'fixme:cc_name': 'CC names',
'fixme:from': 'Sender',
'fixme:from_address': 'Sender address',
'fixme:from_name': 'Sender name',
'fixme:hasAttachments': 'Has attachment',
'fixme:msgid': '',
'fixme:reference': '',
'fixme:mlist': 'Mailing list',
'fixme:attachment_title': 'Attachment title',
'fixme:isSent': '',
// FilterMonodoc
'fixme:name': 'Name',
// FilterMPlayerVideo
'dc:copyright': 'Copyright',
'fixme:video:codec': 'Video codec',
'fixme:audio:codec': 'Audio codec',
'fixme:video:container': 'Video container',
'fixme:video:aspect': 'Aspect ratio',
'fixme:video:width': 'Video width',
'fixme:video:height': 'Video height',
'fixme:video:fps': 'Videp FPS',
'dc:extent': 'Duration',
'fixme:audio:channel_setup': 'Audio channel type',
'fixme:audio:channels': 'Audio channels',
// FilterMusic
'fixme:album': 'Album',
'fixme:artist': 'Artist',
'fixme:performer': 'Performer',
'fixme:composer': 'Composer',
'fixme:genre': 'Genre',
'fixme:tracknumber': 'Track number',
'fixme:trackcount': 'Track count',
'fixme:discnumber': 'Disc number',
'fixme:disccount': 'Disc count',
'fixme:year': 'Year',
'fixme:bitrate': 'Bitrate',
'fixme:samplerate': 'Sampling rate',
'fixme:channels': 'Audio channels',
'fixme:duration': 'Duration',
// FilterOle
'fixme:author': 'Author',
'fixme:last-saved-by': 'Last saved by',
'fixme:generator': 'Creating application',
'fixme:template': 'Template name',
'fixme:company': 'Company',
'fixme:category': 'Category',
// FilterOpenOffice
'fixme:slide-count': 'Number of slides',
'fixme:spreadsheet-count': 'Number of tables/sheets',
// FilterPackage
'fixme:version': 'Version',
'pkg:group': 'Package group',
// FilterPng
'fixme:colortype': 'Colourspace',
'fixme:hasalpha': 'Has alpha channels',
'png:description': 'Description',
'png:comment': 'Comment',
// FilterScribus
'fixme:scribus-version': 'Scribus version',
'fixme:pagecount': 'Number of pages',
// FilterTiff
'exif:DateTimeOriginal': 'Original date',
'exif:DateTimeDigitized': 'Digization date',
// KMailIndexer.cs
'fixme:client': 'Application',
'fixme:account': 'Account',
'fixme:folder': 'Mail folder'
};
