* DONE firemacs: pressing SPC to goto the next page does not work reliably, use separate keybinding.
  CLOSED: [2011-11-30 Wed 10:53]
  - CLOSING NOTE [2011-11-30 Wed 10:53]
* CANCELED check the display of MarsBurner progress bar
  CLOSED: [2011-12-12 Mon 13:09]
  - CLOSING NOTE [2011-12-12 Mon 13:09]
    
    no longer relevant because we changed to mfc/html for UI dialog.
* DONE update MarsBurner UI, remove the setting radio buttons
  CLOSED: [2011-12-05 Mon 11:37]
  - CLOSING NOTE [2011-12-05 Mon 11:37]
* DONE Google并解决visual studion build无法打开文件的问题。
  CLOSED: [2011-11-30 Wed 13:54]
  - CLOSING NOTE [2011-11-30 Wed 13:55] \\
    http://social.msdn.microsoft.com/Forums/da-DK/vcgeneral/thread/fcdde3bc-43a1-4ab6-b0b5-9525fe4e84c8
* DONE MarsBurner: remve the logic of the radio buttons
  CLOSED: [2011-12-05 Mon 09:28]
  - CLOSING NOTE [2011-12-05 Mon 09:28] \\
    done
* DONE MarsBurner: remove the logic of the factory install
  CLOSED: [2011-12-05 Mon 11:37]
  - CLOSING NOTE [2011-12-05 Mon 11:37]
* CANCELED MarsBurner: pop up a warning when OBM is detected in the blf filename.
  CLOSED: [2011-12-05 Mon 16:00]
* DONE MarsBurner: 在Windows 7下必须用Administrator运行。
  CLOSED: [2011-12-05 Mon 09:29]
  - CLOSING NOTE [2011-12-05 Mon 09:30] \\
    Root cause found. It is because flasher.dll is creating temp files
    under install folder, which is write protected.
  需要修改release模式，不采取安装方式，而是用.zip包的方式。
