* TODO 把bbdb的更新方式改成手动方式，不要自动更新

* DONE 回复jira2.el/jira.el merge邮件					 :pe:
  CLOSED: [2012-01-05 Thu 22:43]
  - CLOSING NOTE [2012-01-05 Thu 22:43]
Agreed. I have not looked into org-mode source code yet, so do not know
about contrib/lisp/org-jira.el, but I think it is the same one on
emacswiki, which has been abandoned by its author. So, it will be
trivial to merge its functionality.

You are also right that jira2.el and jira.el can be merged,
theoretically. The jira2.el, as a library, is a superset of jira.el in
terms of functionality, since jira2.el uses soap, while jira.el uses
xml-rpc; and soap is better supported by jira than xml-rpc.

The difficulty lies in that jira.el is also a major mode (in addition to
providing the library for the major mode). To make sure backward
compatible will require some effort. Jira2.el, OTOH, has stopped to be a
major mode, and only provided library for (the new) org-jira.el.

Anyway, I will try to update jira.el and contact the original author to
see if he agrees.

* TODO merge jira2.el and jira.el					 :pe:
