* TODO 为什么set_param会调到vcpath里，而set_mic_mute会调到hifipath里？

* TODO 开始看audio元器件的spec。
** TODO 在marvell代码里搜 MICPGA1_IN_SEL 能看到audio path是怎么处理的。


【 在 chunhui (纯灰) 的大作中提到: 】
: 第一条跟我说的一样啊，苍天，竟然跟大牛不谋而合。

呵呵，李杀推荐过好几种提升Ctrl键按法的方法，我基本都试过，比如（版上应该很多同学也都试过）用手刀的部位去切原来的Ctrl键（这在笔记本上行不通啊）；比如用小指、无名指的第一关节按Ctrl；比如互换capslock/ctrl的位置等。但试到最后发现还是把Alt和Ctrl互换位置最好。因为，Ctrl键好像是比Alt键更重要、频率更高一些，最早的Ctrl键好像就是在现在的Alt键的位置（是不是hhkb等仿古键盘就恢复了这一点呀？）。

: 但是第二条为嘛按capslock当alt呢？那和capslock当ctrl不一样么？

选了第一条再选第二条就很自然的啊。有人互换Ctrl/Alt，有人互换Ctrl/Capslock，为什么不兼而取之呢？我没把它当成alt，而是当成Escape，刚好Emacs里用到alt键的地方基本都可以用Escape替代（其他程序里要用到Alt键打开菜单的话我需要按原来的Ctrl键，因为第一步把Ctrl/Alt互换了，但这种频率极低，不会对手造成什么劳损）。用Escape代替Alt的好处是基本消灭了需要“同时”按下3个键的情形（比如Ctrl+Alt+H），虽然还是按下3个键，但把Escape（原Capslock）独立出来按下放开再去按Ctrl+H，手指就不需要张得那么开，劳损应该不是很严重。

（想到这一条交换方法是有一回到一个Vimer同事的键盘上打了一会Vim，发现他的键盘也被“黑”过，就是交换了Caps/Esc，回到座位上我就开始继续黑自己的键盘部局了:-)

如果按位置优劣来排的话，现在的键盘上Alt > Caps > Escape > Ctrl，但是按键的重要性来排的话，刚好相反：Ctrl > Escape > Caps & Alt.

基本上我现在非常能理解为什么Emacs要同时支持用Escape 和 Meta来表示M-，哈哈。

: 如果alt位置不太靠边儿，还不如也用大拇指。
: ...................

你是说用大拇指去按原来的Ctrl键？这样常见的小指劳损应该不会发生，但大拇指弯得太厉害也该抱怨了。还有就是那种需要3键齐按（Ctrl+Alt+H）的情况还是有不便的。
