* TODO 为什么set_param会调到vcpath里，而set_mic_mute会调到hifipath里？

* TODO 开始看audio元器件的spec。
** TODO 在marvell代码里搜 MICPGA1_IN_SEL 能看到audio path是怎么处理的。


【 在 chunhui (纯灰) 的大作中提到: 】
: 第一条跟我说的一样啊，苍天，竟然跟大牛不谋而合。

呵呵，李杀推荐过好几种提升Ctrl键按法的方法，我基本都试过，比如（版上应该很多同学也都试过）用手刀的部位去切原来的Ctrl键（这在笔记本上行不通啊）；比如用小指、无名指的第一关节按Ctrl；比如互换capslock/ctrl的位置等。但试到最后发现还是把Alt和Ctrl互换位置最好。因为，Ctrl键好像是比Alt键更重要、频率更高一些，最早的Ctrl键好像就是在现在的Alt键的位置（是不是hhkb等仿古键盘就恢复了这一点呀？）。

: 但是第二条为嘛按capslock当alt呢？那和capslock当ctrl不一样么？

选了第一条再选第二条就很自然的啊。有人互换Ctrl/Alt，有人互换Ctrl/Capslock，为什么不兼而取之呢？我没把它当成alt，而是当成Escape，刚好Emacs里用到alt键的地方基本都可以用Escape替代（其他程序里要用到Alt键打开菜单的话我需要按原来的Ctrl键，因为第一步把Ctrl/Alt互换了，但这种频率极低，不会对手造成什么劳损）。用Escape代替Alt的好处是基本消灭了需要“同时”按下3个键的情形（比如Ctrl+Alt+H），虽然还是按下3个键，但把Escape（原Capslock）独立出来按下放开再去按Ctrl+H，手指就不需要张得那么开，劳损应该不是很严重。

（想到这一条交换方法是有一回到一个Vimer同事的键盘上打了一会Vim，发现他的键盘也被“黑”过，就是交换了Caps/Esc，回到座位上我就开始继续黑自己的键盘部局了:-)

如果按位置优劣来排的话，现在的键盘上Alt > Caps > Escape > Ctrl，但是按键的重要性来排的话，刚好相反：Ctrl > Escape > Caps & Alt.

基本上我现在非常能理解为什么Emacs要同时支持用Escape 和 Meta来表示M-，哈哈。

: 如果alt位置不太靠边儿，还不如也用大拇指。
: ...................

你是说用大拇指去按原来的Ctrl键？这样常见的小指劳损应该不会发生，但大拇指弯得太厉害也该抱怨了。还有就是那种需要3键齐按（Ctrl+Alt+H）的情况还是有不便的。

* TODO Binder

    #+begin_example
    Breakpoint 1, mrvl_ap_dev_set_stream_volume_index (pol=0x40e54d30, stream=AUDIO_STREAM_FM, index=10) at vendor/marvell/generic/libaudio/audio_policy_mrvl.c:2579
    (gdb) bt
    #0  mrvl_ap_dev_set_stream_volume_index (pol=0x40e54d30, stream=AUDIO_STREAM_FM, index=10) at vendor/marvell/generic/libaudio/audio_policy_mrvl.c:2579
    #1  0x400e1c90 in setStreamVolumeIndex (index=10, stream=AUDIO_STREAM_FM, this=<optimized out>, device=<optimized out>)
        at frameworks/av/services/audioflinger/AudioPolicyService.cpp:400
    #2  android::AudioPolicyService::setStreamVolumeIndex (this=<optimized out>, stream=AUDIO_STREAM_FM, index=10, device=AUDIO_DEVICE_OUT_WIRED_HEADSET)
        at frameworks/av/services/audioflinger/AudioPolicyService.cpp:380
    #3  0x40251f24 in android::BnAudioPolicyService::onTransact (this=0x40e5a228, code=<optimized out>, data=<optimized out>, reply=0x42076e04, flags=16)
        at frameworks/av/media/libmedia/IAudioPolicyService.cpp:520
    #4  0x401b93da in android::BBinder::transact (this=0x40e5a22c, code=16, data=..., reply=0x42076e04, flags=16) at frameworks/native/libs/binder/Binder.cpp:108
    #5  0x401bbfb6 in android::IPCThreadState::executeCommand (this=0x40e66188, cmd=<optimized out>) at frameworks/native/libs/binder/IPCThreadState.cpp:1034
    #6  0x401bc3e0 in android::IPCThreadState::joinThreadPool (this=0x40e66188, isMain=<optimized out>) at frameworks/native/libs/binder/IPCThreadState.cpp:473
    #7  0x401c02b8 in android::PoolThread::threadLoop (this=0x41d14f10) at frameworks/native/libs/binder/ProcessState.cpp:67
    #8  0x401d9f48 in android::Thread::_threadLoop (user=0x41d14f10) at frameworks/native/libs/utils/Threads.cpp:793
    #9  0x401d9aae in thread_data_t::trampoline (t=<optimized out>) at frameworks/native/libs/utils/Threads.cpp:132
    #10 0x40117bd4 in __thread_entry (func=0x401d9a15 <thread_data_t::trampoline(thread_data_t const*)>, arg=0x41d15170, tls=<optimized out>)
        at bionic/libc/bionic/pthread.c:217
    #11 0x4011732c in pthread_create (thread_out=0x41d15198, attr=0xbef15a88, start_routine=0x401d9a15 <thread_data_t::trampoline(thread_data_t const*)>, arg=0x41d15170)
        at bionic/libc/bionic/pthread.c:356
    #12 0x00000000 in ?? ()
    (gdb) 
    #+end_example
    

* CANCELED write out the cscope-ring's contents, make it a code-reading assistent.
  CLOSED: [2012-11-15 Thu 16:57]
  - CLOSING NOTE [2012-11-15 Thu 16:57]
* DONE write out the gdb usage under Emacs
  CLOSED: [2012-11-15 Thu 16:56]
  - CLOSING NOTE [2012-11-15 Thu 16:56]
