* DONE 把bbdb的更新方式改成手动方式，不要自动更新			 :pe:
  CLOSED: [2012-01-07 Sat 00:13]
  - CLOSING NOTE [2012-01-07 Sat 00:13]

* DONE 回复jira2.el/jira.el merge邮件					 :pe:
  CLOSED: [2012-01-05 Thu 22:43]
  - CLOSING NOTE [2012-01-05 Thu 22:43]
Agreed. I have not looked into org-mode source code yet, so do not know
about contrib/lisp/org-jira.el, but I think it is the same one on
emacswiki, which has been abandoned by its author. So, it will be
trivial to merge its functionality.

You are also right that jira2.el and jira.el can be merged,
theoretically. The jira2.el, as a library, is a superset of jira.el in
terms of functionality, since jira2.el uses soap, while jira.el uses
xml-rpc; and soap is better supported by jira than xml-rpc.

The difficulty lies in that jira.el is also a major mode (in addition to
providing the library for the major mode). To make sure backward
compatible will require some effort. Jira2.el, OTOH, has stopped to be a
major mode, and only provided library for (the new) org-jira.el.

Anyway, I will try to update jira.el and contact the original author to
see if he agrees.

* CANCELED merge jira2.el and jira.el					 :pe:
  CLOSED: [2012-01-07 Sat 00:12]
  - CLOSING NOTE [2012-01-07 Sat 00:12]
    renamed jira2 to jiralib.

* DONE 每次build MarsBurner都把marsburner setting给删掉。
  CLOSED: [2012-01-12 Thu 17:28]
  - CLOSING NOTE [2012-01-12 Thu 17:28]

* factory tool discussion with Doctor Jia

- flashing problem could be factory bottleneck. 
- 1-n flashing.
- RF Calibration, difficult to do in-depth development
- whole set testing, use SFFT, we will do development based on this tool.
- auto test and manual test, need be combined
- wifi/bt/fm/gps etc, test using grassroot method, no SNR test etc.
- test result database.
- Doctor Jia advise to add battery calibration and do SN write in early whole set current test.
- To enter different boot mode, need discuss further
  1. Test gpio is not a long term solution
- To discuss how the factory test station status is saved.
* TODO 把linux console下的键盘大写键与escape键互换一下			 :pe:

* Things done on 2012-01-30
  :PROPERTIES:
  :ID:       o2b:b2810d62-fceb-450f-8958-d60f88668372
  :POST_DATE: [2012-01-31 Tue 10:34]
  :POSTID:   55
  :END:

** Work on org-jira, fixed priority required when creating issue

** Work on Network Manager under sawfish

- Will not allow delete network profile, while under gnome, a auth
  dialog popup asking for root password, and can go on to delete/add
  network profile.

- This is fixed by starting policykit after diff with gnome session
  processes. More may need be fixed.

- Started gnome-keyring-daemen in ~/.xprofile. GDM3 will source this
  file.

- Will not be able to save after you edit a profile, must delete and
  then add and get it right when adding. It is different if you run
  nm-applet as root; in that case it can be saved.

** Work on RNDIS XP driver, turns out only need a .inf file.

* 2012-01-31
  :PROPERTIES:
  :ID:       o2b:006652de-5004-4e2f-9415-f93cf4deff2a
  :POST_DATE: [2012-01-31 Tue 22:28]
  :POSTID:   59
  :END:

- Work on git-push-mac and git-pull-mac, should not use meaningless
  commit message dubbed "mf".

** DONE 把firefox bookmark做成可搜索的？				 :pe:
   CLOSED: [2012-02-01 Wed 12:49]
   - CLOSING NOTE [2012-02-01 Wed 12:49]

** DONE fix gnome-open							 :pe:
   CLOSED: [2012-02-08 Wed 20:27]
   - CLOSING NOTE [2012-02-08 Wed 20:27] \\
     gnome-open will always open nautilus with the target file selected.
     
     rm ~/.local
     
     It is great that I can use this as oc -- open containing folder.
** DONE fix sdim while C-s searching					 :pe:
   CLOSED: [2012-01-31 Tue 22:01]
   - CLOSING NOTE [2012-01-31 Tue 22:01]

** DONE fix emacs url-proxy-services error on home PC			 :pe:
   CLOSED: [2012-01-31 Tue 22:27]
   - CLOSING NOTE [2012-01-31 Tue 22:27] \\
     Must not use localhost:8580 as the proxy; must use 127.0.0.1; IPV6 is
     involved to mess up
