* CANCELED 搞定google nexus的root.
  CLOSED: [2012-03-01 Thu 16:57]
  - CLOSING NOTE [2012-03-01 Thu 16:57]

下载 yakju-icl53f-factory-89fccaac.tgz

unpackbootimg -i boot.img 
mkdir ramdisk
cd ramdisk
cat ../boot.img-ramdisk.gz |gunzip |cpio -i 

mkbootfs . |gzip > ../boot.img-ramdisk.gz 
mkbootimg --kernel boot.img-zImage --base $(cat *-base) --pagesize $(cat *-pagesize) --ramdisk boot.img-ramdisk.gz -o boot.img 
sudo fastboot boot boot.img
* TODO [   14.520965] dcmd: version magic '2.6.29 mod_unload ARMv5 ' should be '3.0.8+ preempt mod_unload ARMv5 '

* 怎么发邮件

Bao Zong刚才问我提review之后给大家发的邮件是不是自动发的，能不能普及一下，
给CM的gerrit/jira等系统用。所以我把我的配置方法写一下。

1. 装davmail，这个是sourceforge上的开源项目，功能是把ms exchange接口封装
   成imap/pop/smtp的接口。
   
   我现在收邮件都是在后台从davmail的imap口上下载到本地看的，发邮件也是从
   它的smtp口发出去。

2. 配置postfix，配置方法可以google一下postfix+gmail的配置方法。

   这样系统的mailx等程序也可以直接给非本机邮箱发邮件。我的review邮件就是
   用这个程序自动发出来的。（如果是thunderbird等图形邮件程序的话大都是支
   持配置smtp host/port的，所以没必要配置postfix。可能mailx等程序也可以
   配置，但是没仔细研究过。）

让CM用这个方法会有一些问题：

1. 系统配置比较麻烦，尤其是在bible服务器上。davmail是一个图形程序，适合给
   单机桌面版用，放在服务器上当daemon跑的话不知道稳定性怎样。

2. 系统吞吐量不知道够不够。
