'\" t
.\"     Title: guilt-export
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 07/17/2011
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.35
.\"  Language: English
.\"
.TH "GUILT\-EXPORT" "1" "07/17/2011" "Guilt v0\&.35" "Guilt Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
guilt-export \- Export a patch series (to be used by quilt)
.SH "SYNOPSIS"
\fIguilt\-export\fR [<target_dir>]
.SH "DESCRIPTION"
Export a guilt series to be used by quilt\&.
.SH "OPTIONS"
.PP
<target_dir>
.RS 4
Name of the directory to export the patch series to\&. (defaults to patches)\&.
.RE
.SH "AUTHOR"
Written by Pierre Habouzit <\m[blue]\fBmadcoder@debian\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "DOCUMENTATION"
Documentation by Pierre Habouzit <\m[blue]\fBmadcoder@debian\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.35)
.SH "NOTES"
.IP " 1." 4
madcoder@debian.org
.RS 4
\%mailto:madcoder@debian.org
.RE
