'\" t
.\"     Title: guilt-push
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 07/17/2011
.\"    Manual: Guilt Manual
.\"    Source: Guilt v0.35
.\"  Language: English
.\"
.TH "GUILT\-PUSH" "1" "07/17/2011" "Guilt v0\&.35" "Guilt Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
guilt-push \- Push patches onto the tree
.SH "SYNOPSIS"
\fIguilt\-push\fR [ \-f ] [\-a | \-\-all | \-n <num> | <patchname>]
.SH "OPTIONS"
.PP
\-f
.RS 4
Force the push if the patch doesn\(cqt apply cleanly
.RE
.PP
\-\-all, \-a
.RS 4
Push all patches on the tree
.RE
.PP
\-n <num>
.RS 4
Push specified number of patches
.RE
.PP
<patchname>
.RS 4
Push all patches up to and including this patch on the tree
.RE
If no patchname is given, push the next patch in the series onto the tree\&.
.SH "AUTHOR"
Written by Josef "Jeff" Sipek <\m[blue]\fBjeffpc@josefsipek\&.net\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "DOCUMENTATION"
Documentation by Brandon Philips <\m[blue]\fBbrandon@ifup\&.org\fR\m[]\&\s-2\u[2]\d\s+2>
.SH "GUILT"
Part of the \fBguilt\fR(7) suite (Generated for Guilt v0\&.35)
.SH "NOTES"
.IP " 1." 4
jeffpc@josefsipek.net
.RS 4
\%mailto:jeffpc@josefsipek.net
.RE
.IP " 2." 4
brandon@ifup.org
.RS 4
\%mailto:brandon@ifup.org
.RE
