.\" beagrep-manage-index(8) manpage
.\"
.\" Copyright (C) 2005 Novell, Inc.
.\"
.TH BEAGREP "8" "Jul 2005" "beagrep" ""
.SH NAME
beagrep-manage-index
.SH SYNOPSIS
.B beagrep-manage-index
<\fIindex_path\fR>
<\fIcommand\fR>
[\fIoptions\fR] 
.SH DESCRIPTION
.PP
.BR beagrep-manage-index ,
is a tool designed for doing low-level Lucene index management
.PP
The
.BR beagrep-manage-index
tool is capable of doing basic low-level Lucene index management and may be
used for debugging and other tasks perfomed by developers or advanced
users. It is not intended to be invoked by the standard user.
.SH COMMANDS
.BR beagrep-manage-index
takes the following commands
.TP
.B merge <index_to_merge>
Merge another Lucene index into the target.
.TP
.B info
Print basic index information.
.TP
.B optimize
Optimize index.
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to <dashboard-hackers@gnome.org>.
.SH COPYRIGHT
Copyright \(co 2005 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagrepd (1),
.BR beagrep-build-index (8)
