.\" beagrep-dump-index(1) manpage
.\"
.\" Copyright (C) 2004-2007 Novell, Inc.
.\"
.TH BEAGREP-DUMP-INDEX "8" "14 Mar 2007"
.SH NAME
beagrep-dump-index
.SH SYNOPSIS
.B beagrep-dump-index
[\fIoptions\fR] [[file or URI to match] ...]
.SH DESCRIPTION
.PP
.BR beagrep-dump-index
is a low-level tool for examining data indexed by the Beagrep search system.
.PP
.SH OPTIONS
.TP
.B --uris
Dump all Uris (default)
.TP
.B --properties
Dump all properties
.TP
.B --term-frequencies
Dump term frequencies
.TP
.B --fields
Dump all fields
.TP
.B --show-counts
Show index count totals (default)
.TP
.B --hide-counts
Hide index count totals
.TP
.B --index=<index name>
Limit results to an index by name.  May be used multiple times.
.TP
.B --indexdir=<directory>
Limit results to an index specified by absolute path.  May be used multiple times.  Example path /home/user/.beagrep/Indexes/FileSystemIndex
.TP
.B file or URI to match
Get information in index about one or more files or URIs.  Note this doesn't make sense with 
.B--term-frequencies 
and will cause an error.
.SH AUTHOR
Novell, Inc.
.SH "REPORTING BUGS"
Report bugs to http://bugzilla.gnome.org
.SH COPYRIGHT
Copyright \(co 2004-2007 Novell, Inc.
.sp
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR beagrepd (1),
.BR http://beagrep-project.org
