(defun synthesize-multiple-events (&rest events)
  (mapc (lambda (e)
          (synthesize-event e (input-focus)))
        events))
(bind-keys global-keymap "KP_End"  '(system "netease-music loop&"))
(bind-keys global-keymap "KP_Up"  '(system "netease-music nloop&"))
(bind-keys global-keymap "KP_Down"  '(system "netease-music info&"))
(bind-keys global-keymap "KP_Prior"  '(system "netease-music lyrics&"))
(bind-keys global-keymap "KP_Next"  '(system "netease-music show&"))
(bind-keys global-keymap "KP_Right"  '(system "netease-music next&"))
(bind-keys global-keymap "KP_Left"  '(system "netease-music prev&"))
(bind-keys global-keymap "KP_Begin"  '(system "netease-music ba&"))
(bind-keys global-keymap "KP_6" '(system "netease-music rchan&"))
(bind-keys global-keymap "KP_Home"  '(system "netease-music replay&"))
(bind-keys global-keymap "KP_Add"  '(system "adjust-volume&"))
(bind-keys global-keymap "KP_Subtract"  '(system "adjust-volume&"))
(bind-keys global-keymap "KP_Insert" '(system "firefox-goto-next-prev-page prev&"))
(bind-keys global-keymap "KP_Delete" '(system "firefox-goto-next-prev-page next&"))
