(defun synthesize-multiple-events (&rest events)
  (mapc (lambda (e)
          (synthesize-event e (input-focus)))
        events))
(bind-keys global-keymap "KP_End"  '(system "douban loop&"))
(bind-keys global-keymap "KP_Up"  '(system "douban nloop&"))
(bind-keys global-keymap "KP_Down"  '(system "douban info&"))
(bind-keys global-keymap "KP_Prior"  '(system "douban lyrics&"))
(bind-keys global-keymap "KP_Next"  '(system "douban show&"))
(bind-keys global-keymap "KP_Right"  '(system "douban next&"))
(bind-keys global-keymap "KP_Left"  '(system "douban prev&"))
(bind-keys global-keymap "KP_Begin"  '(system "douban ba&"))
(bind-keys global-keymap "KP_Home"  '(system "douban replay&"))
(bind-keys global-keymap "KP_Add"  '(system "adjust-volume&"))
(bind-keys global-keymap "KP_Subtract"  '(system "adjust-volume&"))
(bind-keys global-keymap "KP_Insert" '(system "firefox-goto-next-prev-page prev&"))
(bind-keys global-keymap "KP_Delete" '(system "firefox-goto-next-prev-page next&"))
