#!/usr/bin/env bash
set -e

if test $# = 0; then
    set -- "$(xclip -o)"
fi

fill=$(echo "$@"|urlify)

firefox "file:///usr/share/doc/python3.7/html/search.html?q=${fill}&check_keywords=yes&area=default"
